# Stored execution evidence — Dog Breed Identification

This public evidence copy preserves every textual output cell supplied in `mle.zip`.
The original notebook SHA-256 is `fbc0aed882b76adacfb2d917c01a7df460f687a329dd829f1429738c68e57a37`. Embedded binary rich media is removed so
that competition data and generated images are not redistributed. The repository setup cell
now targets `Isso-W/Jiaozi` at `main`; stored metrics and submission receipts remain historical
outputs and are not presented as a fresh rerun of the current branch.

# Standalone MLE-STAR benchmark runner

This is the original compact workflow, extended without changing its seven-dataset
order: each dataset still has one visible execution cell. Shared implementation is
kept in four collapsed helper cells.

For every dataset the cell records OOF MLE-STAR results, reconstructs the selected
ensemble, predicts the Kaggle test set, validates against `sample_submission.csv`,
and optionally submits through the Kaggle API. Vision epochs are selected on an
inner validation split; `MAX_EPOCHS` is only a ceiling.

In [1]:
# Reproducible repository setup for Colab.
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPOSITORY = "https://github.com/Isso-W/Jiaozi.git"
BRANCH = "main"
REPOSITORY_ROOT = Path("/content/Jiaozi")
EXPERIMENT_ROOT = REPOSITORY_ROOT / "experiments" / "mlestar_kaggle_benchmarks"

if REPOSITORY_ROOT.exists():
    shutil.rmtree(REPOSITORY_ROOT)
subprocess.run(
    ["git", "clone", "--depth", "1", "--branch", BRANCH, REPOSITORY, str(REPOSITORY_ROOT)],
    check=True,
)
actual_commit = subprocess.check_output(
    ["git", "-C", str(REPOSITORY_ROOT), "rev-parse", "HEAD"], text=True
).strip()
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", f"{EXPERIMENT_ROOT}[vision,llm,kaggle,dev]"],
    check=True,
)
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "--upgrade", "kaggle==2.2.2"],
    check=True,
)
os.chdir(EXPERIMENT_ROOT)
if str(EXPERIMENT_ROOT) not in sys.path:
    sys.path.insert(0, str(EXPERIMENT_ROOT))
print("Repository commit:", actual_commit)
subprocess.run([sys.executable, "-m", "mlestar.cli", "benchmarks"], check=True)

Repository commit: 01228290ba427023f3e3d386255558f50b21a1a6

CompletedProcess(args=['/usr/bin/python3', '-m', 'mlestar.cli', 'benchmarks'], returncode=0)

In [2]:
# Credentials and experiment controls.
# Add KAGGLE_API_TOKEN in Colab: left sidebar -> key icon -> Secrets.
try:
    from google.colab import userdata
except ImportError:
    userdata = None

def load_colab_secret(name):
    if userdata is None:
        return
    try:
        value = userdata.get(name)
    except Exception:
        value = None
    if value:
        os.environ[name] = value

load_colab_secret("KAGGLE_API_TOKEN")
load_colab_secret("HF_TOKEN")
if os.environ.get("HF_TOKEN"):
    os.environ["HUGGINGFACE_HUB_TOKEN"] = os.environ["HF_TOKEN"]
os.environ["HF_HOME"] = "/content/hf_cache"

# Run All executes these seven pipelines from top to bottom. Comment out a
# name only when intentionally resuming or debugging one task.
BENCHMARKS_TO_RUN = {
    "leaf_classification",
    "plant_pathology_2020",
    "aptos_2019",
    "dog_breed",
    "aerial_cactus",
    "dogs_vs_cats",
    "histopathologic_cancer",
}

SEEDS = (13, 29, 47)
IMAGE_SIZE = 128
# Epoch count is selected inside each training run from an inner validation
# split. MAX_EPOCHS is only a safety ceiling, not the chosen epoch count.
MAX_EPOCHS = 40
MIN_EPOCHS = 3
EARLY_STOPPING_PATIENCE = 5
INNER_VALIDATION_FRACTION = 0.10
BATCH_SIZE = 32
MAX_TRAIN_SAMPLES_PER_FOLD = 2000
NUM_WORKERS = 4
USE_AMP = True  # Set False for strict FP32; AMP can cause tiny numerical differences.

# Every task submits only after its sample-submission schema and IDs pass.
SUBMIT_ALL_VIA_API = True
SUBMISSION_PREFIX = "MLE-STAR unified benchmark"
KAGGLE_SCORE_POLL_SECONDS = 300
# Make genuine data/training/prediction failures visibly red in Colab.
# Kaggle submission rejection is captured as a result rather than raised.
STOP_ON_PIPELINE_FAILURE = True

# Persist OOF artifacts, selected epochs, final checkpoints and submissions.
# Data archives remain under /content and may need to be downloaded again.
PERSIST_RUNS_TO_GOOGLE_DRIVE = True
RESUME_EXISTING_RUNS = True
# Allows recovery of the older notebook's completed OOF artifacts, which
# used fixed 3 epochs. Such a submission is labelled legacy and must not be
# mixed with the new inner-selected-epoch OOF comparison.
ALLOW_LEGACY_FIXED_EPOCH_OOF_RESUME = False

LEGACY_RUNS_ROOT = Path("/content/mlestar-runs")
if PERSIST_RUNS_TO_GOOGLE_DRIVE and userdata is not None:
    from google.colab import drive
    drive.mount("/content/drive")
    RUNS_ROOT = Path("/content/drive/MyDrive/mlestar-runs")
    # Rescue artifacts made by the older notebook in this still-live VM.
    # If the VM was already reset, /content has no old files to recover.
    if LEGACY_RUNS_ROOT.is_dir():
        shutil.copytree(LEGACY_RUNS_ROOT, RUNS_ROOT, dirs_exist_ok=True)
else:
    RUNS_ROOT = LEGACY_RUNS_ROOT
RUNS_ROOT.mkdir(parents=True, exist_ok=True)
print("Kaggle token configured:", bool(os.environ.get("KAGGLE_API_TOKEN")))
print("Selected benchmarks:", sorted(BENCHMARKS_TO_RUN))
print("Persistent runs root:", RUNS_ROOT)

Mounted at /content/drive
Kaggle token configured: True
Selected benchmarks: ['aerial_cactus', 'aptos_2019', 'dog_breed', 'dogs_vs_cats', 'histopathologic_cancer', 'leaf_classification', 'plant_pathology_2020']
Persistent runs root: /content/drive/MyDrive/mlestar-runs

In [3]:
# Reusable Kaggle competition fetcher from the original notebook, rewritten
# without notebook shell interpolation so failures retain stdout/stderr.
import zipfile

def fetch_kaggle_competition(slug: str, data_root: str | Path, marker_file: str) -> Path:
    root = Path(data_root)
    root.mkdir(parents=True, exist_ok=True)
    if (root / marker_file).exists():
        print("Dataset already present:", root)
        return root
    if not os.environ.get("KAGGLE_API_TOKEN"):
        raise RuntimeError(
            f"No {marker_file} in {root} and KAGGLE_API_TOKEN is not configured."
        )
    command = [
        "kaggle", "competitions", "download", "-c", slug,
        "-p", str(root),
    ]
    completed = subprocess.run(
        command, text=True, capture_output=True, check=False,
    )
    if completed.stdout.strip():
        print(completed.stdout.strip())
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or "No error text returned"
        if "403" in detail or "Forbidden" in detail:
            raise PermissionError(
                f"Kaggle denied access to {slug}. The CLI reached Kaggle, but the "
                "account represented by KAGGLE_API_TOKEN cannot download this "
                "competition's files. Open that competition's Rules page while "
                "signed into the same account, join/accept it, then generate a new "
                f"token and retry. Kaggle response:\n{detail}"
            )
        raise RuntimeError(
            f"Kaggle download failed for {slug} (exit {completed.returncode}).\n"
            f"Command: {' '.join(command)}\n"
            f"Kaggle response:\n{detail}"
        )
    outer_zip = root / f"{slug}.zip"
    if outer_zip.exists():
        with zipfile.ZipFile(outer_zip) as archive:
            archive.extractall(root)
    for nested_zip in root.glob("*.zip"):
        if nested_zip == outer_zip:
            continue
        with zipfile.ZipFile(nested_zip) as archive:
            archive.extractall(root)
    if not (root / marker_file).exists():
        raise RuntimeError(
            f"Download did not produce {marker_file} in {root}. Inspect the Kaggle CLI "
            "output and confirm that the token is current and rules are accepted."
        )
    return root

In [4]:
#@title APTOS special preprocessing (shared helper) { display-mode: "form" }
# APTOS-only lossless resize cache. It applies exactly the original adapter's
# Image.open(...).convert("RGB").resize((128, 128)) operation once, then stores
# the result as PNG. Ten images are checked for exact pixel equality.
import json
from concurrent.futures import ThreadPoolExecutor

import numpy as np
from PIL import Image
from tqdm.auto import tqdm

def prepare_aptos_cache(source_root: str | Path) -> Path:
    source_root = Path(source_root)
    cache_root = Path("/content/aptos2019-resized-128")
    cache_root.mkdir(parents=True, exist_ok=True)
    for csv_name in ("train.csv", "test.csv", "sample_submission.csv"):
        source = source_root / csv_name
        if source.is_file():
            shutil.copy2(source, cache_root / csv_name)

    work = []
    for split in ("train_images", "test_images"):
        source_dir = source_root / split
        destination_dir = cache_root / split
        destination_dir.mkdir(parents=True, exist_ok=True)
        work.extend(
            (path, destination_dir / path.name)
            for path in sorted(source_dir.glob("*.png"))
        )
    if not work:
        raise RuntimeError(f"No APTOS PNG images found in {source_root}")

    def resize_one(item):
        source, destination = item
        if destination.is_file():
            return False
        with Image.open(source) as opened:
            resized = opened.convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE))
            temporary = destination.with_suffix(".tmp.png")
            resized.save(temporary, format="PNG", compress_level=1)
            temporary.replace(destination)
        return True

    created = 0
    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        for result in tqdm(
            executor.map(resize_one, work), total=len(work), desc="APTOS lossless cache"
        ):
            created += int(result)
    missing = [str(destination) for _, destination in work if not destination.is_file()]
    if missing:
        raise RuntimeError(f"Incomplete APTOS cache, examples: {missing[:5]}")

    for source, cached in work[:10]:
        with Image.open(source) as opened:
            expected = np.asarray(
                opened.convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE)), dtype=np.uint8
            )
        with Image.open(cached) as opened:
            actual = np.asarray(opened.convert("RGB"), dtype=np.uint8)
        if not np.array_equal(expected, actual):
            raise AssertionError(f"Cached pixels differ for {source.name}")
    print({"cached_images": len(work), "new_files": created, "pixel_checks": 10})
    return cache_root

In [5]:
#@title MLE-selected epoch vision adapter (shared helper) { display-mode: "form" }
# Shared optimized adapter for all six image benchmarks.
from contextlib import nullcontext
from time import perf_counter

import numpy as np
import torch
from sklearn.model_selection import train_test_split
import mlestar.adapters.vision as vision
import mlestar.experiment as experiment_module
from mlestar.experiment import compare
from mlestar.metrics import score_metric

class FastVisionMixin:
    def __init__(
        self,
        *args,
        num_workers=4,
        use_amp=True,
        min_epochs=3,
        early_stopping_patience=5,
        inner_validation_fraction=0.10,
        max_inner_validation_samples=500,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self.num_workers = int(num_workers)
        self.use_amp = bool(use_amp and vision._DEVICE.type == "cuda")
        self.min_epochs = int(min_epochs)
        self.early_stopping_patience = int(early_stopping_patience)
        self.inner_validation_fraction = float(inner_validation_fraction)
        self.max_inner_validation_samples = int(max_inner_validation_samples)
        self._fit_number = 0
        self._epoch_records = []
        self._epoch_context = {}
        if not 1 <= self.min_epochs <= self.epochs:
            raise ValueError("min_epochs must be in [1, max_epochs]")
        if self.early_stopping_patience < 1:
            raise ValueError("early_stopping_patience must be positive")
        if not 0 < self.inner_validation_fraction < 0.5:
            raise ValueError("inner_validation_fraction must be in (0, 0.5)")

    def _loader(self, dataset, *, shuffle, seed=None, drop_last=False):
        options = dict(
            dataset=dataset,
            batch_size=self.batch_size,
            shuffle=shuffle,
            num_workers=self.num_workers,
            pin_memory=(vision._DEVICE.type == "cuda"),
            persistent_workers=(self.num_workers > 0),
            drop_last=bool(drop_last),
        )
        if self.num_workers > 0:
            options["prefetch_factor"] = 2
        if shuffle:
            options["generator"] = torch.Generator().manual_seed(int(seed))
        return torch.utils.data.DataLoader(**options)

    def _scaler(self):
        try:
            return torch.amp.GradScaler("cuda", enabled=self.use_amp)
        except (AttributeError, TypeError):
            return torch.cuda.amp.GradScaler(enabled=self.use_amp)

    def _autocast(self):
        if not self.use_amp:
            return nullcontext()
        return torch.autocast(device_type="cuda", dtype=torch.float16)

    def _fit(self, model, dataset, seed):
        parameters = list(model.parameters())
        if not parameters:
            return
        self._fit_number += 1
        if len(dataset) < 2:
            raise ValueError("Epoch selection requires at least two training rows")
        validation_size = min(
            max(1, int(round(len(dataset) * self.inner_validation_fraction))),
            self.max_inner_validation_samples,
        )
        validation_size = min(validation_size, len(dataset) - 1)
        all_indices = np.arange(len(dataset))
        if self.task.modality == "image_ordinal":
            ordinal_labels = (
                dataset.targets.detach().cpu().numpy().reshape(-1).astype(int)
            )
            fitting_indices, validation_indices = train_test_split(
                all_indices,
                test_size=validation_size,
                random_state=int(seed),
                stratify=ordinal_labels,
            )
        else:
            permutation = torch.randperm(
                len(dataset), generator=torch.Generator().manual_seed(int(seed))
            ).numpy()
            validation_indices = permutation[:validation_size]
            fitting_indices = permutation[validation_size:]
        validation_dataset = torch.utils.data.Subset(
            dataset, validation_indices.tolist()
        )
        fitting_dataset = torch.utils.data.Subset(
            dataset, fitting_indices.tolist()
        )
        initial_state = {
            name: value.detach().cpu().clone()
            for name, value in model.state_dict().items()
        }
        loader = self._loader(
            fitting_dataset,
            shuffle=True,
            seed=seed,
            drop_last=(
                len(fitting_dataset) > self.batch_size
                and len(fitting_dataset) % self.batch_size == 1
            ),
        )
        validation_loader = self._loader(validation_dataset, shuffle=False)
        optimizer = torch.optim.Adam(parameters, lr=1e-4)
        loss_fn = self._loss_fn()
        scaler = self._scaler()
        metric_name = self.task.metric.name
        greater_is_better = bool(self.task.metric.greater_is_better)
        best_metric = float("-inf") if greater_is_better else float("inf")
        selected_epoch_val_loss = None
        best_epoch = None
        stale_epochs = 0
        for epoch in range(self.epochs):
            started = perf_counter()
            loss_sum = 0.0
            model.train()
            for images, targets in loader:
                images = images.to(vision._DEVICE, non_blocking=True)
                targets = targets.to(vision._DEVICE, non_blocking=True)
                optimizer.zero_grad(set_to_none=True)
                with self._autocast():
                    loss = loss_fn(model(images), targets)
                if not torch.isfinite(loss):
                    raise FloatingPointError(f"Non-finite loss: {loss.item()}")
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
                loss_sum += float(loss.detach().cpu())

            validation_loss_sum = 0.0
            validation_rows = 0
            validation_predictions = []
            validation_targets = []
            model.eval()
            with torch.inference_mode():
                for images, targets in validation_loader:
                    images = images.to(vision._DEVICE, non_blocking=True)
                    targets = targets.to(vision._DEVICE, non_blocking=True)
                    with self._autocast():
                        logits = model(images)
                        validation_loss = loss_fn(logits, targets)
                    batch_prediction = self._predict_probs(logits)
                    if torch.is_tensor(batch_prediction):
                        batch_prediction = batch_prediction.detach().float().cpu().numpy()
                    validation_predictions.append(np.asarray(batch_prediction))
                    validation_targets.append(
                        targets.detach().float().cpu().numpy()
                    )
                    batch_rows = int(images.shape[0])
                    validation_loss_sum += float(validation_loss.detach().cpu()) * batch_rows
                    validation_rows += batch_rows
            mean_validation_loss = validation_loss_sum / max(validation_rows, 1)
            metric_truth = np.concatenate(validation_targets)
            metric_prediction = np.concatenate(validation_predictions)
            if self.task.modality in {
                "image_binary", "image_ordinal", "image_multiclass"
            }:
                metric_truth = metric_truth.reshape(-1)
            scoring_truth, scoring_prediction = self._score_inputs(
                metric_truth, metric_prediction
            )
            metric_options = {}
            if self.task.modality == "image_multiclass":
                metric_options["labels"] = list(range(metric_prediction.shape[1]))
            current_metric = float(score_metric(
                self.task.metric,
                scoring_truth,
                scoring_prediction,
                **metric_options,
            ).value)
            if not np.isfinite(current_metric):
                improved = False
            elif greater_is_better:
                improved = current_metric > best_metric + 1e-12
            else:
                improved = current_metric < best_metric - 1e-12
            if improved:
                best_metric = current_metric
                selected_epoch_val_loss = mean_validation_loss
                best_epoch = epoch + 1
                stale_epochs = 0
            else:
                stale_epochs += 1
            selection_text = (
                f"inner_val_{metric_name}={current_metric:.5f} "
                f"best_{metric_name}={best_metric:.5f}"
            )
            print(
                f"  fit={self._fit_number} epoch={epoch + 1}/{self.epochs} "
                f"loss={loss_sum / max(len(loader), 1):.5f} "
                f"inner_val_loss={mean_validation_loss:.5f} "
                f"{selection_text} "
                f"best_epoch={best_epoch} "
                f"seconds={perf_counter() - started:.1f}"
            )
            if (
                epoch + 1 >= self.min_epochs
                and stale_epochs >= self.early_stopping_patience
            ):
                break
        if best_epoch is None:
            raise RuntimeError("Epoch selection did not produce a finite checkpoint")
        # The inner split chooses only the epoch count. Rewind the model and
        # train from the same initialization on every available training row,
        # leaving the outer OOF fold untouched.
        model.load_state_dict(initial_state)
        model.to(vision._DEVICE)
        torch.manual_seed(int(seed))
        if vision._DEVICE.type == "cuda":
            torch.cuda.manual_seed_all(int(seed))
        full_loader = self._loader(
            dataset,
            shuffle=True,
            seed=seed,
            drop_last=(len(dataset) > self.batch_size and len(dataset) % self.batch_size == 1),
        )
        full_optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
        full_scaler = self._scaler()
        for refit_epoch in range(best_epoch):
            model.train()
            full_loss_sum = 0.0
            for images, targets in full_loader:
                images = images.to(vision._DEVICE, non_blocking=True)
                targets = targets.to(vision._DEVICE, non_blocking=True)
                full_optimizer.zero_grad(set_to_none=True)
                with self._autocast():
                    full_loss = loss_fn(model(images), targets)
                if not torch.isfinite(full_loss):
                    raise FloatingPointError(f"Non-finite refit loss: {full_loss.item()}")
                full_scaler.scale(full_loss).backward()
                full_scaler.step(full_optimizer)
                full_scaler.update()
                full_loss_sum += float(full_loss.detach().cpu())
            print(
                f"  fit={self._fit_number} full_refit_epoch={refit_epoch + 1}/{best_epoch} "
                f"loss={full_loss_sum / max(len(full_loader), 1):.5f}"
            )
        record = {
            **self._epoch_context,
            "fit_number": self._fit_number,
            "seed": int(seed),
            "dataset_rows": len(dataset),
            "inner_fit_rows": len(fitting_dataset),
            "inner_validation_rows": len(validation_dataset),
            "selected_epoch": int(best_epoch),
            "best_inner_validation_loss": float(selected_epoch_val_loss),
            "best_inner_validation_metric": float(best_metric),
            "best_inner_validation_metric_name": metric_name,
            "metric_greater_is_better": greater_is_better,
            "best_inner_validation_qwk": (
                float(best_metric) if metric_name == "qwk" else None
            ),
            "max_epochs": int(self.epochs),
            "stopped_early": bool(best_epoch < self.epochs),
            "criterion": (
                f"{'maximum' if greater_is_better else 'minimum'} "
                f"inner-validation {metric_name}"
            ),
            "refit_on_all_training_rows": True,
        }
        self._epoch_records.append(record)
        self.artifacts.write_json(
            "epoch_selection.json",
            {"leakage_rule": "outer OOF rows are not used for epoch selection", "records": self._epoch_records},
        )

    def _predict(self, model, dataset):
        loader = self._loader(dataset, shuffle=False)
        outputs = []
        model.eval()
        with torch.inference_mode():
            for images, _ in loader:
                images = images.to(vision._DEVICE, non_blocking=True)
                with self._autocast():
                    outputs.append(self._predict_probs(model(images)))
        return np.concatenate(outputs, axis=0)

    def run(self, candidate, *, phase, seed, parent_experiment_id=None):
        model_name = candidate.block("model")
        print(f"START seed={seed} phase={phase} model={model_name}")
        started = perf_counter()
        self._epoch_context = {
            "phase": phase,
            "candidate_id": candidate.candidate_id,
            "model": model_name,
        }
        result = super().run(
            candidate, phase=phase, seed=seed,
            parent_experiment_id=parent_experiment_id,
        )
        print(
            f"END   seed={seed} phase={phase} model={model_name} "
            f"metric={result.receipt.metric_value} error={result.receipt.error} "
            f"minutes={(perf_counter() - started) / 60:.2f}"
        )
        self._epoch_context = {}
        return result

for benchmark, base_class in list(experiment_module.ADAPTER_CLASSES.items()):
    if issubclass(base_class, vision.ImageClassificationAdapter):
        fast_class = type(f"Fast{base_class.__name__}", (FastVisionMixin, base_class), {})
        experiment_module.ADAPTER_CLASSES[benchmark] = fast_class

image_requested = any(name != "leaf_classification" for name in BENCHMARKS_TO_RUN)
if image_requested and vision._DEVICE.type != "cuda":
    raise RuntimeError("Enable a Colab GPU runtime before running image benchmarks.")
print(
    "device:",
    torch.cuda.get_device_name(0) if vision._DEVICE.type == "cuda" else "CPU (leaf only)",
)

device: NVIDIA L4

In [6]:
#@title Benchmark runner (shared helper) { display-mode: "form" }
# Unified task registry and runner. Each original benchmark cell below calls
# this same function, so paths, seeds and adapter options cannot drift.
import json
import pandas as pd
from benchmarks.catalog import get_task

TASKS = {
    "leaf_classification": {
        "slug": "leaf-classification", "marker": "train.csv",
        "data_root": "/content/leaf-classification", "vision": False,
    },
    "plant_pathology_2020": {
        "slug": "plant-pathology-2020-fgvc7", "marker": "train.csv",
        "data_root": "/content/plant-pathology-2020-fgvc7", "vision": True,
    },
    "aptos_2019": {
        "slug": "aptos2019-blindness-detection", "marker": "train.csv",
        "data_root": "/content/aptos2019-blindness-detection", "vision": True,
    },
    "dog_breed": {
        "slug": "dog-breed-identification", "marker": "labels.csv",
        "data_root": "/content/dog-breed-identification", "vision": True,
    },
    "aerial_cactus": {
        "slug": "aerial-cactus-identification", "marker": "train.csv",
        "data_root": "/content/aerial-cactus-identification", "vision": True,
    },
    "dogs_vs_cats": {
        "slug": "dogs-vs-cats-redux-kernels-edition", "marker": "train",
        "data_root": "/content/dogs-vs-cats-redux-kernels-edition", "vision": True,
    },
    "histopathologic_cancer": {
        "slug": "histopathologic-cancer-detection", "marker": "train_labels.csv",
        "data_root": "/content/histopathologic-cancer-detection", "vision": True,
    },
}
COMPLETED = {}

def run_benchmark(benchmark):
    if benchmark not in BENCHMARKS_TO_RUN:
        print(f"SKIP {benchmark}; add it to BENCHMARKS_TO_RUN to execute.")
        return None
    config = TASKS[benchmark]
    source_root = fetch_kaggle_competition(
        config["slug"], config["data_root"], config["marker"]
    )
    data_root = prepare_aptos_cache(source_root) if benchmark == "aptos_2019" else source_root
    run_root = RUNS_ROOT / benchmark
    comparison_path = run_root / "comparison.csv"
    receipts_path = run_root / "receipts.jsonl"
    report_path = run_root / "comparison.json"
    if RESUME_EXISTING_RUNS and comparison_path.is_file() and receipts_path.is_file():
        comparison = pd.read_csv(comparison_path)
        expected_rows = {(seed, arm) for seed in SEEDS for arm in (
            "baseline", "mlestar_initial", "mlestar_refined", "mlestar_ensemble"
        )}
        actual_rows = set(zip(comparison["seed"].astype(int), comparison["arm"].astype(str)))
        if actual_rows != expected_rows:
            raise RuntimeError(
                f"Incomplete or incompatible cached comparison for {benchmark}; "
                f"expected {len(expected_rows)} seed/arm rows, got {len(actual_rows)}"
            )
        epoch_evidence_paths = list(run_root.rglob("epoch_selection.json"))
        has_epoch_evidence = bool(epoch_evidence_paths)
        if (
            config["vision"] and not has_epoch_evidence
            and not ALLOW_LEGACY_FIXED_EPOCH_OOF_RESUME
        ):
            raise RuntimeError(
                f"{benchmark} has legacy fixed-epoch OOF artifacts. Set "
                "ALLOW_LEGACY_FIXED_EPOCH_OOF_RESUME=True to reuse them, or delete "
                "the run directory to recompute with MLE-selected epochs."
            )
        if not config["vision"]:
            protocol = "not_applicable_tree_models"
        elif has_epoch_evidence:
            epoch_records = [
                record
                for path in epoch_evidence_paths
                for record in json.loads(path.read_text()).get("records", [])
            ]
            metric = get_task(benchmark).metric
            expected_criterion = (
                f"{'maximum' if metric.greater_is_better else 'minimum'} "
                f"inner-validation {metric.name}"
            )
            if not epoch_records or any(
                record.get("criterion") != expected_criterion
                for record in epoch_records
            ):
                raise RuntimeError(
                    f"Cached {benchmark} artifacts did not select epochs by the "
                    f"official metric ({expected_criterion}). Move or delete that "
                    "run directory before the formal rerun."
                )
            protocol = "mle_inner_official_metric_selected_epochs"
        else:
            protocol = "legacy_fixed_3_epochs"
        report = (
            json.loads(report_path.read_text())
            if report_path.is_file()
            else {"benchmark": benchmark, "status": "resumed_from_artifacts"}
        )
        COMPLETED[benchmark] = {
            "data_root": str(data_root), "run_root": str(run_root),
            "report": report, "resumed": True, "oof_epoch_protocol": protocol,
        }
        print(f"RESUME {benchmark}: OOF comparison skipped ({protocol}).")
        display(comparison)
        display(comparison.groupby("arm")["metric_value"].agg(["mean", "std", "count"]))
        return report
    adapter_kwargs = {}
    if config["vision"]:
        adapter_kwargs = {
            "pretrained": True,
            "image_size": IMAGE_SIZE,
            "epochs": MAX_EPOCHS,
            "batch_size": BATCH_SIZE,
            "max_train_samples": MAX_TRAIN_SAMPLES_PER_FOLD,
            "num_workers": NUM_WORKERS,
            "use_amp": USE_AMP,
            "min_epochs": MIN_EPOCHS,
            "early_stopping_patience": EARLY_STOPPING_PATIENCE,
            "inner_validation_fraction": INNER_VALIDATION_FRACTION,
        }
    report = compare(
        benchmark=benchmark,
        data_root=data_root,
        run_root=run_root,
        seeds=SEEDS,
        outer_rounds=1,
        inner_rounds=1,
        adapter_kwargs=adapter_kwargs,
    )
    comparison = pd.read_csv(run_root / "comparison.csv")
    COMPLETED[benchmark] = {
        "data_root": str(data_root), "run_root": str(run_root), "report": report,
        "resumed": False,
        "oof_epoch_protocol": (
            "mle_inner_official_metric_selected_epochs"
            if config["vision"] else "not_applicable_tree_models"
        ),
    }
    display(comparison)
    display(comparison.groupby("arm")["metric_value"].agg(["mean", "std", "count"]))
    return report

In [8]:
#@title Kaggle prediction and submission (shared helper) { display-mode: "form" }
# Generic final prediction, validation, Kaggle API submission and status capture.
# Each dataset cell below calls run_complete_benchmark exactly once.
import json
import os
import subprocess
from io import StringIO
from pathlib import Path
from time import monotonic, sleep

import numpy as np
import pandas as pd
from timm import create_model
from benchmarks.catalog import get_task
from mlestar.ensemble import blend_test_predictions, select_ensemble

PIPELINE_RESULTS = {}

def build_mle_ensemble_plans(benchmark, data_root, run_root):
    task = get_task(benchmark)
    receipts = [
        json.loads(line)
        for line in (Path(run_root) / "receipts.jsonl").read_text().splitlines()
        if line.strip()
    ]
    if benchmark == "leaf_classification":
        labels = pd.read_csv(Path(data_root) / "train.csv")["species"].astype(str).to_numpy()
    else:
        _, _, labels, _ = vision_data(benchmark, data_root)
    plans = []
    for seed in SEEDS:
        def receipt_for(phase):
            matched = [
                row for row in receipts
                if row.get("phase") == phase and int(row.get("seed")) == seed
                and row.get("metric_value") is not None
            ]
            if len(matched) != 1:
                raise RuntimeError(
                    f"Expected one successful {phase} receipt for {benchmark}, seed {seed}"
                )
            return matched[0]

        baseline = receipt_for("baseline")
        initial_selected = receipt_for("initial_selected")
        refined = receipt_for("refined_selected")
        baseline_oof = pd.read_csv(Path(run_root) / f"seed_{seed}" / baseline["oof_path"])
        refined_oof = pd.read_csv(Path(run_root) / f"seed_{seed}" / refined["oof_path"])
        baseline_values = baseline_oof.iloc[:, 1:].to_numpy(dtype=float)
        refined_values = refined_oof.iloc[:, 1:].to_numpy(dtype=float)
        if baseline_values.shape[1] == 1:
            baseline_values = baseline_values[:, 0]
            refined_values = refined_values[:, 0]
        score_transform = None
        if task.modality == "image_ordinal":
            max_label = int(np.max(labels))
            score_transform = lambda prediction, bound=max_label: np.clip(
                np.rint(prediction), 0, bound
            )
        ensemble = select_ensemble(
            {
                "baseline": (baseline_oof.iloc[:, 0].astype(str).tolist(), baseline_values),
                "refined": (refined_oof.iloc[:, 0].astype(str).tolist(), refined_values),
            },
            labels,
            task.metric,
            score_transform=score_transform,
        )
        comparison = pd.read_csv(Path(run_root) / "comparison.csv")
        reported = comparison.loc[
            (comparison["seed"] == seed)
            & (comparison["arm"] == "mlestar_ensemble"),
            "metric_value",
        ]
        if len(reported) != 1 or not np.isclose(
            float(reported.iloc[0]), float(ensemble.score.value), rtol=0, atol=1e-12
        ):
            raise AssertionError(
                f"Reconstructed ensemble score does not match comparison.csv for seed {seed}"
            )
        plan = {
            "seed": seed,
            "weights": ensemble.weights,
            "oof_score": ensemble.score.value,
            "baseline_receipt": baseline,
            "refined_receipt": refined,
        }
        if benchmark != "leaf_classification":
            initial_id = str(initial_selected["candidate_id"])
            refined_id = str(refined["candidate_id"])
            if refined_id == initial_id:
                refined_model = initial_id
            elif refined_id == f"{initial_id}-model":
                refined_model = (
                    "efficientnet_b0" if initial_id == "resnet18" else "resnet18"
                )
            else:
                raise RuntimeError(
                    f"Cannot reconstruct refined model from initial={initial_id}, refined={refined_id}"
                )
            if refined_model not in {"resnet18", "efficientnet_b0"}:
                raise RuntimeError(f"Unexpected reconstructed model: {refined_model}")
            plan["baseline_model"] = "resnet18"
            plan["refined_model"] = refined_model
        plans.append(plan)
    display(pd.DataFrame([
        {
            "seed": plan["seed"],
            "baseline_weight": plan["weights"]["baseline"],
            "refined_weight": plan["weights"]["refined"],
            "refined_model": plan.get("refined_model", "receipt test predictions"),
            "reconstructed_oof_score": plan["oof_score"],
        }
        for plan in plans
    ]))
    return plans

def build_leaf_submission(data_root, run_root, plans):
    sample = pd.read_csv(Path(data_root) / "sample_submission.csv")
    id_column = sample.columns[0]
    prediction_frames = []
    for plan in plans:
        seed = plan["seed"]
        candidates = {}
        for name, receipt in (
            ("baseline", plan["baseline_receipt"]),
            ("refined", plan["refined_receipt"]),
        ):
            if not receipt.get("test_path"):
                raise RuntimeError(f"Leaf {name} receipt has no test predictions for seed {seed}")
            frame = pd.read_csv(Path(run_root) / f"seed_{seed}" / receipt["test_path"])
            if list(frame.columns) != list(sample.columns):
                raise ValueError("Leaf prediction columns differ from sample_submission.csv")
            if frame[id_column].astype(str).tolist() != sample[id_column].astype(str).tolist():
                raise ValueError("Leaf test IDs or order differ from sample_submission.csv")
            candidates[name] = frame.iloc[:, 1:].to_numpy(dtype=float)
        prediction_frames.append(blend_test_predictions(candidates, plan["weights"]))
    submission = pd.DataFrame(
        np.mean(np.stack(prediction_frames), axis=0),
        columns=list(sample.columns[1:]),
    )
    submission.insert(0, id_column, sample[id_column].to_numpy())
    return submission

def vision_data(benchmark, data_root):
    root = Path(data_root)
    sample = pd.read_csv(root / "sample_submission.csv")
    if benchmark == "plant_pathology_2020":
        train = pd.read_csv(root / "train.csv")
        labels = train[["healthy", "multiple_diseases", "rust", "scab"]].to_numpy(float)
        train_paths = [root / "images" / f"{value}.jpg" for value in train["image_id"].astype(str)]
        test_paths = [root / "images" / f"{value}.jpg" for value in sample["image_id"].astype(str)]
    elif benchmark == "aptos_2019":
        train = pd.read_csv(root / "train.csv")
        labels = train["diagnosis"].to_numpy(float)
        train_paths = [root / "train_images" / f"{value}.png" for value in train["id_code"].astype(str)]
        test_paths = [root / "test_images" / f"{value}.png" for value in sample["id_code"].astype(str)]
    elif benchmark == "dog_breed":
        train = pd.read_csv(root / "labels.csv")
        classes = list(sample.columns[1:])
        mapping = {name: index for index, name in enumerate(classes)}
        if train["breed"].map(mapping).isna().any():
            raise ValueError("Dog Breed labels contain a class absent from sample_submission.csv")
        labels = train["breed"].map(mapping).to_numpy(int)
        train_paths = [root / "train" / f"{value}.jpg" for value in train["id"].astype(str)]
        test_paths = [root / "test" / f"{value}.jpg" for value in sample["id"].astype(str)]
    elif benchmark == "aerial_cactus":
        train = pd.read_csv(root / "train.csv")
        labels = train["has_cactus"].to_numpy(float)
        train_paths = [root / "train" / value for value in train["id"].astype(str)]
        test_paths = [root / "test" / value for value in sample["id"].astype(str)]
    elif benchmark == "dogs_vs_cats":
        train_paths = sorted((root / "train").glob("*.jpg"))
        labels = np.asarray([1.0 if path.name.startswith("dog.") else 0.0 for path in train_paths])
        test_paths = [root / "test" / f"{value}.jpg" for value in sample["id"].astype(str)]
    elif benchmark == "histopathologic_cancer":
        train = pd.read_csv(root / "train_labels.csv")
        labels = train["label"].to_numpy(float)
        train_paths = [root / "train" / f"{value}.tif" for value in train["id"].astype(str)]
        test_paths = [root / "test" / f"{value}.tif" for value in sample["id"].astype(str)]
    else:
        raise KeyError(benchmark)
    missing = [str(path) for path in train_paths + test_paths if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Missing {benchmark} images, examples: {missing[:5]}")
    return sample, train_paths, labels, test_paths

def build_vision_submission(benchmark, data_root, run_root, plans):
    task = get_task(benchmark)
    sample, train_paths, labels, test_paths = vision_data(benchmark, data_root)
    adapter_class = experiment_module.ADAPTER_CLASSES[benchmark]
    predictions = []
    checkpoint_root = Path(run_root) / "final_checkpoints"
    checkpoint_root.mkdir(parents=True, exist_ok=True)
    for plan in plans:
        seed = plan["seed"]
        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        adapter = adapter_class(
            data_root, Path(run_root) / f"final_seed_{seed}", task,
            pretrained=True, image_size=IMAGE_SIZE, epochs=MAX_EPOCHS,
            batch_size=BATCH_SIZE, max_train_samples=None,
            num_workers=NUM_WORKERS, use_amp=USE_AMP,
            min_epochs=MIN_EPOCHS,
            early_stopping_patience=EARLY_STOPPING_PATIENCE,
            inner_validation_fraction=INNER_VALIDATION_FRACTION,
        )
        targets = adapter._prepare_targets(np.asarray(labels))
        train_dataset = vision._ImageDataset(train_paths, targets, IMAGE_SIZE)
        if task.modality == "image_multiclass":
            dummy = torch.zeros(len(test_paths), dtype=torch.long)
        elif task.modality == "image_multilabel":
            dummy = torch.zeros((len(test_paths), len(task.target_columns)), dtype=torch.float32)
        else:
            dummy = torch.zeros((len(test_paths), 1), dtype=torch.float32)
        test_dataset = vision._ImageDataset(test_paths, dummy, IMAGE_SIZE)
        num_classes = adapter._num_classes(np.asarray(labels))
        candidate_predictions = {}
        weighted_models = {}
        for arm_name in ("baseline", "refined"):
            weight = float(plan["weights"][arm_name])
            if weight > 0.0:
                model_name = plan[f"{arm_name}_model"]
                weighted_models[model_name] = weighted_models.get(model_name, 0.0) + weight
        if not weighted_models:
            raise RuntimeError(f"Seed {seed} has no positive MLE ensemble weight")
        for model_name in sorted(weighted_models):
            # Seed each candidate independently, matching the adapter's OOF
            # model construction instead of letting one model consume the
            # next model's random-number stream.
            torch.manual_seed(seed)
            torch.cuda.manual_seed_all(seed)
            model = create_model(model_name, pretrained=True, num_classes=num_classes).to(vision._DEVICE)
            checkpoint_path = checkpoint_root / f"{model_name}_seed_{seed}.pt"
            resumed = False
            if RESUME_EXISTING_RUNS and checkpoint_path.is_file():
                try:
                    checkpoint = torch.load(
                        checkpoint_path, map_location=vision._DEVICE, weights_only=False
                    )
                except TypeError:  # compatibility with older PyTorch
                    checkpoint = torch.load(checkpoint_path, map_location=vision._DEVICE)
                if checkpoint.get("model_name") != model_name or int(checkpoint.get("seed")) != int(seed):
                    raise ValueError(f"Checkpoint metadata mismatch: {checkpoint_path}")
                model.load_state_dict(checkpoint["model"])
                resumed = True
                print(f"Resume final checkpoint: benchmark={benchmark} seed={seed} model={model_name}")
            if not resumed:
                print(f"Final fit: benchmark={benchmark} seed={seed} model={model_name}")
                adapter._epoch_context = {
                    "phase": "final_full_data",
                    "candidate_id": model_name,
                    "model": model_name,
                }
                adapter._fit(model, train_dataset, seed)
                temporary_path = checkpoint_path.with_suffix(".tmp.pt")
                torch.save(
                    {"model": model.state_dict(), "model_name": model_name, "seed": seed},
                    temporary_path,
                )
                temporary_path.replace(checkpoint_path)
            candidate_predictions[model_name] = np.asarray(
                adapter._predict(model, test_dataset), dtype=np.float64
            )
            del model
            torch.cuda.empty_cache()
        predictions.append(sum(
            weight * candidate_predictions[model_name]
            for model_name, weight in weighted_models.items()
        ))
        torch.cuda.empty_cache()
    raw = np.stack(predictions, axis=0)
    mean_prediction = raw.mean(axis=0)
    submission = sample.copy()
    if task.modality == "image_ordinal":
        submission[task.submission.prediction_columns[0]] = np.clip(
            np.rint(mean_prediction), 0, int(np.max(labels))
        ).astype(int)
    elif mean_prediction.ndim == 1:
        submission[task.submission.prediction_columns[0]] = mean_prediction
    else:
        columns = list(sample.columns[1:]) if task.submission.prediction_from_sample else list(task.target_columns)
        if mean_prediction.shape != (len(sample), len(columns)):
            raise ValueError(
                f"Prediction shape {mean_prediction.shape} does not match {len(columns)} columns"
            )
        submission[columns] = mean_prediction
    np.save(Path(run_root) / "raw_test_predictions.npy", raw)
    return submission

def validate_submission(benchmark, data_root, submission):
    task = get_task(benchmark)
    sample = pd.read_csv(Path(data_root) / "sample_submission.csv")
    id_column = task.submission.id_columns[0]
    if list(submission.columns) != list(sample.columns):
        raise AssertionError(f"{benchmark}: columns differ from sample_submission.csv")
    if len(submission) != len(sample):
        raise AssertionError(f"{benchmark}: row count differs from sample_submission.csv")
    if submission[id_column].astype(str).tolist() != sample[id_column].astype(str).tolist():
        raise AssertionError(f"{benchmark}: IDs or order differ from sample_submission.csv")
    values = submission.drop(columns=[id_column]).to_numpy(dtype=float)
    if not np.isfinite(values).all():
        raise AssertionError(f"{benchmark}: predictions contain NaN or infinity")
    if task.modality == "image_ordinal":
        if not np.equal(values, np.rint(values)).all() or not ((values >= 0) & (values <= 4)).all():
            raise AssertionError("APTOS predictions must be integer grades 0..4")
    elif not ((values >= 0) & (values <= 1)).all():
        raise AssertionError(f"{benchmark}: probabilities are outside [0, 1]")
    print(f"Validated {benchmark} submission: rows={len(submission)}, columns={len(submission.columns)}")

def collect_epoch_selection(run_root):
    records = []
    for path in sorted(Path(run_root).rglob("epoch_selection.json")):
        payload = json.loads(path.read_text())
        for record in payload.get("records", []):
            records.append({"artifact": str(path.relative_to(run_root)), **record})
    if not records:
        return [], None
    frame = pd.DataFrame(records)
    output_path = Path(run_root) / "selected_epochs.csv"
    frame.to_csv(output_path, index=False)
    display(frame)
    display(
        frame.groupby(["phase", "model"])["selected_epoch"]
        .agg(["median", "mean", "min", "max", "count"])
    )
    print("Epoch-selection evidence:", output_path)
    return records, str(output_path)

def kaggle_submit_and_capture(benchmark, submission_path):
    slug = TASKS[benchmark]["slug"]
    message = f"{SUBMISSION_PREFIX} | {benchmark}"
    record = {"requested": SUBMIT_ALL_VIA_API, "accepted": False, "message": message}
    if not SUBMIT_ALL_VIA_API:
        record["status"] = "disabled"
        return record
    if not os.environ.get("KAGGLE_API_TOKEN"):
        record.update(status="error", error="KAGGLE_API_TOKEN is not configured")
        return record
    completed = subprocess.run(
        ["kaggle", "competitions", "submit", slug, "-f", str(submission_path), "-m", message],
        text=True, capture_output=True,
    )
    record.update(
        accepted=(completed.returncode == 0),
        submit_stdout=completed.stdout.strip(),
        submit_stderr=completed.stderr.strip(),
        submit_returncode=completed.returncode,
    )
    print(completed.stdout)
    print(completed.stderr)
    if completed.returncode != 0:
        record["status"] = "api_rejected"
        return record

    deadline = monotonic() + KAGGLE_SCORE_POLL_SECONDS
    while True:
        listing = subprocess.run(
            ["kaggle", "competitions", "submissions", slug, "-v"],
            text=True, capture_output=True,
        )
        record["submissions_stdout"] = listing.stdout.strip()
        record["submissions_stderr"] = listing.stderr.strip()
        try:
            # Older Kaggle CLI versions print an upgrade warning before
            # the CSV header. Start parsing at the actual header so that
            # publicScore/privateScore cannot shift into bogus keys.
            output_lines = listing.stdout.splitlines()
            header_index = next(
                index for index, line in enumerate(output_lines)
                if line.lstrip().startswith("fileName,")
            )
            table = pd.read_csv(StringIO("\n".join(output_lines[header_index:])))
            description_column = next(
                (name for name in table.columns if name.lower() == "description"), None
            )
            matched = table[table[description_column] == message] if description_column else table.head(1)
            if not matched.empty:
                latest = matched.iloc[0].replace({np.nan: None}).to_dict()
                record["latest_submission"] = latest
                status = str(latest.get("status", latest.get("Status", ""))).lower()
                if status and status not in {"pending", "running"}:
                    break
        except Exception as error:
            record["listing_parse_error"] = f"{type(error).__name__}: {error}"
        if monotonic() >= deadline:
            break
        sleep(15)
    record["status"] = "accepted"
    return record

def run_complete_benchmark(benchmark):
    result = {"benchmark": benchmark, "stage": "starting", "success": False}
    PIPELINE_RESULTS[benchmark] = result
    if benchmark not in BENCHMARKS_TO_RUN:
        result.update(stage="skipped", error=None)
        print(f"SKIP {benchmark}")
        return result
    try:
        result["stage"] = "data_download_and_oof_comparison"
        run_benchmark(benchmark)
        info = COMPLETED[benchmark]
        data_root = Path(info["data_root"])
        run_root = Path(info["run_root"])
        plans = build_mle_ensemble_plans(benchmark, data_root, run_root)
        result["oof_epoch_protocol"] = info.get("oof_epoch_protocol")
        result["resumed_oof"] = bool(info.get("resumed"))
        result["final_protocol"] = (
            "per-seed mlestar_ensemble OOF weights, then 3-seed mean; "
            + str(info.get("oof_epoch_protocol", "unknown epoch protocol"))
        )
        result["ensemble_plans"] = plans

        result["stage"] = "final_prediction"
        if benchmark == "leaf_classification":
            submission = build_leaf_submission(data_root, run_root, plans)
        else:
            submission = build_vision_submission(benchmark, data_root, run_root, plans)
        epoch_records, epoch_path = collect_epoch_selection(run_root)
        result["epoch_selection"] = {
            "method": (
                "not applicable to tree models"
                if benchmark == "leaf_classification"
                else (
                    f"{'maximum' if get_task(benchmark).metric.greater_is_better else 'minimum'} "
                    f"{get_task(benchmark).metric.name} on an inner split of each "
                    "training fold"
                )
            ),
            "evidence_path": epoch_path,
            "records": epoch_records,
        }
        validate_submission(benchmark, data_root, submission)
        submission_path = run_root / "submission.csv"
        submission.to_csv(submission_path, index=False)
        result["submission_path"] = str(submission_path)
        display(submission.head())

        result["stage"] = "kaggle_api"
        result["kaggle"] = kaggle_submit_and_capture(benchmark, submission_path)
        result.update(stage="complete", success=True)
    except Exception as error:
        result.update(
            success=False,
            error=f"{type(error).__name__}: {error}",
            failed_stage=result["stage"],
            stage="failed",
        )
        print(f"FAILED {benchmark}: {result['error']}")
        if STOP_ON_PIPELINE_FAILURE:
            raise
    finally:
        result_path = RUNS_ROOT / f"{benchmark}_pipeline_result.json"
        result_path.write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")
        print(json.dumps(result, indent=2, default=str))
    return result

In [10]:
# Dog Breed Identification.
DATA_ROOT = "/content/dog-breed-identification"
RUN_ROOT = RUNS_ROOT / "dog_breed"

# OOF comparison -> MLE ensemble reconstruction -> test prediction ->
# sample_submission validation -> Kaggle API submission.
result = run_complete_benchmark("dog_breed")
pd.read_csv(RUN_ROOT / "comparison.csv") if (RUN_ROOT / "comparison.csv").is_file() else result

Downloading dog-breed-identification.zip to /content/dog-breed-identification
START seed=13 phase=baseline model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.79712 inner_val_loss=4.72916 inner_val_multiclass_log_loss=4.72895 best_multiclass_log_loss=4.72895 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=4.63418 inner_val_loss=4.63875 inner_val_multiclass_log_loss=4.63864 best_multiclass_log_loss=4.63864 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=4.47050 inner_val_loss=4.55845 inner_val_multiclass_log_loss=4.55846 best_multiclass_log_loss=4.55846 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=4.28382 inner_val_loss=4.46430 inner_val_multiclass_log_loss=4.46434 best_multiclass_log_loss=4.46434 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=4.06116 inner_val_loss=4.30017 inner_val_multiclass_log_loss=4.30019 best_multiclass_log_loss=4.30019 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=3.85503 inner_val_loss=4.16015 inner_val_multiclass_log_loss=4.16016 best_multiclass_log_loss=4.16016 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=3.62213 inner_val_loss=4.02149 inner_val_multiclass_log_loss=4.02143 best_multiclass_log_loss=4.02143 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=3.38358 inner_val_loss=3.92640 inner_val_multiclass_log_loss=3.92630 best_multiclass_log_loss=3.92630 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=3.16037 inner_val_loss=3.74665 inner_val_multiclass_log_loss=3.74666 best_multiclass_log_loss=3.74666 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=2.94154 inner_val_loss=3.61659 inner_val_multiclass_log_loss=3.61642 best_multiclass_log_loss=3.61642 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=2.70740 inner_val_loss=3.57256 inner_val_multiclass_log_loss=3.57262 best_multiclass_log_loss=3.57262 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=2.51318 inner_val_loss=3.41889 inner_val_multiclass_log_loss=3.41883 best_multiclass_log_loss=3.41883 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=2.30900 inner_val_loss=3.33224 inner_val_multiclass_log_loss=3.33226 best_multiclass_log_loss=3.33226 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=2.10852 inner_val_loss=3.24151 inner_val_multiclass_log_loss=3.24138 best_multiclass_log_loss=3.24138 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=15/40 loss=1.93431 inner_val_loss=3.17292 inner_val_multiclass_log_loss=3.17292 best_multiclass_log_loss=3.17292 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=16/40 loss=1.75495 inner_val_loss=3.05186 inner_val_multiclass_log_loss=3.05185 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=17/40 loss=1.61348 inner_val_loss=3.05905 inner_val_multiclass_log_loss=3.05913 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=18/40 loss=1.45557 inner_val_loss=2.93761 inner_val_multiclass_log_loss=2.93763 best_multiclass_log_loss=2.93763 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=19/40 loss=1.31580 inner_val_loss=2.89615 inner_val_multiclass_log_loss=2.89613 best_multiclass_log_loss=2.89613 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=20/40 loss=1.17896 inner_val_loss=2.85645 inner_val_multiclass_log_loss=2.85643 best_multiclass_log_loss=2.85643 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=21/40 loss=1.06260 inner_val_loss=2.84489 inner_val_multiclass_log_loss=2.84490 best_multiclass_log_loss=2.84490 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=22/40 loss=0.95822 inner_val_loss=2.84380 inner_val_multiclass_log_loss=2.84387 best_multiclass_log_loss=2.84387 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=23/40 loss=0.85304 inner_val_loss=2.75879 inner_val_multiclass_log_loss=2.75881 best_multiclass_log_loss=2.75881 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=24/40 loss=0.76394 inner_val_loss=2.71588 inner_val_multiclass_log_loss=2.71583 best_multiclass_log_loss=2.71583 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=25/40 loss=0.66081 inner_val_loss=2.69955 inner_val_multiclass_log_loss=2.69955 best_multiclass_log_loss=2.69955 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=26/40 loss=0.59643 inner_val_loss=2.65847 inner_val_multiclass_log_loss=2.65846 best_multiclass_log_loss=2.65846 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=27/40 loss=0.54885 inner_val_loss=2.61736 inner_val_multiclass_log_loss=2.61743 best_multiclass_log_loss=2.61743 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=28/40 loss=0.47104 inner_val_loss=2.60538 inner_val_multiclass_log_loss=2.60538 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=29/40 loss=0.42560 inner_val_loss=2.63189 inner_val_multiclass_log_loss=2.63197 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=30/40 loss=0.37612 inner_val_loss=2.58662 inner_val_multiclass_log_loss=2.58660 best_multiclass_log_loss=2.58660 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=31/40 loss=0.32924 inner_val_loss=2.58299 inner_val_multiclass_log_loss=2.58290 best_multiclass_log_loss=2.58290 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=32/40 loss=0.30257 inner_val_loss=2.57410 inner_val_multiclass_log_loss=2.57407 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=33/40 loss=0.26639 inner_val_loss=2.58165 inner_val_multiclass_log_loss=2.58168 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=34/40 loss=0.23653 inner_val_loss=2.59039 inner_val_multiclass_log_loss=2.59034 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=35/40 loss=0.21390 inner_val_loss=2.52620 inner_val_multiclass_log_loss=2.52621 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=36/40 loss=0.18859 inner_val_loss=2.55555 inner_val_multiclass_log_loss=2.55550 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=37/40 loss=0.18017 inner_val_loss=2.52622 inner_val_multiclass_log_loss=2.52619 best_multiclass_log_loss=2.52619 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=38/40 loss=0.17026 inner_val_loss=2.50314 inner_val_multiclass_log_loss=2.50314 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=39/40 loss=0.14754 inner_val_loss=2.56508 inner_val_multiclass_log_loss=2.56509 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.1
  fit=1 epoch=40/40 loss=0.12889 inner_val_loss=2.50436 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/38 loss=4.79225
  fit=1 full_refit_epoch=2/38 loss=4.62037
  fit=1 full_refit_epoch=3/38 loss=4.44866
  fit=1 full_refit_epoch=4/38 loss=4.24984
  fit=1 full_refit_epoch=5/38 loss=4.01907
  fit=1 full_refit_epoch=6/38 loss=3.77273
  fit=1 full_refit_epoch=7/38 loss=3.52588
  fit=1 full_refit_epoch=8/38 loss=3.28835
  fit=1 full_refit_epoch=9/38 loss=3.03910
  fit=1 full_refit_epoch=10/38 loss=2.80156
  fit=1 full_refit_epoch=11/38 loss=2.57053
  fit=1 full_refit_epoch=12/38 loss=2.36705
  fit=1 full_refit_epoch=13/38 loss=2.15250
  fit=1 full_refit_epoch=14/38 loss=1.96159
  fit=1 full_refit_epoch=15/38 loss=1.78097
  fit=1 full_refit_epoch=16/38 loss=1.61023
  fit=1 full_refit_epoch=17/38 loss=1.43917
  fit=1 full_refit_epoch=18/38 loss=1.28383
  fit=1 full_refit_epoch=19/38 loss=1.15441
  fit=1 full_refit_epoch=20/38 loss=1.03974
  fit=1 full_refit_epoch=21/38 loss=0.91690
  fit=1 full_refit_epoch=22/38 loss=0.81272
  fit=1 full_refit_epoch=23/38 loss=0.72282
  fit=1 full_refit_epoch=24/38 loss=0.63660
  fit=1 full_refit_epoch=25/38 loss=0.56613
  fit=1 full_refit_epoch=26/38 loss=0.48675
  fit=1 full_refit_epoch=27/38 loss=0.42957
  fit=1 full_refit_epoch=28/38 loss=0.37788
  fit=1 full_refit_epoch=29/38 loss=0.33382
  fit=1 full_refit_epoch=30/38 loss=0.29093
  fit=1 full_refit_epoch=31/38 loss=0.25549
  fit=1 full_refit_epoch=32/38 loss=0.22188
  fit=1 full_refit_epoch=33/38 loss=0.20243
  fit=1 full_refit_epoch=34/38 loss=0.18404
  fit=1 full_refit_epoch=35/38 loss=0.16301
  fit=1 full_refit_epoch=36/38 loss=0.14652
  fit=1 full_refit_epoch=37/38 loss=0.12670
  fit=1 full_refit_epoch=38/38 loss=0.12125

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=1/40 loss=4.77553 inner_val_loss=4.73282 inner_val_multiclass_log_loss=4.73275 best_multiclass_log_loss=4.73275 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=2/40 loss=4.60929 inner_val_loss=4.65733 inner_val_multiclass_log_loss=4.65727 best_multiclass_log_loss=4.65727 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=3/40 loss=4.44497 inner_val_loss=4.57370 inner_val_multiclass_log_loss=4.57382 best_multiclass_log_loss=4.57382 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=4/40 loss=4.26319 inner_val_loss=4.48674 inner_val_multiclass_log_loss=4.48677 best_multiclass_log_loss=4.48677 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=5/40 loss=4.05132 inner_val_loss=4.31500 inner_val_multiclass_log_loss=4.31489 best_multiclass_log_loss=4.31489 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=6/40 loss=3.83213 inner_val_loss=4.18845 inner_val_multiclass_log_loss=4.18849 best_multiclass_log_loss=4.18849 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=7/40 loss=3.60732 inner_val_loss=4.05701 inner_val_multiclass_log_loss=4.05700 best_multiclass_log_loss=4.05700 best_epoch=7 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=8/40 loss=3.37940 inner_val_loss=3.91249 inner_val_multiclass_log_loss=3.91254 best_multiclass_log_loss=3.91254 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=9/40 loss=3.16246 inner_val_loss=3.73016 inner_val_multiclass_log_loss=3.73024 best_multiclass_log_loss=3.73024 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=10/40 loss=2.93447 inner_val_loss=3.62519 inner_val_multiclass_log_loss=3.62518 best_multiclass_log_loss=3.62518 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=11/40 loss=2.73591 inner_val_loss=3.53324 inner_val_multiclass_log_loss=3.53315 best_multiclass_log_loss=3.53315 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=12/40 loss=2.54380 inner_val_loss=3.39469 inner_val_multiclass_log_loss=3.39464 best_multiclass_log_loss=3.39464 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=13/40 loss=2.33398 inner_val_loss=3.28263 inner_val_multiclass_log_loss=3.28269 best_multiclass_log_loss=3.28269 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=14/40 loss=2.15448 inner_val_loss=3.21115 inner_val_multiclass_log_loss=3.21125 best_multiclass_log_loss=3.21125 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=15/40 loss=1.97533 inner_val_loss=3.12358 inner_val_multiclass_log_loss=3.12356 best_multiclass_log_loss=3.12356 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=16/40 loss=1.81769 inner_val_loss=3.04291 inner_val_multiclass_log_loss=3.04288 best_multiclass_log_loss=3.04288 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=17/40 loss=1.65459 inner_val_loss=2.97311 inner_val_multiclass_log_loss=2.97315 best_multiclass_log_loss=2.97315 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=18/40 loss=1.50685 inner_val_loss=2.96922 inner_val_multiclass_log_loss=2.96925 best_multiclass_log_loss=2.96925 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=19/40 loss=1.37445 inner_val_loss=2.85292 inner_val_multiclass_log_loss=2.85299 best_multiclass_log_loss=2.85299 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=20/40 loss=1.23541 inner_val_loss=2.80633 inner_val_multiclass_log_loss=2.80623 best_multiclass_log_loss=2.80623 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=21/40 loss=1.11991 inner_val_loss=2.79042 inner_val_multiclass_log_loss=2.79041 best_multiclass_log_loss=2.79041 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=22/40 loss=0.99136 inner_val_loss=2.73539 inner_val_multiclass_log_loss=2.73539 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=23/40 loss=0.89412 inner_val_loss=2.75114 inner_val_multiclass_log_loss=2.75109 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=24/40 loss=0.80540 inner_val_loss=2.66510 inner_val_multiclass_log_loss=2.66506 best_multiclass_log_loss=2.66506 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=25/40 loss=0.70602 inner_val_loss=2.65098 inner_val_multiclass_log_loss=2.65102 best_multiclass_log_loss=2.65102 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=26/40 loss=0.64932 inner_val_loss=2.62828 inner_val_multiclass_log_loss=2.62830 best_multiclass_log_loss=2.62830 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=27/40 loss=0.56294 inner_val_loss=2.61059 inner_val_multiclass_log_loss=2.61052 best_multiclass_log_loss=2.61052 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=28/40 loss=0.49822 inner_val_loss=2.59601 inner_val_multiclass_log_loss=2.59603 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=29/40 loss=0.44012 inner_val_loss=2.59872 inner_val_multiclass_log_loss=2.59876 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=30/40 loss=0.39518 inner_val_loss=2.59065 inner_val_multiclass_log_loss=2.59064 best_multiclass_log_loss=2.59064 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=31/40 loss=0.35534 inner_val_loss=2.57242 inner_val_multiclass_log_loss=2.57239 best_multiclass_log_loss=2.57239 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=32/40 loss=0.30867 inner_val_loss=2.54830 inner_val_multiclass_log_loss=2.54820 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=33/40 loss=0.27341 inner_val_loss=2.55249 inner_val_multiclass_log_loss=2.55252 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=34/40 loss=0.25661 inner_val_loss=2.51456 inner_val_multiclass_log_loss=2.51453 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=35/40 loss=0.22872 inner_val_loss=2.53000 inner_val_multiclass_log_loss=2.53009 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=36/40 loss=0.20184 inner_val_loss=2.53498 inner_val_multiclass_log_loss=2.53499 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=37/40 loss=0.17962 inner_val_loss=2.52292 inner_val_multiclass_log_loss=2.52285 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=38/40 loss=0.16442 inner_val_loss=2.49969 inner_val_multiclass_log_loss=2.49963 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=39/40 loss=0.15781 inner_val_loss=2.51261 inner_val_multiclass_log_loss=2.51263 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.1
  fit=2 epoch=40/40 loss=0.13961 inner_val_loss=2.51653 inner_val_multiclass_log_loss=2.51653 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 full_refit_epoch=1/38 loss=4.77411
  fit=2 full_refit_epoch=2/38 loss=4.59733
  fit=2 full_refit_epoch=3/38 loss=4.41914
  fit=2 full_refit_epoch=4/38 loss=4.20830
  fit=2 full_refit_epoch=5/38 loss=3.97909
  fit=2 full_refit_epoch=6/38 loss=3.73578
  fit=2 full_refit_epoch=7/38 loss=3.50391
  fit=2 full_refit_epoch=8/38 loss=3.26557
  fit=2 full_refit_epoch=9/38 loss=3.01664
  fit=2 full_refit_epoch=10/38 loss=2.81115
  fit=2 full_refit_epoch=11/38 loss=2.57071
  fit=2 full_refit_epoch=12/38 loss=2.37255
  fit=2 full_refit_epoch=13/38 loss=2.16822
  fit=2 full_refit_epoch=14/38 loss=1.98347
  fit=2 full_refit_epoch=15/38 loss=1.80699
  fit=2 full_refit_epoch=16/38 loss=1.63341
  fit=2 full_refit_epoch=17/38 loss=1.47600
  fit=2 full_refit_epoch=18/38 loss=1.34416
  fit=2 full_refit_epoch=19/38 loss=1.18925
  fit=2 full_refit_epoch=20/38 loss=1.07348
  fit=2 full_refit_epoch=21/38 loss=0.95393
  fit=2 full_refit_epoch=22/38 loss=0.85577
  fit=2 full_refit_epoch=23/38 loss=0.74525
  fit=2 full_refit_epoch=24/38 loss=0.65977
  fit=2 full_refit_epoch=25/38 loss=0.57781
  fit=2 full_refit_epoch=26/38 loss=0.50285
  fit=2 full_refit_epoch=27/38 loss=0.44326
  fit=2 full_refit_epoch=28/38 loss=0.39476
  fit=2 full_refit_epoch=29/38 loss=0.34185
  fit=2 full_refit_epoch=30/38 loss=0.30400
  fit=2 full_refit_epoch=31/38 loss=0.25974
  fit=2 full_refit_epoch=32/38 loss=0.23101
  fit=2 full_refit_epoch=33/38 loss=0.20916
  fit=2 full_refit_epoch=34/38 loss=0.18475
  fit=2 full_refit_epoch=35/38 loss=0.16759
  fit=2 full_refit_epoch=36/38 loss=0.14573
  fit=2 full_refit_epoch=37/38 loss=0.13086
  fit=2 full_refit_epoch=38/38 loss=0.11576

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=1/40 loss=4.77044 inner_val_loss=4.75381 inner_val_multiclass_log_loss=4.75377 best_multiclass_log_loss=4.75377 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=2/40 loss=4.60228 inner_val_loss=4.68959 inner_val_multiclass_log_loss=4.68957 best_multiclass_log_loss=4.68957 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=3/40 loss=4.43618 inner_val_loss=4.56964 inner_val_multiclass_log_loss=4.56970 best_multiclass_log_loss=4.56970 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=4/40 loss=4.23672 inner_val_loss=4.48310 inner_val_multiclass_log_loss=4.48330 best_multiclass_log_loss=4.48330 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=5/40 loss=4.03506 inner_val_loss=4.32998 inner_val_multiclass_log_loss=4.32999 best_multiclass_log_loss=4.32999 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=6/40 loss=3.80227 inner_val_loss=4.23324 inner_val_multiclass_log_loss=4.23313 best_multiclass_log_loss=4.23313 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=7/40 loss=3.57462 inner_val_loss=4.04866 inner_val_multiclass_log_loss=4.04869 best_multiclass_log_loss=4.04869 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=8/40 loss=3.34862 inner_val_loss=3.92131 inner_val_multiclass_log_loss=3.92140 best_multiclass_log_loss=3.92140 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=9/40 loss=3.12424 inner_val_loss=3.79331 inner_val_multiclass_log_loss=3.79323 best_multiclass_log_loss=3.79323 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=10/40 loss=2.90596 inner_val_loss=3.59769 inner_val_multiclass_log_loss=3.59771 best_multiclass_log_loss=3.59771 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=11/40 loss=2.68628 inner_val_loss=3.55549 inner_val_multiclass_log_loss=3.55536 best_multiclass_log_loss=3.55536 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=12/40 loss=2.47871 inner_val_loss=3.43121 inner_val_multiclass_log_loss=3.43127 best_multiclass_log_loss=3.43127 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=13/40 loss=2.29098 inner_val_loss=3.30385 inner_val_multiclass_log_loss=3.30381 best_multiclass_log_loss=3.30381 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=14/40 loss=2.10778 inner_val_loss=3.26857 inner_val_multiclass_log_loss=3.26864 best_multiclass_log_loss=3.26864 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=15/40 loss=1.93496 inner_val_loss=3.07463 inner_val_multiclass_log_loss=3.07466 best_multiclass_log_loss=3.07466 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=16/40 loss=1.76449 inner_val_loss=3.00117 inner_val_multiclass_log_loss=3.00117 best_multiclass_log_loss=3.00117 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=17/40 loss=1.60781 inner_val_loss=2.97226 inner_val_multiclass_log_loss=2.97225 best_multiclass_log_loss=2.97225 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=18/40 loss=1.46084 inner_val_loss=2.90483 inner_val_multiclass_log_loss=2.90478 best_multiclass_log_loss=2.90478 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=19/40 loss=1.30746 inner_val_loss=2.85118 inner_val_multiclass_log_loss=2.85112 best_multiclass_log_loss=2.85112 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=20/40 loss=1.18474 inner_val_loss=2.76307 inner_val_multiclass_log_loss=2.76312 best_multiclass_log_loss=2.76312 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=21/40 loss=1.07798 inner_val_loss=2.71798 inner_val_multiclass_log_loss=2.71790 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=22/40 loss=0.96543 inner_val_loss=2.74971 inner_val_multiclass_log_loss=2.74973 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=23/40 loss=0.87489 inner_val_loss=2.68882 inner_val_multiclass_log_loss=2.68884 best_multiclass_log_loss=2.68884 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=24/40 loss=0.77007 inner_val_loss=2.64076 inner_val_multiclass_log_loss=2.64069 best_multiclass_log_loss=2.64069 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=25/40 loss=0.68790 inner_val_loss=2.59497 inner_val_multiclass_log_loss=2.59496 best_multiclass_log_loss=2.59496 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=26/40 loss=0.62525 inner_val_loss=2.55839 inner_val_multiclass_log_loss=2.55834 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=27/40 loss=0.54866 inner_val_loss=2.57313 inner_val_multiclass_log_loss=2.57316 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=28/40 loss=0.47933 inner_val_loss=2.54932 inner_val_multiclass_log_loss=2.54928 best_multiclass_log_loss=2.54928 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=29/40 loss=0.44446 inner_val_loss=2.49474 inner_val_multiclass_log_loss=2.49475 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=30/40 loss=0.37983 inner_val_loss=2.50766 inner_val_multiclass_log_loss=2.50771 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=31/40 loss=0.34707 inner_val_loss=2.46953 inner_val_multiclass_log_loss=2.46951 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=32/40 loss=0.30187 inner_val_loss=2.50410 inner_val_multiclass_log_loss=2.50406 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=33/40 loss=0.26999 inner_val_loss=2.48558 inner_val_multiclass_log_loss=2.48560 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=34/40 loss=0.24721 inner_val_loss=2.45993 inner_val_multiclass_log_loss=2.45990 best_multiclass_log_loss=2.45990 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=35/40 loss=0.21843 inner_val_loss=2.44064 inner_val_multiclass_log_loss=2.44068 best_multiclass_log_loss=2.44068 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=36/40 loss=0.20435 inner_val_loss=2.42181 inner_val_multiclass_log_loss=2.42183 best_multiclass_log_loss=2.42183 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=37/40 loss=0.17539 inner_val_loss=2.41809 inner_val_multiclass_log_loss=2.41806 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=38/40 loss=0.15881 inner_val_loss=2.44694 inner_val_multiclass_log_loss=2.44694 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=39/40 loss=0.15315 inner_val_loss=2.42802 inner_val_multiclass_log_loss=2.42807 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0
  fit=3 epoch=40/40 loss=0.13754 inner_val_loss=2.43073 inner_val_multiclass_log_loss=2.43074 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 full_refit_epoch=1/37 loss=4.76610
  fit=3 full_refit_epoch=2/37 loss=4.58809
  fit=3 full_refit_epoch=3/37 loss=4.40191
  fit=3 full_refit_epoch=4/37 loss=4.19280
  fit=3 full_refit_epoch=5/37 loss=3.94694
  fit=3 full_refit_epoch=6/37 loss=3.70573
  fit=3 full_refit_epoch=7/37 loss=3.45771
  fit=3 full_refit_epoch=8/37 loss=3.21290
  fit=3 full_refit_epoch=9/37 loss=2.96554
  fit=3 full_refit_epoch=10/37 loss=2.74399
  fit=3 full_refit_epoch=11/37 loss=2.51527
  fit=3 full_refit_epoch=12/37 loss=2.31445
  fit=3 full_refit_epoch=13/37 loss=2.10738
  fit=3 full_refit_epoch=14/37 loss=1.91163
  fit=3 full_refit_epoch=15/37 loss=1.74298
  fit=3 full_refit_epoch=16/37 loss=1.58161
  fit=3 full_refit_epoch=17/37 loss=1.41502
  fit=3 full_refit_epoch=18/37 loss=1.27785
  fit=3 full_refit_epoch=19/37 loss=1.13593
  fit=3 full_refit_epoch=20/37 loss=1.00394
  fit=3 full_refit_epoch=21/37 loss=0.89995
  fit=3 full_refit_epoch=22/37 loss=0.79272
  fit=3 full_refit_epoch=23/37 loss=0.70862
  fit=3 full_refit_epoch=24/37 loss=0.61145
  fit=3 full_refit_epoch=25/37 loss=0.54015
  fit=3 full_refit_epoch=26/37 loss=0.48481
  fit=3 full_refit_epoch=27/37 loss=0.43559
  fit=3 full_refit_epoch=28/37 loss=0.37559
  fit=3 full_refit_epoch=29/37 loss=0.32676
  fit=3 full_refit_epoch=30/37 loss=0.29414
  fit=3 full_refit_epoch=31/37 loss=0.25896
  fit=3 full_refit_epoch=32/37 loss=0.22610
  fit=3 full_refit_epoch=33/37 loss=0.19819
  fit=3 full_refit_epoch=34/37 loss=0.17827
  fit=3 full_refit_epoch=35/37 loss=0.16779
  fit=3 full_refit_epoch=36/37 loss=0.14451
  fit=3 full_refit_epoch=37/37 loss=0.12893

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=1/40 loss=4.78906 inner_val_loss=4.74795 inner_val_multiclass_log_loss=4.74797 best_multiclass_log_loss=4.74797 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=2/40 loss=4.62550 inner_val_loss=4.68232 inner_val_multiclass_log_loss=4.68236 best_multiclass_log_loss=4.68236 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=3/40 loss=4.46330 inner_val_loss=4.60217 inner_val_multiclass_log_loss=4.60211 best_multiclass_log_loss=4.60211 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=4/40 loss=4.27422 inner_val_loss=4.50101 inner_val_multiclass_log_loss=4.50118 best_multiclass_log_loss=4.50118 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=5/40 loss=4.07407 inner_val_loss=4.37253 inner_val_multiclass_log_loss=4.37265 best_multiclass_log_loss=4.37265 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=6/40 loss=3.84442 inner_val_loss=4.25408 inner_val_multiclass_log_loss=4.25412 best_multiclass_log_loss=4.25412 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=7/40 loss=3.61990 inner_val_loss=4.11079 inner_val_multiclass_log_loss=4.11074 best_multiclass_log_loss=4.11074 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=8/40 loss=3.38342 inner_val_loss=3.96290 inner_val_multiclass_log_loss=3.96301 best_multiclass_log_loss=3.96301 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=9/40 loss=3.15400 inner_val_loss=3.80163 inner_val_multiclass_log_loss=3.80169 best_multiclass_log_loss=3.80169 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=10/40 loss=2.92771 inner_val_loss=3.73142 inner_val_multiclass_log_loss=3.73145 best_multiclass_log_loss=3.73145 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=11/40 loss=2.70259 inner_val_loss=3.60612 inner_val_multiclass_log_loss=3.60612 best_multiclass_log_loss=3.60612 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=12/40 loss=2.49012 inner_val_loss=3.47927 inner_val_multiclass_log_loss=3.47928 best_multiclass_log_loss=3.47928 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=13/40 loss=2.29365 inner_val_loss=3.33652 inner_val_multiclass_log_loss=3.33655 best_multiclass_log_loss=3.33655 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=14/40 loss=2.10643 inner_val_loss=3.26670 inner_val_multiclass_log_loss=3.26674 best_multiclass_log_loss=3.26674 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=15/40 loss=1.91050 inner_val_loss=3.13448 inner_val_multiclass_log_loss=3.13449 best_multiclass_log_loss=3.13449 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=16/40 loss=1.73629 inner_val_loss=3.08385 inner_val_multiclass_log_loss=3.08388 best_multiclass_log_loss=3.08388 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=17/40 loss=1.58935 inner_val_loss=3.00790 inner_val_multiclass_log_loss=3.00798 best_multiclass_log_loss=3.00798 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=18/40 loss=1.42176 inner_val_loss=2.86943 inner_val_multiclass_log_loss=2.86949 best_multiclass_log_loss=2.86949 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=19/40 loss=1.28264 inner_val_loss=2.84649 inner_val_multiclass_log_loss=2.84654 best_multiclass_log_loss=2.84654 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=20/40 loss=1.15295 inner_val_loss=2.82859 inner_val_multiclass_log_loss=2.82862 best_multiclass_log_loss=2.82862 best_epoch=20 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=21/40 loss=1.02289 inner_val_loss=2.75452 inner_val_multiclass_log_loss=2.75460 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=22/40 loss=0.92076 inner_val_loss=2.79044 inner_val_multiclass_log_loss=2.79044 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=23/40 loss=0.82766 inner_val_loss=2.65027 inner_val_multiclass_log_loss=2.65022 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=24/40 loss=0.72237 inner_val_loss=2.68954 inner_val_multiclass_log_loss=2.68958 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=25/40 loss=0.64675 inner_val_loss=2.68187 inner_val_multiclass_log_loss=2.68184 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=26/40 loss=0.57543 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60254 best_multiclass_log_loss=2.60254 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=27/40 loss=0.52233 inner_val_loss=2.55875 inner_val_multiclass_log_loss=2.55874 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=28/40 loss=0.44687 inner_val_loss=2.59887 inner_val_multiclass_log_loss=2.59881 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=29/40 loss=0.40455 inner_val_loss=2.56116 inner_val_multiclass_log_loss=2.56111 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=30/40 loss=0.35947 inner_val_loss=2.54622 inner_val_multiclass_log_loss=2.54619 best_multiclass_log_loss=2.54619 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=31/40 loss=0.30966 inner_val_loss=2.54055 inner_val_multiclass_log_loss=2.54057 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=32/40 loss=0.28341 inner_val_loss=2.60014 inner_val_multiclass_log_loss=2.60014 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=33/40 loss=0.25652 inner_val_loss=2.56220 inner_val_multiclass_log_loss=2.56224 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=34/40 loss=0.22953 inner_val_loss=2.52196 inner_val_multiclass_log_loss=2.52190 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=35/40 loss=0.20994 inner_val_loss=2.52543 inner_val_multiclass_log_loss=2.52545 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=36/40 loss=0.19356 inner_val_loss=2.50430 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=37/40 loss=0.17261 inner_val_loss=2.55080 inner_val_multiclass_log_loss=2.55073 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=38/40 loss=0.14788 inner_val_loss=2.54022 inner_val_multiclass_log_loss=2.54023 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=39/40 loss=0.13704 inner_val_loss=2.51211 inner_val_multiclass_log_loss=2.51212 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0
  fit=4 epoch=40/40 loss=0.12357 inner_val_loss=2.53633 inner_val_multiclass_log_loss=2.53635 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 full_refit_epoch=1/36 loss=4.78933
  fit=4 full_refit_epoch=2/36 loss=4.62183
  fit=4 full_refit_epoch=3/36 loss=4.44740
  fit=4 full_refit_epoch=4/36 loss=4.24532
  fit=4 full_refit_epoch=5/36 loss=4.02094
  fit=4 full_refit_epoch=6/36 loss=3.78293
  fit=4 full_refit_epoch=7/36 loss=3.53231
  fit=4 full_refit_epoch=8/36 loss=3.28427
  fit=4 full_refit_epoch=9/36 loss=3.03381
  fit=4 full_refit_epoch=10/36 loss=2.79936
  fit=4 full_refit_epoch=11/36 loss=2.58011
  fit=4 full_refit_epoch=12/36 loss=2.35711
  fit=4 full_refit_epoch=13/36 loss=2.13863
  fit=4 full_refit_epoch=14/36 loss=1.96065
  fit=4 full_refit_epoch=15/36 loss=1.76849
  fit=4 full_refit_epoch=16/36 loss=1.59651
  fit=4 full_refit_epoch=17/36 loss=1.42424
  fit=4 full_refit_epoch=18/36 loss=1.28335
  fit=4 full_refit_epoch=19/36 loss=1.15012
  fit=4 full_refit_epoch=20/36 loss=1.01315
  fit=4 full_refit_epoch=21/36 loss=0.89809
  fit=4 full_refit_epoch=22/36 loss=0.79891
  fit=4 full_refit_epoch=23/36 loss=0.68675
  fit=4 full_refit_epoch=24/36 loss=0.60914
  fit=4 full_refit_epoch=25/36 loss=0.53905
  fit=4 full_refit_epoch=26/36 loss=0.46530
  fit=4 full_refit_epoch=27/36 loss=0.41107
  fit=4 full_refit_epoch=28/36 loss=0.36036
  fit=4 full_refit_epoch=29/36 loss=0.31609
  fit=4 full_refit_epoch=30/36 loss=0.27736
  fit=4 full_refit_epoch=31/36 loss=0.24527
  fit=4 full_refit_epoch=32/36 loss=0.21381
  fit=4 full_refit_epoch=33/36 loss=0.19448
  fit=4 full_refit_epoch=34/36 loss=0.17119
  fit=4 full_refit_epoch=35/36 loss=0.14893
  fit=4 full_refit_epoch=36/36 loss=0.13754

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=1/40 loss=4.78852 inner_val_loss=4.76904 inner_val_multiclass_log_loss=4.76897 best_multiclass_log_loss=4.76897 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=2/40 loss=4.62429 inner_val_loss=4.71210 inner_val_multiclass_log_loss=4.71216 best_multiclass_log_loss=4.71216 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=3/40 loss=4.46566 inner_val_loss=4.64409 inner_val_multiclass_log_loss=4.64397 best_multiclass_log_loss=4.64397 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=4/40 loss=4.28515 inner_val_loss=4.54058 inner_val_multiclass_log_loss=4.54055 best_multiclass_log_loss=4.54055 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=5/40 loss=4.07529 inner_val_loss=4.44137 inner_val_multiclass_log_loss=4.44133 best_multiclass_log_loss=4.44133 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=6/40 loss=3.85576 inner_val_loss=4.32108 inner_val_multiclass_log_loss=4.32111 best_multiclass_log_loss=4.32111 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=7/40 loss=3.62263 inner_val_loss=4.21201 inner_val_multiclass_log_loss=4.21194 best_multiclass_log_loss=4.21194 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=8/40 loss=3.39331 inner_val_loss=4.03885 inner_val_multiclass_log_loss=4.03889 best_multiclass_log_loss=4.03889 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=9/40 loss=3.15808 inner_val_loss=3.95047 inner_val_multiclass_log_loss=3.95061 best_multiclass_log_loss=3.95061 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=10/40 loss=2.93715 inner_val_loss=3.85990 inner_val_multiclass_log_loss=3.85989 best_multiclass_log_loss=3.85989 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=11/40 loss=2.72324 inner_val_loss=3.73999 inner_val_multiclass_log_loss=3.73991 best_multiclass_log_loss=3.73991 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=12/40 loss=2.52562 inner_val_loss=3.59334 inner_val_multiclass_log_loss=3.59334 best_multiclass_log_loss=3.59334 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=13/40 loss=2.31996 inner_val_loss=3.47636 inner_val_multiclass_log_loss=3.47641 best_multiclass_log_loss=3.47641 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=14/40 loss=2.12754 inner_val_loss=3.39709 inner_val_multiclass_log_loss=3.39711 best_multiclass_log_loss=3.39711 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=15/40 loss=1.95570 inner_val_loss=3.28863 inner_val_multiclass_log_loss=3.28853 best_multiclass_log_loss=3.28853 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=16/40 loss=1.76366 inner_val_loss=3.28249 inner_val_multiclass_log_loss=3.28246 best_multiclass_log_loss=3.28246 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=17/40 loss=1.62190 inner_val_loss=3.19756 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.19763 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=18/40 loss=1.44612 inner_val_loss=3.10082 inner_val_multiclass_log_loss=3.10085 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=19/40 loss=1.31146 inner_val_loss=3.13824 inner_val_multiclass_log_loss=3.13826 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=20/40 loss=1.18608 inner_val_loss=3.02525 inner_val_multiclass_log_loss=3.02514 best_multiclass_log_loss=3.02514 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=21/40 loss=1.05608 inner_val_loss=2.99701 inner_val_multiclass_log_loss=2.99699 best_multiclass_log_loss=2.99699 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=22/40 loss=0.92849 inner_val_loss=2.96264 inner_val_multiclass_log_loss=2.96264 best_multiclass_log_loss=2.96264 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=23/40 loss=0.83730 inner_val_loss=2.89042 inner_val_multiclass_log_loss=2.89043 best_multiclass_log_loss=2.89043 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=24/40 loss=0.72775 inner_val_loss=2.87662 inner_val_multiclass_log_loss=2.87657 best_multiclass_log_loss=2.87657 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=25/40 loss=0.65180 inner_val_loss=2.85888 inner_val_multiclass_log_loss=2.85887 best_multiclass_log_loss=2.85887 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=26/40 loss=0.59433 inner_val_loss=2.81037 inner_val_multiclass_log_loss=2.81039 best_multiclass_log_loss=2.81039 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=27/40 loss=0.51746 inner_val_loss=2.76880 inner_val_multiclass_log_loss=2.76883 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=28/40 loss=0.45104 inner_val_loss=2.78959 inner_val_multiclass_log_loss=2.78966 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=29/40 loss=0.39143 inner_val_loss=2.81155 inner_val_multiclass_log_loss=2.81148 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=30/40 loss=0.36644 inner_val_loss=2.80357 inner_val_multiclass_log_loss=2.80352 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=31/40 loss=0.31340 inner_val_loss=2.75166 inner_val_multiclass_log_loss=2.75162 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=32/40 loss=0.27817 inner_val_loss=2.78633 inner_val_multiclass_log_loss=2.78634 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=33/40 loss=0.24365 inner_val_loss=2.77531 inner_val_multiclass_log_loss=2.77528 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=34/40 loss=0.22111 inner_val_loss=2.75155 inner_val_multiclass_log_loss=2.75155 best_multiclass_log_loss=2.75155 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=35/40 loss=0.20138 inner_val_loss=2.74706 inner_val_multiclass_log_loss=2.74706 best_multiclass_log_loss=2.74706 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=36/40 loss=0.17586 inner_val_loss=2.71929 inner_val_multiclass_log_loss=2.71928 best_multiclass_log_loss=2.71928 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=37/40 loss=0.17020 inner_val_loss=2.71782 inner_val_multiclass_log_loss=2.71780 best_multiclass_log_loss=2.71780 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=38/40 loss=0.14854 inner_val_loss=2.70418 inner_val_multiclass_log_loss=2.70421 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=39/40 loss=0.13157 inner_val_loss=2.75853 inner_val_multiclass_log_loss=2.75848 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0
  fit=5 epoch=40/40 loss=0.12113 inner_val_loss=2.73078 inner_val_multiclass_log_loss=2.73084 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 full_refit_epoch=1/38 loss=4.78588
  fit=5 full_refit_epoch=2/38 loss=4.61993
  fit=5 full_refit_epoch=3/38 loss=4.44642
  fit=5 full_refit_epoch=4/38 loss=4.24635
  fit=5 full_refit_epoch=5/38 loss=4.02090
  fit=5 full_refit_epoch=6/38 loss=3.78011
  fit=5 full_refit_epoch=7/38 loss=3.53233
  fit=5 full_refit_epoch=8/38 loss=3.28899
  fit=5 full_refit_epoch=9/38 loss=3.04329
  fit=5 full_refit_epoch=10/38 loss=2.81072
  fit=5 full_refit_epoch=11/38 loss=2.58246
  fit=5 full_refit_epoch=12/38 loss=2.38099
  fit=5 full_refit_epoch=13/38 loss=2.16343
  fit=5 full_refit_epoch=14/38 loss=1.97204
  fit=5 full_refit_epoch=15/38 loss=1.79387
  fit=5 full_refit_epoch=16/38 loss=1.61716
  fit=5 full_refit_epoch=17/38 loss=1.44508
  fit=5 full_refit_epoch=18/38 loss=1.29190
  fit=5 full_refit_epoch=19/38 loss=1.15543
  fit=5 full_refit_epoch=20/38 loss=1.01886
  fit=5 full_refit_epoch=21/38 loss=0.90017
  fit=5 full_refit_epoch=22/38 loss=0.79421
  fit=5 full_refit_epoch=23/38 loss=0.69174
  fit=5 full_refit_epoch=24/38 loss=0.60423
  fit=5 full_refit_epoch=25/38 loss=0.53090
  fit=5 full_refit_epoch=26/38 loss=0.46597
  fit=5 full_refit_epoch=27/38 loss=0.41092
  fit=5 full_refit_epoch=28/38 loss=0.35185
  fit=5 full_refit_epoch=29/38 loss=0.31449
  fit=5 full_refit_epoch=30/38 loss=0.27410
  fit=5 full_refit_epoch=31/38 loss=0.24654
  fit=5 full_refit_epoch=32/38 loss=0.21647
  fit=5 full_refit_epoch=33/38 loss=0.19490
  fit=5 full_refit_epoch=34/38 loss=0.17505
  fit=5 full_refit_epoch=35/38 loss=0.15285
  fit=5 full_refit_epoch=36/38 loss=0.13916
  fit=5 full_refit_epoch=37/38 loss=0.12314
  fit=5 full_refit_epoch=38/38 loss=0.10869

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=baseline model=resnet18 metric=2.4587492901316477 error=None minutes=13.36
START seed=13 phase=initial model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=1/40 loss=4.79712 inner_val_loss=4.72916 inner_val_multiclass_log_loss=4.72895 best_multiclass_log_loss=4.72895 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=2/40 loss=4.63418 inner_val_loss=4.63875 inner_val_multiclass_log_loss=4.63864 best_multiclass_log_loss=4.63864 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=3/40 loss=4.47050 inner_val_loss=4.55845 inner_val_multiclass_log_loss=4.55846 best_multiclass_log_loss=4.55846 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=4/40 loss=4.28382 inner_val_loss=4.46430 inner_val_multiclass_log_loss=4.46434 best_multiclass_log_loss=4.46434 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=5/40 loss=4.06116 inner_val_loss=4.30017 inner_val_multiclass_log_loss=4.30019 best_multiclass_log_loss=4.30019 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=6/40 loss=3.85503 inner_val_loss=4.16015 inner_val_multiclass_log_loss=4.16016 best_multiclass_log_loss=4.16016 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=7/40 loss=3.62213 inner_val_loss=4.02149 inner_val_multiclass_log_loss=4.02143 best_multiclass_log_loss=4.02143 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=8/40 loss=3.38358 inner_val_loss=3.92640 inner_val_multiclass_log_loss=3.92630 best_multiclass_log_loss=3.92630 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=9/40 loss=3.16037 inner_val_loss=3.74665 inner_val_multiclass_log_loss=3.74666 best_multiclass_log_loss=3.74666 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=10/40 loss=2.94154 inner_val_loss=3.61659 inner_val_multiclass_log_loss=3.61642 best_multiclass_log_loss=3.61642 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=11/40 loss=2.70740 inner_val_loss=3.57256 inner_val_multiclass_log_loss=3.57262 best_multiclass_log_loss=3.57262 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=12/40 loss=2.51318 inner_val_loss=3.41889 inner_val_multiclass_log_loss=3.41883 best_multiclass_log_loss=3.41883 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=13/40 loss=2.30900 inner_val_loss=3.33224 inner_val_multiclass_log_loss=3.33226 best_multiclass_log_loss=3.33226 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=14/40 loss=2.10852 inner_val_loss=3.24151 inner_val_multiclass_log_loss=3.24138 best_multiclass_log_loss=3.24138 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=15/40 loss=1.93431 inner_val_loss=3.17292 inner_val_multiclass_log_loss=3.17292 best_multiclass_log_loss=3.17292 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=16/40 loss=1.75495 inner_val_loss=3.05186 inner_val_multiclass_log_loss=3.05185 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=17/40 loss=1.61348 inner_val_loss=3.05905 inner_val_multiclass_log_loss=3.05913 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=18/40 loss=1.45557 inner_val_loss=2.93761 inner_val_multiclass_log_loss=2.93763 best_multiclass_log_loss=2.93763 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=19/40 loss=1.31580 inner_val_loss=2.89615 inner_val_multiclass_log_loss=2.89613 best_multiclass_log_loss=2.89613 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=20/40 loss=1.17896 inner_val_loss=2.85645 inner_val_multiclass_log_loss=2.85643 best_multiclass_log_loss=2.85643 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=21/40 loss=1.06260 inner_val_loss=2.84489 inner_val_multiclass_log_loss=2.84490 best_multiclass_log_loss=2.84490 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=22/40 loss=0.95822 inner_val_loss=2.84380 inner_val_multiclass_log_loss=2.84387 best_multiclass_log_loss=2.84387 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=23/40 loss=0.85304 inner_val_loss=2.75879 inner_val_multiclass_log_loss=2.75881 best_multiclass_log_loss=2.75881 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=24/40 loss=0.76394 inner_val_loss=2.71588 inner_val_multiclass_log_loss=2.71583 best_multiclass_log_loss=2.71583 best_epoch=24 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=25/40 loss=0.66081 inner_val_loss=2.69955 inner_val_multiclass_log_loss=2.69955 best_multiclass_log_loss=2.69955 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=26/40 loss=0.59643 inner_val_loss=2.65847 inner_val_multiclass_log_loss=2.65846 best_multiclass_log_loss=2.65846 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=27/40 loss=0.54885 inner_val_loss=2.61736 inner_val_multiclass_log_loss=2.61743 best_multiclass_log_loss=2.61743 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=28/40 loss=0.47104 inner_val_loss=2.60538 inner_val_multiclass_log_loss=2.60538 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=29/40 loss=0.42560 inner_val_loss=2.63189 inner_val_multiclass_log_loss=2.63197 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=30/40 loss=0.37612 inner_val_loss=2.58662 inner_val_multiclass_log_loss=2.58660 best_multiclass_log_loss=2.58660 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=31/40 loss=0.32924 inner_val_loss=2.58299 inner_val_multiclass_log_loss=2.58290 best_multiclass_log_loss=2.58290 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=32/40 loss=0.30257 inner_val_loss=2.57410 inner_val_multiclass_log_loss=2.57407 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=33/40 loss=0.26639 inner_val_loss=2.58165 inner_val_multiclass_log_loss=2.58168 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=34/40 loss=0.23653 inner_val_loss=2.59039 inner_val_multiclass_log_loss=2.59034 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=35/40 loss=0.21390 inner_val_loss=2.52620 inner_val_multiclass_log_loss=2.52621 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=36/40 loss=0.18859 inner_val_loss=2.55555 inner_val_multiclass_log_loss=2.55550 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=37/40 loss=0.18017 inner_val_loss=2.52622 inner_val_multiclass_log_loss=2.52619 best_multiclass_log_loss=2.52619 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=38/40 loss=0.17026 inner_val_loss=2.50314 inner_val_multiclass_log_loss=2.50314 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=39/40 loss=0.14754 inner_val_loss=2.56508 inner_val_multiclass_log_loss=2.56509 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0
  fit=6 epoch=40/40 loss=0.12889 inner_val_loss=2.50436 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 full_refit_epoch=1/38 loss=4.79225
  fit=6 full_refit_epoch=2/38 loss=4.62037
  fit=6 full_refit_epoch=3/38 loss=4.44866
  fit=6 full_refit_epoch=4/38 loss=4.24984
  fit=6 full_refit_epoch=5/38 loss=4.01907
  fit=6 full_refit_epoch=6/38 loss=3.77273
  fit=6 full_refit_epoch=7/38 loss=3.52588
  fit=6 full_refit_epoch=8/38 loss=3.28835
  fit=6 full_refit_epoch=9/38 loss=3.03910
  fit=6 full_refit_epoch=10/38 loss=2.80156
  fit=6 full_refit_epoch=11/38 loss=2.57053
  fit=6 full_refit_epoch=12/38 loss=2.36705
  fit=6 full_refit_epoch=13/38 loss=2.15250
  fit=6 full_refit_epoch=14/38 loss=1.96159
  fit=6 full_refit_epoch=15/38 loss=1.78097
  fit=6 full_refit_epoch=16/38 loss=1.61023
  fit=6 full_refit_epoch=17/38 loss=1.43917
  fit=6 full_refit_epoch=18/38 loss=1.28383
  fit=6 full_refit_epoch=19/38 loss=1.15441
  fit=6 full_refit_epoch=20/38 loss=1.03974
  fit=6 full_refit_epoch=21/38 loss=0.91690
  fit=6 full_refit_epoch=22/38 loss=0.81272
  fit=6 full_refit_epoch=23/38 loss=0.72282
  fit=6 full_refit_epoch=24/38 loss=0.63660
  fit=6 full_refit_epoch=25/38 loss=0.56613
  fit=6 full_refit_epoch=26/38 loss=0.48675
  fit=6 full_refit_epoch=27/38 loss=0.42957
  fit=6 full_refit_epoch=28/38 loss=0.37788
  fit=6 full_refit_epoch=29/38 loss=0.33382
  fit=6 full_refit_epoch=30/38 loss=0.29093
  fit=6 full_refit_epoch=31/38 loss=0.25549
  fit=6 full_refit_epoch=32/38 loss=0.22188
  fit=6 full_refit_epoch=33/38 loss=0.20243
  fit=6 full_refit_epoch=34/38 loss=0.18404
  fit=6 full_refit_epoch=35/38 loss=0.16301
  fit=6 full_refit_epoch=36/38 loss=0.14652
  fit=6 full_refit_epoch=37/38 loss=0.12670
  fit=6 full_refit_epoch=38/38 loss=0.12125

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=1/40 loss=4.77553 inner_val_loss=4.73282 inner_val_multiclass_log_loss=4.73275 best_multiclass_log_loss=4.73275 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=2/40 loss=4.60929 inner_val_loss=4.65733 inner_val_multiclass_log_loss=4.65727 best_multiclass_log_loss=4.65727 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=3/40 loss=4.44497 inner_val_loss=4.57370 inner_val_multiclass_log_loss=4.57382 best_multiclass_log_loss=4.57382 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=4/40 loss=4.26319 inner_val_loss=4.48674 inner_val_multiclass_log_loss=4.48677 best_multiclass_log_loss=4.48677 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=5/40 loss=4.05132 inner_val_loss=4.31500 inner_val_multiclass_log_loss=4.31489 best_multiclass_log_loss=4.31489 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=6/40 loss=3.83213 inner_val_loss=4.18845 inner_val_multiclass_log_loss=4.18849 best_multiclass_log_loss=4.18849 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=7/40 loss=3.60732 inner_val_loss=4.05701 inner_val_multiclass_log_loss=4.05700 best_multiclass_log_loss=4.05700 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=8/40 loss=3.37940 inner_val_loss=3.91249 inner_val_multiclass_log_loss=3.91254 best_multiclass_log_loss=3.91254 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=9/40 loss=3.16246 inner_val_loss=3.73016 inner_val_multiclass_log_loss=3.73024 best_multiclass_log_loss=3.73024 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=10/40 loss=2.93447 inner_val_loss=3.62519 inner_val_multiclass_log_loss=3.62518 best_multiclass_log_loss=3.62518 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=11/40 loss=2.73591 inner_val_loss=3.53324 inner_val_multiclass_log_loss=3.53315 best_multiclass_log_loss=3.53315 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=12/40 loss=2.54380 inner_val_loss=3.39469 inner_val_multiclass_log_loss=3.39464 best_multiclass_log_loss=3.39464 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=13/40 loss=2.33398 inner_val_loss=3.28263 inner_val_multiclass_log_loss=3.28269 best_multiclass_log_loss=3.28269 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=14/40 loss=2.15448 inner_val_loss=3.21115 inner_val_multiclass_log_loss=3.21125 best_multiclass_log_loss=3.21125 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=15/40 loss=1.97533 inner_val_loss=3.12358 inner_val_multiclass_log_loss=3.12356 best_multiclass_log_loss=3.12356 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=16/40 loss=1.81769 inner_val_loss=3.04291 inner_val_multiclass_log_loss=3.04288 best_multiclass_log_loss=3.04288 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=17/40 loss=1.65459 inner_val_loss=2.97311 inner_val_multiclass_log_loss=2.97315 best_multiclass_log_loss=2.97315 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=18/40 loss=1.50685 inner_val_loss=2.96922 inner_val_multiclass_log_loss=2.96925 best_multiclass_log_loss=2.96925 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=19/40 loss=1.37445 inner_val_loss=2.85292 inner_val_multiclass_log_loss=2.85299 best_multiclass_log_loss=2.85299 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=20/40 loss=1.23541 inner_val_loss=2.80633 inner_val_multiclass_log_loss=2.80623 best_multiclass_log_loss=2.80623 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=21/40 loss=1.11991 inner_val_loss=2.79042 inner_val_multiclass_log_loss=2.79041 best_multiclass_log_loss=2.79041 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=22/40 loss=0.99136 inner_val_loss=2.73539 inner_val_multiclass_log_loss=2.73539 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=23/40 loss=0.89412 inner_val_loss=2.75114 inner_val_multiclass_log_loss=2.75109 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=24/40 loss=0.80540 inner_val_loss=2.66510 inner_val_multiclass_log_loss=2.66506 best_multiclass_log_loss=2.66506 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=25/40 loss=0.70602 inner_val_loss=2.65098 inner_val_multiclass_log_loss=2.65102 best_multiclass_log_loss=2.65102 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=26/40 loss=0.64932 inner_val_loss=2.62828 inner_val_multiclass_log_loss=2.62830 best_multiclass_log_loss=2.62830 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=27/40 loss=0.56294 inner_val_loss=2.61059 inner_val_multiclass_log_loss=2.61052 best_multiclass_log_loss=2.61052 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=28/40 loss=0.49822 inner_val_loss=2.59601 inner_val_multiclass_log_loss=2.59603 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=29/40 loss=0.44012 inner_val_loss=2.59872 inner_val_multiclass_log_loss=2.59876 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=30/40 loss=0.39518 inner_val_loss=2.59065 inner_val_multiclass_log_loss=2.59064 best_multiclass_log_loss=2.59064 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=31/40 loss=0.35534 inner_val_loss=2.57242 inner_val_multiclass_log_loss=2.57239 best_multiclass_log_loss=2.57239 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=32/40 loss=0.30867 inner_val_loss=2.54830 inner_val_multiclass_log_loss=2.54820 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=33/40 loss=0.27341 inner_val_loss=2.55249 inner_val_multiclass_log_loss=2.55252 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=34/40 loss=0.25661 inner_val_loss=2.51456 inner_val_multiclass_log_loss=2.51453 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=35/40 loss=0.22872 inner_val_loss=2.53000 inner_val_multiclass_log_loss=2.53009 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=36/40 loss=0.20184 inner_val_loss=2.53498 inner_val_multiclass_log_loss=2.53499 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=37/40 loss=0.17962 inner_val_loss=2.52292 inner_val_multiclass_log_loss=2.52285 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=38/40 loss=0.16442 inner_val_loss=2.49969 inner_val_multiclass_log_loss=2.49963 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=39/40 loss=0.15781 inner_val_loss=2.51261 inner_val_multiclass_log_loss=2.51263 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.2
  fit=7 epoch=40/40 loss=0.13961 inner_val_loss=2.51653 inner_val_multiclass_log_loss=2.51653 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 full_refit_epoch=1/38 loss=4.77411
  fit=7 full_refit_epoch=2/38 loss=4.59733
  fit=7 full_refit_epoch=3/38 loss=4.41914
  fit=7 full_refit_epoch=4/38 loss=4.20830
  fit=7 full_refit_epoch=5/38 loss=3.97909
  fit=7 full_refit_epoch=6/38 loss=3.73578
  fit=7 full_refit_epoch=7/38 loss=3.50391
  fit=7 full_refit_epoch=8/38 loss=3.26557
  fit=7 full_refit_epoch=9/38 loss=3.01664
  fit=7 full_refit_epoch=10/38 loss=2.81115
  fit=7 full_refit_epoch=11/38 loss=2.57071
  fit=7 full_refit_epoch=12/38 loss=2.37255
  fit=7 full_refit_epoch=13/38 loss=2.16822
  fit=7 full_refit_epoch=14/38 loss=1.98347
  fit=7 full_refit_epoch=15/38 loss=1.80699
  fit=7 full_refit_epoch=16/38 loss=1.63341
  fit=7 full_refit_epoch=17/38 loss=1.47600
  fit=7 full_refit_epoch=18/38 loss=1.34416
  fit=7 full_refit_epoch=19/38 loss=1.18925
  fit=7 full_refit_epoch=20/38 loss=1.07348
  fit=7 full_refit_epoch=21/38 loss=0.95393
  fit=7 full_refit_epoch=22/38 loss=0.85577
  fit=7 full_refit_epoch=23/38 loss=0.74525
  fit=7 full_refit_epoch=24/38 loss=0.65977
  fit=7 full_refit_epoch=25/38 loss=0.57781
  fit=7 full_refit_epoch=26/38 loss=0.50285
  fit=7 full_refit_epoch=27/38 loss=0.44326
  fit=7 full_refit_epoch=28/38 loss=0.39476
  fit=7 full_refit_epoch=29/38 loss=0.34185
  fit=7 full_refit_epoch=30/38 loss=0.30400
  fit=7 full_refit_epoch=31/38 loss=0.25974
  fit=7 full_refit_epoch=32/38 loss=0.23101
  fit=7 full_refit_epoch=33/38 loss=0.20916
  fit=7 full_refit_epoch=34/38 loss=0.18475
  fit=7 full_refit_epoch=35/38 loss=0.16759
  fit=7 full_refit_epoch=36/38 loss=0.14573
  fit=7 full_refit_epoch=37/38 loss=0.13086
  fit=7 full_refit_epoch=38/38 loss=0.11576

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=1/40 loss=4.77044 inner_val_loss=4.75381 inner_val_multiclass_log_loss=4.75377 best_multiclass_log_loss=4.75377 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=2/40 loss=4.60228 inner_val_loss=4.68959 inner_val_multiclass_log_loss=4.68957 best_multiclass_log_loss=4.68957 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=3/40 loss=4.43618 inner_val_loss=4.56964 inner_val_multiclass_log_loss=4.56970 best_multiclass_log_loss=4.56970 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=4/40 loss=4.23672 inner_val_loss=4.48310 inner_val_multiclass_log_loss=4.48330 best_multiclass_log_loss=4.48330 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=5/40 loss=4.03506 inner_val_loss=4.32998 inner_val_multiclass_log_loss=4.32999 best_multiclass_log_loss=4.32999 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=6/40 loss=3.80227 inner_val_loss=4.23324 inner_val_multiclass_log_loss=4.23313 best_multiclass_log_loss=4.23313 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=7/40 loss=3.57462 inner_val_loss=4.04866 inner_val_multiclass_log_loss=4.04869 best_multiclass_log_loss=4.04869 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=8/40 loss=3.34862 inner_val_loss=3.92131 inner_val_multiclass_log_loss=3.92140 best_multiclass_log_loss=3.92140 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=9/40 loss=3.12424 inner_val_loss=3.79331 inner_val_multiclass_log_loss=3.79323 best_multiclass_log_loss=3.79323 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=10/40 loss=2.90596 inner_val_loss=3.59769 inner_val_multiclass_log_loss=3.59771 best_multiclass_log_loss=3.59771 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=11/40 loss=2.68628 inner_val_loss=3.55549 inner_val_multiclass_log_loss=3.55536 best_multiclass_log_loss=3.55536 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=12/40 loss=2.47871 inner_val_loss=3.43121 inner_val_multiclass_log_loss=3.43127 best_multiclass_log_loss=3.43127 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=13/40 loss=2.29098 inner_val_loss=3.30385 inner_val_multiclass_log_loss=3.30381 best_multiclass_log_loss=3.30381 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=14/40 loss=2.10778 inner_val_loss=3.26857 inner_val_multiclass_log_loss=3.26864 best_multiclass_log_loss=3.26864 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=15/40 loss=1.93496 inner_val_loss=3.07463 inner_val_multiclass_log_loss=3.07466 best_multiclass_log_loss=3.07466 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=16/40 loss=1.76449 inner_val_loss=3.00117 inner_val_multiclass_log_loss=3.00117 best_multiclass_log_loss=3.00117 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=17/40 loss=1.60781 inner_val_loss=2.97226 inner_val_multiclass_log_loss=2.97225 best_multiclass_log_loss=2.97225 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=18/40 loss=1.46084 inner_val_loss=2.90483 inner_val_multiclass_log_loss=2.90478 best_multiclass_log_loss=2.90478 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=19/40 loss=1.30746 inner_val_loss=2.85118 inner_val_multiclass_log_loss=2.85112 best_multiclass_log_loss=2.85112 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=20/40 loss=1.18474 inner_val_loss=2.76307 inner_val_multiclass_log_loss=2.76312 best_multiclass_log_loss=2.76312 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=21/40 loss=1.07798 inner_val_loss=2.71798 inner_val_multiclass_log_loss=2.71790 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=22/40 loss=0.96543 inner_val_loss=2.74971 inner_val_multiclass_log_loss=2.74973 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=23/40 loss=0.87489 inner_val_loss=2.68882 inner_val_multiclass_log_loss=2.68884 best_multiclass_log_loss=2.68884 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=24/40 loss=0.77007 inner_val_loss=2.64076 inner_val_multiclass_log_loss=2.64069 best_multiclass_log_loss=2.64069 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=25/40 loss=0.68790 inner_val_loss=2.59497 inner_val_multiclass_log_loss=2.59496 best_multiclass_log_loss=2.59496 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=26/40 loss=0.62525 inner_val_loss=2.55839 inner_val_multiclass_log_loss=2.55834 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=27/40 loss=0.54866 inner_val_loss=2.57313 inner_val_multiclass_log_loss=2.57316 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=28/40 loss=0.47933 inner_val_loss=2.54932 inner_val_multiclass_log_loss=2.54928 best_multiclass_log_loss=2.54928 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=29/40 loss=0.44446 inner_val_loss=2.49474 inner_val_multiclass_log_loss=2.49475 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=30/40 loss=0.37983 inner_val_loss=2.50766 inner_val_multiclass_log_loss=2.50771 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=31/40 loss=0.34707 inner_val_loss=2.46953 inner_val_multiclass_log_loss=2.46951 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=32/40 loss=0.30187 inner_val_loss=2.50410 inner_val_multiclass_log_loss=2.50406 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=33/40 loss=0.26999 inner_val_loss=2.48558 inner_val_multiclass_log_loss=2.48560 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=34/40 loss=0.24721 inner_val_loss=2.45993 inner_val_multiclass_log_loss=2.45990 best_multiclass_log_loss=2.45990 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=35/40 loss=0.21843 inner_val_loss=2.44064 inner_val_multiclass_log_loss=2.44068 best_multiclass_log_loss=2.44068 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=36/40 loss=0.20435 inner_val_loss=2.42181 inner_val_multiclass_log_loss=2.42183 best_multiclass_log_loss=2.42183 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=37/40 loss=0.17539 inner_val_loss=2.41809 inner_val_multiclass_log_loss=2.41806 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=38/40 loss=0.15881 inner_val_loss=2.44694 inner_val_multiclass_log_loss=2.44694 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=39/40 loss=0.15315 inner_val_loss=2.42802 inner_val_multiclass_log_loss=2.42807 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1
  fit=8 epoch=40/40 loss=0.13754 inner_val_loss=2.43073 inner_val_multiclass_log_loss=2.43074 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 full_refit_epoch=1/37 loss=4.76610
  fit=8 full_refit_epoch=2/37 loss=4.58809
  fit=8 full_refit_epoch=3/37 loss=4.40191
  fit=8 full_refit_epoch=4/37 loss=4.19280
  fit=8 full_refit_epoch=5/37 loss=3.94694
  fit=8 full_refit_epoch=6/37 loss=3.70573
  fit=8 full_refit_epoch=7/37 loss=3.45771
  fit=8 full_refit_epoch=8/37 loss=3.21290
  fit=8 full_refit_epoch=9/37 loss=2.96554
  fit=8 full_refit_epoch=10/37 loss=2.74399
  fit=8 full_refit_epoch=11/37 loss=2.51527
  fit=8 full_refit_epoch=12/37 loss=2.31445
  fit=8 full_refit_epoch=13/37 loss=2.10738
  fit=8 full_refit_epoch=14/37 loss=1.91163
  fit=8 full_refit_epoch=15/37 loss=1.74298
  fit=8 full_refit_epoch=16/37 loss=1.58161
  fit=8 full_refit_epoch=17/37 loss=1.41502
  fit=8 full_refit_epoch=18/37 loss=1.27785
  fit=8 full_refit_epoch=19/37 loss=1.13593
  fit=8 full_refit_epoch=20/37 loss=1.00394
  fit=8 full_refit_epoch=21/37 loss=0.89995
  fit=8 full_refit_epoch=22/37 loss=0.79272
  fit=8 full_refit_epoch=23/37 loss=0.70862
  fit=8 full_refit_epoch=24/37 loss=0.61145
  fit=8 full_refit_epoch=25/37 loss=0.54015
  fit=8 full_refit_epoch=26/37 loss=0.48481
  fit=8 full_refit_epoch=27/37 loss=0.43559
  fit=8 full_refit_epoch=28/37 loss=0.37559
  fit=8 full_refit_epoch=29/37 loss=0.32676
  fit=8 full_refit_epoch=30/37 loss=0.29414
  fit=8 full_refit_epoch=31/37 loss=0.25896
  fit=8 full_refit_epoch=32/37 loss=0.22610
  fit=8 full_refit_epoch=33/37 loss=0.19819
  fit=8 full_refit_epoch=34/37 loss=0.17827
  fit=8 full_refit_epoch=35/37 loss=0.16779
  fit=8 full_refit_epoch=36/37 loss=0.14451
  fit=8 full_refit_epoch=37/37 loss=0.12893

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=1/40 loss=4.78906 inner_val_loss=4.74795 inner_val_multiclass_log_loss=4.74797 best_multiclass_log_loss=4.74797 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=2/40 loss=4.62550 inner_val_loss=4.68232 inner_val_multiclass_log_loss=4.68236 best_multiclass_log_loss=4.68236 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=3/40 loss=4.46330 inner_val_loss=4.60217 inner_val_multiclass_log_loss=4.60211 best_multiclass_log_loss=4.60211 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=4/40 loss=4.27422 inner_val_loss=4.50101 inner_val_multiclass_log_loss=4.50118 best_multiclass_log_loss=4.50118 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=5/40 loss=4.07407 inner_val_loss=4.37253 inner_val_multiclass_log_loss=4.37265 best_multiclass_log_loss=4.37265 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=6/40 loss=3.84442 inner_val_loss=4.25408 inner_val_multiclass_log_loss=4.25412 best_multiclass_log_loss=4.25412 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=7/40 loss=3.61990 inner_val_loss=4.11079 inner_val_multiclass_log_loss=4.11074 best_multiclass_log_loss=4.11074 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=8/40 loss=3.38342 inner_val_loss=3.96290 inner_val_multiclass_log_loss=3.96301 best_multiclass_log_loss=3.96301 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=9/40 loss=3.15400 inner_val_loss=3.80163 inner_val_multiclass_log_loss=3.80169 best_multiclass_log_loss=3.80169 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=10/40 loss=2.92771 inner_val_loss=3.73142 inner_val_multiclass_log_loss=3.73145 best_multiclass_log_loss=3.73145 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=11/40 loss=2.70259 inner_val_loss=3.60612 inner_val_multiclass_log_loss=3.60612 best_multiclass_log_loss=3.60612 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=12/40 loss=2.49012 inner_val_loss=3.47927 inner_val_multiclass_log_loss=3.47928 best_multiclass_log_loss=3.47928 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=13/40 loss=2.29365 inner_val_loss=3.33652 inner_val_multiclass_log_loss=3.33655 best_multiclass_log_loss=3.33655 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=14/40 loss=2.10643 inner_val_loss=3.26670 inner_val_multiclass_log_loss=3.26674 best_multiclass_log_loss=3.26674 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=15/40 loss=1.91050 inner_val_loss=3.13448 inner_val_multiclass_log_loss=3.13449 best_multiclass_log_loss=3.13449 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=16/40 loss=1.73629 inner_val_loss=3.08385 inner_val_multiclass_log_loss=3.08388 best_multiclass_log_loss=3.08388 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=17/40 loss=1.58935 inner_val_loss=3.00790 inner_val_multiclass_log_loss=3.00798 best_multiclass_log_loss=3.00798 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=18/40 loss=1.42176 inner_val_loss=2.86943 inner_val_multiclass_log_loss=2.86949 best_multiclass_log_loss=2.86949 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=19/40 loss=1.28264 inner_val_loss=2.84649 inner_val_multiclass_log_loss=2.84654 best_multiclass_log_loss=2.84654 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=20/40 loss=1.15295 inner_val_loss=2.82859 inner_val_multiclass_log_loss=2.82862 best_multiclass_log_loss=2.82862 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=21/40 loss=1.02289 inner_val_loss=2.75452 inner_val_multiclass_log_loss=2.75460 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=22/40 loss=0.92076 inner_val_loss=2.79044 inner_val_multiclass_log_loss=2.79044 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=23/40 loss=0.82766 inner_val_loss=2.65027 inner_val_multiclass_log_loss=2.65022 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=24/40 loss=0.72237 inner_val_loss=2.68954 inner_val_multiclass_log_loss=2.68958 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=25/40 loss=0.64675 inner_val_loss=2.68187 inner_val_multiclass_log_loss=2.68184 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=26/40 loss=0.57543 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60254 best_multiclass_log_loss=2.60254 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=27/40 loss=0.52233 inner_val_loss=2.55875 inner_val_multiclass_log_loss=2.55874 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=28/40 loss=0.44687 inner_val_loss=2.59887 inner_val_multiclass_log_loss=2.59881 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=29/40 loss=0.40455 inner_val_loss=2.56116 inner_val_multiclass_log_loss=2.56111 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=30/40 loss=0.35947 inner_val_loss=2.54622 inner_val_multiclass_log_loss=2.54619 best_multiclass_log_loss=2.54619 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=31/40 loss=0.30966 inner_val_loss=2.54055 inner_val_multiclass_log_loss=2.54057 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=32/40 loss=0.28341 inner_val_loss=2.60014 inner_val_multiclass_log_loss=2.60014 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=33/40 loss=0.25652 inner_val_loss=2.56220 inner_val_multiclass_log_loss=2.56224 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=34/40 loss=0.22953 inner_val_loss=2.52196 inner_val_multiclass_log_loss=2.52190 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=35/40 loss=0.20994 inner_val_loss=2.52543 inner_val_multiclass_log_loss=2.52545 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=36/40 loss=0.19356 inner_val_loss=2.50430 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=37/40 loss=0.17261 inner_val_loss=2.55080 inner_val_multiclass_log_loss=2.55073 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=38/40 loss=0.14788 inner_val_loss=2.54022 inner_val_multiclass_log_loss=2.54023 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=39/40 loss=0.13704 inner_val_loss=2.51211 inner_val_multiclass_log_loss=2.51212 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1
  fit=9 epoch=40/40 loss=0.12357 inner_val_loss=2.53633 inner_val_multiclass_log_loss=2.53635 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 full_refit_epoch=1/36 loss=4.78933
  fit=9 full_refit_epoch=2/36 loss=4.62183
  fit=9 full_refit_epoch=3/36 loss=4.44740
  fit=9 full_refit_epoch=4/36 loss=4.24532
  fit=9 full_refit_epoch=5/36 loss=4.02094
  fit=9 full_refit_epoch=6/36 loss=3.78293
  fit=9 full_refit_epoch=7/36 loss=3.53231
  fit=9 full_refit_epoch=8/36 loss=3.28427
  fit=9 full_refit_epoch=9/36 loss=3.03381
  fit=9 full_refit_epoch=10/36 loss=2.79936
  fit=9 full_refit_epoch=11/36 loss=2.58011
  fit=9 full_refit_epoch=12/36 loss=2.35711
  fit=9 full_refit_epoch=13/36 loss=2.13863
  fit=9 full_refit_epoch=14/36 loss=1.96065
  fit=9 full_refit_epoch=15/36 loss=1.76849
  fit=9 full_refit_epoch=16/36 loss=1.59651
  fit=9 full_refit_epoch=17/36 loss=1.42424
  fit=9 full_refit_epoch=18/36 loss=1.28335
  fit=9 full_refit_epoch=19/36 loss=1.15012
  fit=9 full_refit_epoch=20/36 loss=1.01315
  fit=9 full_refit_epoch=21/36 loss=0.89809
  fit=9 full_refit_epoch=22/36 loss=0.79891
  fit=9 full_refit_epoch=23/36 loss=0.68675
  fit=9 full_refit_epoch=24/36 loss=0.60914
  fit=9 full_refit_epoch=25/36 loss=0.53905
  fit=9 full_refit_epoch=26/36 loss=0.46530
  fit=9 full_refit_epoch=27/36 loss=0.41107
  fit=9 full_refit_epoch=28/36 loss=0.36036
  fit=9 full_refit_epoch=29/36 loss=0.31609
  fit=9 full_refit_epoch=30/36 loss=0.27736
  fit=9 full_refit_epoch=31/36 loss=0.24527
  fit=9 full_refit_epoch=32/36 loss=0.21381
  fit=9 full_refit_epoch=33/36 loss=0.19448
  fit=9 full_refit_epoch=34/36 loss=0.17119
  fit=9 full_refit_epoch=35/36 loss=0.14893
  fit=9 full_refit_epoch=36/36 loss=0.13754

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=1/40 loss=4.78852 inner_val_loss=4.76904 inner_val_multiclass_log_loss=4.76897 best_multiclass_log_loss=4.76897 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=2/40 loss=4.62429 inner_val_loss=4.71210 inner_val_multiclass_log_loss=4.71216 best_multiclass_log_loss=4.71216 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=3/40 loss=4.46566 inner_val_loss=4.64409 inner_val_multiclass_log_loss=4.64397 best_multiclass_log_loss=4.64397 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=4/40 loss=4.28515 inner_val_loss=4.54058 inner_val_multiclass_log_loss=4.54055 best_multiclass_log_loss=4.54055 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=5/40 loss=4.07529 inner_val_loss=4.44137 inner_val_multiclass_log_loss=4.44133 best_multiclass_log_loss=4.44133 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=6/40 loss=3.85576 inner_val_loss=4.32108 inner_val_multiclass_log_loss=4.32111 best_multiclass_log_loss=4.32111 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=7/40 loss=3.62263 inner_val_loss=4.21201 inner_val_multiclass_log_loss=4.21194 best_multiclass_log_loss=4.21194 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=8/40 loss=3.39331 inner_val_loss=4.03885 inner_val_multiclass_log_loss=4.03889 best_multiclass_log_loss=4.03889 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=9/40 loss=3.15808 inner_val_loss=3.95047 inner_val_multiclass_log_loss=3.95061 best_multiclass_log_loss=3.95061 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=10/40 loss=2.93715 inner_val_loss=3.85990 inner_val_multiclass_log_loss=3.85989 best_multiclass_log_loss=3.85989 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=11/40 loss=2.72324 inner_val_loss=3.73999 inner_val_multiclass_log_loss=3.73991 best_multiclass_log_loss=3.73991 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=12/40 loss=2.52562 inner_val_loss=3.59334 inner_val_multiclass_log_loss=3.59334 best_multiclass_log_loss=3.59334 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=13/40 loss=2.31996 inner_val_loss=3.47636 inner_val_multiclass_log_loss=3.47641 best_multiclass_log_loss=3.47641 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=14/40 loss=2.12754 inner_val_loss=3.39709 inner_val_multiclass_log_loss=3.39711 best_multiclass_log_loss=3.39711 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=15/40 loss=1.95570 inner_val_loss=3.28863 inner_val_multiclass_log_loss=3.28853 best_multiclass_log_loss=3.28853 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=16/40 loss=1.76366 inner_val_loss=3.28249 inner_val_multiclass_log_loss=3.28246 best_multiclass_log_loss=3.28246 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=17/40 loss=1.62190 inner_val_loss=3.19756 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.19763 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=18/40 loss=1.44612 inner_val_loss=3.10082 inner_val_multiclass_log_loss=3.10085 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=19/40 loss=1.31146 inner_val_loss=3.13824 inner_val_multiclass_log_loss=3.13826 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=20/40 loss=1.18608 inner_val_loss=3.02525 inner_val_multiclass_log_loss=3.02514 best_multiclass_log_loss=3.02514 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=21/40 loss=1.05608 inner_val_loss=2.99701 inner_val_multiclass_log_loss=2.99699 best_multiclass_log_loss=2.99699 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=22/40 loss=0.92849 inner_val_loss=2.96264 inner_val_multiclass_log_loss=2.96264 best_multiclass_log_loss=2.96264 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=23/40 loss=0.83730 inner_val_loss=2.89042 inner_val_multiclass_log_loss=2.89043 best_multiclass_log_loss=2.89043 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=24/40 loss=0.72775 inner_val_loss=2.87662 inner_val_multiclass_log_loss=2.87657 best_multiclass_log_loss=2.87657 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=25/40 loss=0.65180 inner_val_loss=2.85888 inner_val_multiclass_log_loss=2.85887 best_multiclass_log_loss=2.85887 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=26/40 loss=0.59433 inner_val_loss=2.81037 inner_val_multiclass_log_loss=2.81039 best_multiclass_log_loss=2.81039 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=27/40 loss=0.51746 inner_val_loss=2.76880 inner_val_multiclass_log_loss=2.76883 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=28/40 loss=0.45104 inner_val_loss=2.78959 inner_val_multiclass_log_loss=2.78966 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=29/40 loss=0.39143 inner_val_loss=2.81155 inner_val_multiclass_log_loss=2.81148 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=30/40 loss=0.36644 inner_val_loss=2.80357 inner_val_multiclass_log_loss=2.80352 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=31/40 loss=0.31340 inner_val_loss=2.75166 inner_val_multiclass_log_loss=2.75162 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=32/40 loss=0.27817 inner_val_loss=2.78633 inner_val_multiclass_log_loss=2.78634 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=33/40 loss=0.24365 inner_val_loss=2.77531 inner_val_multiclass_log_loss=2.77528 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=34/40 loss=0.22111 inner_val_loss=2.75155 inner_val_multiclass_log_loss=2.75155 best_multiclass_log_loss=2.75155 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=35/40 loss=0.20138 inner_val_loss=2.74706 inner_val_multiclass_log_loss=2.74706 best_multiclass_log_loss=2.74706 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=36/40 loss=0.17586 inner_val_loss=2.71929 inner_val_multiclass_log_loss=2.71928 best_multiclass_log_loss=2.71928 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=37/40 loss=0.17020 inner_val_loss=2.71782 inner_val_multiclass_log_loss=2.71780 best_multiclass_log_loss=2.71780 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=38/40 loss=0.14854 inner_val_loss=2.70418 inner_val_multiclass_log_loss=2.70421 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=39/40 loss=0.13157 inner_val_loss=2.75853 inner_val_multiclass_log_loss=2.75848 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.1
  fit=10 epoch=40/40 loss=0.12113 inner_val_loss=2.73078 inner_val_multiclass_log_loss=2.73084 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 full_refit_epoch=1/38 loss=4.78588
  fit=10 full_refit_epoch=2/38 loss=4.61993
  fit=10 full_refit_epoch=3/38 loss=4.44642
  fit=10 full_refit_epoch=4/38 loss=4.24635
  fit=10 full_refit_epoch=5/38 loss=4.02090
  fit=10 full_refit_epoch=6/38 loss=3.78011
  fit=10 full_refit_epoch=7/38 loss=3.53233
  fit=10 full_refit_epoch=8/38 loss=3.28899
  fit=10 full_refit_epoch=9/38 loss=3.04329
  fit=10 full_refit_epoch=10/38 loss=2.81072
  fit=10 full_refit_epoch=11/38 loss=2.58246
  fit=10 full_refit_epoch=12/38 loss=2.38099
  fit=10 full_refit_epoch=13/38 loss=2.16343
  fit=10 full_refit_epoch=14/38 loss=1.97204
  fit=10 full_refit_epoch=15/38 loss=1.79387
  fit=10 full_refit_epoch=16/38 loss=1.61716
  fit=10 full_refit_epoch=17/38 loss=1.44508
  fit=10 full_refit_epoch=18/38 loss=1.29190
  fit=10 full_refit_epoch=19/38 loss=1.15543
  fit=10 full_refit_epoch=20/38 loss=1.01886
  fit=10 full_refit_epoch=21/38 loss=0.90017
  fit=10 full_refit_epoch=22/38 loss=0.79421
  fit=10 full_refit_epoch=23/38 loss=0.69174
  fit=10 full_refit_epoch=24/38 loss=0.60423
  fit=10 full_refit_epoch=25/38 loss=0.53090
  fit=10 full_refit_epoch=26/38 loss=0.46597
  fit=10 full_refit_epoch=27/38 loss=0.41092
  fit=10 full_refit_epoch=28/38 loss=0.35185
  fit=10 full_refit_epoch=29/38 loss=0.31449
  fit=10 full_refit_epoch=30/38 loss=0.27410
  fit=10 full_refit_epoch=31/38 loss=0.24654
  fit=10 full_refit_epoch=32/38 loss=0.21647
  fit=10 full_refit_epoch=33/38 loss=0.19490
  fit=10 full_refit_epoch=34/38 loss=0.17505
  fit=10 full_refit_epoch=35/38 loss=0.15285
  fit=10 full_refit_epoch=36/38 loss=0.13916
  fit=10 full_refit_epoch=37/38 loss=0.12314
  fit=10 full_refit_epoch=38/38 loss=0.10869

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=initial model=resnet18 metric=2.4587492901316477 error=None minutes=13.32
START seed=13 phase=initial model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=1/40 loss=4.99036 inner_val_loss=4.97611 inner_val_multiclass_log_loss=4.97623 best_multiclass_log_loss=4.97623 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=2/40 loss=3.86951 inner_val_loss=4.66832 inner_val_multiclass_log_loss=4.66829 best_multiclass_log_loss=4.66829 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=3/40 loss=2.86598 inner_val_loss=4.36706 inner_val_multiclass_log_loss=4.36709 best_multiclass_log_loss=4.36709 best_epoch=3 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=4/40 loss=2.09927 inner_val_loss=4.12978 inner_val_multiclass_log_loss=4.12960 best_multiclass_log_loss=4.12960 best_epoch=4 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=5/40 loss=1.47379 inner_val_loss=3.91091 inner_val_multiclass_log_loss=3.91094 best_multiclass_log_loss=3.91094 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=6/40 loss=1.04768 inner_val_loss=3.74101 inner_val_multiclass_log_loss=3.74110 best_multiclass_log_loss=3.74110 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=7/40 loss=0.73715 inner_val_loss=3.63261 inner_val_multiclass_log_loss=3.63263 best_multiclass_log_loss=3.63263 best_epoch=7 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=8/40 loss=0.49567 inner_val_loss=3.53976 inner_val_multiclass_log_loss=3.53977 best_multiclass_log_loss=3.53977 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=9/40 loss=0.35736 inner_val_loss=3.46971 inner_val_multiclass_log_loss=3.46964 best_multiclass_log_loss=3.46964 best_epoch=9 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=10/40 loss=0.26701 inner_val_loss=3.42923 inner_val_multiclass_log_loss=3.42920 best_multiclass_log_loss=3.42920 best_epoch=10 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=11/40 loss=0.19902 inner_val_loss=3.43796 inner_val_multiclass_log_loss=3.43808 best_multiclass_log_loss=3.42920 best_epoch=10 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=12/40 loss=0.16136 inner_val_loss=3.36230 inner_val_multiclass_log_loss=3.36233 best_multiclass_log_loss=3.36233 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=13/40 loss=0.13671 inner_val_loss=3.34908 inner_val_multiclass_log_loss=3.34915 best_multiclass_log_loss=3.34915 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=14/40 loss=0.11585 inner_val_loss=3.30774 inner_val_multiclass_log_loss=3.30780 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=15/40 loss=0.10349 inner_val_loss=3.32454 inner_val_multiclass_log_loss=3.32450 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=16/40 loss=0.07807 inner_val_loss=3.31154 inner_val_multiclass_log_loss=3.31149 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=17/40 loss=0.07354 inner_val_loss=3.33854 inner_val_multiclass_log_loss=3.33849 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=18/40 loss=0.07539 inner_val_loss=3.25912 inner_val_multiclass_log_loss=3.25914 best_multiclass_log_loss=3.25914 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=19/40 loss=0.06123 inner_val_loss=3.21976 inner_val_multiclass_log_loss=3.21976 best_multiclass_log_loss=3.21976 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=20/40 loss=0.04795 inner_val_loss=3.21730 inner_val_multiclass_log_loss=3.21725 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=21/40 loss=0.04407 inner_val_loss=3.28103 inner_val_multiclass_log_loss=3.28111 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=22/40 loss=0.04990 inner_val_loss=3.22119 inner_val_multiclass_log_loss=3.22107 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=23/40 loss=0.04440 inner_val_loss=3.21981 inner_val_multiclass_log_loss=3.21979 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=24/40 loss=0.03520 inner_val_loss=3.21580 inner_val_multiclass_log_loss=3.21583 best_multiclass_log_loss=3.21583 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=25/40 loss=0.03019 inner_val_loss=3.23000 inner_val_multiclass_log_loss=3.22994 best_multiclass_log_loss=3.21583 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=26/40 loss=0.03016 inner_val_loss=3.19271 inner_val_multiclass_log_loss=3.19273 best_multiclass_log_loss=3.19273 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=27/40 loss=0.03207 inner_val_loss=3.16384 inner_val_multiclass_log_loss=3.16386 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=28/40 loss=0.03207 inner_val_loss=3.18086 inner_val_multiclass_log_loss=3.18086 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=29/40 loss=0.02549 inner_val_loss=3.19129 inner_val_multiclass_log_loss=3.19124 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=30/40 loss=0.02544 inner_val_loss=3.15057 inner_val_multiclass_log_loss=3.15063 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=31/40 loss=0.02418 inner_val_loss=3.19703 inner_val_multiclass_log_loss=3.19700 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=32/40 loss=0.02842 inner_val_loss=3.17133 inner_val_multiclass_log_loss=3.17135 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=33/40 loss=0.02037 inner_val_loss=3.27333 inner_val_multiclass_log_loss=3.27328 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=34/40 loss=0.01847 inner_val_loss=3.22376 inner_val_multiclass_log_loss=3.22368 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=2.9
  fit=11 epoch=35/40 loss=0.01911 inner_val_loss=3.20446 inner_val_multiclass_log_loss=3.20447 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 full_refit_epoch=1/30 loss=5.01537
  fit=11 full_refit_epoch=2/30 loss=3.79898
  fit=11 full_refit_epoch=3/30 loss=2.81691
  fit=11 full_refit_epoch=4/30 loss=2.01400
  fit=11 full_refit_epoch=5/30 loss=1.39826
  fit=11 full_refit_epoch=6/30 loss=0.94136
  fit=11 full_refit_epoch=7/30 loss=0.63438
  fit=11 full_refit_epoch=8/30 loss=0.44331
  fit=11 full_refit_epoch=9/30 loss=0.30277
  fit=11 full_refit_epoch=10/30 loss=0.21354
  fit=11 full_refit_epoch=11/30 loss=0.16515
  fit=11 full_refit_epoch=12/30 loss=0.13133
  fit=11 full_refit_epoch=13/30 loss=0.10407
  fit=11 full_refit_epoch=14/30 loss=0.08619
  fit=11 full_refit_epoch=15/30 loss=0.06605
  fit=11 full_refit_epoch=16/30 loss=0.06412
  fit=11 full_refit_epoch=17/30 loss=0.05045
  fit=11 full_refit_epoch=18/30 loss=0.04414
  fit=11 full_refit_epoch=19/30 loss=0.03931
  fit=11 full_refit_epoch=20/30 loss=0.03662
  fit=11 full_refit_epoch=21/30 loss=0.03217
  fit=11 full_refit_epoch=22/30 loss=0.02900
  fit=11 full_refit_epoch=23/30 loss=0.02693
  fit=11 full_refit_epoch=24/30 loss=0.02411
  fit=11 full_refit_epoch=25/30 loss=0.02224
  fit=11 full_refit_epoch=26/30 loss=0.01896
  fit=11 full_refit_epoch=27/30 loss=0.01988
  fit=11 full_refit_epoch=28/30 loss=0.01723
  fit=11 full_refit_epoch=29/30 loss=0.01547
  fit=11 full_refit_epoch=30/30 loss=0.01455

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=1/40 loss=5.00992 inner_val_loss=4.75961 inner_val_multiclass_log_loss=4.75979 best_multiclass_log_loss=4.75979 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=2/40 loss=3.84845 inner_val_loss=4.44167 inner_val_multiclass_log_loss=4.44177 best_multiclass_log_loss=4.44177 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=3/40 loss=2.91570 inner_val_loss=4.14369 inner_val_multiclass_log_loss=4.14368 best_multiclass_log_loss=4.14368 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=4/40 loss=2.11675 inner_val_loss=3.88348 inner_val_multiclass_log_loss=3.88344 best_multiclass_log_loss=3.88344 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=5/40 loss=1.48583 inner_val_loss=3.68816 inner_val_multiclass_log_loss=3.68816 best_multiclass_log_loss=3.68816 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=6/40 loss=1.00633 inner_val_loss=3.51250 inner_val_multiclass_log_loss=3.51247 best_multiclass_log_loss=3.51247 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=7/40 loss=0.69965 inner_val_loss=3.43604 inner_val_multiclass_log_loss=3.43613 best_multiclass_log_loss=3.43613 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=8/40 loss=0.49791 inner_val_loss=3.34718 inner_val_multiclass_log_loss=3.34722 best_multiclass_log_loss=3.34722 best_epoch=8 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=9/40 loss=0.34502 inner_val_loss=3.28710 inner_val_multiclass_log_loss=3.28711 best_multiclass_log_loss=3.28711 best_epoch=9 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=10/40 loss=0.26464 inner_val_loss=3.24824 inner_val_multiclass_log_loss=3.24819 best_multiclass_log_loss=3.24819 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=11/40 loss=0.21598 inner_val_loss=3.18775 inner_val_multiclass_log_loss=3.18778 best_multiclass_log_loss=3.18778 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=12/40 loss=0.16815 inner_val_loss=3.17137 inner_val_multiclass_log_loss=3.17143 best_multiclass_log_loss=3.17143 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=13/40 loss=0.13388 inner_val_loss=3.13357 inner_val_multiclass_log_loss=3.13352 best_multiclass_log_loss=3.13352 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=14/40 loss=0.11197 inner_val_loss=3.11475 inner_val_multiclass_log_loss=3.11474 best_multiclass_log_loss=3.11474 best_epoch=14 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=15/40 loss=0.08880 inner_val_loss=3.10371 inner_val_multiclass_log_loss=3.10376 best_multiclass_log_loss=3.10376 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=16/40 loss=0.09289 inner_val_loss=3.08496 inner_val_multiclass_log_loss=3.08500 best_multiclass_log_loss=3.08500 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=17/40 loss=0.07723 inner_val_loss=3.11840 inner_val_multiclass_log_loss=3.11841 best_multiclass_log_loss=3.08500 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=18/40 loss=0.06629 inner_val_loss=3.08397 inner_val_multiclass_log_loss=3.08402 best_multiclass_log_loss=3.08402 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=19/40 loss=0.06014 inner_val_loss=3.05166 inner_val_multiclass_log_loss=3.05159 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=20/40 loss=0.05484 inner_val_loss=3.06879 inner_val_multiclass_log_loss=3.06886 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=21/40 loss=0.04870 inner_val_loss=3.05673 inner_val_multiclass_log_loss=3.05670 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=22/40 loss=0.04216 inner_val_loss=3.01840 inner_val_multiclass_log_loss=3.01851 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=23/40 loss=0.03570 inner_val_loss=3.08866 inner_val_multiclass_log_loss=3.08867 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=24/40 loss=0.04381 inner_val_loss=3.02241 inner_val_multiclass_log_loss=3.02246 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=25/40 loss=0.03283 inner_val_loss=3.04847 inner_val_multiclass_log_loss=3.04854 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=26/40 loss=0.04609 inner_val_loss=3.02190 inner_val_multiclass_log_loss=3.02190 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=2.9
  fit=12 epoch=27/40 loss=0.03072 inner_val_loss=3.02740 inner_val_multiclass_log_loss=3.02748 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 full_refit_epoch=1/22 loss=4.97448
  fit=12 full_refit_epoch=2/22 loss=3.80416
  fit=12 full_refit_epoch=3/22 loss=2.82054
  fit=12 full_refit_epoch=4/22 loss=1.98839
  fit=12 full_refit_epoch=5/22 loss=1.36942
  fit=12 full_refit_epoch=6/22 loss=0.93086
  fit=12 full_refit_epoch=7/22 loss=0.63039
  fit=12 full_refit_epoch=8/22 loss=0.42832
  fit=12 full_refit_epoch=9/22 loss=0.28680
  fit=12 full_refit_epoch=10/22 loss=0.23010
  fit=12 full_refit_epoch=11/22 loss=0.16731
  fit=12 full_refit_epoch=12/22 loss=0.12764
  fit=12 full_refit_epoch=13/22 loss=0.10052
  fit=12 full_refit_epoch=14/22 loss=0.08987
  fit=12 full_refit_epoch=15/22 loss=0.07087
  fit=12 full_refit_epoch=16/22 loss=0.06400
  fit=12 full_refit_epoch=17/22 loss=0.05344
  fit=12 full_refit_epoch=18/22 loss=0.04902
  fit=12 full_refit_epoch=19/22 loss=0.03863
  fit=12 full_refit_epoch=20/22 loss=0.03833
  fit=12 full_refit_epoch=21/22 loss=0.03375
  fit=12 full_refit_epoch=22/22 loss=0.03340

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=1/40 loss=5.02928 inner_val_loss=4.75876 inner_val_multiclass_log_loss=4.75877 best_multiclass_log_loss=4.75877 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=2/40 loss=3.88965 inner_val_loss=4.45946 inner_val_multiclass_log_loss=4.45952 best_multiclass_log_loss=4.45952 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=3/40 loss=2.94098 inner_val_loss=4.13572 inner_val_multiclass_log_loss=4.13578 best_multiclass_log_loss=4.13578 best_epoch=3 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=4/40 loss=2.11327 inner_val_loss=3.90386 inner_val_multiclass_log_loss=3.90377 best_multiclass_log_loss=3.90377 best_epoch=4 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=5/40 loss=1.52675 inner_val_loss=3.65165 inner_val_multiclass_log_loss=3.65158 best_multiclass_log_loss=3.65158 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=6/40 loss=1.04543 inner_val_loss=3.50287 inner_val_multiclass_log_loss=3.50283 best_multiclass_log_loss=3.50283 best_epoch=6 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=7/40 loss=0.73523 inner_val_loss=3.34494 inner_val_multiclass_log_loss=3.34498 best_multiclass_log_loss=3.34498 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=8/40 loss=0.50714 inner_val_loss=3.24464 inner_val_multiclass_log_loss=3.24462 best_multiclass_log_loss=3.24462 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=9/40 loss=0.36471 inner_val_loss=3.11621 inner_val_multiclass_log_loss=3.11616 best_multiclass_log_loss=3.11616 best_epoch=9 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=10/40 loss=0.27011 inner_val_loss=3.02721 inner_val_multiclass_log_loss=3.02719 best_multiclass_log_loss=3.02719 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=11/40 loss=0.20206 inner_val_loss=3.02960 inner_val_multiclass_log_loss=3.02953 best_multiclass_log_loss=3.02719 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=12/40 loss=0.15179 inner_val_loss=2.98925 inner_val_multiclass_log_loss=2.98932 best_multiclass_log_loss=2.98932 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=13/40 loss=0.14685 inner_val_loss=2.94003 inner_val_multiclass_log_loss=2.94006 best_multiclass_log_loss=2.94006 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=14/40 loss=0.11094 inner_val_loss=2.91133 inner_val_multiclass_log_loss=2.91140 best_multiclass_log_loss=2.91140 best_epoch=14 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=15/40 loss=0.09812 inner_val_loss=2.88417 inner_val_multiclass_log_loss=2.88409 best_multiclass_log_loss=2.88409 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=16/40 loss=0.07885 inner_val_loss=2.83419 inner_val_multiclass_log_loss=2.83425 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=17/40 loss=0.07247 inner_val_loss=2.85331 inner_val_multiclass_log_loss=2.85335 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=18/40 loss=0.06819 inner_val_loss=2.88378 inner_val_multiclass_log_loss=2.88382 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=19/40 loss=0.05696 inner_val_loss=2.86688 inner_val_multiclass_log_loss=2.86689 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=20/40 loss=0.04778 inner_val_loss=2.83068 inner_val_multiclass_log_loss=2.83063 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=21/40 loss=0.05320 inner_val_loss=2.84203 inner_val_multiclass_log_loss=2.84200 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=22/40 loss=0.03946 inner_val_loss=2.84926 inner_val_multiclass_log_loss=2.84917 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=23/40 loss=0.03536 inner_val_loss=2.81412 inner_val_multiclass_log_loss=2.81412 best_multiclass_log_loss=2.81412 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=24/40 loss=0.04317 inner_val_loss=2.87428 inner_val_multiclass_log_loss=2.87423 best_multiclass_log_loss=2.81412 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=25/40 loss=0.03561 inner_val_loss=2.76194 inner_val_multiclass_log_loss=2.76193 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=26/40 loss=0.03697 inner_val_loss=2.77370 inner_val_multiclass_log_loss=2.77371 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=27/40 loss=0.03180 inner_val_loss=2.80618 inner_val_multiclass_log_loss=2.80614 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=28/40 loss=0.02790 inner_val_loss=2.79801 inner_val_multiclass_log_loss=2.79803 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=29/40 loss=0.03464 inner_val_loss=2.75913 inner_val_multiclass_log_loss=2.75912 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=30/40 loss=0.02486 inner_val_loss=2.78148 inner_val_multiclass_log_loss=2.78146 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=31/40 loss=0.03316 inner_val_loss=2.78911 inner_val_multiclass_log_loss=2.78917 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=32/40 loss=0.02018 inner_val_loss=2.87988 inner_val_multiclass_log_loss=2.87981 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=33/40 loss=0.02472 inner_val_loss=2.85514 inner_val_multiclass_log_loss=2.85524 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0
  fit=13 epoch=34/40 loss=0.02243 inner_val_loss=2.81325 inner_val_multiclass_log_loss=2.81314 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 full_refit_epoch=1/29 loss=5.00494
  fit=13 full_refit_epoch=2/29 loss=3.82182
  fit=13 full_refit_epoch=3/29 loss=2.85212
  fit=13 full_refit_epoch=4/29 loss=2.04077
  fit=13 full_refit_epoch=5/29 loss=1.41067
  fit=13 full_refit_epoch=6/29 loss=0.94601
  fit=13 full_refit_epoch=7/29 loss=0.64570
  fit=13 full_refit_epoch=8/29 loss=0.44875
  fit=13 full_refit_epoch=9/29 loss=0.31190
  fit=13 full_refit_epoch=10/29 loss=0.22977
  fit=13 full_refit_epoch=11/29 loss=0.16520
  fit=13 full_refit_epoch=12/29 loss=0.13355
  fit=13 full_refit_epoch=13/29 loss=0.10679
  fit=13 full_refit_epoch=14/29 loss=0.08821
  fit=13 full_refit_epoch=15/29 loss=0.07112
  fit=13 full_refit_epoch=16/29 loss=0.06172
  fit=13 full_refit_epoch=17/29 loss=0.05536
  fit=13 full_refit_epoch=18/29 loss=0.04815
  fit=13 full_refit_epoch=19/29 loss=0.04073
  fit=13 full_refit_epoch=20/29 loss=0.03730
  fit=13 full_refit_epoch=21/29 loss=0.03279
  fit=13 full_refit_epoch=22/29 loss=0.02885
  fit=13 full_refit_epoch=23/29 loss=0.02860
  fit=13 full_refit_epoch=24/29 loss=0.02341
  fit=13 full_refit_epoch=25/29 loss=0.02331
  fit=13 full_refit_epoch=26/29 loss=0.02115
  fit=13 full_refit_epoch=27/29 loss=0.01984
  fit=13 full_refit_epoch=28/29 loss=0.01793
  fit=13 full_refit_epoch=29/29 loss=0.01568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=1/40 loss=4.98903 inner_val_loss=4.89898 inner_val_multiclass_log_loss=4.89885 best_multiclass_log_loss=4.89885 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=2/40 loss=3.82121 inner_val_loss=4.63836 inner_val_multiclass_log_loss=4.63835 best_multiclass_log_loss=4.63835 best_epoch=2 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=3/40 loss=2.88924 inner_val_loss=4.33970 inner_val_multiclass_log_loss=4.33974 best_multiclass_log_loss=4.33974 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=4/40 loss=2.09632 inner_val_loss=4.08573 inner_val_multiclass_log_loss=4.08580 best_multiclass_log_loss=4.08580 best_epoch=4 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=5/40 loss=1.48138 inner_val_loss=3.93854 inner_val_multiclass_log_loss=3.93854 best_multiclass_log_loss=3.93854 best_epoch=5 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=6/40 loss=0.99804 inner_val_loss=3.77461 inner_val_multiclass_log_loss=3.77469 best_multiclass_log_loss=3.77469 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=7/40 loss=0.68846 inner_val_loss=3.67316 inner_val_multiclass_log_loss=3.67313 best_multiclass_log_loss=3.67313 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=8/40 loss=0.48933 inner_val_loss=3.58673 inner_val_multiclass_log_loss=3.58673 best_multiclass_log_loss=3.58673 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=9/40 loss=0.33644 inner_val_loss=3.55173 inner_val_multiclass_log_loss=3.55171 best_multiclass_log_loss=3.55171 best_epoch=9 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=10/40 loss=0.25505 inner_val_loss=3.48588 inner_val_multiclass_log_loss=3.48574 best_multiclass_log_loss=3.48574 best_epoch=10 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=11/40 loss=0.20054 inner_val_loss=3.44556 inner_val_multiclass_log_loss=3.44553 best_multiclass_log_loss=3.44553 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=12/40 loss=0.15455 inner_val_loss=3.40841 inner_val_multiclass_log_loss=3.40840 best_multiclass_log_loss=3.40840 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=13/40 loss=0.12102 inner_val_loss=3.41139 inner_val_multiclass_log_loss=3.41136 best_multiclass_log_loss=3.40840 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=14/40 loss=0.10360 inner_val_loss=3.37341 inner_val_multiclass_log_loss=3.37342 best_multiclass_log_loss=3.37342 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=15/40 loss=0.09872 inner_val_loss=3.35078 inner_val_multiclass_log_loss=3.35079 best_multiclass_log_loss=3.35079 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=16/40 loss=0.07685 inner_val_loss=3.36781 inner_val_multiclass_log_loss=3.36775 best_multiclass_log_loss=3.35079 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=17/40 loss=0.07714 inner_val_loss=3.33298 inner_val_multiclass_log_loss=3.33298 best_multiclass_log_loss=3.33298 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=18/40 loss=0.06124 inner_val_loss=3.35884 inner_val_multiclass_log_loss=3.35893 best_multiclass_log_loss=3.33298 best_epoch=17 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=19/40 loss=0.05238 inner_val_loss=3.29291 inner_val_multiclass_log_loss=3.29290 best_multiclass_log_loss=3.29290 best_epoch=19 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=20/40 loss=0.05201 inner_val_loss=3.38271 inner_val_multiclass_log_loss=3.38274 best_multiclass_log_loss=3.29290 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=21/40 loss=0.04452 inner_val_loss=3.29206 inner_val_multiclass_log_loss=3.29217 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=22/40 loss=0.04371 inner_val_loss=3.37507 inner_val_multiclass_log_loss=3.37513 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=23/40 loss=0.05074 inner_val_loss=3.31665 inner_val_multiclass_log_loss=3.31667 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=24/40 loss=0.04695 inner_val_loss=3.35377 inner_val_multiclass_log_loss=3.35381 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=25/40 loss=0.03638 inner_val_loss=3.35455 inner_val_multiclass_log_loss=3.35450 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.1
  fit=14 epoch=26/40 loss=0.03241 inner_val_loss=3.31469 inner_val_multiclass_log_loss=3.31479 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 full_refit_epoch=1/21 loss=4.99289
  fit=14 full_refit_epoch=2/21 loss=3.80848
  fit=14 full_refit_epoch=3/21 loss=2.81671
  fit=14 full_refit_epoch=4/21 loss=1.99271
  fit=14 full_refit_epoch=5/21 loss=1.40373
  fit=14 full_refit_epoch=6/21 loss=0.92812
  fit=14 full_refit_epoch=7/21 loss=0.61731
  fit=14 full_refit_epoch=8/21 loss=0.42340
  fit=14 full_refit_epoch=9/21 loss=0.28486
  fit=14 full_refit_epoch=10/21 loss=0.21522
  fit=14 full_refit_epoch=11/21 loss=0.16616
  fit=14 full_refit_epoch=12/21 loss=0.12758
  fit=14 full_refit_epoch=13/21 loss=0.10093
  fit=14 full_refit_epoch=14/21 loss=0.08144
  fit=14 full_refit_epoch=15/21 loss=0.07077
  fit=14 full_refit_epoch=16/21 loss=0.06118
  fit=14 full_refit_epoch=17/21 loss=0.05449
  fit=14 full_refit_epoch=18/21 loss=0.04808
  fit=14 full_refit_epoch=19/21 loss=0.04306
  fit=14 full_refit_epoch=20/21 loss=0.03729
  fit=14 full_refit_epoch=21/21 loss=0.03417

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=1/40 loss=4.99133 inner_val_loss=4.80050 inner_val_multiclass_log_loss=4.80046 best_multiclass_log_loss=4.80046 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=2/40 loss=3.83315 inner_val_loss=4.59151 inner_val_multiclass_log_loss=4.59149 best_multiclass_log_loss=4.59149 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=3/40 loss=2.91217 inner_val_loss=4.30327 inner_val_multiclass_log_loss=4.30326 best_multiclass_log_loss=4.30326 best_epoch=3 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=4/40 loss=2.10385 inner_val_loss=4.06685 inner_val_multiclass_log_loss=4.06681 best_multiclass_log_loss=4.06681 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=5/40 loss=1.47456 inner_val_loss=3.87030 inner_val_multiclass_log_loss=3.87028 best_multiclass_log_loss=3.87028 best_epoch=5 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=6/40 loss=1.01236 inner_val_loss=3.77471 inner_val_multiclass_log_loss=3.77471 best_multiclass_log_loss=3.77471 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=7/40 loss=0.71925 inner_val_loss=3.63381 inner_val_multiclass_log_loss=3.63378 best_multiclass_log_loss=3.63378 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=8/40 loss=0.49814 inner_val_loss=3.58678 inner_val_multiclass_log_loss=3.58679 best_multiclass_log_loss=3.58679 best_epoch=8 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=9/40 loss=0.35224 inner_val_loss=3.50579 inner_val_multiclass_log_loss=3.50588 best_multiclass_log_loss=3.50588 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=10/40 loss=0.25242 inner_val_loss=3.46802 inner_val_multiclass_log_loss=3.46803 best_multiclass_log_loss=3.46803 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=11/40 loss=0.19769 inner_val_loss=3.42091 inner_val_multiclass_log_loss=3.42093 best_multiclass_log_loss=3.42093 best_epoch=11 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=12/40 loss=0.17037 inner_val_loss=3.41417 inner_val_multiclass_log_loss=3.41421 best_multiclass_log_loss=3.41421 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=13/40 loss=0.13681 inner_val_loss=3.35525 inner_val_multiclass_log_loss=3.35531 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=14/40 loss=0.11016 inner_val_loss=3.36710 inner_val_multiclass_log_loss=3.36702 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=15/40 loss=0.10173 inner_val_loss=3.35579 inner_val_multiclass_log_loss=3.35585 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=16/40 loss=0.07651 inner_val_loss=3.33813 inner_val_multiclass_log_loss=3.33815 best_multiclass_log_loss=3.33815 best_epoch=16 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=17/40 loss=0.07286 inner_val_loss=3.32815 inner_val_multiclass_log_loss=3.32816 best_multiclass_log_loss=3.32816 best_epoch=17 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=18/40 loss=0.06445 inner_val_loss=3.31810 inner_val_multiclass_log_loss=3.31823 best_multiclass_log_loss=3.31823 best_epoch=18 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=19/40 loss=0.06365 inner_val_loss=3.32532 inner_val_multiclass_log_loss=3.32537 best_multiclass_log_loss=3.31823 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=20/40 loss=0.05656 inner_val_loss=3.28177 inner_val_multiclass_log_loss=3.28172 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=21/40 loss=0.04482 inner_val_loss=3.31671 inner_val_multiclass_log_loss=3.31674 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=22/40 loss=0.04102 inner_val_loss=3.33449 inner_val_multiclass_log_loss=3.33454 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=23/40 loss=0.04465 inner_val_loss=3.31654 inner_val_multiclass_log_loss=3.31656 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=24/40 loss=0.03236 inner_val_loss=3.25695 inner_val_multiclass_log_loss=3.25687 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=25/40 loss=0.04175 inner_val_loss=3.29445 inner_val_multiclass_log_loss=3.29447 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=26/40 loss=0.03368 inner_val_loss=3.25695 inner_val_multiclass_log_loss=3.25691 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=27/40 loss=0.03458 inner_val_loss=3.27971 inner_val_multiclass_log_loss=3.27963 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=28/40 loss=0.03367 inner_val_loss=3.27923 inner_val_multiclass_log_loss=3.27921 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2
  fit=15 epoch=29/40 loss=0.02623 inner_val_loss=3.32177 inner_val_multiclass_log_loss=3.32176 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 full_refit_epoch=1/24 loss=4.95899
  fit=15 full_refit_epoch=2/24 loss=3.77304
  fit=15 full_refit_epoch=3/24 loss=2.80964
  fit=15 full_refit_epoch=4/24 loss=2.02023
  fit=15 full_refit_epoch=5/24 loss=1.39449
  fit=15 full_refit_epoch=6/24 loss=0.93873
  fit=15 full_refit_epoch=7/24 loss=0.63759
  fit=15 full_refit_epoch=8/24 loss=0.43921
  fit=15 full_refit_epoch=9/24 loss=0.30028
  fit=15 full_refit_epoch=10/24 loss=0.23258
  fit=15 full_refit_epoch=11/24 loss=0.16769
  fit=15 full_refit_epoch=12/24 loss=0.13131
  fit=15 full_refit_epoch=13/24 loss=0.10614
  fit=15 full_refit_epoch=14/24 loss=0.08923
  fit=15 full_refit_epoch=15/24 loss=0.07203
  fit=15 full_refit_epoch=16/24 loss=0.06302
  fit=15 full_refit_epoch=17/24 loss=0.05344
  fit=15 full_refit_epoch=18/24 loss=0.04723
  fit=15 full_refit_epoch=19/24 loss=0.04379
  fit=15 full_refit_epoch=20/24 loss=0.03631
  fit=15 full_refit_epoch=21/24 loss=0.03360
  fit=15 full_refit_epoch=22/24 loss=0.03044
  fit=15 full_refit_epoch=23/24 loss=0.02782
  fit=15 full_refit_epoch=24/24 loss=0.02464

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=initial model=efficientnet_b0 metric=2.945880327772081 error=None minutes=14.52
START seed=13 phase=initial_merge model=ensemble:resnet18+efficientnet_b0
END   seed=13 phase=initial_merge model=ensemble:resnet18+efficientnet_b0 metric=None error=AssertionError:  minutes=0.01
START seed=13 phase=initial_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=1/40 loss=4.79712 inner_val_loss=4.72916 inner_val_multiclass_log_loss=4.72895 best_multiclass_log_loss=4.72895 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=2/40 loss=4.63418 inner_val_loss=4.63875 inner_val_multiclass_log_loss=4.63864 best_multiclass_log_loss=4.63864 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=3/40 loss=4.47050 inner_val_loss=4.55845 inner_val_multiclass_log_loss=4.55846 best_multiclass_log_loss=4.55846 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=4/40 loss=4.28382 inner_val_loss=4.46430 inner_val_multiclass_log_loss=4.46434 best_multiclass_log_loss=4.46434 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=5/40 loss=4.06116 inner_val_loss=4.30017 inner_val_multiclass_log_loss=4.30019 best_multiclass_log_loss=4.30019 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=6/40 loss=3.85503 inner_val_loss=4.16015 inner_val_multiclass_log_loss=4.16016 best_multiclass_log_loss=4.16016 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=7/40 loss=3.62213 inner_val_loss=4.02149 inner_val_multiclass_log_loss=4.02143 best_multiclass_log_loss=4.02143 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=8/40 loss=3.38358 inner_val_loss=3.92640 inner_val_multiclass_log_loss=3.92630 best_multiclass_log_loss=3.92630 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=9/40 loss=3.16037 inner_val_loss=3.74665 inner_val_multiclass_log_loss=3.74666 best_multiclass_log_loss=3.74666 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=10/40 loss=2.94154 inner_val_loss=3.61659 inner_val_multiclass_log_loss=3.61642 best_multiclass_log_loss=3.61642 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=11/40 loss=2.70740 inner_val_loss=3.57256 inner_val_multiclass_log_loss=3.57262 best_multiclass_log_loss=3.57262 best_epoch=11 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=12/40 loss=2.51318 inner_val_loss=3.41889 inner_val_multiclass_log_loss=3.41883 best_multiclass_log_loss=3.41883 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=13/40 loss=2.30900 inner_val_loss=3.33224 inner_val_multiclass_log_loss=3.33226 best_multiclass_log_loss=3.33226 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=14/40 loss=2.10852 inner_val_loss=3.24151 inner_val_multiclass_log_loss=3.24138 best_multiclass_log_loss=3.24138 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=15/40 loss=1.93431 inner_val_loss=3.17292 inner_val_multiclass_log_loss=3.17292 best_multiclass_log_loss=3.17292 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=16/40 loss=1.75495 inner_val_loss=3.05186 inner_val_multiclass_log_loss=3.05185 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=17/40 loss=1.61348 inner_val_loss=3.05905 inner_val_multiclass_log_loss=3.05913 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=18/40 loss=1.45557 inner_val_loss=2.93761 inner_val_multiclass_log_loss=2.93763 best_multiclass_log_loss=2.93763 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=19/40 loss=1.31580 inner_val_loss=2.89615 inner_val_multiclass_log_loss=2.89613 best_multiclass_log_loss=2.89613 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=20/40 loss=1.17896 inner_val_loss=2.85645 inner_val_multiclass_log_loss=2.85643 best_multiclass_log_loss=2.85643 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=21/40 loss=1.06260 inner_val_loss=2.84489 inner_val_multiclass_log_loss=2.84490 best_multiclass_log_loss=2.84490 best_epoch=21 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=22/40 loss=0.95822 inner_val_loss=2.84380 inner_val_multiclass_log_loss=2.84387 best_multiclass_log_loss=2.84387 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=23/40 loss=0.85304 inner_val_loss=2.75879 inner_val_multiclass_log_loss=2.75881 best_multiclass_log_loss=2.75881 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=24/40 loss=0.76394 inner_val_loss=2.71588 inner_val_multiclass_log_loss=2.71583 best_multiclass_log_loss=2.71583 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=25/40 loss=0.66081 inner_val_loss=2.69955 inner_val_multiclass_log_loss=2.69955 best_multiclass_log_loss=2.69955 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=26/40 loss=0.59643 inner_val_loss=2.65847 inner_val_multiclass_log_loss=2.65846 best_multiclass_log_loss=2.65846 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=27/40 loss=0.54885 inner_val_loss=2.61736 inner_val_multiclass_log_loss=2.61743 best_multiclass_log_loss=2.61743 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=28/40 loss=0.47104 inner_val_loss=2.60538 inner_val_multiclass_log_loss=2.60538 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=29/40 loss=0.42560 inner_val_loss=2.63189 inner_val_multiclass_log_loss=2.63197 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=30/40 loss=0.37612 inner_val_loss=2.58662 inner_val_multiclass_log_loss=2.58660 best_multiclass_log_loss=2.58660 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=31/40 loss=0.32924 inner_val_loss=2.58299 inner_val_multiclass_log_loss=2.58290 best_multiclass_log_loss=2.58290 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=32/40 loss=0.30257 inner_val_loss=2.57410 inner_val_multiclass_log_loss=2.57407 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=33/40 loss=0.26639 inner_val_loss=2.58165 inner_val_multiclass_log_loss=2.58168 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=34/40 loss=0.23653 inner_val_loss=2.59039 inner_val_multiclass_log_loss=2.59034 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=35/40 loss=0.21390 inner_val_loss=2.52620 inner_val_multiclass_log_loss=2.52621 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=36/40 loss=0.18859 inner_val_loss=2.55555 inner_val_multiclass_log_loss=2.55550 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=37/40 loss=0.18017 inner_val_loss=2.52622 inner_val_multiclass_log_loss=2.52619 best_multiclass_log_loss=2.52619 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=38/40 loss=0.17026 inner_val_loss=2.50314 inner_val_multiclass_log_loss=2.50314 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=39/40 loss=0.14754 inner_val_loss=2.56508 inner_val_multiclass_log_loss=2.56509 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0
  fit=16 epoch=40/40 loss=0.12889 inner_val_loss=2.50436 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 full_refit_epoch=1/38 loss=4.79225
  fit=16 full_refit_epoch=2/38 loss=4.62037
  fit=16 full_refit_epoch=3/38 loss=4.44866
  fit=16 full_refit_epoch=4/38 loss=4.24984
  fit=16 full_refit_epoch=5/38 loss=4.01907
  fit=16 full_refit_epoch=6/38 loss=3.77273
  fit=16 full_refit_epoch=7/38 loss=3.52588
  fit=16 full_refit_epoch=8/38 loss=3.28835
  fit=16 full_refit_epoch=9/38 loss=3.03910
  fit=16 full_refit_epoch=10/38 loss=2.80156
  fit=16 full_refit_epoch=11/38 loss=2.57053
  fit=16 full_refit_epoch=12/38 loss=2.36705
  fit=16 full_refit_epoch=13/38 loss=2.15250
  fit=16 full_refit_epoch=14/38 loss=1.96159
  fit=16 full_refit_epoch=15/38 loss=1.78097
  fit=16 full_refit_epoch=16/38 loss=1.61023
  fit=16 full_refit_epoch=17/38 loss=1.43917
  fit=16 full_refit_epoch=18/38 loss=1.28383
  fit=16 full_refit_epoch=19/38 loss=1.15441
  fit=16 full_refit_epoch=20/38 loss=1.03974
  fit=16 full_refit_epoch=21/38 loss=0.91690
  fit=16 full_refit_epoch=22/38 loss=0.81272
  fit=16 full_refit_epoch=23/38 loss=0.72282
  fit=16 full_refit_epoch=24/38 loss=0.63660
  fit=16 full_refit_epoch=25/38 loss=0.56613
  fit=16 full_refit_epoch=26/38 loss=0.48675
  fit=16 full_refit_epoch=27/38 loss=0.42957
  fit=16 full_refit_epoch=28/38 loss=0.37788
  fit=16 full_refit_epoch=29/38 loss=0.33382
  fit=16 full_refit_epoch=30/38 loss=0.29093
  fit=16 full_refit_epoch=31/38 loss=0.25549
  fit=16 full_refit_epoch=32/38 loss=0.22188
  fit=16 full_refit_epoch=33/38 loss=0.20243
  fit=16 full_refit_epoch=34/38 loss=0.18404
  fit=16 full_refit_epoch=35/38 loss=0.16301
  fit=16 full_refit_epoch=36/38 loss=0.14652
  fit=16 full_refit_epoch=37/38 loss=0.12670
  fit=16 full_refit_epoch=38/38 loss=0.12125

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=1/40 loss=4.77553 inner_val_loss=4.73282 inner_val_multiclass_log_loss=4.73275 best_multiclass_log_loss=4.73275 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=2/40 loss=4.60929 inner_val_loss=4.65733 inner_val_multiclass_log_loss=4.65727 best_multiclass_log_loss=4.65727 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=3/40 loss=4.44497 inner_val_loss=4.57370 inner_val_multiclass_log_loss=4.57382 best_multiclass_log_loss=4.57382 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=4/40 loss=4.26319 inner_val_loss=4.48674 inner_val_multiclass_log_loss=4.48677 best_multiclass_log_loss=4.48677 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=5/40 loss=4.05132 inner_val_loss=4.31500 inner_val_multiclass_log_loss=4.31489 best_multiclass_log_loss=4.31489 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=6/40 loss=3.83213 inner_val_loss=4.18845 inner_val_multiclass_log_loss=4.18849 best_multiclass_log_loss=4.18849 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=7/40 loss=3.60732 inner_val_loss=4.05701 inner_val_multiclass_log_loss=4.05700 best_multiclass_log_loss=4.05700 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=8/40 loss=3.37940 inner_val_loss=3.91249 inner_val_multiclass_log_loss=3.91254 best_multiclass_log_loss=3.91254 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=9/40 loss=3.16246 inner_val_loss=3.73016 inner_val_multiclass_log_loss=3.73024 best_multiclass_log_loss=3.73024 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=10/40 loss=2.93447 inner_val_loss=3.62519 inner_val_multiclass_log_loss=3.62518 best_multiclass_log_loss=3.62518 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=11/40 loss=2.73591 inner_val_loss=3.53324 inner_val_multiclass_log_loss=3.53315 best_multiclass_log_loss=3.53315 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=12/40 loss=2.54380 inner_val_loss=3.39469 inner_val_multiclass_log_loss=3.39464 best_multiclass_log_loss=3.39464 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=13/40 loss=2.33398 inner_val_loss=3.28263 inner_val_multiclass_log_loss=3.28269 best_multiclass_log_loss=3.28269 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=14/40 loss=2.15448 inner_val_loss=3.21115 inner_val_multiclass_log_loss=3.21125 best_multiclass_log_loss=3.21125 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=15/40 loss=1.97533 inner_val_loss=3.12358 inner_val_multiclass_log_loss=3.12356 best_multiclass_log_loss=3.12356 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=16/40 loss=1.81769 inner_val_loss=3.04291 inner_val_multiclass_log_loss=3.04288 best_multiclass_log_loss=3.04288 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=17/40 loss=1.65459 inner_val_loss=2.97311 inner_val_multiclass_log_loss=2.97315 best_multiclass_log_loss=2.97315 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=18/40 loss=1.50685 inner_val_loss=2.96922 inner_val_multiclass_log_loss=2.96925 best_multiclass_log_loss=2.96925 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=19/40 loss=1.37445 inner_val_loss=2.85292 inner_val_multiclass_log_loss=2.85299 best_multiclass_log_loss=2.85299 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=20/40 loss=1.23541 inner_val_loss=2.80633 inner_val_multiclass_log_loss=2.80623 best_multiclass_log_loss=2.80623 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=21/40 loss=1.11991 inner_val_loss=2.79042 inner_val_multiclass_log_loss=2.79041 best_multiclass_log_loss=2.79041 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=22/40 loss=0.99136 inner_val_loss=2.73539 inner_val_multiclass_log_loss=2.73539 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=23/40 loss=0.89412 inner_val_loss=2.75114 inner_val_multiclass_log_loss=2.75109 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=24/40 loss=0.80540 inner_val_loss=2.66510 inner_val_multiclass_log_loss=2.66506 best_multiclass_log_loss=2.66506 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=25/40 loss=0.70602 inner_val_loss=2.65098 inner_val_multiclass_log_loss=2.65102 best_multiclass_log_loss=2.65102 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=26/40 loss=0.64932 inner_val_loss=2.62828 inner_val_multiclass_log_loss=2.62830 best_multiclass_log_loss=2.62830 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=27/40 loss=0.56294 inner_val_loss=2.61059 inner_val_multiclass_log_loss=2.61052 best_multiclass_log_loss=2.61052 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=28/40 loss=0.49822 inner_val_loss=2.59601 inner_val_multiclass_log_loss=2.59603 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=29/40 loss=0.44012 inner_val_loss=2.59872 inner_val_multiclass_log_loss=2.59876 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=30/40 loss=0.39518 inner_val_loss=2.59065 inner_val_multiclass_log_loss=2.59064 best_multiclass_log_loss=2.59064 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=31/40 loss=0.35534 inner_val_loss=2.57242 inner_val_multiclass_log_loss=2.57239 best_multiclass_log_loss=2.57239 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=32/40 loss=0.30867 inner_val_loss=2.54830 inner_val_multiclass_log_loss=2.54820 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=33/40 loss=0.27341 inner_val_loss=2.55249 inner_val_multiclass_log_loss=2.55252 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=34/40 loss=0.25661 inner_val_loss=2.51456 inner_val_multiclass_log_loss=2.51453 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=35/40 loss=0.22872 inner_val_loss=2.53000 inner_val_multiclass_log_loss=2.53009 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=36/40 loss=0.20184 inner_val_loss=2.53498 inner_val_multiclass_log_loss=2.53499 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=37/40 loss=0.17962 inner_val_loss=2.52292 inner_val_multiclass_log_loss=2.52285 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=38/40 loss=0.16442 inner_val_loss=2.49969 inner_val_multiclass_log_loss=2.49963 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=39/40 loss=0.15781 inner_val_loss=2.51261 inner_val_multiclass_log_loss=2.51263 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0
  fit=17 epoch=40/40 loss=0.13961 inner_val_loss=2.51653 inner_val_multiclass_log_loss=2.51653 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 full_refit_epoch=1/38 loss=4.77411
  fit=17 full_refit_epoch=2/38 loss=4.59733
  fit=17 full_refit_epoch=3/38 loss=4.41914
  fit=17 full_refit_epoch=4/38 loss=4.20830
  fit=17 full_refit_epoch=5/38 loss=3.97909
  fit=17 full_refit_epoch=6/38 loss=3.73578
  fit=17 full_refit_epoch=7/38 loss=3.50391
  fit=17 full_refit_epoch=8/38 loss=3.26557
  fit=17 full_refit_epoch=9/38 loss=3.01664
  fit=17 full_refit_epoch=10/38 loss=2.81115
  fit=17 full_refit_epoch=11/38 loss=2.57071
  fit=17 full_refit_epoch=12/38 loss=2.37255
  fit=17 full_refit_epoch=13/38 loss=2.16822
  fit=17 full_refit_epoch=14/38 loss=1.98347
  fit=17 full_refit_epoch=15/38 loss=1.80699
  fit=17 full_refit_epoch=16/38 loss=1.63341
  fit=17 full_refit_epoch=17/38 loss=1.47600
  fit=17 full_refit_epoch=18/38 loss=1.34416
  fit=17 full_refit_epoch=19/38 loss=1.18925
  fit=17 full_refit_epoch=20/38 loss=1.07348
  fit=17 full_refit_epoch=21/38 loss=0.95393
  fit=17 full_refit_epoch=22/38 loss=0.85577
  fit=17 full_refit_epoch=23/38 loss=0.74525
  fit=17 full_refit_epoch=24/38 loss=0.65977
  fit=17 full_refit_epoch=25/38 loss=0.57781
  fit=17 full_refit_epoch=26/38 loss=0.50285
  fit=17 full_refit_epoch=27/38 loss=0.44326
  fit=17 full_refit_epoch=28/38 loss=0.39476
  fit=17 full_refit_epoch=29/38 loss=0.34185
  fit=17 full_refit_epoch=30/38 loss=0.30400
  fit=17 full_refit_epoch=31/38 loss=0.25974
  fit=17 full_refit_epoch=32/38 loss=0.23101
  fit=17 full_refit_epoch=33/38 loss=0.20916
  fit=17 full_refit_epoch=34/38 loss=0.18475
  fit=17 full_refit_epoch=35/38 loss=0.16759
  fit=17 full_refit_epoch=36/38 loss=0.14573
  fit=17 full_refit_epoch=37/38 loss=0.13086
  fit=17 full_refit_epoch=38/38 loss=0.11576

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=1/40 loss=4.77044 inner_val_loss=4.75381 inner_val_multiclass_log_loss=4.75377 best_multiclass_log_loss=4.75377 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=2/40 loss=4.60228 inner_val_loss=4.68959 inner_val_multiclass_log_loss=4.68957 best_multiclass_log_loss=4.68957 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=3/40 loss=4.43618 inner_val_loss=4.56964 inner_val_multiclass_log_loss=4.56970 best_multiclass_log_loss=4.56970 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=4/40 loss=4.23672 inner_val_loss=4.48310 inner_val_multiclass_log_loss=4.48330 best_multiclass_log_loss=4.48330 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=5/40 loss=4.03506 inner_val_loss=4.32998 inner_val_multiclass_log_loss=4.32999 best_multiclass_log_loss=4.32999 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=6/40 loss=3.80227 inner_val_loss=4.23324 inner_val_multiclass_log_loss=4.23313 best_multiclass_log_loss=4.23313 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=7/40 loss=3.57462 inner_val_loss=4.04866 inner_val_multiclass_log_loss=4.04869 best_multiclass_log_loss=4.04869 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=8/40 loss=3.34862 inner_val_loss=3.92131 inner_val_multiclass_log_loss=3.92140 best_multiclass_log_loss=3.92140 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=9/40 loss=3.12424 inner_val_loss=3.79331 inner_val_multiclass_log_loss=3.79323 best_multiclass_log_loss=3.79323 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=10/40 loss=2.90596 inner_val_loss=3.59769 inner_val_multiclass_log_loss=3.59771 best_multiclass_log_loss=3.59771 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=11/40 loss=2.68628 inner_val_loss=3.55549 inner_val_multiclass_log_loss=3.55536 best_multiclass_log_loss=3.55536 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=12/40 loss=2.47871 inner_val_loss=3.43121 inner_val_multiclass_log_loss=3.43127 best_multiclass_log_loss=3.43127 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=13/40 loss=2.29098 inner_val_loss=3.30385 inner_val_multiclass_log_loss=3.30381 best_multiclass_log_loss=3.30381 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=14/40 loss=2.10778 inner_val_loss=3.26857 inner_val_multiclass_log_loss=3.26864 best_multiclass_log_loss=3.26864 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=15/40 loss=1.93496 inner_val_loss=3.07463 inner_val_multiclass_log_loss=3.07466 best_multiclass_log_loss=3.07466 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=16/40 loss=1.76449 inner_val_loss=3.00117 inner_val_multiclass_log_loss=3.00117 best_multiclass_log_loss=3.00117 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=17/40 loss=1.60781 inner_val_loss=2.97226 inner_val_multiclass_log_loss=2.97225 best_multiclass_log_loss=2.97225 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=18/40 loss=1.46084 inner_val_loss=2.90483 inner_val_multiclass_log_loss=2.90478 best_multiclass_log_loss=2.90478 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=19/40 loss=1.30746 inner_val_loss=2.85118 inner_val_multiclass_log_loss=2.85112 best_multiclass_log_loss=2.85112 best_epoch=19 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=20/40 loss=1.18474 inner_val_loss=2.76307 inner_val_multiclass_log_loss=2.76312 best_multiclass_log_loss=2.76312 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=21/40 loss=1.07798 inner_val_loss=2.71798 inner_val_multiclass_log_loss=2.71790 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=22/40 loss=0.96543 inner_val_loss=2.74971 inner_val_multiclass_log_loss=2.74973 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=23/40 loss=0.87489 inner_val_loss=2.68882 inner_val_multiclass_log_loss=2.68884 best_multiclass_log_loss=2.68884 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=24/40 loss=0.77007 inner_val_loss=2.64076 inner_val_multiclass_log_loss=2.64069 best_multiclass_log_loss=2.64069 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=25/40 loss=0.68790 inner_val_loss=2.59497 inner_val_multiclass_log_loss=2.59496 best_multiclass_log_loss=2.59496 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=26/40 loss=0.62525 inner_val_loss=2.55839 inner_val_multiclass_log_loss=2.55834 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=27/40 loss=0.54866 inner_val_loss=2.57313 inner_val_multiclass_log_loss=2.57316 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=28/40 loss=0.47933 inner_val_loss=2.54932 inner_val_multiclass_log_loss=2.54928 best_multiclass_log_loss=2.54928 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=29/40 loss=0.44446 inner_val_loss=2.49474 inner_val_multiclass_log_loss=2.49475 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=30/40 loss=0.37983 inner_val_loss=2.50766 inner_val_multiclass_log_loss=2.50771 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=31/40 loss=0.34707 inner_val_loss=2.46953 inner_val_multiclass_log_loss=2.46951 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=32/40 loss=0.30187 inner_val_loss=2.50410 inner_val_multiclass_log_loss=2.50406 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=33/40 loss=0.26999 inner_val_loss=2.48558 inner_val_multiclass_log_loss=2.48560 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=34/40 loss=0.24721 inner_val_loss=2.45993 inner_val_multiclass_log_loss=2.45990 best_multiclass_log_loss=2.45990 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=35/40 loss=0.21843 inner_val_loss=2.44064 inner_val_multiclass_log_loss=2.44068 best_multiclass_log_loss=2.44068 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=36/40 loss=0.20435 inner_val_loss=2.42181 inner_val_multiclass_log_loss=2.42183 best_multiclass_log_loss=2.42183 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=37/40 loss=0.17539 inner_val_loss=2.41809 inner_val_multiclass_log_loss=2.41806 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=38/40 loss=0.15881 inner_val_loss=2.44694 inner_val_multiclass_log_loss=2.44694 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=39/40 loss=0.15315 inner_val_loss=2.42802 inner_val_multiclass_log_loss=2.42807 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0
  fit=18 epoch=40/40 loss=0.13754 inner_val_loss=2.43073 inner_val_multiclass_log_loss=2.43074 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 full_refit_epoch=1/37 loss=4.76610
  fit=18 full_refit_epoch=2/37 loss=4.58809
  fit=18 full_refit_epoch=3/37 loss=4.40191
  fit=18 full_refit_epoch=4/37 loss=4.19280
  fit=18 full_refit_epoch=5/37 loss=3.94694
  fit=18 full_refit_epoch=6/37 loss=3.70573
  fit=18 full_refit_epoch=7/37 loss=3.45771
  fit=18 full_refit_epoch=8/37 loss=3.21290
  fit=18 full_refit_epoch=9/37 loss=2.96554
  fit=18 full_refit_epoch=10/37 loss=2.74399
  fit=18 full_refit_epoch=11/37 loss=2.51527
  fit=18 full_refit_epoch=12/37 loss=2.31445
  fit=18 full_refit_epoch=13/37 loss=2.10738
  fit=18 full_refit_epoch=14/37 loss=1.91163
  fit=18 full_refit_epoch=15/37 loss=1.74298
  fit=18 full_refit_epoch=16/37 loss=1.58161
  fit=18 full_refit_epoch=17/37 loss=1.41502
  fit=18 full_refit_epoch=18/37 loss=1.27785
  fit=18 full_refit_epoch=19/37 loss=1.13593
  fit=18 full_refit_epoch=20/37 loss=1.00394
  fit=18 full_refit_epoch=21/37 loss=0.89995
  fit=18 full_refit_epoch=22/37 loss=0.79272
  fit=18 full_refit_epoch=23/37 loss=0.70862
  fit=18 full_refit_epoch=24/37 loss=0.61145
  fit=18 full_refit_epoch=25/37 loss=0.54015
  fit=18 full_refit_epoch=26/37 loss=0.48481
  fit=18 full_refit_epoch=27/37 loss=0.43559
  fit=18 full_refit_epoch=28/37 loss=0.37559
  fit=18 full_refit_epoch=29/37 loss=0.32676
  fit=18 full_refit_epoch=30/37 loss=0.29414
  fit=18 full_refit_epoch=31/37 loss=0.25896
  fit=18 full_refit_epoch=32/37 loss=0.22610
  fit=18 full_refit_epoch=33/37 loss=0.19819
  fit=18 full_refit_epoch=34/37 loss=0.17827
  fit=18 full_refit_epoch=35/37 loss=0.16779
  fit=18 full_refit_epoch=36/37 loss=0.14451
  fit=18 full_refit_epoch=37/37 loss=0.12893

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=1/40 loss=4.78906 inner_val_loss=4.74795 inner_val_multiclass_log_loss=4.74797 best_multiclass_log_loss=4.74797 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=2/40 loss=4.62550 inner_val_loss=4.68232 inner_val_multiclass_log_loss=4.68236 best_multiclass_log_loss=4.68236 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=3/40 loss=4.46330 inner_val_loss=4.60217 inner_val_multiclass_log_loss=4.60211 best_multiclass_log_loss=4.60211 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=4/40 loss=4.27422 inner_val_loss=4.50101 inner_val_multiclass_log_loss=4.50118 best_multiclass_log_loss=4.50118 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=5/40 loss=4.07407 inner_val_loss=4.37253 inner_val_multiclass_log_loss=4.37265 best_multiclass_log_loss=4.37265 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=6/40 loss=3.84442 inner_val_loss=4.25408 inner_val_multiclass_log_loss=4.25412 best_multiclass_log_loss=4.25412 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=7/40 loss=3.61990 inner_val_loss=4.11079 inner_val_multiclass_log_loss=4.11074 best_multiclass_log_loss=4.11074 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=8/40 loss=3.38342 inner_val_loss=3.96290 inner_val_multiclass_log_loss=3.96301 best_multiclass_log_loss=3.96301 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=9/40 loss=3.15400 inner_val_loss=3.80163 inner_val_multiclass_log_loss=3.80169 best_multiclass_log_loss=3.80169 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=10/40 loss=2.92771 inner_val_loss=3.73142 inner_val_multiclass_log_loss=3.73145 best_multiclass_log_loss=3.73145 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=11/40 loss=2.70259 inner_val_loss=3.60612 inner_val_multiclass_log_loss=3.60612 best_multiclass_log_loss=3.60612 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=12/40 loss=2.49012 inner_val_loss=3.47927 inner_val_multiclass_log_loss=3.47928 best_multiclass_log_loss=3.47928 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=13/40 loss=2.29365 inner_val_loss=3.33652 inner_val_multiclass_log_loss=3.33655 best_multiclass_log_loss=3.33655 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=14/40 loss=2.10643 inner_val_loss=3.26670 inner_val_multiclass_log_loss=3.26674 best_multiclass_log_loss=3.26674 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=15/40 loss=1.91050 inner_val_loss=3.13448 inner_val_multiclass_log_loss=3.13449 best_multiclass_log_loss=3.13449 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=16/40 loss=1.73629 inner_val_loss=3.08385 inner_val_multiclass_log_loss=3.08388 best_multiclass_log_loss=3.08388 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=17/40 loss=1.58935 inner_val_loss=3.00790 inner_val_multiclass_log_loss=3.00798 best_multiclass_log_loss=3.00798 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=18/40 loss=1.42176 inner_val_loss=2.86943 inner_val_multiclass_log_loss=2.86949 best_multiclass_log_loss=2.86949 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=19/40 loss=1.28264 inner_val_loss=2.84649 inner_val_multiclass_log_loss=2.84654 best_multiclass_log_loss=2.84654 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=20/40 loss=1.15295 inner_val_loss=2.82859 inner_val_multiclass_log_loss=2.82862 best_multiclass_log_loss=2.82862 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=21/40 loss=1.02289 inner_val_loss=2.75452 inner_val_multiclass_log_loss=2.75460 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=22/40 loss=0.92076 inner_val_loss=2.79044 inner_val_multiclass_log_loss=2.79044 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=23/40 loss=0.82766 inner_val_loss=2.65027 inner_val_multiclass_log_loss=2.65022 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=24/40 loss=0.72237 inner_val_loss=2.68954 inner_val_multiclass_log_loss=2.68958 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=25/40 loss=0.64675 inner_val_loss=2.68187 inner_val_multiclass_log_loss=2.68184 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=26/40 loss=0.57543 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60254 best_multiclass_log_loss=2.60254 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=27/40 loss=0.52233 inner_val_loss=2.55875 inner_val_multiclass_log_loss=2.55874 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=28/40 loss=0.44687 inner_val_loss=2.59887 inner_val_multiclass_log_loss=2.59881 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=29/40 loss=0.40455 inner_val_loss=2.56116 inner_val_multiclass_log_loss=2.56111 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=30/40 loss=0.35947 inner_val_loss=2.54622 inner_val_multiclass_log_loss=2.54619 best_multiclass_log_loss=2.54619 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=31/40 loss=0.30966 inner_val_loss=2.54055 inner_val_multiclass_log_loss=2.54057 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=32/40 loss=0.28341 inner_val_loss=2.60014 inner_val_multiclass_log_loss=2.60014 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=33/40 loss=0.25652 inner_val_loss=2.56220 inner_val_multiclass_log_loss=2.56224 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=34/40 loss=0.22953 inner_val_loss=2.52196 inner_val_multiclass_log_loss=2.52190 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=35/40 loss=0.20994 inner_val_loss=2.52543 inner_val_multiclass_log_loss=2.52545 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=36/40 loss=0.19356 inner_val_loss=2.50430 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=37/40 loss=0.17261 inner_val_loss=2.55080 inner_val_multiclass_log_loss=2.55073 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=38/40 loss=0.14788 inner_val_loss=2.54022 inner_val_multiclass_log_loss=2.54023 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=39/40 loss=0.13704 inner_val_loss=2.51211 inner_val_multiclass_log_loss=2.51212 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1
  fit=19 epoch=40/40 loss=0.12357 inner_val_loss=2.53633 inner_val_multiclass_log_loss=2.53635 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 full_refit_epoch=1/36 loss=4.78933
  fit=19 full_refit_epoch=2/36 loss=4.62183
  fit=19 full_refit_epoch=3/36 loss=4.44740
  fit=19 full_refit_epoch=4/36 loss=4.24532
  fit=19 full_refit_epoch=5/36 loss=4.02094
  fit=19 full_refit_epoch=6/36 loss=3.78293
  fit=19 full_refit_epoch=7/36 loss=3.53231
  fit=19 full_refit_epoch=8/36 loss=3.28427
  fit=19 full_refit_epoch=9/36 loss=3.03381
  fit=19 full_refit_epoch=10/36 loss=2.79936
  fit=19 full_refit_epoch=11/36 loss=2.58011
  fit=19 full_refit_epoch=12/36 loss=2.35711
  fit=19 full_refit_epoch=13/36 loss=2.13863
  fit=19 full_refit_epoch=14/36 loss=1.96065
  fit=19 full_refit_epoch=15/36 loss=1.76849
  fit=19 full_refit_epoch=16/36 loss=1.59651
  fit=19 full_refit_epoch=17/36 loss=1.42424
  fit=19 full_refit_epoch=18/36 loss=1.28335
  fit=19 full_refit_epoch=19/36 loss=1.15012
  fit=19 full_refit_epoch=20/36 loss=1.01315
  fit=19 full_refit_epoch=21/36 loss=0.89809
  fit=19 full_refit_epoch=22/36 loss=0.79891
  fit=19 full_refit_epoch=23/36 loss=0.68675
  fit=19 full_refit_epoch=24/36 loss=0.60914
  fit=19 full_refit_epoch=25/36 loss=0.53905
  fit=19 full_refit_epoch=26/36 loss=0.46530
  fit=19 full_refit_epoch=27/36 loss=0.41107
  fit=19 full_refit_epoch=28/36 loss=0.36036
  fit=19 full_refit_epoch=29/36 loss=0.31609
  fit=19 full_refit_epoch=30/36 loss=0.27736
  fit=19 full_refit_epoch=31/36 loss=0.24527
  fit=19 full_refit_epoch=32/36 loss=0.21381
  fit=19 full_refit_epoch=33/36 loss=0.19448
  fit=19 full_refit_epoch=34/36 loss=0.17119
  fit=19 full_refit_epoch=35/36 loss=0.14893
  fit=19 full_refit_epoch=36/36 loss=0.13754

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=1/40 loss=4.78852 inner_val_loss=4.76904 inner_val_multiclass_log_loss=4.76897 best_multiclass_log_loss=4.76897 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=2/40 loss=4.62429 inner_val_loss=4.71210 inner_val_multiclass_log_loss=4.71216 best_multiclass_log_loss=4.71216 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=3/40 loss=4.46566 inner_val_loss=4.64409 inner_val_multiclass_log_loss=4.64397 best_multiclass_log_loss=4.64397 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=4/40 loss=4.28515 inner_val_loss=4.54058 inner_val_multiclass_log_loss=4.54055 best_multiclass_log_loss=4.54055 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=5/40 loss=4.07529 inner_val_loss=4.44137 inner_val_multiclass_log_loss=4.44133 best_multiclass_log_loss=4.44133 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=6/40 loss=3.85576 inner_val_loss=4.32108 inner_val_multiclass_log_loss=4.32111 best_multiclass_log_loss=4.32111 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=7/40 loss=3.62263 inner_val_loss=4.21201 inner_val_multiclass_log_loss=4.21194 best_multiclass_log_loss=4.21194 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=8/40 loss=3.39331 inner_val_loss=4.03885 inner_val_multiclass_log_loss=4.03889 best_multiclass_log_loss=4.03889 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=9/40 loss=3.15808 inner_val_loss=3.95047 inner_val_multiclass_log_loss=3.95061 best_multiclass_log_loss=3.95061 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=10/40 loss=2.93715 inner_val_loss=3.85990 inner_val_multiclass_log_loss=3.85989 best_multiclass_log_loss=3.85989 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=11/40 loss=2.72324 inner_val_loss=3.73999 inner_val_multiclass_log_loss=3.73991 best_multiclass_log_loss=3.73991 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=12/40 loss=2.52562 inner_val_loss=3.59334 inner_val_multiclass_log_loss=3.59334 best_multiclass_log_loss=3.59334 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=13/40 loss=2.31996 inner_val_loss=3.47636 inner_val_multiclass_log_loss=3.47641 best_multiclass_log_loss=3.47641 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=14/40 loss=2.12754 inner_val_loss=3.39709 inner_val_multiclass_log_loss=3.39711 best_multiclass_log_loss=3.39711 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=15/40 loss=1.95570 inner_val_loss=3.28863 inner_val_multiclass_log_loss=3.28853 best_multiclass_log_loss=3.28853 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=16/40 loss=1.76366 inner_val_loss=3.28249 inner_val_multiclass_log_loss=3.28246 best_multiclass_log_loss=3.28246 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=17/40 loss=1.62190 inner_val_loss=3.19756 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.19763 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=18/40 loss=1.44612 inner_val_loss=3.10082 inner_val_multiclass_log_loss=3.10085 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=19/40 loss=1.31146 inner_val_loss=3.13824 inner_val_multiclass_log_loss=3.13826 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=20/40 loss=1.18608 inner_val_loss=3.02525 inner_val_multiclass_log_loss=3.02514 best_multiclass_log_loss=3.02514 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=21/40 loss=1.05608 inner_val_loss=2.99701 inner_val_multiclass_log_loss=2.99699 best_multiclass_log_loss=2.99699 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=22/40 loss=0.92849 inner_val_loss=2.96264 inner_val_multiclass_log_loss=2.96264 best_multiclass_log_loss=2.96264 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=23/40 loss=0.83730 inner_val_loss=2.89042 inner_val_multiclass_log_loss=2.89043 best_multiclass_log_loss=2.89043 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=24/40 loss=0.72775 inner_val_loss=2.87662 inner_val_multiclass_log_loss=2.87657 best_multiclass_log_loss=2.87657 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=25/40 loss=0.65180 inner_val_loss=2.85888 inner_val_multiclass_log_loss=2.85887 best_multiclass_log_loss=2.85887 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=26/40 loss=0.59433 inner_val_loss=2.81037 inner_val_multiclass_log_loss=2.81039 best_multiclass_log_loss=2.81039 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=27/40 loss=0.51746 inner_val_loss=2.76880 inner_val_multiclass_log_loss=2.76883 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=28/40 loss=0.45104 inner_val_loss=2.78959 inner_val_multiclass_log_loss=2.78966 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=29/40 loss=0.39143 inner_val_loss=2.81155 inner_val_multiclass_log_loss=2.81148 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=30/40 loss=0.36644 inner_val_loss=2.80357 inner_val_multiclass_log_loss=2.80352 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=31/40 loss=0.31340 inner_val_loss=2.75166 inner_val_multiclass_log_loss=2.75162 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=32/40 loss=0.27817 inner_val_loss=2.78633 inner_val_multiclass_log_loss=2.78634 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=33/40 loss=0.24365 inner_val_loss=2.77531 inner_val_multiclass_log_loss=2.77528 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=34/40 loss=0.22111 inner_val_loss=2.75155 inner_val_multiclass_log_loss=2.75155 best_multiclass_log_loss=2.75155 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=35/40 loss=0.20138 inner_val_loss=2.74706 inner_val_multiclass_log_loss=2.74706 best_multiclass_log_loss=2.74706 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=36/40 loss=0.17586 inner_val_loss=2.71929 inner_val_multiclass_log_loss=2.71928 best_multiclass_log_loss=2.71928 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=37/40 loss=0.17020 inner_val_loss=2.71782 inner_val_multiclass_log_loss=2.71780 best_multiclass_log_loss=2.71780 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=38/40 loss=0.14854 inner_val_loss=2.70418 inner_val_multiclass_log_loss=2.70421 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=39/40 loss=0.13157 inner_val_loss=2.75853 inner_val_multiclass_log_loss=2.75848 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.1
  fit=20 epoch=40/40 loss=0.12113 inner_val_loss=2.73078 inner_val_multiclass_log_loss=2.73084 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 full_refit_epoch=1/38 loss=4.78588
  fit=20 full_refit_epoch=2/38 loss=4.61993
  fit=20 full_refit_epoch=3/38 loss=4.44642
  fit=20 full_refit_epoch=4/38 loss=4.24635
  fit=20 full_refit_epoch=5/38 loss=4.02090
  fit=20 full_refit_epoch=6/38 loss=3.78011
  fit=20 full_refit_epoch=7/38 loss=3.53233
  fit=20 full_refit_epoch=8/38 loss=3.28899
  fit=20 full_refit_epoch=9/38 loss=3.04329
  fit=20 full_refit_epoch=10/38 loss=2.81072
  fit=20 full_refit_epoch=11/38 loss=2.58246
  fit=20 full_refit_epoch=12/38 loss=2.38099
  fit=20 full_refit_epoch=13/38 loss=2.16343
  fit=20 full_refit_epoch=14/38 loss=1.97204
  fit=20 full_refit_epoch=15/38 loss=1.79387
  fit=20 full_refit_epoch=16/38 loss=1.61716
  fit=20 full_refit_epoch=17/38 loss=1.44508
  fit=20 full_refit_epoch=18/38 loss=1.29190
  fit=20 full_refit_epoch=19/38 loss=1.15543
  fit=20 full_refit_epoch=20/38 loss=1.01886
  fit=20 full_refit_epoch=21/38 loss=0.90017
  fit=20 full_refit_epoch=22/38 loss=0.79421
  fit=20 full_refit_epoch=23/38 loss=0.69174
  fit=20 full_refit_epoch=24/38 loss=0.60423
  fit=20 full_refit_epoch=25/38 loss=0.53090
  fit=20 full_refit_epoch=26/38 loss=0.46597
  fit=20 full_refit_epoch=27/38 loss=0.41092
  fit=20 full_refit_epoch=28/38 loss=0.35185
  fit=20 full_refit_epoch=29/38 loss=0.31449
  fit=20 full_refit_epoch=30/38 loss=0.27410
  fit=20 full_refit_epoch=31/38 loss=0.24654
  fit=20 full_refit_epoch=32/38 loss=0.21647
  fit=20 full_refit_epoch=33/38 loss=0.19490
  fit=20 full_refit_epoch=34/38 loss=0.17505
  fit=20 full_refit_epoch=35/38 loss=0.15285
  fit=20 full_refit_epoch=36/38 loss=0.13916
  fit=20 full_refit_epoch=37/38 loss=0.12314
  fit=20 full_refit_epoch=38/38 loss=0.10869

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=initial_selected model=resnet18 metric=2.4587492901316477 error=None minutes=13.33
START seed=13 phase=ablation model=pass

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=ablation model=pass metric=4.787491690627983 error=None minutes=0.23
START seed=13 phase=refinement model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=1/40 loss=4.99036 inner_val_loss=4.97611 inner_val_multiclass_log_loss=4.97623 best_multiclass_log_loss=4.97623 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=2/40 loss=3.86951 inner_val_loss=4.66832 inner_val_multiclass_log_loss=4.66829 best_multiclass_log_loss=4.66829 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=3/40 loss=2.86598 inner_val_loss=4.36706 inner_val_multiclass_log_loss=4.36709 best_multiclass_log_loss=4.36709 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=4/40 loss=2.09927 inner_val_loss=4.12978 inner_val_multiclass_log_loss=4.12960 best_multiclass_log_loss=4.12960 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=5/40 loss=1.47379 inner_val_loss=3.91091 inner_val_multiclass_log_loss=3.91094 best_multiclass_log_loss=3.91094 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=6/40 loss=1.04768 inner_val_loss=3.74101 inner_val_multiclass_log_loss=3.74110 best_multiclass_log_loss=3.74110 best_epoch=6 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=7/40 loss=0.73715 inner_val_loss=3.63261 inner_val_multiclass_log_loss=3.63263 best_multiclass_log_loss=3.63263 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=8/40 loss=0.49567 inner_val_loss=3.53976 inner_val_multiclass_log_loss=3.53977 best_multiclass_log_loss=3.53977 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=9/40 loss=0.35736 inner_val_loss=3.46971 inner_val_multiclass_log_loss=3.46964 best_multiclass_log_loss=3.46964 best_epoch=9 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=10/40 loss=0.26701 inner_val_loss=3.42923 inner_val_multiclass_log_loss=3.42920 best_multiclass_log_loss=3.42920 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=11/40 loss=0.19902 inner_val_loss=3.43796 inner_val_multiclass_log_loss=3.43808 best_multiclass_log_loss=3.42920 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=12/40 loss=0.16136 inner_val_loss=3.36230 inner_val_multiclass_log_loss=3.36233 best_multiclass_log_loss=3.36233 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=13/40 loss=0.13671 inner_val_loss=3.34908 inner_val_multiclass_log_loss=3.34915 best_multiclass_log_loss=3.34915 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=14/40 loss=0.11585 inner_val_loss=3.30774 inner_val_multiclass_log_loss=3.30780 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=15/40 loss=0.10349 inner_val_loss=3.32454 inner_val_multiclass_log_loss=3.32450 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=16/40 loss=0.07807 inner_val_loss=3.31154 inner_val_multiclass_log_loss=3.31149 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=17/40 loss=0.07354 inner_val_loss=3.33854 inner_val_multiclass_log_loss=3.33849 best_multiclass_log_loss=3.30780 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=18/40 loss=0.07539 inner_val_loss=3.25912 inner_val_multiclass_log_loss=3.25914 best_multiclass_log_loss=3.25914 best_epoch=18 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=19/40 loss=0.06123 inner_val_loss=3.21976 inner_val_multiclass_log_loss=3.21976 best_multiclass_log_loss=3.21976 best_epoch=19 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=20/40 loss=0.04795 inner_val_loss=3.21730 inner_val_multiclass_log_loss=3.21725 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=21/40 loss=0.04407 inner_val_loss=3.28103 inner_val_multiclass_log_loss=3.28111 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=22/40 loss=0.04990 inner_val_loss=3.22119 inner_val_multiclass_log_loss=3.22107 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=23/40 loss=0.04440 inner_val_loss=3.21981 inner_val_multiclass_log_loss=3.21979 best_multiclass_log_loss=3.21725 best_epoch=20 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=24/40 loss=0.03520 inner_val_loss=3.21580 inner_val_multiclass_log_loss=3.21583 best_multiclass_log_loss=3.21583 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=25/40 loss=0.03019 inner_val_loss=3.23000 inner_val_multiclass_log_loss=3.22994 best_multiclass_log_loss=3.21583 best_epoch=24 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=26/40 loss=0.03016 inner_val_loss=3.19271 inner_val_multiclass_log_loss=3.19273 best_multiclass_log_loss=3.19273 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=27/40 loss=0.03207 inner_val_loss=3.16384 inner_val_multiclass_log_loss=3.16386 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=28/40 loss=0.03207 inner_val_loss=3.18086 inner_val_multiclass_log_loss=3.18086 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=29/40 loss=0.02549 inner_val_loss=3.19129 inner_val_multiclass_log_loss=3.19124 best_multiclass_log_loss=3.16386 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=30/40 loss=0.02544 inner_val_loss=3.15057 inner_val_multiclass_log_loss=3.15063 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=31/40 loss=0.02418 inner_val_loss=3.19703 inner_val_multiclass_log_loss=3.19700 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=32/40 loss=0.02842 inner_val_loss=3.17133 inner_val_multiclass_log_loss=3.17135 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=33/40 loss=0.02037 inner_val_loss=3.27333 inner_val_multiclass_log_loss=3.27328 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=34/40 loss=0.01847 inner_val_loss=3.22376 inner_val_multiclass_log_loss=3.22368 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=3.0
  fit=21 epoch=35/40 loss=0.01911 inner_val_loss=3.20446 inner_val_multiclass_log_loss=3.20447 best_multiclass_log_loss=3.15063 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 full_refit_epoch=1/30 loss=5.01537
  fit=21 full_refit_epoch=2/30 loss=3.79898
  fit=21 full_refit_epoch=3/30 loss=2.81691
  fit=21 full_refit_epoch=4/30 loss=2.01400
  fit=21 full_refit_epoch=5/30 loss=1.39826
  fit=21 full_refit_epoch=6/30 loss=0.94136
  fit=21 full_refit_epoch=7/30 loss=0.63438
  fit=21 full_refit_epoch=8/30 loss=0.44331
  fit=21 full_refit_epoch=9/30 loss=0.30277
  fit=21 full_refit_epoch=10/30 loss=0.21354
  fit=21 full_refit_epoch=11/30 loss=0.16515
  fit=21 full_refit_epoch=12/30 loss=0.13133
  fit=21 full_refit_epoch=13/30 loss=0.10407
  fit=21 full_refit_epoch=14/30 loss=0.08619
  fit=21 full_refit_epoch=15/30 loss=0.06605
  fit=21 full_refit_epoch=16/30 loss=0.06412
  fit=21 full_refit_epoch=17/30 loss=0.05045
  fit=21 full_refit_epoch=18/30 loss=0.04414
  fit=21 full_refit_epoch=19/30 loss=0.03931
  fit=21 full_refit_epoch=20/30 loss=0.03662
  fit=21 full_refit_epoch=21/30 loss=0.03217
  fit=21 full_refit_epoch=22/30 loss=0.02900
  fit=21 full_refit_epoch=23/30 loss=0.02693
  fit=21 full_refit_epoch=24/30 loss=0.02411
  fit=21 full_refit_epoch=25/30 loss=0.02224
  fit=21 full_refit_epoch=26/30 loss=0.01896
  fit=21 full_refit_epoch=27/30 loss=0.01988
  fit=21 full_refit_epoch=28/30 loss=0.01723
  fit=21 full_refit_epoch=29/30 loss=0.01547
  fit=21 full_refit_epoch=30/30 loss=0.01455

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=1/40 loss=5.00992 inner_val_loss=4.75961 inner_val_multiclass_log_loss=4.75979 best_multiclass_log_loss=4.75979 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=2/40 loss=3.84845 inner_val_loss=4.44167 inner_val_multiclass_log_loss=4.44177 best_multiclass_log_loss=4.44177 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=3/40 loss=2.91570 inner_val_loss=4.14369 inner_val_multiclass_log_loss=4.14368 best_multiclass_log_loss=4.14368 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=4/40 loss=2.11675 inner_val_loss=3.88348 inner_val_multiclass_log_loss=3.88344 best_multiclass_log_loss=3.88344 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=5/40 loss=1.48583 inner_val_loss=3.68816 inner_val_multiclass_log_loss=3.68816 best_multiclass_log_loss=3.68816 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=6/40 loss=1.00633 inner_val_loss=3.51250 inner_val_multiclass_log_loss=3.51247 best_multiclass_log_loss=3.51247 best_epoch=6 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=7/40 loss=0.69965 inner_val_loss=3.43604 inner_val_multiclass_log_loss=3.43613 best_multiclass_log_loss=3.43613 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=8/40 loss=0.49791 inner_val_loss=3.34718 inner_val_multiclass_log_loss=3.34722 best_multiclass_log_loss=3.34722 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=9/40 loss=0.34502 inner_val_loss=3.28710 inner_val_multiclass_log_loss=3.28711 best_multiclass_log_loss=3.28711 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=10/40 loss=0.26464 inner_val_loss=3.24824 inner_val_multiclass_log_loss=3.24819 best_multiclass_log_loss=3.24819 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=11/40 loss=0.21598 inner_val_loss=3.18775 inner_val_multiclass_log_loss=3.18778 best_multiclass_log_loss=3.18778 best_epoch=11 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=12/40 loss=0.16815 inner_val_loss=3.17137 inner_val_multiclass_log_loss=3.17143 best_multiclass_log_loss=3.17143 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=13/40 loss=0.13388 inner_val_loss=3.13357 inner_val_multiclass_log_loss=3.13352 best_multiclass_log_loss=3.13352 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=14/40 loss=0.11197 inner_val_loss=3.11475 inner_val_multiclass_log_loss=3.11474 best_multiclass_log_loss=3.11474 best_epoch=14 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=15/40 loss=0.08880 inner_val_loss=3.10371 inner_val_multiclass_log_loss=3.10376 best_multiclass_log_loss=3.10376 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=16/40 loss=0.09289 inner_val_loss=3.08496 inner_val_multiclass_log_loss=3.08500 best_multiclass_log_loss=3.08500 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=17/40 loss=0.07723 inner_val_loss=3.11840 inner_val_multiclass_log_loss=3.11841 best_multiclass_log_loss=3.08500 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=18/40 loss=0.06629 inner_val_loss=3.08397 inner_val_multiclass_log_loss=3.08402 best_multiclass_log_loss=3.08402 best_epoch=18 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=19/40 loss=0.06014 inner_val_loss=3.05166 inner_val_multiclass_log_loss=3.05159 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=20/40 loss=0.05484 inner_val_loss=3.06879 inner_val_multiclass_log_loss=3.06886 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=21/40 loss=0.04870 inner_val_loss=3.05673 inner_val_multiclass_log_loss=3.05670 best_multiclass_log_loss=3.05159 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=22/40 loss=0.04216 inner_val_loss=3.01840 inner_val_multiclass_log_loss=3.01851 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=23/40 loss=0.03570 inner_val_loss=3.08866 inner_val_multiclass_log_loss=3.08867 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=24/40 loss=0.04381 inner_val_loss=3.02241 inner_val_multiclass_log_loss=3.02246 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=25/40 loss=0.03283 inner_val_loss=3.04847 inner_val_multiclass_log_loss=3.04854 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=26/40 loss=0.04609 inner_val_loss=3.02190 inner_val_multiclass_log_loss=3.02190 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.0
  fit=22 epoch=27/40 loss=0.03072 inner_val_loss=3.02740 inner_val_multiclass_log_loss=3.02748 best_multiclass_log_loss=3.01851 best_epoch=22 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 full_refit_epoch=1/22 loss=4.97448
  fit=22 full_refit_epoch=2/22 loss=3.80416
  fit=22 full_refit_epoch=3/22 loss=2.82054
  fit=22 full_refit_epoch=4/22 loss=1.98839
  fit=22 full_refit_epoch=5/22 loss=1.36942
  fit=22 full_refit_epoch=6/22 loss=0.93086
  fit=22 full_refit_epoch=7/22 loss=0.63039
  fit=22 full_refit_epoch=8/22 loss=0.42832
  fit=22 full_refit_epoch=9/22 loss=0.28680
  fit=22 full_refit_epoch=10/22 loss=0.23010
  fit=22 full_refit_epoch=11/22 loss=0.16731
  fit=22 full_refit_epoch=12/22 loss=0.12764
  fit=22 full_refit_epoch=13/22 loss=0.10052
  fit=22 full_refit_epoch=14/22 loss=0.08987
  fit=22 full_refit_epoch=15/22 loss=0.07087
  fit=22 full_refit_epoch=16/22 loss=0.06400
  fit=22 full_refit_epoch=17/22 loss=0.05344
  fit=22 full_refit_epoch=18/22 loss=0.04902
  fit=22 full_refit_epoch=19/22 loss=0.03863
  fit=22 full_refit_epoch=20/22 loss=0.03833
  fit=22 full_refit_epoch=21/22 loss=0.03375
  fit=22 full_refit_epoch=22/22 loss=0.03340

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=1/40 loss=5.02928 inner_val_loss=4.75876 inner_val_multiclass_log_loss=4.75877 best_multiclass_log_loss=4.75877 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=2/40 loss=3.88965 inner_val_loss=4.45946 inner_val_multiclass_log_loss=4.45952 best_multiclass_log_loss=4.45952 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=3/40 loss=2.94098 inner_val_loss=4.13572 inner_val_multiclass_log_loss=4.13578 best_multiclass_log_loss=4.13578 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=4/40 loss=2.11327 inner_val_loss=3.90386 inner_val_multiclass_log_loss=3.90377 best_multiclass_log_loss=3.90377 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=5/40 loss=1.52675 inner_val_loss=3.65165 inner_val_multiclass_log_loss=3.65158 best_multiclass_log_loss=3.65158 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=6/40 loss=1.04543 inner_val_loss=3.50287 inner_val_multiclass_log_loss=3.50283 best_multiclass_log_loss=3.50283 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=7/40 loss=0.73523 inner_val_loss=3.34494 inner_val_multiclass_log_loss=3.34498 best_multiclass_log_loss=3.34498 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=8/40 loss=0.50714 inner_val_loss=3.24464 inner_val_multiclass_log_loss=3.24462 best_multiclass_log_loss=3.24462 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=9/40 loss=0.36471 inner_val_loss=3.11621 inner_val_multiclass_log_loss=3.11616 best_multiclass_log_loss=3.11616 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=10/40 loss=0.27011 inner_val_loss=3.02721 inner_val_multiclass_log_loss=3.02719 best_multiclass_log_loss=3.02719 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=11/40 loss=0.20206 inner_val_loss=3.02960 inner_val_multiclass_log_loss=3.02953 best_multiclass_log_loss=3.02719 best_epoch=10 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=12/40 loss=0.15179 inner_val_loss=2.98925 inner_val_multiclass_log_loss=2.98932 best_multiclass_log_loss=2.98932 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=13/40 loss=0.14685 inner_val_loss=2.94003 inner_val_multiclass_log_loss=2.94006 best_multiclass_log_loss=2.94006 best_epoch=13 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=14/40 loss=0.11094 inner_val_loss=2.91133 inner_val_multiclass_log_loss=2.91140 best_multiclass_log_loss=2.91140 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=15/40 loss=0.09812 inner_val_loss=2.88417 inner_val_multiclass_log_loss=2.88409 best_multiclass_log_loss=2.88409 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=16/40 loss=0.07885 inner_val_loss=2.83419 inner_val_multiclass_log_loss=2.83425 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=17/40 loss=0.07247 inner_val_loss=2.85331 inner_val_multiclass_log_loss=2.85335 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=18/40 loss=0.06819 inner_val_loss=2.88378 inner_val_multiclass_log_loss=2.88382 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=19/40 loss=0.05696 inner_val_loss=2.86688 inner_val_multiclass_log_loss=2.86689 best_multiclass_log_loss=2.83425 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=20/40 loss=0.04778 inner_val_loss=2.83068 inner_val_multiclass_log_loss=2.83063 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=21/40 loss=0.05320 inner_val_loss=2.84203 inner_val_multiclass_log_loss=2.84200 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=22/40 loss=0.03946 inner_val_loss=2.84926 inner_val_multiclass_log_loss=2.84917 best_multiclass_log_loss=2.83063 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=23/40 loss=0.03536 inner_val_loss=2.81412 inner_val_multiclass_log_loss=2.81412 best_multiclass_log_loss=2.81412 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=24/40 loss=0.04317 inner_val_loss=2.87428 inner_val_multiclass_log_loss=2.87423 best_multiclass_log_loss=2.81412 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=25/40 loss=0.03561 inner_val_loss=2.76194 inner_val_multiclass_log_loss=2.76193 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=26/40 loss=0.03697 inner_val_loss=2.77370 inner_val_multiclass_log_loss=2.77371 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=27/40 loss=0.03180 inner_val_loss=2.80618 inner_val_multiclass_log_loss=2.80614 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=28/40 loss=0.02790 inner_val_loss=2.79801 inner_val_multiclass_log_loss=2.79803 best_multiclass_log_loss=2.76193 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=29/40 loss=0.03464 inner_val_loss=2.75913 inner_val_multiclass_log_loss=2.75912 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=30/40 loss=0.02486 inner_val_loss=2.78148 inner_val_multiclass_log_loss=2.78146 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=31/40 loss=0.03316 inner_val_loss=2.78911 inner_val_multiclass_log_loss=2.78917 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=32/40 loss=0.02018 inner_val_loss=2.87988 inner_val_multiclass_log_loss=2.87981 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=33/40 loss=0.02472 inner_val_loss=2.85514 inner_val_multiclass_log_loss=2.85524 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.1
  fit=23 epoch=34/40 loss=0.02243 inner_val_loss=2.81325 inner_val_multiclass_log_loss=2.81314 best_multiclass_log_loss=2.75912 best_epoch=29 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 full_refit_epoch=1/29 loss=5.00494
  fit=23 full_refit_epoch=2/29 loss=3.82182
  fit=23 full_refit_epoch=3/29 loss=2.85212
  fit=23 full_refit_epoch=4/29 loss=2.04077
  fit=23 full_refit_epoch=5/29 loss=1.41067
  fit=23 full_refit_epoch=6/29 loss=0.94601
  fit=23 full_refit_epoch=7/29 loss=0.64570
  fit=23 full_refit_epoch=8/29 loss=0.44875
  fit=23 full_refit_epoch=9/29 loss=0.31190
  fit=23 full_refit_epoch=10/29 loss=0.22977
  fit=23 full_refit_epoch=11/29 loss=0.16520
  fit=23 full_refit_epoch=12/29 loss=0.13355
  fit=23 full_refit_epoch=13/29 loss=0.10679
  fit=23 full_refit_epoch=14/29 loss=0.08821
  fit=23 full_refit_epoch=15/29 loss=0.07112
  fit=23 full_refit_epoch=16/29 loss=0.06172
  fit=23 full_refit_epoch=17/29 loss=0.05536
  fit=23 full_refit_epoch=18/29 loss=0.04815
  fit=23 full_refit_epoch=19/29 loss=0.04073
  fit=23 full_refit_epoch=20/29 loss=0.03730
  fit=23 full_refit_epoch=21/29 loss=0.03279
  fit=23 full_refit_epoch=22/29 loss=0.02885
  fit=23 full_refit_epoch=23/29 loss=0.02860
  fit=23 full_refit_epoch=24/29 loss=0.02341
  fit=23 full_refit_epoch=25/29 loss=0.02331
  fit=23 full_refit_epoch=26/29 loss=0.02115
  fit=23 full_refit_epoch=27/29 loss=0.01984
  fit=23 full_refit_epoch=28/29 loss=0.01793
  fit=23 full_refit_epoch=29/29 loss=0.01568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=1/40 loss=4.98903 inner_val_loss=4.89898 inner_val_multiclass_log_loss=4.89885 best_multiclass_log_loss=4.89885 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=2/40 loss=3.82121 inner_val_loss=4.63836 inner_val_multiclass_log_loss=4.63835 best_multiclass_log_loss=4.63835 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=3/40 loss=2.88924 inner_val_loss=4.33970 inner_val_multiclass_log_loss=4.33974 best_multiclass_log_loss=4.33974 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=4/40 loss=2.09632 inner_val_loss=4.08573 inner_val_multiclass_log_loss=4.08580 best_multiclass_log_loss=4.08580 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=5/40 loss=1.48138 inner_val_loss=3.93854 inner_val_multiclass_log_loss=3.93854 best_multiclass_log_loss=3.93854 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=6/40 loss=0.99804 inner_val_loss=3.77461 inner_val_multiclass_log_loss=3.77469 best_multiclass_log_loss=3.77469 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=7/40 loss=0.68846 inner_val_loss=3.67316 inner_val_multiclass_log_loss=3.67313 best_multiclass_log_loss=3.67313 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=8/40 loss=0.48933 inner_val_loss=3.58673 inner_val_multiclass_log_loss=3.58673 best_multiclass_log_loss=3.58673 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=9/40 loss=0.33644 inner_val_loss=3.55173 inner_val_multiclass_log_loss=3.55171 best_multiclass_log_loss=3.55171 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=10/40 loss=0.25505 inner_val_loss=3.48588 inner_val_multiclass_log_loss=3.48574 best_multiclass_log_loss=3.48574 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=11/40 loss=0.20054 inner_val_loss=3.44556 inner_val_multiclass_log_loss=3.44553 best_multiclass_log_loss=3.44553 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=12/40 loss=0.15455 inner_val_loss=3.40841 inner_val_multiclass_log_loss=3.40840 best_multiclass_log_loss=3.40840 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=13/40 loss=0.12102 inner_val_loss=3.41139 inner_val_multiclass_log_loss=3.41136 best_multiclass_log_loss=3.40840 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=14/40 loss=0.10360 inner_val_loss=3.37341 inner_val_multiclass_log_loss=3.37342 best_multiclass_log_loss=3.37342 best_epoch=14 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=15/40 loss=0.09872 inner_val_loss=3.35078 inner_val_multiclass_log_loss=3.35079 best_multiclass_log_loss=3.35079 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=16/40 loss=0.07685 inner_val_loss=3.36781 inner_val_multiclass_log_loss=3.36775 best_multiclass_log_loss=3.35079 best_epoch=15 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=17/40 loss=0.07714 inner_val_loss=3.33298 inner_val_multiclass_log_loss=3.33298 best_multiclass_log_loss=3.33298 best_epoch=17 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=18/40 loss=0.06124 inner_val_loss=3.35884 inner_val_multiclass_log_loss=3.35893 best_multiclass_log_loss=3.33298 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=19/40 loss=0.05238 inner_val_loss=3.29291 inner_val_multiclass_log_loss=3.29290 best_multiclass_log_loss=3.29290 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=20/40 loss=0.05201 inner_val_loss=3.38271 inner_val_multiclass_log_loss=3.38274 best_multiclass_log_loss=3.29290 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=21/40 loss=0.04452 inner_val_loss=3.29206 inner_val_multiclass_log_loss=3.29217 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=22/40 loss=0.04371 inner_val_loss=3.37507 inner_val_multiclass_log_loss=3.37513 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=23/40 loss=0.05074 inner_val_loss=3.31665 inner_val_multiclass_log_loss=3.31667 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=24/40 loss=0.04695 inner_val_loss=3.35377 inner_val_multiclass_log_loss=3.35381 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=25/40 loss=0.03638 inner_val_loss=3.35455 inner_val_multiclass_log_loss=3.35450 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.1
  fit=24 epoch=26/40 loss=0.03241 inner_val_loss=3.31469 inner_val_multiclass_log_loss=3.31479 best_multiclass_log_loss=3.29217 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 full_refit_epoch=1/21 loss=4.99289
  fit=24 full_refit_epoch=2/21 loss=3.80848
  fit=24 full_refit_epoch=3/21 loss=2.81671
  fit=24 full_refit_epoch=4/21 loss=1.99271
  fit=24 full_refit_epoch=5/21 loss=1.40373
  fit=24 full_refit_epoch=6/21 loss=0.92812
  fit=24 full_refit_epoch=7/21 loss=0.61731
  fit=24 full_refit_epoch=8/21 loss=0.42340
  fit=24 full_refit_epoch=9/21 loss=0.28486
  fit=24 full_refit_epoch=10/21 loss=0.21522
  fit=24 full_refit_epoch=11/21 loss=0.16616
  fit=24 full_refit_epoch=12/21 loss=0.12758
  fit=24 full_refit_epoch=13/21 loss=0.10093
  fit=24 full_refit_epoch=14/21 loss=0.08144
  fit=24 full_refit_epoch=15/21 loss=0.07077
  fit=24 full_refit_epoch=16/21 loss=0.06118
  fit=24 full_refit_epoch=17/21 loss=0.05449
  fit=24 full_refit_epoch=18/21 loss=0.04808
  fit=24 full_refit_epoch=19/21 loss=0.04306
  fit=24 full_refit_epoch=20/21 loss=0.03729
  fit=24 full_refit_epoch=21/21 loss=0.03417

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=1/40 loss=4.99133 inner_val_loss=4.80050 inner_val_multiclass_log_loss=4.80046 best_multiclass_log_loss=4.80046 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=2/40 loss=3.83315 inner_val_loss=4.59151 inner_val_multiclass_log_loss=4.59149 best_multiclass_log_loss=4.59149 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=3/40 loss=2.91217 inner_val_loss=4.30327 inner_val_multiclass_log_loss=4.30326 best_multiclass_log_loss=4.30326 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=4/40 loss=2.10385 inner_val_loss=4.06685 inner_val_multiclass_log_loss=4.06681 best_multiclass_log_loss=4.06681 best_epoch=4 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=5/40 loss=1.47456 inner_val_loss=3.87030 inner_val_multiclass_log_loss=3.87028 best_multiclass_log_loss=3.87028 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=6/40 loss=1.01236 inner_val_loss=3.77471 inner_val_multiclass_log_loss=3.77471 best_multiclass_log_loss=3.77471 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=7/40 loss=0.71925 inner_val_loss=3.63381 inner_val_multiclass_log_loss=3.63378 best_multiclass_log_loss=3.63378 best_epoch=7 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=8/40 loss=0.49814 inner_val_loss=3.58678 inner_val_multiclass_log_loss=3.58679 best_multiclass_log_loss=3.58679 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=9/40 loss=0.35224 inner_val_loss=3.50579 inner_val_multiclass_log_loss=3.50588 best_multiclass_log_loss=3.50588 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=10/40 loss=0.25242 inner_val_loss=3.46802 inner_val_multiclass_log_loss=3.46803 best_multiclass_log_loss=3.46803 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=11/40 loss=0.19769 inner_val_loss=3.42091 inner_val_multiclass_log_loss=3.42093 best_multiclass_log_loss=3.42093 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=12/40 loss=0.17037 inner_val_loss=3.41417 inner_val_multiclass_log_loss=3.41421 best_multiclass_log_loss=3.41421 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=13/40 loss=0.13681 inner_val_loss=3.35525 inner_val_multiclass_log_loss=3.35531 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=14/40 loss=0.11016 inner_val_loss=3.36710 inner_val_multiclass_log_loss=3.36702 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=15/40 loss=0.10173 inner_val_loss=3.35579 inner_val_multiclass_log_loss=3.35585 best_multiclass_log_loss=3.35531 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=16/40 loss=0.07651 inner_val_loss=3.33813 inner_val_multiclass_log_loss=3.33815 best_multiclass_log_loss=3.33815 best_epoch=16 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=17/40 loss=0.07286 inner_val_loss=3.32815 inner_val_multiclass_log_loss=3.32816 best_multiclass_log_loss=3.32816 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=18/40 loss=0.06445 inner_val_loss=3.31810 inner_val_multiclass_log_loss=3.31823 best_multiclass_log_loss=3.31823 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=19/40 loss=0.06365 inner_val_loss=3.32532 inner_val_multiclass_log_loss=3.32537 best_multiclass_log_loss=3.31823 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=20/40 loss=0.05656 inner_val_loss=3.28177 inner_val_multiclass_log_loss=3.28172 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=21/40 loss=0.04482 inner_val_loss=3.31671 inner_val_multiclass_log_loss=3.31674 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=22/40 loss=0.04102 inner_val_loss=3.33449 inner_val_multiclass_log_loss=3.33454 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=23/40 loss=0.04465 inner_val_loss=3.31654 inner_val_multiclass_log_loss=3.31656 best_multiclass_log_loss=3.28172 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=24/40 loss=0.03236 inner_val_loss=3.25695 inner_val_multiclass_log_loss=3.25687 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=25/40 loss=0.04175 inner_val_loss=3.29445 inner_val_multiclass_log_loss=3.29447 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=26/40 loss=0.03368 inner_val_loss=3.25695 inner_val_multiclass_log_loss=3.25691 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=27/40 loss=0.03458 inner_val_loss=3.27971 inner_val_multiclass_log_loss=3.27963 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=28/40 loss=0.03367 inner_val_loss=3.27923 inner_val_multiclass_log_loss=3.27921 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=2.9
  fit=25 epoch=29/40 loss=0.02623 inner_val_loss=3.32177 inner_val_multiclass_log_loss=3.32176 best_multiclass_log_loss=3.25687 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 full_refit_epoch=1/24 loss=4.95899
  fit=25 full_refit_epoch=2/24 loss=3.77304
  fit=25 full_refit_epoch=3/24 loss=2.80964
  fit=25 full_refit_epoch=4/24 loss=2.02023
  fit=25 full_refit_epoch=5/24 loss=1.39449
  fit=25 full_refit_epoch=6/24 loss=0.93873
  fit=25 full_refit_epoch=7/24 loss=0.63759
  fit=25 full_refit_epoch=8/24 loss=0.43921
  fit=25 full_refit_epoch=9/24 loss=0.30028
  fit=25 full_refit_epoch=10/24 loss=0.23258
  fit=25 full_refit_epoch=11/24 loss=0.16769
  fit=25 full_refit_epoch=12/24 loss=0.13131
  fit=25 full_refit_epoch=13/24 loss=0.10614
  fit=25 full_refit_epoch=14/24 loss=0.08923
  fit=25 full_refit_epoch=15/24 loss=0.07203
  fit=25 full_refit_epoch=16/24 loss=0.06302
  fit=25 full_refit_epoch=17/24 loss=0.05344
  fit=25 full_refit_epoch=18/24 loss=0.04723
  fit=25 full_refit_epoch=19/24 loss=0.04379
  fit=25 full_refit_epoch=20/24 loss=0.03631
  fit=25 full_refit_epoch=21/24 loss=0.03360
  fit=25 full_refit_epoch=22/24 loss=0.03044
  fit=25 full_refit_epoch=23/24 loss=0.02782
  fit=25 full_refit_epoch=24/24 loss=0.02464

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=refinement model=efficientnet_b0 metric=2.945880327772081 error=None minutes=14.39
START seed=13 phase=refined_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=1/40 loss=4.79712 inner_val_loss=4.72916 inner_val_multiclass_log_loss=4.72895 best_multiclass_log_loss=4.72895 best_epoch=1 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=2/40 loss=4.63418 inner_val_loss=4.63875 inner_val_multiclass_log_loss=4.63864 best_multiclass_log_loss=4.63864 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=3/40 loss=4.47050 inner_val_loss=4.55845 inner_val_multiclass_log_loss=4.55846 best_multiclass_log_loss=4.55846 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=4/40 loss=4.28382 inner_val_loss=4.46430 inner_val_multiclass_log_loss=4.46434 best_multiclass_log_loss=4.46434 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=5/40 loss=4.06116 inner_val_loss=4.30017 inner_val_multiclass_log_loss=4.30019 best_multiclass_log_loss=4.30019 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=6/40 loss=3.85503 inner_val_loss=4.16015 inner_val_multiclass_log_loss=4.16016 best_multiclass_log_loss=4.16016 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=7/40 loss=3.62213 inner_val_loss=4.02149 inner_val_multiclass_log_loss=4.02143 best_multiclass_log_loss=4.02143 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=8/40 loss=3.38358 inner_val_loss=3.92640 inner_val_multiclass_log_loss=3.92630 best_multiclass_log_loss=3.92630 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=9/40 loss=3.16037 inner_val_loss=3.74665 inner_val_multiclass_log_loss=3.74666 best_multiclass_log_loss=3.74666 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=10/40 loss=2.94154 inner_val_loss=3.61659 inner_val_multiclass_log_loss=3.61642 best_multiclass_log_loss=3.61642 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=11/40 loss=2.70740 inner_val_loss=3.57256 inner_val_multiclass_log_loss=3.57262 best_multiclass_log_loss=3.57262 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=12/40 loss=2.51318 inner_val_loss=3.41889 inner_val_multiclass_log_loss=3.41883 best_multiclass_log_loss=3.41883 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=13/40 loss=2.30900 inner_val_loss=3.33224 inner_val_multiclass_log_loss=3.33226 best_multiclass_log_loss=3.33226 best_epoch=13 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=14/40 loss=2.10852 inner_val_loss=3.24151 inner_val_multiclass_log_loss=3.24138 best_multiclass_log_loss=3.24138 best_epoch=14 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=15/40 loss=1.93431 inner_val_loss=3.17292 inner_val_multiclass_log_loss=3.17292 best_multiclass_log_loss=3.17292 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=16/40 loss=1.75495 inner_val_loss=3.05186 inner_val_multiclass_log_loss=3.05185 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=17/40 loss=1.61348 inner_val_loss=3.05905 inner_val_multiclass_log_loss=3.05913 best_multiclass_log_loss=3.05185 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=18/40 loss=1.45557 inner_val_loss=2.93761 inner_val_multiclass_log_loss=2.93763 best_multiclass_log_loss=2.93763 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=19/40 loss=1.31580 inner_val_loss=2.89615 inner_val_multiclass_log_loss=2.89613 best_multiclass_log_loss=2.89613 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=20/40 loss=1.17896 inner_val_loss=2.85645 inner_val_multiclass_log_loss=2.85643 best_multiclass_log_loss=2.85643 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=21/40 loss=1.06260 inner_val_loss=2.84489 inner_val_multiclass_log_loss=2.84490 best_multiclass_log_loss=2.84490 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=22/40 loss=0.95822 inner_val_loss=2.84380 inner_val_multiclass_log_loss=2.84387 best_multiclass_log_loss=2.84387 best_epoch=22 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=23/40 loss=0.85304 inner_val_loss=2.75879 inner_val_multiclass_log_loss=2.75881 best_multiclass_log_loss=2.75881 best_epoch=23 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=24/40 loss=0.76394 inner_val_loss=2.71588 inner_val_multiclass_log_loss=2.71583 best_multiclass_log_loss=2.71583 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=25/40 loss=0.66081 inner_val_loss=2.69955 inner_val_multiclass_log_loss=2.69955 best_multiclass_log_loss=2.69955 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=26/40 loss=0.59643 inner_val_loss=2.65847 inner_val_multiclass_log_loss=2.65846 best_multiclass_log_loss=2.65846 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=27/40 loss=0.54885 inner_val_loss=2.61736 inner_val_multiclass_log_loss=2.61743 best_multiclass_log_loss=2.61743 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=28/40 loss=0.47104 inner_val_loss=2.60538 inner_val_multiclass_log_loss=2.60538 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=29/40 loss=0.42560 inner_val_loss=2.63189 inner_val_multiclass_log_loss=2.63197 best_multiclass_log_loss=2.60538 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=30/40 loss=0.37612 inner_val_loss=2.58662 inner_val_multiclass_log_loss=2.58660 best_multiclass_log_loss=2.58660 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=31/40 loss=0.32924 inner_val_loss=2.58299 inner_val_multiclass_log_loss=2.58290 best_multiclass_log_loss=2.58290 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=32/40 loss=0.30257 inner_val_loss=2.57410 inner_val_multiclass_log_loss=2.57407 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=33/40 loss=0.26639 inner_val_loss=2.58165 inner_val_multiclass_log_loss=2.58168 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=34/40 loss=0.23653 inner_val_loss=2.59039 inner_val_multiclass_log_loss=2.59034 best_multiclass_log_loss=2.57407 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=35/40 loss=0.21390 inner_val_loss=2.52620 inner_val_multiclass_log_loss=2.52621 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=36/40 loss=0.18859 inner_val_loss=2.55555 inner_val_multiclass_log_loss=2.55550 best_multiclass_log_loss=2.52621 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=37/40 loss=0.18017 inner_val_loss=2.52622 inner_val_multiclass_log_loss=2.52619 best_multiclass_log_loss=2.52619 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=38/40 loss=0.17026 inner_val_loss=2.50314 inner_val_multiclass_log_loss=2.50314 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=39/40 loss=0.14754 inner_val_loss=2.56508 inner_val_multiclass_log_loss=2.56509 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0
  fit=26 epoch=40/40 loss=0.12889 inner_val_loss=2.50436 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50314 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 full_refit_epoch=1/38 loss=4.79225
  fit=26 full_refit_epoch=2/38 loss=4.62037
  fit=26 full_refit_epoch=3/38 loss=4.44866
  fit=26 full_refit_epoch=4/38 loss=4.24984
  fit=26 full_refit_epoch=5/38 loss=4.01907
  fit=26 full_refit_epoch=6/38 loss=3.77273
  fit=26 full_refit_epoch=7/38 loss=3.52588
  fit=26 full_refit_epoch=8/38 loss=3.28835
  fit=26 full_refit_epoch=9/38 loss=3.03910
  fit=26 full_refit_epoch=10/38 loss=2.80156
  fit=26 full_refit_epoch=11/38 loss=2.57053
  fit=26 full_refit_epoch=12/38 loss=2.36705
  fit=26 full_refit_epoch=13/38 loss=2.15250
  fit=26 full_refit_epoch=14/38 loss=1.96159
  fit=26 full_refit_epoch=15/38 loss=1.78097
  fit=26 full_refit_epoch=16/38 loss=1.61023
  fit=26 full_refit_epoch=17/38 loss=1.43917
  fit=26 full_refit_epoch=18/38 loss=1.28383
  fit=26 full_refit_epoch=19/38 loss=1.15441
  fit=26 full_refit_epoch=20/38 loss=1.03974
  fit=26 full_refit_epoch=21/38 loss=0.91690
  fit=26 full_refit_epoch=22/38 loss=0.81272
  fit=26 full_refit_epoch=23/38 loss=0.72282
  fit=26 full_refit_epoch=24/38 loss=0.63660
  fit=26 full_refit_epoch=25/38 loss=0.56613
  fit=26 full_refit_epoch=26/38 loss=0.48675
  fit=26 full_refit_epoch=27/38 loss=0.42957
  fit=26 full_refit_epoch=28/38 loss=0.37788
  fit=26 full_refit_epoch=29/38 loss=0.33382
  fit=26 full_refit_epoch=30/38 loss=0.29093
  fit=26 full_refit_epoch=31/38 loss=0.25549
  fit=26 full_refit_epoch=32/38 loss=0.22188
  fit=26 full_refit_epoch=33/38 loss=0.20243
  fit=26 full_refit_epoch=34/38 loss=0.18404
  fit=26 full_refit_epoch=35/38 loss=0.16301
  fit=26 full_refit_epoch=36/38 loss=0.14652
  fit=26 full_refit_epoch=37/38 loss=0.12670
  fit=26 full_refit_epoch=38/38 loss=0.12125

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=1/40 loss=4.77553 inner_val_loss=4.73282 inner_val_multiclass_log_loss=4.73275 best_multiclass_log_loss=4.73275 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=2/40 loss=4.60929 inner_val_loss=4.65733 inner_val_multiclass_log_loss=4.65727 best_multiclass_log_loss=4.65727 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=3/40 loss=4.44497 inner_val_loss=4.57370 inner_val_multiclass_log_loss=4.57382 best_multiclass_log_loss=4.57382 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=4/40 loss=4.26319 inner_val_loss=4.48674 inner_val_multiclass_log_loss=4.48677 best_multiclass_log_loss=4.48677 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=5/40 loss=4.05132 inner_val_loss=4.31500 inner_val_multiclass_log_loss=4.31489 best_multiclass_log_loss=4.31489 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=6/40 loss=3.83213 inner_val_loss=4.18845 inner_val_multiclass_log_loss=4.18849 best_multiclass_log_loss=4.18849 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=7/40 loss=3.60732 inner_val_loss=4.05701 inner_val_multiclass_log_loss=4.05700 best_multiclass_log_loss=4.05700 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=8/40 loss=3.37940 inner_val_loss=3.91249 inner_val_multiclass_log_loss=3.91254 best_multiclass_log_loss=3.91254 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=9/40 loss=3.16246 inner_val_loss=3.73016 inner_val_multiclass_log_loss=3.73024 best_multiclass_log_loss=3.73024 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=10/40 loss=2.93447 inner_val_loss=3.62519 inner_val_multiclass_log_loss=3.62518 best_multiclass_log_loss=3.62518 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=11/40 loss=2.73591 inner_val_loss=3.53324 inner_val_multiclass_log_loss=3.53315 best_multiclass_log_loss=3.53315 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=12/40 loss=2.54380 inner_val_loss=3.39469 inner_val_multiclass_log_loss=3.39464 best_multiclass_log_loss=3.39464 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=13/40 loss=2.33398 inner_val_loss=3.28263 inner_val_multiclass_log_loss=3.28269 best_multiclass_log_loss=3.28269 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=14/40 loss=2.15448 inner_val_loss=3.21115 inner_val_multiclass_log_loss=3.21125 best_multiclass_log_loss=3.21125 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=15/40 loss=1.97533 inner_val_loss=3.12358 inner_val_multiclass_log_loss=3.12356 best_multiclass_log_loss=3.12356 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=16/40 loss=1.81769 inner_val_loss=3.04291 inner_val_multiclass_log_loss=3.04288 best_multiclass_log_loss=3.04288 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=17/40 loss=1.65459 inner_val_loss=2.97311 inner_val_multiclass_log_loss=2.97315 best_multiclass_log_loss=2.97315 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=18/40 loss=1.50685 inner_val_loss=2.96922 inner_val_multiclass_log_loss=2.96925 best_multiclass_log_loss=2.96925 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=19/40 loss=1.37445 inner_val_loss=2.85292 inner_val_multiclass_log_loss=2.85299 best_multiclass_log_loss=2.85299 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=20/40 loss=1.23541 inner_val_loss=2.80633 inner_val_multiclass_log_loss=2.80623 best_multiclass_log_loss=2.80623 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=21/40 loss=1.11991 inner_val_loss=2.79042 inner_val_multiclass_log_loss=2.79041 best_multiclass_log_loss=2.79041 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=22/40 loss=0.99136 inner_val_loss=2.73539 inner_val_multiclass_log_loss=2.73539 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=23/40 loss=0.89412 inner_val_loss=2.75114 inner_val_multiclass_log_loss=2.75109 best_multiclass_log_loss=2.73539 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=24/40 loss=0.80540 inner_val_loss=2.66510 inner_val_multiclass_log_loss=2.66506 best_multiclass_log_loss=2.66506 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=25/40 loss=0.70602 inner_val_loss=2.65098 inner_val_multiclass_log_loss=2.65102 best_multiclass_log_loss=2.65102 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=26/40 loss=0.64932 inner_val_loss=2.62828 inner_val_multiclass_log_loss=2.62830 best_multiclass_log_loss=2.62830 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=27/40 loss=0.56294 inner_val_loss=2.61059 inner_val_multiclass_log_loss=2.61052 best_multiclass_log_loss=2.61052 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=28/40 loss=0.49822 inner_val_loss=2.59601 inner_val_multiclass_log_loss=2.59603 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=29/40 loss=0.44012 inner_val_loss=2.59872 inner_val_multiclass_log_loss=2.59876 best_multiclass_log_loss=2.59603 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=30/40 loss=0.39518 inner_val_loss=2.59065 inner_val_multiclass_log_loss=2.59064 best_multiclass_log_loss=2.59064 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=31/40 loss=0.35534 inner_val_loss=2.57242 inner_val_multiclass_log_loss=2.57239 best_multiclass_log_loss=2.57239 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=32/40 loss=0.30867 inner_val_loss=2.54830 inner_val_multiclass_log_loss=2.54820 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=33/40 loss=0.27341 inner_val_loss=2.55249 inner_val_multiclass_log_loss=2.55252 best_multiclass_log_loss=2.54820 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=34/40 loss=0.25661 inner_val_loss=2.51456 inner_val_multiclass_log_loss=2.51453 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=35/40 loss=0.22872 inner_val_loss=2.53000 inner_val_multiclass_log_loss=2.53009 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=36/40 loss=0.20184 inner_val_loss=2.53498 inner_val_multiclass_log_loss=2.53499 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=37/40 loss=0.17962 inner_val_loss=2.52292 inner_val_multiclass_log_loss=2.52285 best_multiclass_log_loss=2.51453 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=38/40 loss=0.16442 inner_val_loss=2.49969 inner_val_multiclass_log_loss=2.49963 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=39/40 loss=0.15781 inner_val_loss=2.51261 inner_val_multiclass_log_loss=2.51263 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0
  fit=27 epoch=40/40 loss=0.13961 inner_val_loss=2.51653 inner_val_multiclass_log_loss=2.51653 best_multiclass_log_loss=2.49963 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 full_refit_epoch=1/38 loss=4.77411
  fit=27 full_refit_epoch=2/38 loss=4.59733
  fit=27 full_refit_epoch=3/38 loss=4.41914
  fit=27 full_refit_epoch=4/38 loss=4.20830
  fit=27 full_refit_epoch=5/38 loss=3.97909
  fit=27 full_refit_epoch=6/38 loss=3.73578
  fit=27 full_refit_epoch=7/38 loss=3.50391
  fit=27 full_refit_epoch=8/38 loss=3.26557
  fit=27 full_refit_epoch=9/38 loss=3.01664
  fit=27 full_refit_epoch=10/38 loss=2.81115
  fit=27 full_refit_epoch=11/38 loss=2.57071
  fit=27 full_refit_epoch=12/38 loss=2.37255
  fit=27 full_refit_epoch=13/38 loss=2.16822
  fit=27 full_refit_epoch=14/38 loss=1.98347
  fit=27 full_refit_epoch=15/38 loss=1.80699
  fit=27 full_refit_epoch=16/38 loss=1.63341
  fit=27 full_refit_epoch=17/38 loss=1.47600
  fit=27 full_refit_epoch=18/38 loss=1.34416
  fit=27 full_refit_epoch=19/38 loss=1.18925
  fit=27 full_refit_epoch=20/38 loss=1.07348
  fit=27 full_refit_epoch=21/38 loss=0.95393
  fit=27 full_refit_epoch=22/38 loss=0.85577
  fit=27 full_refit_epoch=23/38 loss=0.74525
  fit=27 full_refit_epoch=24/38 loss=0.65977
  fit=27 full_refit_epoch=25/38 loss=0.57781
  fit=27 full_refit_epoch=26/38 loss=0.50285
  fit=27 full_refit_epoch=27/38 loss=0.44326
  fit=27 full_refit_epoch=28/38 loss=0.39476
  fit=27 full_refit_epoch=29/38 loss=0.34185
  fit=27 full_refit_epoch=30/38 loss=0.30400
  fit=27 full_refit_epoch=31/38 loss=0.25974
  fit=27 full_refit_epoch=32/38 loss=0.23101
  fit=27 full_refit_epoch=33/38 loss=0.20916
  fit=27 full_refit_epoch=34/38 loss=0.18475
  fit=27 full_refit_epoch=35/38 loss=0.16759
  fit=27 full_refit_epoch=36/38 loss=0.14573
  fit=27 full_refit_epoch=37/38 loss=0.13086
  fit=27 full_refit_epoch=38/38 loss=0.11576

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=1/40 loss=4.77044 inner_val_loss=4.75381 inner_val_multiclass_log_loss=4.75377 best_multiclass_log_loss=4.75377 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=2/40 loss=4.60228 inner_val_loss=4.68959 inner_val_multiclass_log_loss=4.68957 best_multiclass_log_loss=4.68957 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=3/40 loss=4.43618 inner_val_loss=4.56964 inner_val_multiclass_log_loss=4.56970 best_multiclass_log_loss=4.56970 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=4/40 loss=4.23672 inner_val_loss=4.48310 inner_val_multiclass_log_loss=4.48330 best_multiclass_log_loss=4.48330 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=5/40 loss=4.03506 inner_val_loss=4.32998 inner_val_multiclass_log_loss=4.32999 best_multiclass_log_loss=4.32999 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=6/40 loss=3.80227 inner_val_loss=4.23324 inner_val_multiclass_log_loss=4.23313 best_multiclass_log_loss=4.23313 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=7/40 loss=3.57462 inner_val_loss=4.04866 inner_val_multiclass_log_loss=4.04869 best_multiclass_log_loss=4.04869 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=8/40 loss=3.34862 inner_val_loss=3.92131 inner_val_multiclass_log_loss=3.92140 best_multiclass_log_loss=3.92140 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=9/40 loss=3.12424 inner_val_loss=3.79331 inner_val_multiclass_log_loss=3.79323 best_multiclass_log_loss=3.79323 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=10/40 loss=2.90596 inner_val_loss=3.59769 inner_val_multiclass_log_loss=3.59771 best_multiclass_log_loss=3.59771 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=11/40 loss=2.68628 inner_val_loss=3.55549 inner_val_multiclass_log_loss=3.55536 best_multiclass_log_loss=3.55536 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=12/40 loss=2.47871 inner_val_loss=3.43121 inner_val_multiclass_log_loss=3.43127 best_multiclass_log_loss=3.43127 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=13/40 loss=2.29098 inner_val_loss=3.30385 inner_val_multiclass_log_loss=3.30381 best_multiclass_log_loss=3.30381 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=14/40 loss=2.10778 inner_val_loss=3.26857 inner_val_multiclass_log_loss=3.26864 best_multiclass_log_loss=3.26864 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=15/40 loss=1.93496 inner_val_loss=3.07463 inner_val_multiclass_log_loss=3.07466 best_multiclass_log_loss=3.07466 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=16/40 loss=1.76449 inner_val_loss=3.00117 inner_val_multiclass_log_loss=3.00117 best_multiclass_log_loss=3.00117 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=17/40 loss=1.60781 inner_val_loss=2.97226 inner_val_multiclass_log_loss=2.97225 best_multiclass_log_loss=2.97225 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=18/40 loss=1.46084 inner_val_loss=2.90483 inner_val_multiclass_log_loss=2.90478 best_multiclass_log_loss=2.90478 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=19/40 loss=1.30746 inner_val_loss=2.85118 inner_val_multiclass_log_loss=2.85112 best_multiclass_log_loss=2.85112 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=20/40 loss=1.18474 inner_val_loss=2.76307 inner_val_multiclass_log_loss=2.76312 best_multiclass_log_loss=2.76312 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=21/40 loss=1.07798 inner_val_loss=2.71798 inner_val_multiclass_log_loss=2.71790 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=22/40 loss=0.96543 inner_val_loss=2.74971 inner_val_multiclass_log_loss=2.74973 best_multiclass_log_loss=2.71790 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=23/40 loss=0.87489 inner_val_loss=2.68882 inner_val_multiclass_log_loss=2.68884 best_multiclass_log_loss=2.68884 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=24/40 loss=0.77007 inner_val_loss=2.64076 inner_val_multiclass_log_loss=2.64069 best_multiclass_log_loss=2.64069 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=25/40 loss=0.68790 inner_val_loss=2.59497 inner_val_multiclass_log_loss=2.59496 best_multiclass_log_loss=2.59496 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=26/40 loss=0.62525 inner_val_loss=2.55839 inner_val_multiclass_log_loss=2.55834 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=27/40 loss=0.54866 inner_val_loss=2.57313 inner_val_multiclass_log_loss=2.57316 best_multiclass_log_loss=2.55834 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=28/40 loss=0.47933 inner_val_loss=2.54932 inner_val_multiclass_log_loss=2.54928 best_multiclass_log_loss=2.54928 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=29/40 loss=0.44446 inner_val_loss=2.49474 inner_val_multiclass_log_loss=2.49475 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=30/40 loss=0.37983 inner_val_loss=2.50766 inner_val_multiclass_log_loss=2.50771 best_multiclass_log_loss=2.49475 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=31/40 loss=0.34707 inner_val_loss=2.46953 inner_val_multiclass_log_loss=2.46951 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=32/40 loss=0.30187 inner_val_loss=2.50410 inner_val_multiclass_log_loss=2.50406 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=33/40 loss=0.26999 inner_val_loss=2.48558 inner_val_multiclass_log_loss=2.48560 best_multiclass_log_loss=2.46951 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=34/40 loss=0.24721 inner_val_loss=2.45993 inner_val_multiclass_log_loss=2.45990 best_multiclass_log_loss=2.45990 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=35/40 loss=0.21843 inner_val_loss=2.44064 inner_val_multiclass_log_loss=2.44068 best_multiclass_log_loss=2.44068 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=36/40 loss=0.20435 inner_val_loss=2.42181 inner_val_multiclass_log_loss=2.42183 best_multiclass_log_loss=2.42183 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=37/40 loss=0.17539 inner_val_loss=2.41809 inner_val_multiclass_log_loss=2.41806 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=38/40 loss=0.15881 inner_val_loss=2.44694 inner_val_multiclass_log_loss=2.44694 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=39/40 loss=0.15315 inner_val_loss=2.42802 inner_val_multiclass_log_loss=2.42807 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1
  fit=28 epoch=40/40 loss=0.13754 inner_val_loss=2.43073 inner_val_multiclass_log_loss=2.43074 best_multiclass_log_loss=2.41806 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 full_refit_epoch=1/37 loss=4.76610
  fit=28 full_refit_epoch=2/37 loss=4.58809
  fit=28 full_refit_epoch=3/37 loss=4.40191
  fit=28 full_refit_epoch=4/37 loss=4.19280
  fit=28 full_refit_epoch=5/37 loss=3.94694
  fit=28 full_refit_epoch=6/37 loss=3.70573
  fit=28 full_refit_epoch=7/37 loss=3.45771
  fit=28 full_refit_epoch=8/37 loss=3.21290
  fit=28 full_refit_epoch=9/37 loss=2.96554
  fit=28 full_refit_epoch=10/37 loss=2.74399
  fit=28 full_refit_epoch=11/37 loss=2.51527
  fit=28 full_refit_epoch=12/37 loss=2.31445
  fit=28 full_refit_epoch=13/37 loss=2.10738
  fit=28 full_refit_epoch=14/37 loss=1.91163
  fit=28 full_refit_epoch=15/37 loss=1.74298
  fit=28 full_refit_epoch=16/37 loss=1.58161
  fit=28 full_refit_epoch=17/37 loss=1.41502
  fit=28 full_refit_epoch=18/37 loss=1.27785
  fit=28 full_refit_epoch=19/37 loss=1.13593
  fit=28 full_refit_epoch=20/37 loss=1.00394
  fit=28 full_refit_epoch=21/37 loss=0.89995
  fit=28 full_refit_epoch=22/37 loss=0.79272
  fit=28 full_refit_epoch=23/37 loss=0.70862
  fit=28 full_refit_epoch=24/37 loss=0.61145
  fit=28 full_refit_epoch=25/37 loss=0.54015
  fit=28 full_refit_epoch=26/37 loss=0.48481
  fit=28 full_refit_epoch=27/37 loss=0.43559
  fit=28 full_refit_epoch=28/37 loss=0.37559
  fit=28 full_refit_epoch=29/37 loss=0.32676
  fit=28 full_refit_epoch=30/37 loss=0.29414
  fit=28 full_refit_epoch=31/37 loss=0.25896
  fit=28 full_refit_epoch=32/37 loss=0.22610
  fit=28 full_refit_epoch=33/37 loss=0.19819
  fit=28 full_refit_epoch=34/37 loss=0.17827
  fit=28 full_refit_epoch=35/37 loss=0.16779
  fit=28 full_refit_epoch=36/37 loss=0.14451
  fit=28 full_refit_epoch=37/37 loss=0.12893

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=1/40 loss=4.78906 inner_val_loss=4.74795 inner_val_multiclass_log_loss=4.74797 best_multiclass_log_loss=4.74797 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=2/40 loss=4.62550 inner_val_loss=4.68232 inner_val_multiclass_log_loss=4.68236 best_multiclass_log_loss=4.68236 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=3/40 loss=4.46330 inner_val_loss=4.60217 inner_val_multiclass_log_loss=4.60211 best_multiclass_log_loss=4.60211 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=4/40 loss=4.27422 inner_val_loss=4.50101 inner_val_multiclass_log_loss=4.50118 best_multiclass_log_loss=4.50118 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=5/40 loss=4.07407 inner_val_loss=4.37253 inner_val_multiclass_log_loss=4.37265 best_multiclass_log_loss=4.37265 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=6/40 loss=3.84442 inner_val_loss=4.25408 inner_val_multiclass_log_loss=4.25412 best_multiclass_log_loss=4.25412 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=7/40 loss=3.61990 inner_val_loss=4.11079 inner_val_multiclass_log_loss=4.11074 best_multiclass_log_loss=4.11074 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=8/40 loss=3.38342 inner_val_loss=3.96290 inner_val_multiclass_log_loss=3.96301 best_multiclass_log_loss=3.96301 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=9/40 loss=3.15400 inner_val_loss=3.80163 inner_val_multiclass_log_loss=3.80169 best_multiclass_log_loss=3.80169 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=10/40 loss=2.92771 inner_val_loss=3.73142 inner_val_multiclass_log_loss=3.73145 best_multiclass_log_loss=3.73145 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=11/40 loss=2.70259 inner_val_loss=3.60612 inner_val_multiclass_log_loss=3.60612 best_multiclass_log_loss=3.60612 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=12/40 loss=2.49012 inner_val_loss=3.47927 inner_val_multiclass_log_loss=3.47928 best_multiclass_log_loss=3.47928 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=13/40 loss=2.29365 inner_val_loss=3.33652 inner_val_multiclass_log_loss=3.33655 best_multiclass_log_loss=3.33655 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=14/40 loss=2.10643 inner_val_loss=3.26670 inner_val_multiclass_log_loss=3.26674 best_multiclass_log_loss=3.26674 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=15/40 loss=1.91050 inner_val_loss=3.13448 inner_val_multiclass_log_loss=3.13449 best_multiclass_log_loss=3.13449 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=16/40 loss=1.73629 inner_val_loss=3.08385 inner_val_multiclass_log_loss=3.08388 best_multiclass_log_loss=3.08388 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=17/40 loss=1.58935 inner_val_loss=3.00790 inner_val_multiclass_log_loss=3.00798 best_multiclass_log_loss=3.00798 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=18/40 loss=1.42176 inner_val_loss=2.86943 inner_val_multiclass_log_loss=2.86949 best_multiclass_log_loss=2.86949 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=19/40 loss=1.28264 inner_val_loss=2.84649 inner_val_multiclass_log_loss=2.84654 best_multiclass_log_loss=2.84654 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=20/40 loss=1.15295 inner_val_loss=2.82859 inner_val_multiclass_log_loss=2.82862 best_multiclass_log_loss=2.82862 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=21/40 loss=1.02289 inner_val_loss=2.75452 inner_val_multiclass_log_loss=2.75460 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=22/40 loss=0.92076 inner_val_loss=2.79044 inner_val_multiclass_log_loss=2.79044 best_multiclass_log_loss=2.75460 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=23/40 loss=0.82766 inner_val_loss=2.65027 inner_val_multiclass_log_loss=2.65022 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=24/40 loss=0.72237 inner_val_loss=2.68954 inner_val_multiclass_log_loss=2.68958 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=25/40 loss=0.64675 inner_val_loss=2.68187 inner_val_multiclass_log_loss=2.68184 best_multiclass_log_loss=2.65022 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=26/40 loss=0.57543 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60254 best_multiclass_log_loss=2.60254 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=27/40 loss=0.52233 inner_val_loss=2.55875 inner_val_multiclass_log_loss=2.55874 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=28/40 loss=0.44687 inner_val_loss=2.59887 inner_val_multiclass_log_loss=2.59881 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=29/40 loss=0.40455 inner_val_loss=2.56116 inner_val_multiclass_log_loss=2.56111 best_multiclass_log_loss=2.55874 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=30/40 loss=0.35947 inner_val_loss=2.54622 inner_val_multiclass_log_loss=2.54619 best_multiclass_log_loss=2.54619 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=31/40 loss=0.30966 inner_val_loss=2.54055 inner_val_multiclass_log_loss=2.54057 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=32/40 loss=0.28341 inner_val_loss=2.60014 inner_val_multiclass_log_loss=2.60014 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=33/40 loss=0.25652 inner_val_loss=2.56220 inner_val_multiclass_log_loss=2.56224 best_multiclass_log_loss=2.54057 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=34/40 loss=0.22953 inner_val_loss=2.52196 inner_val_multiclass_log_loss=2.52190 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=35/40 loss=0.20994 inner_val_loss=2.52543 inner_val_multiclass_log_loss=2.52545 best_multiclass_log_loss=2.52190 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=36/40 loss=0.19356 inner_val_loss=2.50430 inner_val_multiclass_log_loss=2.50429 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=37/40 loss=0.17261 inner_val_loss=2.55080 inner_val_multiclass_log_loss=2.55073 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=38/40 loss=0.14788 inner_val_loss=2.54022 inner_val_multiclass_log_loss=2.54023 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=39/40 loss=0.13704 inner_val_loss=2.51211 inner_val_multiclass_log_loss=2.51212 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0
  fit=29 epoch=40/40 loss=0.12357 inner_val_loss=2.53633 inner_val_multiclass_log_loss=2.53635 best_multiclass_log_loss=2.50429 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 full_refit_epoch=1/36 loss=4.78933
  fit=29 full_refit_epoch=2/36 loss=4.62183
  fit=29 full_refit_epoch=3/36 loss=4.44740
  fit=29 full_refit_epoch=4/36 loss=4.24532
  fit=29 full_refit_epoch=5/36 loss=4.02094
  fit=29 full_refit_epoch=6/36 loss=3.78293
  fit=29 full_refit_epoch=7/36 loss=3.53231
  fit=29 full_refit_epoch=8/36 loss=3.28427
  fit=29 full_refit_epoch=9/36 loss=3.03381
  fit=29 full_refit_epoch=10/36 loss=2.79936
  fit=29 full_refit_epoch=11/36 loss=2.58011
  fit=29 full_refit_epoch=12/36 loss=2.35711
  fit=29 full_refit_epoch=13/36 loss=2.13863
  fit=29 full_refit_epoch=14/36 loss=1.96065
  fit=29 full_refit_epoch=15/36 loss=1.76849
  fit=29 full_refit_epoch=16/36 loss=1.59651
  fit=29 full_refit_epoch=17/36 loss=1.42424
  fit=29 full_refit_epoch=18/36 loss=1.28335
  fit=29 full_refit_epoch=19/36 loss=1.15012
  fit=29 full_refit_epoch=20/36 loss=1.01315
  fit=29 full_refit_epoch=21/36 loss=0.89809
  fit=29 full_refit_epoch=22/36 loss=0.79891
  fit=29 full_refit_epoch=23/36 loss=0.68675
  fit=29 full_refit_epoch=24/36 loss=0.60914
  fit=29 full_refit_epoch=25/36 loss=0.53905
  fit=29 full_refit_epoch=26/36 loss=0.46530
  fit=29 full_refit_epoch=27/36 loss=0.41107
  fit=29 full_refit_epoch=28/36 loss=0.36036
  fit=29 full_refit_epoch=29/36 loss=0.31609
  fit=29 full_refit_epoch=30/36 loss=0.27736
  fit=29 full_refit_epoch=31/36 loss=0.24527
  fit=29 full_refit_epoch=32/36 loss=0.21381
  fit=29 full_refit_epoch=33/36 loss=0.19448
  fit=29 full_refit_epoch=34/36 loss=0.17119
  fit=29 full_refit_epoch=35/36 loss=0.14893
  fit=29 full_refit_epoch=36/36 loss=0.13754

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=1/40 loss=4.78852 inner_val_loss=4.76904 inner_val_multiclass_log_loss=4.76897 best_multiclass_log_loss=4.76897 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=2/40 loss=4.62429 inner_val_loss=4.71210 inner_val_multiclass_log_loss=4.71216 best_multiclass_log_loss=4.71216 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=3/40 loss=4.46566 inner_val_loss=4.64409 inner_val_multiclass_log_loss=4.64397 best_multiclass_log_loss=4.64397 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=4/40 loss=4.28515 inner_val_loss=4.54058 inner_val_multiclass_log_loss=4.54055 best_multiclass_log_loss=4.54055 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=5/40 loss=4.07529 inner_val_loss=4.44137 inner_val_multiclass_log_loss=4.44133 best_multiclass_log_loss=4.44133 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=6/40 loss=3.85576 inner_val_loss=4.32108 inner_val_multiclass_log_loss=4.32111 best_multiclass_log_loss=4.32111 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=7/40 loss=3.62263 inner_val_loss=4.21201 inner_val_multiclass_log_loss=4.21194 best_multiclass_log_loss=4.21194 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=8/40 loss=3.39331 inner_val_loss=4.03885 inner_val_multiclass_log_loss=4.03889 best_multiclass_log_loss=4.03889 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=9/40 loss=3.15808 inner_val_loss=3.95047 inner_val_multiclass_log_loss=3.95061 best_multiclass_log_loss=3.95061 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=10/40 loss=2.93715 inner_val_loss=3.85990 inner_val_multiclass_log_loss=3.85989 best_multiclass_log_loss=3.85989 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=11/40 loss=2.72324 inner_val_loss=3.73999 inner_val_multiclass_log_loss=3.73991 best_multiclass_log_loss=3.73991 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=12/40 loss=2.52562 inner_val_loss=3.59334 inner_val_multiclass_log_loss=3.59334 best_multiclass_log_loss=3.59334 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=13/40 loss=2.31996 inner_val_loss=3.47636 inner_val_multiclass_log_loss=3.47641 best_multiclass_log_loss=3.47641 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=14/40 loss=2.12754 inner_val_loss=3.39709 inner_val_multiclass_log_loss=3.39711 best_multiclass_log_loss=3.39711 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=15/40 loss=1.95570 inner_val_loss=3.28863 inner_val_multiclass_log_loss=3.28853 best_multiclass_log_loss=3.28853 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=16/40 loss=1.76366 inner_val_loss=3.28249 inner_val_multiclass_log_loss=3.28246 best_multiclass_log_loss=3.28246 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=17/40 loss=1.62190 inner_val_loss=3.19756 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.19763 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=18/40 loss=1.44612 inner_val_loss=3.10082 inner_val_multiclass_log_loss=3.10085 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=19/40 loss=1.31146 inner_val_loss=3.13824 inner_val_multiclass_log_loss=3.13826 best_multiclass_log_loss=3.10085 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=20/40 loss=1.18608 inner_val_loss=3.02525 inner_val_multiclass_log_loss=3.02514 best_multiclass_log_loss=3.02514 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=21/40 loss=1.05608 inner_val_loss=2.99701 inner_val_multiclass_log_loss=2.99699 best_multiclass_log_loss=2.99699 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=22/40 loss=0.92849 inner_val_loss=2.96264 inner_val_multiclass_log_loss=2.96264 best_multiclass_log_loss=2.96264 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=23/40 loss=0.83730 inner_val_loss=2.89042 inner_val_multiclass_log_loss=2.89043 best_multiclass_log_loss=2.89043 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=24/40 loss=0.72775 inner_val_loss=2.87662 inner_val_multiclass_log_loss=2.87657 best_multiclass_log_loss=2.87657 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=25/40 loss=0.65180 inner_val_loss=2.85888 inner_val_multiclass_log_loss=2.85887 best_multiclass_log_loss=2.85887 best_epoch=25 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=26/40 loss=0.59433 inner_val_loss=2.81037 inner_val_multiclass_log_loss=2.81039 best_multiclass_log_loss=2.81039 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=27/40 loss=0.51746 inner_val_loss=2.76880 inner_val_multiclass_log_loss=2.76883 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=28/40 loss=0.45104 inner_val_loss=2.78959 inner_val_multiclass_log_loss=2.78966 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=29/40 loss=0.39143 inner_val_loss=2.81155 inner_val_multiclass_log_loss=2.81148 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=30/40 loss=0.36644 inner_val_loss=2.80357 inner_val_multiclass_log_loss=2.80352 best_multiclass_log_loss=2.76883 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=31/40 loss=0.31340 inner_val_loss=2.75166 inner_val_multiclass_log_loss=2.75162 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=32/40 loss=0.27817 inner_val_loss=2.78633 inner_val_multiclass_log_loss=2.78634 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=33/40 loss=0.24365 inner_val_loss=2.77531 inner_val_multiclass_log_loss=2.77528 best_multiclass_log_loss=2.75162 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=34/40 loss=0.22111 inner_val_loss=2.75155 inner_val_multiclass_log_loss=2.75155 best_multiclass_log_loss=2.75155 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=35/40 loss=0.20138 inner_val_loss=2.74706 inner_val_multiclass_log_loss=2.74706 best_multiclass_log_loss=2.74706 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=36/40 loss=0.17586 inner_val_loss=2.71929 inner_val_multiclass_log_loss=2.71928 best_multiclass_log_loss=2.71928 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=37/40 loss=0.17020 inner_val_loss=2.71782 inner_val_multiclass_log_loss=2.71780 best_multiclass_log_loss=2.71780 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=38/40 loss=0.14854 inner_val_loss=2.70418 inner_val_multiclass_log_loss=2.70421 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=39/40 loss=0.13157 inner_val_loss=2.75853 inner_val_multiclass_log_loss=2.75848 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0
  fit=30 epoch=40/40 loss=0.12113 inner_val_loss=2.73078 inner_val_multiclass_log_loss=2.73084 best_multiclass_log_loss=2.70421 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 full_refit_epoch=1/38 loss=4.78588
  fit=30 full_refit_epoch=2/38 loss=4.61993
  fit=30 full_refit_epoch=3/38 loss=4.44642
  fit=30 full_refit_epoch=4/38 loss=4.24635
  fit=30 full_refit_epoch=5/38 loss=4.02090
  fit=30 full_refit_epoch=6/38 loss=3.78011
  fit=30 full_refit_epoch=7/38 loss=3.53233
  fit=30 full_refit_epoch=8/38 loss=3.28899
  fit=30 full_refit_epoch=9/38 loss=3.04329
  fit=30 full_refit_epoch=10/38 loss=2.81072
  fit=30 full_refit_epoch=11/38 loss=2.58246
  fit=30 full_refit_epoch=12/38 loss=2.38099
  fit=30 full_refit_epoch=13/38 loss=2.16343
  fit=30 full_refit_epoch=14/38 loss=1.97204
  fit=30 full_refit_epoch=15/38 loss=1.79387
  fit=30 full_refit_epoch=16/38 loss=1.61716
  fit=30 full_refit_epoch=17/38 loss=1.44508
  fit=30 full_refit_epoch=18/38 loss=1.29190
  fit=30 full_refit_epoch=19/38 loss=1.15543
  fit=30 full_refit_epoch=20/38 loss=1.01886
  fit=30 full_refit_epoch=21/38 loss=0.90017
  fit=30 full_refit_epoch=22/38 loss=0.79421
  fit=30 full_refit_epoch=23/38 loss=0.69174
  fit=30 full_refit_epoch=24/38 loss=0.60423
  fit=30 full_refit_epoch=25/38 loss=0.53090
  fit=30 full_refit_epoch=26/38 loss=0.46597
  fit=30 full_refit_epoch=27/38 loss=0.41092
  fit=30 full_refit_epoch=28/38 loss=0.35185
  fit=30 full_refit_epoch=29/38 loss=0.31449
  fit=30 full_refit_epoch=30/38 loss=0.27410
  fit=30 full_refit_epoch=31/38 loss=0.24654
  fit=30 full_refit_epoch=32/38 loss=0.21647
  fit=30 full_refit_epoch=33/38 loss=0.19490
  fit=30 full_refit_epoch=34/38 loss=0.17505
  fit=30 full_refit_epoch=35/38 loss=0.15285
  fit=30 full_refit_epoch=36/38 loss=0.13916
  fit=30 full_refit_epoch=37/38 loss=0.12314
  fit=30 full_refit_epoch=38/38 loss=0.10869

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=13 phase=refined_selected model=resnet18 metric=2.4587492901316477 error=None minutes=13.27

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

START seed=29 phase=baseline model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.79144 inner_val_loss=4.76133 inner_val_multiclass_log_loss=4.76143 best_multiclass_log_loss=4.76143 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=4.62554 inner_val_loss=4.70355 inner_val_multiclass_log_loss=4.70364 best_multiclass_log_loss=4.70364 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=4.45690 inner_val_loss=4.61165 inner_val_multiclass_log_loss=4.61160 best_multiclass_log_loss=4.61160 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=4.26439 inner_val_loss=4.48426 inner_val_multiclass_log_loss=4.48426 best_multiclass_log_loss=4.48426 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=4.04628 inner_val_loss=4.35704 inner_val_multiclass_log_loss=4.35702 best_multiclass_log_loss=4.35702 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=3.82694 inner_val_loss=4.22893 inner_val_multiclass_log_loss=4.22889 best_multiclass_log_loss=4.22889 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=3.58612 inner_val_loss=4.09031 inner_val_multiclass_log_loss=4.09028 best_multiclass_log_loss=4.09028 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=3.37138 inner_val_loss=3.92341 inner_val_multiclass_log_loss=3.92337 best_multiclass_log_loss=3.92337 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=3.16131 inner_val_loss=3.84799 inner_val_multiclass_log_loss=3.84804 best_multiclass_log_loss=3.84804 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=2.93246 inner_val_loss=3.68492 inner_val_multiclass_log_loss=3.68490 best_multiclass_log_loss=3.68490 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=2.71793 inner_val_loss=3.61770 inner_val_multiclass_log_loss=3.61779 best_multiclass_log_loss=3.61779 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=2.51520 inner_val_loss=3.50337 inner_val_multiclass_log_loss=3.50331 best_multiclass_log_loss=3.50331 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=2.31603 inner_val_loss=3.38420 inner_val_multiclass_log_loss=3.38421 best_multiclass_log_loss=3.38421 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=2.13215 inner_val_loss=3.33402 inner_val_multiclass_log_loss=3.33402 best_multiclass_log_loss=3.33402 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=15/40 loss=1.94203 inner_val_loss=3.19962 inner_val_multiclass_log_loss=3.19959 best_multiclass_log_loss=3.19959 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=16/40 loss=1.77130 inner_val_loss=3.11036 inner_val_multiclass_log_loss=3.11039 best_multiclass_log_loss=3.11039 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=17/40 loss=1.61756 inner_val_loss=3.06941 inner_val_multiclass_log_loss=3.06935 best_multiclass_log_loss=3.06935 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=18/40 loss=1.46287 inner_val_loss=3.01414 inner_val_multiclass_log_loss=3.01415 best_multiclass_log_loss=3.01415 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=19/40 loss=1.31347 inner_val_loss=2.99891 inner_val_multiclass_log_loss=2.99883 best_multiclass_log_loss=2.99883 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=20/40 loss=1.18822 inner_val_loss=2.92087 inner_val_multiclass_log_loss=2.92080 best_multiclass_log_loss=2.92080 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=21/40 loss=1.05517 inner_val_loss=2.88822 inner_val_multiclass_log_loss=2.88816 best_multiclass_log_loss=2.88816 best_epoch=21 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=22/40 loss=0.95697 inner_val_loss=2.83501 inner_val_multiclass_log_loss=2.83497 best_multiclass_log_loss=2.83497 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=23/40 loss=0.87262 inner_val_loss=2.77049 inner_val_multiclass_log_loss=2.77046 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=24/40 loss=0.76393 inner_val_loss=2.77348 inner_val_multiclass_log_loss=2.77354 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=25/40 loss=0.68706 inner_val_loss=2.76672 inner_val_multiclass_log_loss=2.76677 best_multiclass_log_loss=2.76677 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=26/40 loss=0.61515 inner_val_loss=2.71639 inner_val_multiclass_log_loss=2.71637 best_multiclass_log_loss=2.71637 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=27/40 loss=0.52934 inner_val_loss=2.71243 inner_val_multiclass_log_loss=2.71235 best_multiclass_log_loss=2.71235 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=28/40 loss=0.48928 inner_val_loss=2.68442 inner_val_multiclass_log_loss=2.68437 best_multiclass_log_loss=2.68437 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=29/40 loss=0.43681 inner_val_loss=2.63053 inner_val_multiclass_log_loss=2.63058 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=30/40 loss=0.37328 inner_val_loss=2.72091 inner_val_multiclass_log_loss=2.72089 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=31/40 loss=0.33404 inner_val_loss=2.66172 inner_val_multiclass_log_loss=2.66172 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=32/40 loss=0.30090 inner_val_loss=2.67711 inner_val_multiclass_log_loss=2.67710 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=33/40 loss=0.26609 inner_val_loss=2.64585 inner_val_multiclass_log_loss=2.64582 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1
  fit=1 epoch=34/40 loss=0.23828 inner_val_loss=2.65238 inner_val_multiclass_log_loss=2.65240 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/29 loss=4.78822
  fit=1 full_refit_epoch=2/29 loss=4.61409
  fit=1 full_refit_epoch=3/29 loss=4.43218
  fit=1 full_refit_epoch=4/29 loss=4.22360
  fit=1 full_refit_epoch=5/29 loss=3.98506
  fit=1 full_refit_epoch=6/29 loss=3.73938
  fit=1 full_refit_epoch=7/29 loss=3.49234
  fit=1 full_refit_epoch=8/29 loss=3.25799
  fit=1 full_refit_epoch=9/29 loss=3.02037
  fit=1 full_refit_epoch=10/29 loss=2.77619
  fit=1 full_refit_epoch=11/29 loss=2.57066
  fit=1 full_refit_epoch=12/29 loss=2.35277
  fit=1 full_refit_epoch=13/29 loss=2.14352
  fit=1 full_refit_epoch=14/29 loss=1.95123
  fit=1 full_refit_epoch=15/29 loss=1.76259
  fit=1 full_refit_epoch=16/29 loss=1.60713
  fit=1 full_refit_epoch=17/29 loss=1.43215
  fit=1 full_refit_epoch=18/29 loss=1.30671
  fit=1 full_refit_epoch=19/29 loss=1.15336
  fit=1 full_refit_epoch=20/29 loss=1.02409
  fit=1 full_refit_epoch=21/29 loss=0.90996
  fit=1 full_refit_epoch=22/29 loss=0.80927
  fit=1 full_refit_epoch=23/29 loss=0.70711
  fit=1 full_refit_epoch=24/29 loss=0.62528
  fit=1 full_refit_epoch=25/29 loss=0.54107
  fit=1 full_refit_epoch=26/29 loss=0.48100
  fit=1 full_refit_epoch=27/29 loss=0.41610
  fit=1 full_refit_epoch=28/29 loss=0.37348
  fit=1 full_refit_epoch=29/29 loss=0.32870

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=1/40 loss=4.77688 inner_val_loss=4.73210 inner_val_multiclass_log_loss=4.73224 best_multiclass_log_loss=4.73224 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=2/40 loss=4.60466 inner_val_loss=4.64713 inner_val_multiclass_log_loss=4.64698 best_multiclass_log_loss=4.64698 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=3/40 loss=4.43182 inner_val_loss=4.56443 inner_val_multiclass_log_loss=4.56453 best_multiclass_log_loss=4.56453 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=4/40 loss=4.24171 inner_val_loss=4.41614 inner_val_multiclass_log_loss=4.41620 best_multiclass_log_loss=4.41620 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=5/40 loss=4.02471 inner_val_loss=4.28676 inner_val_multiclass_log_loss=4.28664 best_multiclass_log_loss=4.28664 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=6/40 loss=3.79899 inner_val_loss=4.12236 inner_val_multiclass_log_loss=4.12235 best_multiclass_log_loss=4.12235 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=7/40 loss=3.57838 inner_val_loss=3.96545 inner_val_multiclass_log_loss=3.96543 best_multiclass_log_loss=3.96543 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=8/40 loss=3.32654 inner_val_loss=3.81237 inner_val_multiclass_log_loss=3.81239 best_multiclass_log_loss=3.81239 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=9/40 loss=3.10657 inner_val_loss=3.74201 inner_val_multiclass_log_loss=3.74201 best_multiclass_log_loss=3.74201 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=10/40 loss=2.88596 inner_val_loss=3.58560 inner_val_multiclass_log_loss=3.58566 best_multiclass_log_loss=3.58566 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=11/40 loss=2.65791 inner_val_loss=3.46592 inner_val_multiclass_log_loss=3.46595 best_multiclass_log_loss=3.46595 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=12/40 loss=2.44689 inner_val_loss=3.35923 inner_val_multiclass_log_loss=3.35918 best_multiclass_log_loss=3.35918 best_epoch=12 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=13/40 loss=2.27432 inner_val_loss=3.24337 inner_val_multiclass_log_loss=3.24334 best_multiclass_log_loss=3.24334 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=14/40 loss=2.07651 inner_val_loss=3.14473 inner_val_multiclass_log_loss=3.14488 best_multiclass_log_loss=3.14488 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=15/40 loss=1.89470 inner_val_loss=3.06804 inner_val_multiclass_log_loss=3.06804 best_multiclass_log_loss=3.06804 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=16/40 loss=1.73623 inner_val_loss=2.95022 inner_val_multiclass_log_loss=2.95029 best_multiclass_log_loss=2.95029 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=17/40 loss=1.55428 inner_val_loss=2.92689 inner_val_multiclass_log_loss=2.92689 best_multiclass_log_loss=2.92689 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=18/40 loss=1.41175 inner_val_loss=2.82146 inner_val_multiclass_log_loss=2.82155 best_multiclass_log_loss=2.82155 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=19/40 loss=1.26964 inner_val_loss=2.72490 inner_val_multiclass_log_loss=2.72484 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=20/40 loss=1.16999 inner_val_loss=2.75291 inner_val_multiclass_log_loss=2.75287 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=21/40 loss=1.03966 inner_val_loss=2.67443 inner_val_multiclass_log_loss=2.67446 best_multiclass_log_loss=2.67446 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=22/40 loss=0.91439 inner_val_loss=2.60952 inner_val_multiclass_log_loss=2.60943 best_multiclass_log_loss=2.60943 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=23/40 loss=0.83581 inner_val_loss=2.58285 inner_val_multiclass_log_loss=2.58288 best_multiclass_log_loss=2.58288 best_epoch=23 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=24/40 loss=0.74141 inner_val_loss=2.53561 inner_val_multiclass_log_loss=2.53560 best_multiclass_log_loss=2.53560 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=25/40 loss=0.66409 inner_val_loss=2.50372 inner_val_multiclass_log_loss=2.50371 best_multiclass_log_loss=2.50371 best_epoch=25 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=26/40 loss=0.57358 inner_val_loss=2.47309 inner_val_multiclass_log_loss=2.47307 best_multiclass_log_loss=2.47307 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=27/40 loss=0.50854 inner_val_loss=2.45066 inner_val_multiclass_log_loss=2.45066 best_multiclass_log_loss=2.45066 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=28/40 loss=0.45707 inner_val_loss=2.44689 inner_val_multiclass_log_loss=2.44685 best_multiclass_log_loss=2.44685 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=29/40 loss=0.40134 inner_val_loss=2.42541 inner_val_multiclass_log_loss=2.42539 best_multiclass_log_loss=2.42539 best_epoch=29 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=30/40 loss=0.36173 inner_val_loss=2.41848 inner_val_multiclass_log_loss=2.41857 best_multiclass_log_loss=2.41857 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=31/40 loss=0.31615 inner_val_loss=2.38013 inner_val_multiclass_log_loss=2.38011 best_multiclass_log_loss=2.38011 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=32/40 loss=0.28382 inner_val_loss=2.37641 inner_val_multiclass_log_loss=2.37642 best_multiclass_log_loss=2.37642 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=33/40 loss=0.26356 inner_val_loss=2.36904 inner_val_multiclass_log_loss=2.36903 best_multiclass_log_loss=2.36903 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=34/40 loss=0.23373 inner_val_loss=2.36645 inner_val_multiclass_log_loss=2.36651 best_multiclass_log_loss=2.36651 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=35/40 loss=0.21890 inner_val_loss=2.35982 inner_val_multiclass_log_loss=2.35984 best_multiclass_log_loss=2.35984 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=36/40 loss=0.18600 inner_val_loss=2.35639 inner_val_multiclass_log_loss=2.35638 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=37/40 loss=0.17461 inner_val_loss=2.36209 inner_val_multiclass_log_loss=2.36213 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=38/40 loss=0.14695 inner_val_loss=2.36564 inner_val_multiclass_log_loss=2.36560 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=39/40 loss=0.13963 inner_val_loss=2.32751 inner_val_multiclass_log_loss=2.32756 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1
  fit=2 epoch=40/40 loss=0.13450 inner_val_loss=2.34288 inner_val_multiclass_log_loss=2.34286 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 full_refit_epoch=1/39 loss=4.77703
  fit=2 full_refit_epoch=2/39 loss=4.58965
  fit=2 full_refit_epoch=3/39 loss=4.40609
  fit=2 full_refit_epoch=4/39 loss=4.18434
  fit=2 full_refit_epoch=5/39 loss=3.94119
  fit=2 full_refit_epoch=6/39 loss=3.68977
  fit=2 full_refit_epoch=7/39 loss=3.44150
  fit=2 full_refit_epoch=8/39 loss=3.18243
  fit=2 full_refit_epoch=9/39 loss=2.94295
  fit=2 full_refit_epoch=10/39 loss=2.70540
  fit=2 full_refit_epoch=11/39 loss=2.47803
  fit=2 full_refit_epoch=12/39 loss=2.26517
  fit=2 full_refit_epoch=13/39 loss=2.05341
  fit=2 full_refit_epoch=14/39 loss=1.86164
  fit=2 full_refit_epoch=15/39 loss=1.71295
  fit=2 full_refit_epoch=16/39 loss=1.52613
  fit=2 full_refit_epoch=17/39 loss=1.34509
  fit=2 full_refit_epoch=18/39 loss=1.22839
  fit=2 full_refit_epoch=19/39 loss=1.07973
  fit=2 full_refit_epoch=20/39 loss=0.97077
  fit=2 full_refit_epoch=21/39 loss=0.85544
  fit=2 full_refit_epoch=22/39 loss=0.74625
  fit=2 full_refit_epoch=23/39 loss=0.66027
  fit=2 full_refit_epoch=24/39 loss=0.57647
  fit=2 full_refit_epoch=25/39 loss=0.50676
  fit=2 full_refit_epoch=26/39 loss=0.45746
  fit=2 full_refit_epoch=27/39 loss=0.38876
  fit=2 full_refit_epoch=28/39 loss=0.35025
  fit=2 full_refit_epoch=29/39 loss=0.29588
  fit=2 full_refit_epoch=30/39 loss=0.27610
  fit=2 full_refit_epoch=31/39 loss=0.23597
  fit=2 full_refit_epoch=32/39 loss=0.21136
  fit=2 full_refit_epoch=33/39 loss=0.18650
  fit=2 full_refit_epoch=34/39 loss=0.17262
  fit=2 full_refit_epoch=35/39 loss=0.14920
  fit=2 full_refit_epoch=36/39 loss=0.13083
  fit=2 full_refit_epoch=37/39 loss=0.11639
  fit=2 full_refit_epoch=38/39 loss=0.10687
  fit=2 full_refit_epoch=39/39 loss=0.09848

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=1/40 loss=4.78788 inner_val_loss=4.73453 inner_val_multiclass_log_loss=4.73440 best_multiclass_log_loss=4.73440 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=2/40 loss=4.62429 inner_val_loss=4.65916 inner_val_multiclass_log_loss=4.65916 best_multiclass_log_loss=4.65916 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=3/40 loss=4.46878 inner_val_loss=4.56776 inner_val_multiclass_log_loss=4.56775 best_multiclass_log_loss=4.56775 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=4/40 loss=4.28168 inner_val_loss=4.46579 inner_val_multiclass_log_loss=4.46588 best_multiclass_log_loss=4.46588 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=5/40 loss=4.08050 inner_val_loss=4.29853 inner_val_multiclass_log_loss=4.29854 best_multiclass_log_loss=4.29854 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=6/40 loss=3.86685 inner_val_loss=4.14481 inner_val_multiclass_log_loss=4.14487 best_multiclass_log_loss=4.14487 best_epoch=6 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=7/40 loss=3.62955 inner_val_loss=3.99955 inner_val_multiclass_log_loss=3.99964 best_multiclass_log_loss=3.99964 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=8/40 loss=3.40460 inner_val_loss=3.84375 inner_val_multiclass_log_loss=3.84382 best_multiclass_log_loss=3.84382 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=9/40 loss=3.17732 inner_val_loss=3.75653 inner_val_multiclass_log_loss=3.75648 best_multiclass_log_loss=3.75648 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=10/40 loss=2.95777 inner_val_loss=3.55647 inner_val_multiclass_log_loss=3.55653 best_multiclass_log_loss=3.55653 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=11/40 loss=2.73494 inner_val_loss=3.48144 inner_val_multiclass_log_loss=3.48145 best_multiclass_log_loss=3.48145 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=12/40 loss=2.52807 inner_val_loss=3.36669 inner_val_multiclass_log_loss=3.36679 best_multiclass_log_loss=3.36679 best_epoch=12 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=13/40 loss=2.32670 inner_val_loss=3.23321 inner_val_multiclass_log_loss=3.23324 best_multiclass_log_loss=3.23324 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=14/40 loss=2.14211 inner_val_loss=3.13339 inner_val_multiclass_log_loss=3.13334 best_multiclass_log_loss=3.13334 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=15/40 loss=1.97379 inner_val_loss=2.99862 inner_val_multiclass_log_loss=2.99856 best_multiclass_log_loss=2.99856 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=16/40 loss=1.79112 inner_val_loss=2.95137 inner_val_multiclass_log_loss=2.95135 best_multiclass_log_loss=2.95135 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=17/40 loss=1.64030 inner_val_loss=2.85254 inner_val_multiclass_log_loss=2.85257 best_multiclass_log_loss=2.85257 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=18/40 loss=1.47695 inner_val_loss=2.79063 inner_val_multiclass_log_loss=2.79060 best_multiclass_log_loss=2.79060 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=19/40 loss=1.34568 inner_val_loss=2.71051 inner_val_multiclass_log_loss=2.71048 best_multiclass_log_loss=2.71048 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=20/40 loss=1.20112 inner_val_loss=2.69370 inner_val_multiclass_log_loss=2.69368 best_multiclass_log_loss=2.69368 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=21/40 loss=1.08037 inner_val_loss=2.65799 inner_val_multiclass_log_loss=2.65796 best_multiclass_log_loss=2.65796 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=22/40 loss=0.98182 inner_val_loss=2.59564 inner_val_multiclass_log_loss=2.59567 best_multiclass_log_loss=2.59567 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=23/40 loss=0.87696 inner_val_loss=2.57080 inner_val_multiclass_log_loss=2.57078 best_multiclass_log_loss=2.57078 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=24/40 loss=0.77895 inner_val_loss=2.49865 inner_val_multiclass_log_loss=2.49860 best_multiclass_log_loss=2.49860 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=25/40 loss=0.69952 inner_val_loss=2.48903 inner_val_multiclass_log_loss=2.48896 best_multiclass_log_loss=2.48896 best_epoch=25 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=26/40 loss=0.62977 inner_val_loss=2.48067 inner_val_multiclass_log_loss=2.48063 best_multiclass_log_loss=2.48063 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=27/40 loss=0.54283 inner_val_loss=2.44089 inner_val_multiclass_log_loss=2.44091 best_multiclass_log_loss=2.44091 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=28/40 loss=0.48600 inner_val_loss=2.42942 inner_val_multiclass_log_loss=2.42940 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=29/40 loss=0.43038 inner_val_loss=2.44990 inner_val_multiclass_log_loss=2.44988 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=30/40 loss=0.38295 inner_val_loss=2.40124 inner_val_multiclass_log_loss=2.40129 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=31/40 loss=0.34102 inner_val_loss=2.42409 inner_val_multiclass_log_loss=2.42413 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=32/40 loss=0.29692 inner_val_loss=2.40238 inner_val_multiclass_log_loss=2.40230 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=33/40 loss=0.26235 inner_val_loss=2.34556 inner_val_multiclass_log_loss=2.34554 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=34/40 loss=0.24309 inner_val_loss=2.37027 inner_val_multiclass_log_loss=2.37025 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=35/40 loss=0.21402 inner_val_loss=2.33308 inner_val_multiclass_log_loss=2.33300 best_multiclass_log_loss=2.33300 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=36/40 loss=0.18834 inner_val_loss=2.32832 inner_val_multiclass_log_loss=2.32835 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=37/40 loss=0.17150 inner_val_loss=2.33830 inner_val_multiclass_log_loss=2.33827 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=38/40 loss=0.16646 inner_val_loss=2.34553 inner_val_multiclass_log_loss=2.34549 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=39/40 loss=0.14529 inner_val_loss=2.35859 inner_val_multiclass_log_loss=2.35854 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1
  fit=3 epoch=40/40 loss=0.12740 inner_val_loss=2.36939 inner_val_multiclass_log_loss=2.36934 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 full_refit_epoch=1/36 loss=4.78174
  fit=3 full_refit_epoch=2/36 loss=4.61084
  fit=3 full_refit_epoch=3/36 loss=4.43466
  fit=3 full_refit_epoch=4/36 loss=4.23122
  fit=3 full_refit_epoch=5/36 loss=4.00552
  fit=3 full_refit_epoch=6/36 loss=3.76720
  fit=3 full_refit_epoch=7/36 loss=3.51458
  fit=3 full_refit_epoch=8/36 loss=3.27506
  fit=3 full_refit_epoch=9/36 loss=3.02642
  fit=3 full_refit_epoch=10/36 loss=2.79304
  fit=3 full_refit_epoch=11/36 loss=2.57939
  fit=3 full_refit_epoch=12/36 loss=2.36072
  fit=3 full_refit_epoch=13/36 loss=2.15404
  fit=3 full_refit_epoch=14/36 loss=1.96215
  fit=3 full_refit_epoch=15/36 loss=1.78668
  fit=3 full_refit_epoch=16/36 loss=1.61511
  fit=3 full_refit_epoch=17/36 loss=1.45979
  fit=3 full_refit_epoch=18/36 loss=1.30436
  fit=3 full_refit_epoch=19/36 loss=1.17129
  fit=3 full_refit_epoch=20/36 loss=1.03604
  fit=3 full_refit_epoch=21/36 loss=0.93486
  fit=3 full_refit_epoch=22/36 loss=0.82323
  fit=3 full_refit_epoch=23/36 loss=0.73781
  fit=3 full_refit_epoch=24/36 loss=0.63958
  fit=3 full_refit_epoch=25/36 loss=0.55612
  fit=3 full_refit_epoch=26/36 loss=0.49764
  fit=3 full_refit_epoch=27/36 loss=0.43395
  fit=3 full_refit_epoch=28/36 loss=0.38153
  fit=3 full_refit_epoch=29/36 loss=0.33402
  fit=3 full_refit_epoch=30/36 loss=0.29779
  fit=3 full_refit_epoch=31/36 loss=0.26630
  fit=3 full_refit_epoch=32/36 loss=0.23283
  fit=3 full_refit_epoch=33/36 loss=0.20140
  fit=3 full_refit_epoch=34/36 loss=0.18013
  fit=3 full_refit_epoch=35/36 loss=0.16015
  fit=3 full_refit_epoch=36/36 loss=0.15038

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=1/40 loss=4.78972 inner_val_loss=4.78068 inner_val_multiclass_log_loss=4.78091 best_multiclass_log_loss=4.78091 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=2/40 loss=4.61644 inner_val_loss=4.70122 inner_val_multiclass_log_loss=4.70113 best_multiclass_log_loss=4.70113 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=3/40 loss=4.45221 inner_val_loss=4.62067 inner_val_multiclass_log_loss=4.62064 best_multiclass_log_loss=4.62064 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=4/40 loss=4.27089 inner_val_loss=4.47619 inner_val_multiclass_log_loss=4.47618 best_multiclass_log_loss=4.47618 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=5/40 loss=4.06268 inner_val_loss=4.36162 inner_val_multiclass_log_loss=4.36158 best_multiclass_log_loss=4.36158 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=6/40 loss=3.84209 inner_val_loss=4.26205 inner_val_multiclass_log_loss=4.26196 best_multiclass_log_loss=4.26196 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=7/40 loss=3.61849 inner_val_loss=4.08260 inner_val_multiclass_log_loss=4.08265 best_multiclass_log_loss=4.08265 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=8/40 loss=3.39831 inner_val_loss=3.93322 inner_val_multiclass_log_loss=3.93321 best_multiclass_log_loss=3.93321 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=9/40 loss=3.19004 inner_val_loss=3.87016 inner_val_multiclass_log_loss=3.87020 best_multiclass_log_loss=3.87020 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=10/40 loss=2.96517 inner_val_loss=3.75255 inner_val_multiclass_log_loss=3.75255 best_multiclass_log_loss=3.75255 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=11/40 loss=2.75054 inner_val_loss=3.67104 inner_val_multiclass_log_loss=3.67106 best_multiclass_log_loss=3.67106 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=12/40 loss=2.54064 inner_val_loss=3.57192 inner_val_multiclass_log_loss=3.57195 best_multiclass_log_loss=3.57195 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=13/40 loss=2.34203 inner_val_loss=3.46974 inner_val_multiclass_log_loss=3.46984 best_multiclass_log_loss=3.46984 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=14/40 loss=2.14699 inner_val_loss=3.39058 inner_val_multiclass_log_loss=3.39060 best_multiclass_log_loss=3.39060 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=15/40 loss=1.97566 inner_val_loss=3.22496 inner_val_multiclass_log_loss=3.22488 best_multiclass_log_loss=3.22488 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=16/40 loss=1.78328 inner_val_loss=3.20142 inner_val_multiclass_log_loss=3.20133 best_multiclass_log_loss=3.20133 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=17/40 loss=1.61451 inner_val_loss=3.10055 inner_val_multiclass_log_loss=3.10061 best_multiclass_log_loss=3.10061 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=18/40 loss=1.48052 inner_val_loss=3.06376 inner_val_multiclass_log_loss=3.06376 best_multiclass_log_loss=3.06376 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=19/40 loss=1.30872 inner_val_loss=2.99257 inner_val_multiclass_log_loss=2.99263 best_multiclass_log_loss=2.99263 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=20/40 loss=1.18439 inner_val_loss=2.97069 inner_val_multiclass_log_loss=2.97066 best_multiclass_log_loss=2.97066 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=21/40 loss=1.07813 inner_val_loss=2.89766 inner_val_multiclass_log_loss=2.89778 best_multiclass_log_loss=2.89778 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=22/40 loss=0.94472 inner_val_loss=2.84399 inner_val_multiclass_log_loss=2.84401 best_multiclass_log_loss=2.84401 best_epoch=22 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=23/40 loss=0.85215 inner_val_loss=2.81882 inner_val_multiclass_log_loss=2.81876 best_multiclass_log_loss=2.81876 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=24/40 loss=0.76193 inner_val_loss=2.78520 inner_val_multiclass_log_loss=2.78512 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=25/40 loss=0.67522 inner_val_loss=2.79527 inner_val_multiclass_log_loss=2.79529 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=26/40 loss=0.59620 inner_val_loss=2.76630 inner_val_multiclass_log_loss=2.76634 best_multiclass_log_loss=2.76634 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=27/40 loss=0.53659 inner_val_loss=2.73014 inner_val_multiclass_log_loss=2.73021 best_multiclass_log_loss=2.73021 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=28/40 loss=0.46902 inner_val_loss=2.68155 inner_val_multiclass_log_loss=2.68160 best_multiclass_log_loss=2.68160 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=29/40 loss=0.42078 inner_val_loss=2.66191 inner_val_multiclass_log_loss=2.66190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=30/40 loss=0.37526 inner_val_loss=2.67838 inner_val_multiclass_log_loss=2.67840 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=31/40 loss=0.32713 inner_val_loss=2.67195 inner_val_multiclass_log_loss=2.67190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=32/40 loss=0.29732 inner_val_loss=2.64314 inner_val_multiclass_log_loss=2.64318 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=33/40 loss=0.26400 inner_val_loss=2.64539 inner_val_multiclass_log_loss=2.64539 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=34/40 loss=0.22863 inner_val_loss=2.62849 inner_val_multiclass_log_loss=2.62847 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=35/40 loss=0.21273 inner_val_loss=2.68348 inner_val_multiclass_log_loss=2.68344 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=36/40 loss=0.18296 inner_val_loss=2.62064 inner_val_multiclass_log_loss=2.62070 best_multiclass_log_loss=2.62070 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=37/40 loss=0.16822 inner_val_loss=2.59413 inner_val_multiclass_log_loss=2.59413 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=38/40 loss=0.15150 inner_val_loss=2.62271 inner_val_multiclass_log_loss=2.62273 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=39/40 loss=0.14116 inner_val_loss=2.60107 inner_val_multiclass_log_loss=2.60106 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1
  fit=4 epoch=40/40 loss=0.12134 inner_val_loss=2.58163 inner_val_multiclass_log_loss=2.58163 best_multiclass_log_loss=2.58163 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 full_refit_epoch=1/40 loss=4.78354
  fit=4 full_refit_epoch=2/40 loss=4.60792
  fit=4 full_refit_epoch=3/40 loss=4.43281
  fit=4 full_refit_epoch=4/40 loss=4.22375
  fit=4 full_refit_epoch=5/40 loss=3.98823
  fit=4 full_refit_epoch=6/40 loss=3.75429
  fit=4 full_refit_epoch=7/40 loss=3.52034
  fit=4 full_refit_epoch=8/40 loss=3.27720
  fit=4 full_refit_epoch=9/40 loss=3.03494
  fit=4 full_refit_epoch=10/40 loss=2.80688
  fit=4 full_refit_epoch=11/40 loss=2.58710
  fit=4 full_refit_epoch=12/40 loss=2.35734
  fit=4 full_refit_epoch=13/40 loss=2.16211
  fit=4 full_refit_epoch=14/40 loss=1.95755
  fit=4 full_refit_epoch=15/40 loss=1.76778
  fit=4 full_refit_epoch=16/40 loss=1.59597
  fit=4 full_refit_epoch=17/40 loss=1.43546
  fit=4 full_refit_epoch=18/40 loss=1.29959
  fit=4 full_refit_epoch=19/40 loss=1.14497
  fit=4 full_refit_epoch=20/40 loss=1.00626
  fit=4 full_refit_epoch=21/40 loss=0.90324
  fit=4 full_refit_epoch=22/40 loss=0.80394
  fit=4 full_refit_epoch=23/40 loss=0.70506
  fit=4 full_refit_epoch=24/40 loss=0.60783
  fit=4 full_refit_epoch=25/40 loss=0.54702
  fit=4 full_refit_epoch=26/40 loss=0.47226
  fit=4 full_refit_epoch=27/40 loss=0.41576
  fit=4 full_refit_epoch=28/40 loss=0.36619
  fit=4 full_refit_epoch=29/40 loss=0.31657
  fit=4 full_refit_epoch=30/40 loss=0.27211
  fit=4 full_refit_epoch=31/40 loss=0.24408
  fit=4 full_refit_epoch=32/40 loss=0.21425
  fit=4 full_refit_epoch=33/40 loss=0.19270
  fit=4 full_refit_epoch=34/40 loss=0.17262
  fit=4 full_refit_epoch=35/40 loss=0.15522
  fit=4 full_refit_epoch=36/40 loss=0.13730
  fit=4 full_refit_epoch=37/40 loss=0.12264
  fit=4 full_refit_epoch=38/40 loss=0.11303
  fit=4 full_refit_epoch=39/40 loss=0.10542
  fit=4 full_refit_epoch=40/40 loss=0.09377

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=1/40 loss=4.77984 inner_val_loss=4.72068 inner_val_multiclass_log_loss=4.72080 best_multiclass_log_loss=4.72080 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=2/40 loss=4.61636 inner_val_loss=4.63699 inner_val_multiclass_log_loss=4.63693 best_multiclass_log_loss=4.63693 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=3/40 loss=4.45690 inner_val_loss=4.53775 inner_val_multiclass_log_loss=4.53788 best_multiclass_log_loss=4.53788 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=4/40 loss=4.27154 inner_val_loss=4.42661 inner_val_multiclass_log_loss=4.42666 best_multiclass_log_loss=4.42666 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=5/40 loss=4.07261 inner_val_loss=4.30221 inner_val_multiclass_log_loss=4.30233 best_multiclass_log_loss=4.30233 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=6/40 loss=3.86698 inner_val_loss=4.12875 inner_val_multiclass_log_loss=4.12878 best_multiclass_log_loss=4.12878 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=7/40 loss=3.63809 inner_val_loss=4.01937 inner_val_multiclass_log_loss=4.01942 best_multiclass_log_loss=4.01942 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=8/40 loss=3.41935 inner_val_loss=3.87518 inner_val_multiclass_log_loss=3.87534 best_multiclass_log_loss=3.87534 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=9/40 loss=3.18955 inner_val_loss=3.70662 inner_val_multiclass_log_loss=3.70651 best_multiclass_log_loss=3.70651 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=10/40 loss=2.97659 inner_val_loss=3.54444 inner_val_multiclass_log_loss=3.54442 best_multiclass_log_loss=3.54442 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=11/40 loss=2.76710 inner_val_loss=3.46261 inner_val_multiclass_log_loss=3.46251 best_multiclass_log_loss=3.46251 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=12/40 loss=2.57334 inner_val_loss=3.27116 inner_val_multiclass_log_loss=3.27115 best_multiclass_log_loss=3.27115 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=13/40 loss=2.36194 inner_val_loss=3.19750 inner_val_multiclass_log_loss=3.19768 best_multiclass_log_loss=3.19768 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=14/40 loss=2.17910 inner_val_loss=3.07389 inner_val_multiclass_log_loss=3.07391 best_multiclass_log_loss=3.07391 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=15/40 loss=1.99885 inner_val_loss=3.01897 inner_val_multiclass_log_loss=3.01895 best_multiclass_log_loss=3.01895 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=16/40 loss=1.82771 inner_val_loss=2.94047 inner_val_multiclass_log_loss=2.94037 best_multiclass_log_loss=2.94037 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=17/40 loss=1.65915 inner_val_loss=2.81063 inner_val_multiclass_log_loss=2.81061 best_multiclass_log_loss=2.81061 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=18/40 loss=1.51430 inner_val_loss=2.77291 inner_val_multiclass_log_loss=2.77299 best_multiclass_log_loss=2.77299 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=19/40 loss=1.36006 inner_val_loss=2.70794 inner_val_multiclass_log_loss=2.70795 best_multiclass_log_loss=2.70795 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=20/40 loss=1.24242 inner_val_loss=2.63758 inner_val_multiclass_log_loss=2.63757 best_multiclass_log_loss=2.63757 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=21/40 loss=1.10894 inner_val_loss=2.62117 inner_val_multiclass_log_loss=2.62113 best_multiclass_log_loss=2.62113 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=22/40 loss=0.99728 inner_val_loss=2.57374 inner_val_multiclass_log_loss=2.57372 best_multiclass_log_loss=2.57372 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=23/40 loss=0.89508 inner_val_loss=2.56801 inner_val_multiclass_log_loss=2.56802 best_multiclass_log_loss=2.56802 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=24/40 loss=0.79840 inner_val_loss=2.51540 inner_val_multiclass_log_loss=2.51532 best_multiclass_log_loss=2.51532 best_epoch=24 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=25/40 loss=0.70842 inner_val_loss=2.48709 inner_val_multiclass_log_loss=2.48713 best_multiclass_log_loss=2.48713 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=26/40 loss=0.63383 inner_val_loss=2.45845 inner_val_multiclass_log_loss=2.45841 best_multiclass_log_loss=2.45841 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=27/40 loss=0.57510 inner_val_loss=2.43780 inner_val_multiclass_log_loss=2.43789 best_multiclass_log_loss=2.43789 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=28/40 loss=0.49380 inner_val_loss=2.40752 inner_val_multiclass_log_loss=2.40752 best_multiclass_log_loss=2.40752 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=29/40 loss=0.43158 inner_val_loss=2.38063 inner_val_multiclass_log_loss=2.38061 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=30/40 loss=0.40393 inner_val_loss=2.40156 inner_val_multiclass_log_loss=2.40155 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=31/40 loss=0.34829 inner_val_loss=2.34321 inner_val_multiclass_log_loss=2.34324 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=32/40 loss=0.30293 inner_val_loss=2.34830 inner_val_multiclass_log_loss=2.34833 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=33/40 loss=0.27191 inner_val_loss=2.33435 inner_val_multiclass_log_loss=2.33438 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=34/40 loss=0.24077 inner_val_loss=2.36642 inner_val_multiclass_log_loss=2.36640 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=35/40 loss=0.21350 inner_val_loss=2.35795 inner_val_multiclass_log_loss=2.35801 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=36/40 loss=0.21089 inner_val_loss=2.32175 inner_val_multiclass_log_loss=2.32167 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=37/40 loss=0.17882 inner_val_loss=2.32570 inner_val_multiclass_log_loss=2.32573 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=38/40 loss=0.16260 inner_val_loss=2.31285 inner_val_multiclass_log_loss=2.31276 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=39/40 loss=0.14282 inner_val_loss=2.37636 inner_val_multiclass_log_loss=2.37630 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.0
  fit=5 epoch=40/40 loss=0.13584 inner_val_loss=2.33817 inner_val_multiclass_log_loss=2.33822 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 full_refit_epoch=1/38 loss=4.77285
  fit=5 full_refit_epoch=2/38 loss=4.60156
  fit=5 full_refit_epoch=3/38 loss=4.42367
  fit=5 full_refit_epoch=4/38 loss=4.21951
  fit=5 full_refit_epoch=5/38 loss=3.99543
  fit=5 full_refit_epoch=6/38 loss=3.76219
  fit=5 full_refit_epoch=7/38 loss=3.51045
  fit=5 full_refit_epoch=8/38 loss=3.26475
  fit=5 full_refit_epoch=9/38 loss=3.01855
  fit=5 full_refit_epoch=10/38 loss=2.79697
  fit=5 full_refit_epoch=11/38 loss=2.56724
  fit=5 full_refit_epoch=12/38 loss=2.34649
  fit=5 full_refit_epoch=13/38 loss=2.14739
  fit=5 full_refit_epoch=14/38 loss=1.94784
  fit=5 full_refit_epoch=15/38 loss=1.77608
  fit=5 full_refit_epoch=16/38 loss=1.58856
  fit=5 full_refit_epoch=17/38 loss=1.43336
  fit=5 full_refit_epoch=18/38 loss=1.28592
  fit=5 full_refit_epoch=19/38 loss=1.14915
  fit=5 full_refit_epoch=20/38 loss=1.01684
  fit=5 full_refit_epoch=21/38 loss=0.90502
  fit=5 full_refit_epoch=22/38 loss=0.79337
  fit=5 full_refit_epoch=23/38 loss=0.69822
  fit=5 full_refit_epoch=24/38 loss=0.61281
  fit=5 full_refit_epoch=25/38 loss=0.54337
  fit=5 full_refit_epoch=26/38 loss=0.47650
  fit=5 full_refit_epoch=27/38 loss=0.42055
  fit=5 full_refit_epoch=28/38 loss=0.35945
  fit=5 full_refit_epoch=29/38 loss=0.32238
  fit=5 full_refit_epoch=30/38 loss=0.28152
  fit=5 full_refit_epoch=31/38 loss=0.25445
  fit=5 full_refit_epoch=32/38 loss=0.21704
  fit=5 full_refit_epoch=33/38 loss=0.19919
  fit=5 full_refit_epoch=34/38 loss=0.17358
  fit=5 full_refit_epoch=35/38 loss=0.15832
  fit=5 full_refit_epoch=36/38 loss=0.14008
  fit=5 full_refit_epoch=37/38 loss=0.12395
  fit=5 full_refit_epoch=38/38 loss=0.11568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=baseline model=resnet18 metric=2.471291572428004 error=None minutes=13.19
START seed=29 phase=initial model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=1/40 loss=4.79144 inner_val_loss=4.76133 inner_val_multiclass_log_loss=4.76143 best_multiclass_log_loss=4.76143 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=2/40 loss=4.62554 inner_val_loss=4.70355 inner_val_multiclass_log_loss=4.70364 best_multiclass_log_loss=4.70364 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=3/40 loss=4.45690 inner_val_loss=4.61165 inner_val_multiclass_log_loss=4.61160 best_multiclass_log_loss=4.61160 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=4/40 loss=4.26439 inner_val_loss=4.48426 inner_val_multiclass_log_loss=4.48426 best_multiclass_log_loss=4.48426 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=5/40 loss=4.04628 inner_val_loss=4.35704 inner_val_multiclass_log_loss=4.35702 best_multiclass_log_loss=4.35702 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=6/40 loss=3.82694 inner_val_loss=4.22893 inner_val_multiclass_log_loss=4.22889 best_multiclass_log_loss=4.22889 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=7/40 loss=3.58612 inner_val_loss=4.09031 inner_val_multiclass_log_loss=4.09028 best_multiclass_log_loss=4.09028 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=8/40 loss=3.37138 inner_val_loss=3.92341 inner_val_multiclass_log_loss=3.92337 best_multiclass_log_loss=3.92337 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=9/40 loss=3.16131 inner_val_loss=3.84799 inner_val_multiclass_log_loss=3.84804 best_multiclass_log_loss=3.84804 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=10/40 loss=2.93246 inner_val_loss=3.68492 inner_val_multiclass_log_loss=3.68490 best_multiclass_log_loss=3.68490 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=11/40 loss=2.71793 inner_val_loss=3.61770 inner_val_multiclass_log_loss=3.61779 best_multiclass_log_loss=3.61779 best_epoch=11 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=12/40 loss=2.51520 inner_val_loss=3.50337 inner_val_multiclass_log_loss=3.50331 best_multiclass_log_loss=3.50331 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=13/40 loss=2.31603 inner_val_loss=3.38420 inner_val_multiclass_log_loss=3.38421 best_multiclass_log_loss=3.38421 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=14/40 loss=2.13215 inner_val_loss=3.33402 inner_val_multiclass_log_loss=3.33402 best_multiclass_log_loss=3.33402 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=15/40 loss=1.94203 inner_val_loss=3.19962 inner_val_multiclass_log_loss=3.19959 best_multiclass_log_loss=3.19959 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=16/40 loss=1.77130 inner_val_loss=3.11036 inner_val_multiclass_log_loss=3.11039 best_multiclass_log_loss=3.11039 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=17/40 loss=1.61756 inner_val_loss=3.06941 inner_val_multiclass_log_loss=3.06935 best_multiclass_log_loss=3.06935 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=18/40 loss=1.46287 inner_val_loss=3.01414 inner_val_multiclass_log_loss=3.01415 best_multiclass_log_loss=3.01415 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=19/40 loss=1.31347 inner_val_loss=2.99891 inner_val_multiclass_log_loss=2.99883 best_multiclass_log_loss=2.99883 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=20/40 loss=1.18822 inner_val_loss=2.92087 inner_val_multiclass_log_loss=2.92080 best_multiclass_log_loss=2.92080 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=21/40 loss=1.05517 inner_val_loss=2.88822 inner_val_multiclass_log_loss=2.88816 best_multiclass_log_loss=2.88816 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=22/40 loss=0.95697 inner_val_loss=2.83501 inner_val_multiclass_log_loss=2.83497 best_multiclass_log_loss=2.83497 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=23/40 loss=0.87262 inner_val_loss=2.77049 inner_val_multiclass_log_loss=2.77046 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=24/40 loss=0.76393 inner_val_loss=2.77348 inner_val_multiclass_log_loss=2.77354 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=25/40 loss=0.68706 inner_val_loss=2.76672 inner_val_multiclass_log_loss=2.76677 best_multiclass_log_loss=2.76677 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=26/40 loss=0.61515 inner_val_loss=2.71639 inner_val_multiclass_log_loss=2.71637 best_multiclass_log_loss=2.71637 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=27/40 loss=0.52934 inner_val_loss=2.71243 inner_val_multiclass_log_loss=2.71235 best_multiclass_log_loss=2.71235 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=28/40 loss=0.48928 inner_val_loss=2.68442 inner_val_multiclass_log_loss=2.68437 best_multiclass_log_loss=2.68437 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=29/40 loss=0.43681 inner_val_loss=2.63053 inner_val_multiclass_log_loss=2.63058 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=30/40 loss=0.37328 inner_val_loss=2.72091 inner_val_multiclass_log_loss=2.72089 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=31/40 loss=0.33404 inner_val_loss=2.66172 inner_val_multiclass_log_loss=2.66172 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=32/40 loss=0.30090 inner_val_loss=2.67711 inner_val_multiclass_log_loss=2.67710 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=33/40 loss=0.26609 inner_val_loss=2.64585 inner_val_multiclass_log_loss=2.64582 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0
  fit=6 epoch=34/40 loss=0.23828 inner_val_loss=2.65238 inner_val_multiclass_log_loss=2.65240 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 full_refit_epoch=1/29 loss=4.78822
  fit=6 full_refit_epoch=2/29 loss=4.61409
  fit=6 full_refit_epoch=3/29 loss=4.43218
  fit=6 full_refit_epoch=4/29 loss=4.22360
  fit=6 full_refit_epoch=5/29 loss=3.98506
  fit=6 full_refit_epoch=6/29 loss=3.73938
  fit=6 full_refit_epoch=7/29 loss=3.49234
  fit=6 full_refit_epoch=8/29 loss=3.25799
  fit=6 full_refit_epoch=9/29 loss=3.02037
  fit=6 full_refit_epoch=10/29 loss=2.77619
  fit=6 full_refit_epoch=11/29 loss=2.57066
  fit=6 full_refit_epoch=12/29 loss=2.35277
  fit=6 full_refit_epoch=13/29 loss=2.14352
  fit=6 full_refit_epoch=14/29 loss=1.95123
  fit=6 full_refit_epoch=15/29 loss=1.76259
  fit=6 full_refit_epoch=16/29 loss=1.60713
  fit=6 full_refit_epoch=17/29 loss=1.43215
  fit=6 full_refit_epoch=18/29 loss=1.30671
  fit=6 full_refit_epoch=19/29 loss=1.15336
  fit=6 full_refit_epoch=20/29 loss=1.02409
  fit=6 full_refit_epoch=21/29 loss=0.90996
  fit=6 full_refit_epoch=22/29 loss=0.80927
  fit=6 full_refit_epoch=23/29 loss=0.70711
  fit=6 full_refit_epoch=24/29 loss=0.62528
  fit=6 full_refit_epoch=25/29 loss=0.54107
  fit=6 full_refit_epoch=26/29 loss=0.48100
  fit=6 full_refit_epoch=27/29 loss=0.41610
  fit=6 full_refit_epoch=28/29 loss=0.37348
  fit=6 full_refit_epoch=29/29 loss=0.32870

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=1/40 loss=4.77688 inner_val_loss=4.73210 inner_val_multiclass_log_loss=4.73224 best_multiclass_log_loss=4.73224 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=2/40 loss=4.60466 inner_val_loss=4.64713 inner_val_multiclass_log_loss=4.64698 best_multiclass_log_loss=4.64698 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=3/40 loss=4.43182 inner_val_loss=4.56443 inner_val_multiclass_log_loss=4.56453 best_multiclass_log_loss=4.56453 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=4/40 loss=4.24171 inner_val_loss=4.41614 inner_val_multiclass_log_loss=4.41620 best_multiclass_log_loss=4.41620 best_epoch=4 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=5/40 loss=4.02471 inner_val_loss=4.28676 inner_val_multiclass_log_loss=4.28664 best_multiclass_log_loss=4.28664 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=6/40 loss=3.79899 inner_val_loss=4.12236 inner_val_multiclass_log_loss=4.12235 best_multiclass_log_loss=4.12235 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=7/40 loss=3.57838 inner_val_loss=3.96545 inner_val_multiclass_log_loss=3.96543 best_multiclass_log_loss=3.96543 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=8/40 loss=3.32654 inner_val_loss=3.81237 inner_val_multiclass_log_loss=3.81239 best_multiclass_log_loss=3.81239 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=9/40 loss=3.10657 inner_val_loss=3.74201 inner_val_multiclass_log_loss=3.74201 best_multiclass_log_loss=3.74201 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=10/40 loss=2.88596 inner_val_loss=3.58560 inner_val_multiclass_log_loss=3.58566 best_multiclass_log_loss=3.58566 best_epoch=10 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=11/40 loss=2.65791 inner_val_loss=3.46592 inner_val_multiclass_log_loss=3.46595 best_multiclass_log_loss=3.46595 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=12/40 loss=2.44689 inner_val_loss=3.35923 inner_val_multiclass_log_loss=3.35918 best_multiclass_log_loss=3.35918 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=13/40 loss=2.27432 inner_val_loss=3.24337 inner_val_multiclass_log_loss=3.24334 best_multiclass_log_loss=3.24334 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=14/40 loss=2.07651 inner_val_loss=3.14473 inner_val_multiclass_log_loss=3.14488 best_multiclass_log_loss=3.14488 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=15/40 loss=1.89470 inner_val_loss=3.06804 inner_val_multiclass_log_loss=3.06804 best_multiclass_log_loss=3.06804 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=16/40 loss=1.73623 inner_val_loss=2.95022 inner_val_multiclass_log_loss=2.95029 best_multiclass_log_loss=2.95029 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=17/40 loss=1.55428 inner_val_loss=2.92689 inner_val_multiclass_log_loss=2.92689 best_multiclass_log_loss=2.92689 best_epoch=17 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=18/40 loss=1.41175 inner_val_loss=2.82146 inner_val_multiclass_log_loss=2.82155 best_multiclass_log_loss=2.82155 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=19/40 loss=1.26964 inner_val_loss=2.72490 inner_val_multiclass_log_loss=2.72484 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=20/40 loss=1.16999 inner_val_loss=2.75291 inner_val_multiclass_log_loss=2.75287 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=21/40 loss=1.03966 inner_val_loss=2.67443 inner_val_multiclass_log_loss=2.67446 best_multiclass_log_loss=2.67446 best_epoch=21 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=22/40 loss=0.91439 inner_val_loss=2.60952 inner_val_multiclass_log_loss=2.60943 best_multiclass_log_loss=2.60943 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=23/40 loss=0.83581 inner_val_loss=2.58285 inner_val_multiclass_log_loss=2.58288 best_multiclass_log_loss=2.58288 best_epoch=23 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=24/40 loss=0.74141 inner_val_loss=2.53561 inner_val_multiclass_log_loss=2.53560 best_multiclass_log_loss=2.53560 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=25/40 loss=0.66409 inner_val_loss=2.50372 inner_val_multiclass_log_loss=2.50371 best_multiclass_log_loss=2.50371 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=26/40 loss=0.57358 inner_val_loss=2.47309 inner_val_multiclass_log_loss=2.47307 best_multiclass_log_loss=2.47307 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=27/40 loss=0.50854 inner_val_loss=2.45066 inner_val_multiclass_log_loss=2.45066 best_multiclass_log_loss=2.45066 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=28/40 loss=0.45707 inner_val_loss=2.44689 inner_val_multiclass_log_loss=2.44685 best_multiclass_log_loss=2.44685 best_epoch=28 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=29/40 loss=0.40134 inner_val_loss=2.42541 inner_val_multiclass_log_loss=2.42539 best_multiclass_log_loss=2.42539 best_epoch=29 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=30/40 loss=0.36173 inner_val_loss=2.41848 inner_val_multiclass_log_loss=2.41857 best_multiclass_log_loss=2.41857 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=31/40 loss=0.31615 inner_val_loss=2.38013 inner_val_multiclass_log_loss=2.38011 best_multiclass_log_loss=2.38011 best_epoch=31 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=32/40 loss=0.28382 inner_val_loss=2.37641 inner_val_multiclass_log_loss=2.37642 best_multiclass_log_loss=2.37642 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=33/40 loss=0.26356 inner_val_loss=2.36904 inner_val_multiclass_log_loss=2.36903 best_multiclass_log_loss=2.36903 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=34/40 loss=0.23373 inner_val_loss=2.36645 inner_val_multiclass_log_loss=2.36651 best_multiclass_log_loss=2.36651 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=35/40 loss=0.21890 inner_val_loss=2.35982 inner_val_multiclass_log_loss=2.35984 best_multiclass_log_loss=2.35984 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=36/40 loss=0.18600 inner_val_loss=2.35639 inner_val_multiclass_log_loss=2.35638 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=37/40 loss=0.17461 inner_val_loss=2.36209 inner_val_multiclass_log_loss=2.36213 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=38/40 loss=0.14695 inner_val_loss=2.36564 inner_val_multiclass_log_loss=2.36560 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=39/40 loss=0.13963 inner_val_loss=2.32751 inner_val_multiclass_log_loss=2.32756 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1
  fit=7 epoch=40/40 loss=0.13450 inner_val_loss=2.34288 inner_val_multiclass_log_loss=2.34286 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 full_refit_epoch=1/39 loss=4.77703
  fit=7 full_refit_epoch=2/39 loss=4.58965
  fit=7 full_refit_epoch=3/39 loss=4.40609
  fit=7 full_refit_epoch=4/39 loss=4.18434
  fit=7 full_refit_epoch=5/39 loss=3.94119
  fit=7 full_refit_epoch=6/39 loss=3.68977
  fit=7 full_refit_epoch=7/39 loss=3.44150
  fit=7 full_refit_epoch=8/39 loss=3.18243
  fit=7 full_refit_epoch=9/39 loss=2.94295
  fit=7 full_refit_epoch=10/39 loss=2.70540
  fit=7 full_refit_epoch=11/39 loss=2.47803
  fit=7 full_refit_epoch=12/39 loss=2.26517
  fit=7 full_refit_epoch=13/39 loss=2.05341
  fit=7 full_refit_epoch=14/39 loss=1.86164
  fit=7 full_refit_epoch=15/39 loss=1.71295
  fit=7 full_refit_epoch=16/39 loss=1.52613
  fit=7 full_refit_epoch=17/39 loss=1.34509
  fit=7 full_refit_epoch=18/39 loss=1.22839
  fit=7 full_refit_epoch=19/39 loss=1.07973
  fit=7 full_refit_epoch=20/39 loss=0.97077
  fit=7 full_refit_epoch=21/39 loss=0.85544
  fit=7 full_refit_epoch=22/39 loss=0.74625
  fit=7 full_refit_epoch=23/39 loss=0.66027
  fit=7 full_refit_epoch=24/39 loss=0.57647
  fit=7 full_refit_epoch=25/39 loss=0.50676
  fit=7 full_refit_epoch=26/39 loss=0.45746
  fit=7 full_refit_epoch=27/39 loss=0.38876
  fit=7 full_refit_epoch=28/39 loss=0.35025
  fit=7 full_refit_epoch=29/39 loss=0.29588
  fit=7 full_refit_epoch=30/39 loss=0.27610
  fit=7 full_refit_epoch=31/39 loss=0.23597
  fit=7 full_refit_epoch=32/39 loss=0.21136
  fit=7 full_refit_epoch=33/39 loss=0.18650
  fit=7 full_refit_epoch=34/39 loss=0.17262
  fit=7 full_refit_epoch=35/39 loss=0.14920
  fit=7 full_refit_epoch=36/39 loss=0.13083
  fit=7 full_refit_epoch=37/39 loss=0.11639
  fit=7 full_refit_epoch=38/39 loss=0.10687
  fit=7 full_refit_epoch=39/39 loss=0.09848

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=1/40 loss=4.78788 inner_val_loss=4.73453 inner_val_multiclass_log_loss=4.73440 best_multiclass_log_loss=4.73440 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=2/40 loss=4.62429 inner_val_loss=4.65916 inner_val_multiclass_log_loss=4.65916 best_multiclass_log_loss=4.65916 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=3/40 loss=4.46878 inner_val_loss=4.56776 inner_val_multiclass_log_loss=4.56775 best_multiclass_log_loss=4.56775 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=4/40 loss=4.28168 inner_val_loss=4.46579 inner_val_multiclass_log_loss=4.46588 best_multiclass_log_loss=4.46588 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=5/40 loss=4.08050 inner_val_loss=4.29853 inner_val_multiclass_log_loss=4.29854 best_multiclass_log_loss=4.29854 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=6/40 loss=3.86685 inner_val_loss=4.14481 inner_val_multiclass_log_loss=4.14487 best_multiclass_log_loss=4.14487 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=7/40 loss=3.62955 inner_val_loss=3.99955 inner_val_multiclass_log_loss=3.99964 best_multiclass_log_loss=3.99964 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=8/40 loss=3.40460 inner_val_loss=3.84375 inner_val_multiclass_log_loss=3.84382 best_multiclass_log_loss=3.84382 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=9/40 loss=3.17732 inner_val_loss=3.75653 inner_val_multiclass_log_loss=3.75648 best_multiclass_log_loss=3.75648 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=10/40 loss=2.95777 inner_val_loss=3.55647 inner_val_multiclass_log_loss=3.55653 best_multiclass_log_loss=3.55653 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=11/40 loss=2.73494 inner_val_loss=3.48144 inner_val_multiclass_log_loss=3.48145 best_multiclass_log_loss=3.48145 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=12/40 loss=2.52807 inner_val_loss=3.36669 inner_val_multiclass_log_loss=3.36679 best_multiclass_log_loss=3.36679 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=13/40 loss=2.32670 inner_val_loss=3.23321 inner_val_multiclass_log_loss=3.23324 best_multiclass_log_loss=3.23324 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=14/40 loss=2.14211 inner_val_loss=3.13339 inner_val_multiclass_log_loss=3.13334 best_multiclass_log_loss=3.13334 best_epoch=14 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=15/40 loss=1.97379 inner_val_loss=2.99862 inner_val_multiclass_log_loss=2.99856 best_multiclass_log_loss=2.99856 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=16/40 loss=1.79112 inner_val_loss=2.95137 inner_val_multiclass_log_loss=2.95135 best_multiclass_log_loss=2.95135 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=17/40 loss=1.64030 inner_val_loss=2.85254 inner_val_multiclass_log_loss=2.85257 best_multiclass_log_loss=2.85257 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=18/40 loss=1.47695 inner_val_loss=2.79063 inner_val_multiclass_log_loss=2.79060 best_multiclass_log_loss=2.79060 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=19/40 loss=1.34568 inner_val_loss=2.71051 inner_val_multiclass_log_loss=2.71048 best_multiclass_log_loss=2.71048 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=20/40 loss=1.20112 inner_val_loss=2.69370 inner_val_multiclass_log_loss=2.69368 best_multiclass_log_loss=2.69368 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=21/40 loss=1.08037 inner_val_loss=2.65799 inner_val_multiclass_log_loss=2.65796 best_multiclass_log_loss=2.65796 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=22/40 loss=0.98182 inner_val_loss=2.59564 inner_val_multiclass_log_loss=2.59567 best_multiclass_log_loss=2.59567 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=23/40 loss=0.87696 inner_val_loss=2.57080 inner_val_multiclass_log_loss=2.57078 best_multiclass_log_loss=2.57078 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=24/40 loss=0.77895 inner_val_loss=2.49865 inner_val_multiclass_log_loss=2.49860 best_multiclass_log_loss=2.49860 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=25/40 loss=0.69952 inner_val_loss=2.48903 inner_val_multiclass_log_loss=2.48896 best_multiclass_log_loss=2.48896 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=26/40 loss=0.62977 inner_val_loss=2.48067 inner_val_multiclass_log_loss=2.48063 best_multiclass_log_loss=2.48063 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=27/40 loss=0.54283 inner_val_loss=2.44089 inner_val_multiclass_log_loss=2.44091 best_multiclass_log_loss=2.44091 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=28/40 loss=0.48600 inner_val_loss=2.42942 inner_val_multiclass_log_loss=2.42940 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=29/40 loss=0.43038 inner_val_loss=2.44990 inner_val_multiclass_log_loss=2.44988 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=30/40 loss=0.38295 inner_val_loss=2.40124 inner_val_multiclass_log_loss=2.40129 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=31/40 loss=0.34102 inner_val_loss=2.42409 inner_val_multiclass_log_loss=2.42413 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=32/40 loss=0.29692 inner_val_loss=2.40238 inner_val_multiclass_log_loss=2.40230 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=33/40 loss=0.26235 inner_val_loss=2.34556 inner_val_multiclass_log_loss=2.34554 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=34/40 loss=0.24309 inner_val_loss=2.37027 inner_val_multiclass_log_loss=2.37025 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=35/40 loss=0.21402 inner_val_loss=2.33308 inner_val_multiclass_log_loss=2.33300 best_multiclass_log_loss=2.33300 best_epoch=35 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=36/40 loss=0.18834 inner_val_loss=2.32832 inner_val_multiclass_log_loss=2.32835 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=37/40 loss=0.17150 inner_val_loss=2.33830 inner_val_multiclass_log_loss=2.33827 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=38/40 loss=0.16646 inner_val_loss=2.34553 inner_val_multiclass_log_loss=2.34549 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=39/40 loss=0.14529 inner_val_loss=2.35859 inner_val_multiclass_log_loss=2.35854 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.0
  fit=8 epoch=40/40 loss=0.12740 inner_val_loss=2.36939 inner_val_multiclass_log_loss=2.36934 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 full_refit_epoch=1/36 loss=4.78174
  fit=8 full_refit_epoch=2/36 loss=4.61084
  fit=8 full_refit_epoch=3/36 loss=4.43466
  fit=8 full_refit_epoch=4/36 loss=4.23122
  fit=8 full_refit_epoch=5/36 loss=4.00552
  fit=8 full_refit_epoch=6/36 loss=3.76720
  fit=8 full_refit_epoch=7/36 loss=3.51458
  fit=8 full_refit_epoch=8/36 loss=3.27506
  fit=8 full_refit_epoch=9/36 loss=3.02642
  fit=8 full_refit_epoch=10/36 loss=2.79304
  fit=8 full_refit_epoch=11/36 loss=2.57939
  fit=8 full_refit_epoch=12/36 loss=2.36072
  fit=8 full_refit_epoch=13/36 loss=2.15404
  fit=8 full_refit_epoch=14/36 loss=1.96215
  fit=8 full_refit_epoch=15/36 loss=1.78668
  fit=8 full_refit_epoch=16/36 loss=1.61511
  fit=8 full_refit_epoch=17/36 loss=1.45979
  fit=8 full_refit_epoch=18/36 loss=1.30436
  fit=8 full_refit_epoch=19/36 loss=1.17129
  fit=8 full_refit_epoch=20/36 loss=1.03604
  fit=8 full_refit_epoch=21/36 loss=0.93486
  fit=8 full_refit_epoch=22/36 loss=0.82323
  fit=8 full_refit_epoch=23/36 loss=0.73781
  fit=8 full_refit_epoch=24/36 loss=0.63958
  fit=8 full_refit_epoch=25/36 loss=0.55612
  fit=8 full_refit_epoch=26/36 loss=0.49764
  fit=8 full_refit_epoch=27/36 loss=0.43395
  fit=8 full_refit_epoch=28/36 loss=0.38153
  fit=8 full_refit_epoch=29/36 loss=0.33402
  fit=8 full_refit_epoch=30/36 loss=0.29779
  fit=8 full_refit_epoch=31/36 loss=0.26630
  fit=8 full_refit_epoch=32/36 loss=0.23283
  fit=8 full_refit_epoch=33/36 loss=0.20140
  fit=8 full_refit_epoch=34/36 loss=0.18013
  fit=8 full_refit_epoch=35/36 loss=0.16015
  fit=8 full_refit_epoch=36/36 loss=0.15038

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=1/40 loss=4.78972 inner_val_loss=4.78068 inner_val_multiclass_log_loss=4.78091 best_multiclass_log_loss=4.78091 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=2/40 loss=4.61644 inner_val_loss=4.70122 inner_val_multiclass_log_loss=4.70113 best_multiclass_log_loss=4.70113 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=3/40 loss=4.45221 inner_val_loss=4.62067 inner_val_multiclass_log_loss=4.62064 best_multiclass_log_loss=4.62064 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=4/40 loss=4.27089 inner_val_loss=4.47619 inner_val_multiclass_log_loss=4.47618 best_multiclass_log_loss=4.47618 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=5/40 loss=4.06268 inner_val_loss=4.36162 inner_val_multiclass_log_loss=4.36158 best_multiclass_log_loss=4.36158 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=6/40 loss=3.84209 inner_val_loss=4.26205 inner_val_multiclass_log_loss=4.26196 best_multiclass_log_loss=4.26196 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=7/40 loss=3.61849 inner_val_loss=4.08260 inner_val_multiclass_log_loss=4.08265 best_multiclass_log_loss=4.08265 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=8/40 loss=3.39831 inner_val_loss=3.93322 inner_val_multiclass_log_loss=3.93321 best_multiclass_log_loss=3.93321 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=9/40 loss=3.19004 inner_val_loss=3.87016 inner_val_multiclass_log_loss=3.87020 best_multiclass_log_loss=3.87020 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=10/40 loss=2.96517 inner_val_loss=3.75255 inner_val_multiclass_log_loss=3.75255 best_multiclass_log_loss=3.75255 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=11/40 loss=2.75054 inner_val_loss=3.67104 inner_val_multiclass_log_loss=3.67106 best_multiclass_log_loss=3.67106 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=12/40 loss=2.54064 inner_val_loss=3.57192 inner_val_multiclass_log_loss=3.57195 best_multiclass_log_loss=3.57195 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=13/40 loss=2.34203 inner_val_loss=3.46974 inner_val_multiclass_log_loss=3.46984 best_multiclass_log_loss=3.46984 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=14/40 loss=2.14699 inner_val_loss=3.39058 inner_val_multiclass_log_loss=3.39060 best_multiclass_log_loss=3.39060 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=15/40 loss=1.97566 inner_val_loss=3.22496 inner_val_multiclass_log_loss=3.22488 best_multiclass_log_loss=3.22488 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=16/40 loss=1.78328 inner_val_loss=3.20142 inner_val_multiclass_log_loss=3.20133 best_multiclass_log_loss=3.20133 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=17/40 loss=1.61451 inner_val_loss=3.10055 inner_val_multiclass_log_loss=3.10061 best_multiclass_log_loss=3.10061 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=18/40 loss=1.48052 inner_val_loss=3.06376 inner_val_multiclass_log_loss=3.06376 best_multiclass_log_loss=3.06376 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=19/40 loss=1.30872 inner_val_loss=2.99257 inner_val_multiclass_log_loss=2.99263 best_multiclass_log_loss=2.99263 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=20/40 loss=1.18439 inner_val_loss=2.97069 inner_val_multiclass_log_loss=2.97066 best_multiclass_log_loss=2.97066 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=21/40 loss=1.07813 inner_val_loss=2.89766 inner_val_multiclass_log_loss=2.89778 best_multiclass_log_loss=2.89778 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=22/40 loss=0.94472 inner_val_loss=2.84399 inner_val_multiclass_log_loss=2.84401 best_multiclass_log_loss=2.84401 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=23/40 loss=0.85215 inner_val_loss=2.81882 inner_val_multiclass_log_loss=2.81876 best_multiclass_log_loss=2.81876 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=24/40 loss=0.76193 inner_val_loss=2.78520 inner_val_multiclass_log_loss=2.78512 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=25/40 loss=0.67522 inner_val_loss=2.79527 inner_val_multiclass_log_loss=2.79529 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=26/40 loss=0.59620 inner_val_loss=2.76630 inner_val_multiclass_log_loss=2.76634 best_multiclass_log_loss=2.76634 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=27/40 loss=0.53659 inner_val_loss=2.73014 inner_val_multiclass_log_loss=2.73021 best_multiclass_log_loss=2.73021 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=28/40 loss=0.46902 inner_val_loss=2.68155 inner_val_multiclass_log_loss=2.68160 best_multiclass_log_loss=2.68160 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=29/40 loss=0.42078 inner_val_loss=2.66191 inner_val_multiclass_log_loss=2.66190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=30/40 loss=0.37526 inner_val_loss=2.67838 inner_val_multiclass_log_loss=2.67840 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=31/40 loss=0.32713 inner_val_loss=2.67195 inner_val_multiclass_log_loss=2.67190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=32/40 loss=0.29732 inner_val_loss=2.64314 inner_val_multiclass_log_loss=2.64318 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=33/40 loss=0.26400 inner_val_loss=2.64539 inner_val_multiclass_log_loss=2.64539 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=34/40 loss=0.22863 inner_val_loss=2.62849 inner_val_multiclass_log_loss=2.62847 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=35/40 loss=0.21273 inner_val_loss=2.68348 inner_val_multiclass_log_loss=2.68344 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=36/40 loss=0.18296 inner_val_loss=2.62064 inner_val_multiclass_log_loss=2.62070 best_multiclass_log_loss=2.62070 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=37/40 loss=0.16822 inner_val_loss=2.59413 inner_val_multiclass_log_loss=2.59413 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=38/40 loss=0.15150 inner_val_loss=2.62271 inner_val_multiclass_log_loss=2.62273 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=39/40 loss=0.14116 inner_val_loss=2.60107 inner_val_multiclass_log_loss=2.60106 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1
  fit=9 epoch=40/40 loss=0.12134 inner_val_loss=2.58163 inner_val_multiclass_log_loss=2.58163 best_multiclass_log_loss=2.58163 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 full_refit_epoch=1/40 loss=4.78354
  fit=9 full_refit_epoch=2/40 loss=4.60792
  fit=9 full_refit_epoch=3/40 loss=4.43281
  fit=9 full_refit_epoch=4/40 loss=4.22375
  fit=9 full_refit_epoch=5/40 loss=3.98823
  fit=9 full_refit_epoch=6/40 loss=3.75429
  fit=9 full_refit_epoch=7/40 loss=3.52034
  fit=9 full_refit_epoch=8/40 loss=3.27720
  fit=9 full_refit_epoch=9/40 loss=3.03494
  fit=9 full_refit_epoch=10/40 loss=2.80688
  fit=9 full_refit_epoch=11/40 loss=2.58710
  fit=9 full_refit_epoch=12/40 loss=2.35734
  fit=9 full_refit_epoch=13/40 loss=2.16211
  fit=9 full_refit_epoch=14/40 loss=1.95755
  fit=9 full_refit_epoch=15/40 loss=1.76778
  fit=9 full_refit_epoch=16/40 loss=1.59597
  fit=9 full_refit_epoch=17/40 loss=1.43546
  fit=9 full_refit_epoch=18/40 loss=1.29959
  fit=9 full_refit_epoch=19/40 loss=1.14497
  fit=9 full_refit_epoch=20/40 loss=1.00626
  fit=9 full_refit_epoch=21/40 loss=0.90324
  fit=9 full_refit_epoch=22/40 loss=0.80394
  fit=9 full_refit_epoch=23/40 loss=0.70506
  fit=9 full_refit_epoch=24/40 loss=0.60783
  fit=9 full_refit_epoch=25/40 loss=0.54702
  fit=9 full_refit_epoch=26/40 loss=0.47226
  fit=9 full_refit_epoch=27/40 loss=0.41576
  fit=9 full_refit_epoch=28/40 loss=0.36619
  fit=9 full_refit_epoch=29/40 loss=0.31657
  fit=9 full_refit_epoch=30/40 loss=0.27211
  fit=9 full_refit_epoch=31/40 loss=0.24408
  fit=9 full_refit_epoch=32/40 loss=0.21425
  fit=9 full_refit_epoch=33/40 loss=0.19270
  fit=9 full_refit_epoch=34/40 loss=0.17262
  fit=9 full_refit_epoch=35/40 loss=0.15522
  fit=9 full_refit_epoch=36/40 loss=0.13730
  fit=9 full_refit_epoch=37/40 loss=0.12264
  fit=9 full_refit_epoch=38/40 loss=0.11303
  fit=9 full_refit_epoch=39/40 loss=0.10542
  fit=9 full_refit_epoch=40/40 loss=0.09377

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=1/40 loss=4.77984 inner_val_loss=4.72068 inner_val_multiclass_log_loss=4.72080 best_multiclass_log_loss=4.72080 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=2/40 loss=4.61636 inner_val_loss=4.63699 inner_val_multiclass_log_loss=4.63693 best_multiclass_log_loss=4.63693 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=3/40 loss=4.45690 inner_val_loss=4.53775 inner_val_multiclass_log_loss=4.53788 best_multiclass_log_loss=4.53788 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=4/40 loss=4.27154 inner_val_loss=4.42661 inner_val_multiclass_log_loss=4.42666 best_multiclass_log_loss=4.42666 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=5/40 loss=4.07261 inner_val_loss=4.30221 inner_val_multiclass_log_loss=4.30233 best_multiclass_log_loss=4.30233 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=6/40 loss=3.86698 inner_val_loss=4.12875 inner_val_multiclass_log_loss=4.12878 best_multiclass_log_loss=4.12878 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=7/40 loss=3.63809 inner_val_loss=4.01937 inner_val_multiclass_log_loss=4.01942 best_multiclass_log_loss=4.01942 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=8/40 loss=3.41935 inner_val_loss=3.87518 inner_val_multiclass_log_loss=3.87534 best_multiclass_log_loss=3.87534 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=9/40 loss=3.18955 inner_val_loss=3.70662 inner_val_multiclass_log_loss=3.70651 best_multiclass_log_loss=3.70651 best_epoch=9 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=10/40 loss=2.97659 inner_val_loss=3.54444 inner_val_multiclass_log_loss=3.54442 best_multiclass_log_loss=3.54442 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=11/40 loss=2.76710 inner_val_loss=3.46261 inner_val_multiclass_log_loss=3.46251 best_multiclass_log_loss=3.46251 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=12/40 loss=2.57334 inner_val_loss=3.27116 inner_val_multiclass_log_loss=3.27115 best_multiclass_log_loss=3.27115 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=13/40 loss=2.36194 inner_val_loss=3.19750 inner_val_multiclass_log_loss=3.19768 best_multiclass_log_loss=3.19768 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=14/40 loss=2.17910 inner_val_loss=3.07389 inner_val_multiclass_log_loss=3.07391 best_multiclass_log_loss=3.07391 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=15/40 loss=1.99885 inner_val_loss=3.01897 inner_val_multiclass_log_loss=3.01895 best_multiclass_log_loss=3.01895 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=16/40 loss=1.82771 inner_val_loss=2.94047 inner_val_multiclass_log_loss=2.94037 best_multiclass_log_loss=2.94037 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=17/40 loss=1.65915 inner_val_loss=2.81063 inner_val_multiclass_log_loss=2.81061 best_multiclass_log_loss=2.81061 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=18/40 loss=1.51430 inner_val_loss=2.77291 inner_val_multiclass_log_loss=2.77299 best_multiclass_log_loss=2.77299 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=19/40 loss=1.36006 inner_val_loss=2.70794 inner_val_multiclass_log_loss=2.70795 best_multiclass_log_loss=2.70795 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=20/40 loss=1.24242 inner_val_loss=2.63758 inner_val_multiclass_log_loss=2.63757 best_multiclass_log_loss=2.63757 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=21/40 loss=1.10894 inner_val_loss=2.62117 inner_val_multiclass_log_loss=2.62113 best_multiclass_log_loss=2.62113 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=22/40 loss=0.99728 inner_val_loss=2.57374 inner_val_multiclass_log_loss=2.57372 best_multiclass_log_loss=2.57372 best_epoch=22 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=23/40 loss=0.89508 inner_val_loss=2.56801 inner_val_multiclass_log_loss=2.56802 best_multiclass_log_loss=2.56802 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=24/40 loss=0.79840 inner_val_loss=2.51540 inner_val_multiclass_log_loss=2.51532 best_multiclass_log_loss=2.51532 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=25/40 loss=0.70842 inner_val_loss=2.48709 inner_val_multiclass_log_loss=2.48713 best_multiclass_log_loss=2.48713 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=26/40 loss=0.63383 inner_val_loss=2.45845 inner_val_multiclass_log_loss=2.45841 best_multiclass_log_loss=2.45841 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=27/40 loss=0.57510 inner_val_loss=2.43780 inner_val_multiclass_log_loss=2.43789 best_multiclass_log_loss=2.43789 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=28/40 loss=0.49380 inner_val_loss=2.40752 inner_val_multiclass_log_loss=2.40752 best_multiclass_log_loss=2.40752 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=29/40 loss=0.43158 inner_val_loss=2.38063 inner_val_multiclass_log_loss=2.38061 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=30/40 loss=0.40393 inner_val_loss=2.40156 inner_val_multiclass_log_loss=2.40155 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=31/40 loss=0.34829 inner_val_loss=2.34321 inner_val_multiclass_log_loss=2.34324 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=32/40 loss=0.30293 inner_val_loss=2.34830 inner_val_multiclass_log_loss=2.34833 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=33/40 loss=0.27191 inner_val_loss=2.33435 inner_val_multiclass_log_loss=2.33438 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=34/40 loss=0.24077 inner_val_loss=2.36642 inner_val_multiclass_log_loss=2.36640 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=35/40 loss=0.21350 inner_val_loss=2.35795 inner_val_multiclass_log_loss=2.35801 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=36/40 loss=0.21089 inner_val_loss=2.32175 inner_val_multiclass_log_loss=2.32167 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=37/40 loss=0.17882 inner_val_loss=2.32570 inner_val_multiclass_log_loss=2.32573 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=38/40 loss=0.16260 inner_val_loss=2.31285 inner_val_multiclass_log_loss=2.31276 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=39/40 loss=0.14282 inner_val_loss=2.37636 inner_val_multiclass_log_loss=2.37630 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1
  fit=10 epoch=40/40 loss=0.13584 inner_val_loss=2.33817 inner_val_multiclass_log_loss=2.33822 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 full_refit_epoch=1/38 loss=4.77285
  fit=10 full_refit_epoch=2/38 loss=4.60156
  fit=10 full_refit_epoch=3/38 loss=4.42367
  fit=10 full_refit_epoch=4/38 loss=4.21951
  fit=10 full_refit_epoch=5/38 loss=3.99543
  fit=10 full_refit_epoch=6/38 loss=3.76219
  fit=10 full_refit_epoch=7/38 loss=3.51045
  fit=10 full_refit_epoch=8/38 loss=3.26475
  fit=10 full_refit_epoch=9/38 loss=3.01855
  fit=10 full_refit_epoch=10/38 loss=2.79697
  fit=10 full_refit_epoch=11/38 loss=2.56724
  fit=10 full_refit_epoch=12/38 loss=2.34649
  fit=10 full_refit_epoch=13/38 loss=2.14739
  fit=10 full_refit_epoch=14/38 loss=1.94784
  fit=10 full_refit_epoch=15/38 loss=1.77608
  fit=10 full_refit_epoch=16/38 loss=1.58856
  fit=10 full_refit_epoch=17/38 loss=1.43336
  fit=10 full_refit_epoch=18/38 loss=1.28592
  fit=10 full_refit_epoch=19/38 loss=1.14915
  fit=10 full_refit_epoch=20/38 loss=1.01684
  fit=10 full_refit_epoch=21/38 loss=0.90502
  fit=10 full_refit_epoch=22/38 loss=0.79337
  fit=10 full_refit_epoch=23/38 loss=0.69822
  fit=10 full_refit_epoch=24/38 loss=0.61281
  fit=10 full_refit_epoch=25/38 loss=0.54337
  fit=10 full_refit_epoch=26/38 loss=0.47650
  fit=10 full_refit_epoch=27/38 loss=0.42055
  fit=10 full_refit_epoch=28/38 loss=0.35945
  fit=10 full_refit_epoch=29/38 loss=0.32238
  fit=10 full_refit_epoch=30/38 loss=0.28152
  fit=10 full_refit_epoch=31/38 loss=0.25445
  fit=10 full_refit_epoch=32/38 loss=0.21704
  fit=10 full_refit_epoch=33/38 loss=0.19919
  fit=10 full_refit_epoch=34/38 loss=0.17358
  fit=10 full_refit_epoch=35/38 loss=0.15832
  fit=10 full_refit_epoch=36/38 loss=0.14008
  fit=10 full_refit_epoch=37/38 loss=0.12395
  fit=10 full_refit_epoch=38/38 loss=0.11568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=initial model=resnet18 metric=2.471291572428004 error=None minutes=13.17
START seed=29 phase=initial model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=1/40 loss=5.02100 inner_val_loss=4.78337 inner_val_multiclass_log_loss=4.78327 best_multiclass_log_loss=4.78327 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=2/40 loss=3.87256 inner_val_loss=4.48209 inner_val_multiclass_log_loss=4.48205 best_multiclass_log_loss=4.48205 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=3/40 loss=2.92353 inner_val_loss=4.23134 inner_val_multiclass_log_loss=4.23137 best_multiclass_log_loss=4.23137 best_epoch=3 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=4/40 loss=2.11493 inner_val_loss=3.96919 inner_val_multiclass_log_loss=3.96931 best_multiclass_log_loss=3.96931 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=5/40 loss=1.47399 inner_val_loss=3.77509 inner_val_multiclass_log_loss=3.77514 best_multiclass_log_loss=3.77514 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=6/40 loss=1.04729 inner_val_loss=3.57786 inner_val_multiclass_log_loss=3.57778 best_multiclass_log_loss=3.57778 best_epoch=6 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=7/40 loss=0.69747 inner_val_loss=3.48617 inner_val_multiclass_log_loss=3.48619 best_multiclass_log_loss=3.48619 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=8/40 loss=0.50278 inner_val_loss=3.36251 inner_val_multiclass_log_loss=3.36246 best_multiclass_log_loss=3.36246 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=9/40 loss=0.36162 inner_val_loss=3.33188 inner_val_multiclass_log_loss=3.33183 best_multiclass_log_loss=3.33183 best_epoch=9 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=10/40 loss=0.25721 inner_val_loss=3.28651 inner_val_multiclass_log_loss=3.28647 best_multiclass_log_loss=3.28647 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=11/40 loss=0.19091 inner_val_loss=3.24312 inner_val_multiclass_log_loss=3.24315 best_multiclass_log_loss=3.24315 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=12/40 loss=0.15870 inner_val_loss=3.19438 inner_val_multiclass_log_loss=3.19431 best_multiclass_log_loss=3.19431 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=13/40 loss=0.12977 inner_val_loss=3.17543 inner_val_multiclass_log_loss=3.17544 best_multiclass_log_loss=3.17544 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=14/40 loss=0.11018 inner_val_loss=3.18009 inner_val_multiclass_log_loss=3.18016 best_multiclass_log_loss=3.17544 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=15/40 loss=0.10090 inner_val_loss=3.14716 inner_val_multiclass_log_loss=3.14715 best_multiclass_log_loss=3.14715 best_epoch=15 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=16/40 loss=0.08278 inner_val_loss=3.09490 inner_val_multiclass_log_loss=3.09486 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=17/40 loss=0.07331 inner_val_loss=3.11212 inner_val_multiclass_log_loss=3.11211 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=18/40 loss=0.06614 inner_val_loss=3.15242 inner_val_multiclass_log_loss=3.15243 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=19/40 loss=0.05272 inner_val_loss=3.12751 inner_val_multiclass_log_loss=3.12754 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=20/40 loss=0.05146 inner_val_loss=3.11677 inner_val_multiclass_log_loss=3.11675 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=21/40 loss=0.04559 inner_val_loss=3.08631 inner_val_multiclass_log_loss=3.08622 best_multiclass_log_loss=3.08622 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=22/40 loss=0.04532 inner_val_loss=3.07370 inner_val_multiclass_log_loss=3.07371 best_multiclass_log_loss=3.07371 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=23/40 loss=0.05045 inner_val_loss=3.09611 inner_val_multiclass_log_loss=3.09614 best_multiclass_log_loss=3.07371 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=24/40 loss=0.03505 inner_val_loss=3.05473 inner_val_multiclass_log_loss=3.05463 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=25/40 loss=0.03975 inner_val_loss=3.07794 inner_val_multiclass_log_loss=3.07793 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=26/40 loss=0.04033 inner_val_loss=3.07039 inner_val_multiclass_log_loss=3.07035 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=27/40 loss=0.03676 inner_val_loss=3.03101 inner_val_multiclass_log_loss=3.03099 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=28/40 loss=0.03001 inner_val_loss=3.03908 inner_val_multiclass_log_loss=3.03900 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=29/40 loss=0.03443 inner_val_loss=3.03278 inner_val_multiclass_log_loss=3.03281 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=30/40 loss=0.02742 inner_val_loss=3.06223 inner_val_multiclass_log_loss=3.06221 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=31/40 loss=0.02591 inner_val_loss=3.02145 inner_val_multiclass_log_loss=3.02143 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=32/40 loss=0.02433 inner_val_loss=3.03211 inner_val_multiclass_log_loss=3.03209 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=33/40 loss=0.02665 inner_val_loss=3.02693 inner_val_multiclass_log_loss=3.02691 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=34/40 loss=0.02612 inner_val_loss=3.06065 inner_val_multiclass_log_loss=3.06064 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=35/40 loss=0.02708 inner_val_loss=3.02986 inner_val_multiclass_log_loss=3.02984 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.1
  fit=11 epoch=36/40 loss=0.02549 inner_val_loss=3.04284 inner_val_multiclass_log_loss=3.04280 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 full_refit_epoch=1/31 loss=5.00139
  fit=11 full_refit_epoch=2/31 loss=3.84352
  fit=11 full_refit_epoch=3/31 loss=2.85575
  fit=11 full_refit_epoch=4/31 loss=2.04283
  fit=11 full_refit_epoch=5/31 loss=1.40794
  fit=11 full_refit_epoch=6/31 loss=0.96872
  fit=11 full_refit_epoch=7/31 loss=0.64211
  fit=11 full_refit_epoch=8/31 loss=0.45176
  fit=11 full_refit_epoch=9/31 loss=0.31685
  fit=11 full_refit_epoch=10/31 loss=0.21854
  fit=11 full_refit_epoch=11/31 loss=0.17218
  fit=11 full_refit_epoch=12/31 loss=0.13666
  fit=11 full_refit_epoch=13/31 loss=0.10461
  fit=11 full_refit_epoch=14/31 loss=0.08595
  fit=11 full_refit_epoch=15/31 loss=0.07387
  fit=11 full_refit_epoch=16/31 loss=0.06669
  fit=11 full_refit_epoch=17/31 loss=0.05321
  fit=11 full_refit_epoch=18/31 loss=0.05171
  fit=11 full_refit_epoch=19/31 loss=0.04069
  fit=11 full_refit_epoch=20/31 loss=0.03612
  fit=11 full_refit_epoch=21/31 loss=0.03302
  fit=11 full_refit_epoch=22/31 loss=0.03047
  fit=11 full_refit_epoch=23/31 loss=0.02655
  fit=11 full_refit_epoch=24/31 loss=0.02366
  fit=11 full_refit_epoch=25/31 loss=0.02182
  fit=11 full_refit_epoch=26/31 loss=0.02042
  fit=11 full_refit_epoch=27/31 loss=0.01822
  fit=11 full_refit_epoch=28/31 loss=0.01950
  fit=11 full_refit_epoch=29/31 loss=0.01738
  fit=11 full_refit_epoch=30/31 loss=0.01559
  fit=11 full_refit_epoch=31/31 loss=0.01436

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=1/40 loss=4.95998 inner_val_loss=4.68228 inner_val_multiclass_log_loss=4.68235 best_multiclass_log_loss=4.68235 best_epoch=1 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=2/40 loss=3.77159 inner_val_loss=4.36527 inner_val_multiclass_log_loss=4.36545 best_multiclass_log_loss=4.36545 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=3/40 loss=2.84222 inner_val_loss=4.05057 inner_val_multiclass_log_loss=4.05053 best_multiclass_log_loss=4.05053 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=4/40 loss=2.03547 inner_val_loss=3.79064 inner_val_multiclass_log_loss=3.79062 best_multiclass_log_loss=3.79062 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=5/40 loss=1.44016 inner_val_loss=3.62697 inner_val_multiclass_log_loss=3.62698 best_multiclass_log_loss=3.62698 best_epoch=5 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=6/40 loss=1.01564 inner_val_loss=3.49032 inner_val_multiclass_log_loss=3.49032 best_multiclass_log_loss=3.49032 best_epoch=6 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=7/40 loss=0.72444 inner_val_loss=3.35060 inner_val_multiclass_log_loss=3.35058 best_multiclass_log_loss=3.35058 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=8/40 loss=0.49946 inner_val_loss=3.28810 inner_val_multiclass_log_loss=3.28817 best_multiclass_log_loss=3.28817 best_epoch=8 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=9/40 loss=0.36389 inner_val_loss=3.24911 inner_val_multiclass_log_loss=3.24917 best_multiclass_log_loss=3.24917 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=10/40 loss=0.24461 inner_val_loss=3.16254 inner_val_multiclass_log_loss=3.16260 best_multiclass_log_loss=3.16260 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=11/40 loss=0.18992 inner_val_loss=3.13044 inner_val_multiclass_log_loss=3.13040 best_multiclass_log_loss=3.13040 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=12/40 loss=0.15069 inner_val_loss=3.11354 inner_val_multiclass_log_loss=3.11356 best_multiclass_log_loss=3.11356 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=13/40 loss=0.14095 inner_val_loss=3.07106 inner_val_multiclass_log_loss=3.07114 best_multiclass_log_loss=3.07114 best_epoch=13 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=14/40 loss=0.11642 inner_val_loss=3.09126 inner_val_multiclass_log_loss=3.09138 best_multiclass_log_loss=3.07114 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=15/40 loss=0.09857 inner_val_loss=2.97833 inner_val_multiclass_log_loss=2.97833 best_multiclass_log_loss=2.97833 best_epoch=15 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=16/40 loss=0.08564 inner_val_loss=2.91931 inner_val_multiclass_log_loss=2.91926 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=17/40 loss=0.06383 inner_val_loss=3.03987 inner_val_multiclass_log_loss=3.03989 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=18/40 loss=0.06642 inner_val_loss=2.98580 inner_val_multiclass_log_loss=2.98585 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=19/40 loss=0.05966 inner_val_loss=2.93723 inner_val_multiclass_log_loss=2.93714 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=20/40 loss=0.06922 inner_val_loss=2.96727 inner_val_multiclass_log_loss=2.96728 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.2
  fit=12 epoch=21/40 loss=0.05367 inner_val_loss=2.98030 inner_val_multiclass_log_loss=2.98028 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 full_refit_epoch=1/16 loss=4.94496
  fit=12 full_refit_epoch=2/16 loss=3.75428
  fit=12 full_refit_epoch=3/16 loss=2.76960
  fit=12 full_refit_epoch=4/16 loss=1.97311
  fit=12 full_refit_epoch=5/16 loss=1.36724
  fit=12 full_refit_epoch=6/16 loss=0.94047
  fit=12 full_refit_epoch=7/16 loss=0.64077
  fit=12 full_refit_epoch=8/16 loss=0.42261
  fit=12 full_refit_epoch=9/16 loss=0.28528
  fit=12 full_refit_epoch=10/16 loss=0.21444
  fit=12 full_refit_epoch=11/16 loss=0.16258
  fit=12 full_refit_epoch=12/16 loss=0.12386
  fit=12 full_refit_epoch=13/16 loss=0.10125
  fit=12 full_refit_epoch=14/16 loss=0.08116
  fit=12 full_refit_epoch=15/16 loss=0.07681
  fit=12 full_refit_epoch=16/16 loss=0.06467

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=1/40 loss=5.01382 inner_val_loss=4.83018 inner_val_multiclass_log_loss=4.83014 best_multiclass_log_loss=4.83014 best_epoch=1 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=2/40 loss=3.87394 inner_val_loss=4.52617 inner_val_multiclass_log_loss=4.52617 best_multiclass_log_loss=4.52617 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=3/40 loss=2.95614 inner_val_loss=4.24006 inner_val_multiclass_log_loss=4.24010 best_multiclass_log_loss=4.24010 best_epoch=3 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=4/40 loss=2.15813 inner_val_loss=4.04224 inner_val_multiclass_log_loss=4.04221 best_multiclass_log_loss=4.04221 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=5/40 loss=1.55526 inner_val_loss=3.82327 inner_val_multiclass_log_loss=3.82331 best_multiclass_log_loss=3.82331 best_epoch=5 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=6/40 loss=1.10219 inner_val_loss=3.72264 inner_val_multiclass_log_loss=3.72258 best_multiclass_log_loss=3.72258 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=7/40 loss=0.74562 inner_val_loss=3.53901 inner_val_multiclass_log_loss=3.53902 best_multiclass_log_loss=3.53902 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=8/40 loss=0.54086 inner_val_loss=3.46953 inner_val_multiclass_log_loss=3.46958 best_multiclass_log_loss=3.46958 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=9/40 loss=0.38486 inner_val_loss=3.44521 inner_val_multiclass_log_loss=3.44516 best_multiclass_log_loss=3.44516 best_epoch=9 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=10/40 loss=0.27137 inner_val_loss=3.41685 inner_val_multiclass_log_loss=3.41685 best_multiclass_log_loss=3.41685 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=11/40 loss=0.22049 inner_val_loss=3.32103 inner_val_multiclass_log_loss=3.32104 best_multiclass_log_loss=3.32104 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=12/40 loss=0.17037 inner_val_loss=3.30205 inner_val_multiclass_log_loss=3.30204 best_multiclass_log_loss=3.30204 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=13/40 loss=0.13642 inner_val_loss=3.27293 inner_val_multiclass_log_loss=3.27300 best_multiclass_log_loss=3.27300 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=14/40 loss=0.10984 inner_val_loss=3.28362 inner_val_multiclass_log_loss=3.28362 best_multiclass_log_loss=3.27300 best_epoch=13 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=15/40 loss=0.10162 inner_val_loss=3.23432 inner_val_multiclass_log_loss=3.23444 best_multiclass_log_loss=3.23444 best_epoch=15 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=16/40 loss=0.08316 inner_val_loss=3.22857 inner_val_multiclass_log_loss=3.22860 best_multiclass_log_loss=3.22860 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=17/40 loss=0.07666 inner_val_loss=3.21848 inner_val_multiclass_log_loss=3.21847 best_multiclass_log_loss=3.21847 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=18/40 loss=0.06484 inner_val_loss=3.20966 inner_val_multiclass_log_loss=3.20964 best_multiclass_log_loss=3.20964 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=19/40 loss=0.06298 inner_val_loss=3.20902 inner_val_multiclass_log_loss=3.20901 best_multiclass_log_loss=3.20901 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=20/40 loss=0.05495 inner_val_loss=3.20852 inner_val_multiclass_log_loss=3.20846 best_multiclass_log_loss=3.20846 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=21/40 loss=0.04924 inner_val_loss=3.19677 inner_val_multiclass_log_loss=3.19675 best_multiclass_log_loss=3.19675 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=22/40 loss=0.04873 inner_val_loss=3.21843 inner_val_multiclass_log_loss=3.21846 best_multiclass_log_loss=3.19675 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=23/40 loss=0.04317 inner_val_loss=3.13414 inner_val_multiclass_log_loss=3.13417 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=24/40 loss=0.03744 inner_val_loss=3.14222 inner_val_multiclass_log_loss=3.14226 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=25/40 loss=0.03473 inner_val_loss=3.14247 inner_val_multiclass_log_loss=3.14256 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=26/40 loss=0.03297 inner_val_loss=3.18391 inner_val_multiclass_log_loss=3.18390 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=27/40 loss=0.02870 inner_val_loss=3.16270 inner_val_multiclass_log_loss=3.16263 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.0
  fit=13 epoch=28/40 loss=0.02833 inner_val_loss=3.14724 inner_val_multiclass_log_loss=3.14719 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 full_refit_epoch=1/23 loss=4.99828
  fit=13 full_refit_epoch=2/23 loss=3.80875
  fit=13 full_refit_epoch=3/23 loss=2.84190
  fit=13 full_refit_epoch=4/23 loss=2.06904
  fit=13 full_refit_epoch=5/23 loss=1.46311
  fit=13 full_refit_epoch=6/23 loss=1.01374
  fit=13 full_refit_epoch=7/23 loss=0.68216
  fit=13 full_refit_epoch=8/23 loss=0.46436
  fit=13 full_refit_epoch=9/23 loss=0.31909
  fit=13 full_refit_epoch=10/23 loss=0.21868
  fit=13 full_refit_epoch=11/23 loss=0.17230
  fit=13 full_refit_epoch=12/23 loss=0.13999
  fit=13 full_refit_epoch=13/23 loss=0.11060
  fit=13 full_refit_epoch=14/23 loss=0.08966
  fit=13 full_refit_epoch=15/23 loss=0.07738
  fit=13 full_refit_epoch=16/23 loss=0.06555
  fit=13 full_refit_epoch=17/23 loss=0.05954
  fit=13 full_refit_epoch=18/23 loss=0.04987
  fit=13 full_refit_epoch=19/23 loss=0.04109
  fit=13 full_refit_epoch=20/23 loss=0.03629
  fit=13 full_refit_epoch=21/23 loss=0.03325
  fit=13 full_refit_epoch=22/23 loss=0.03119
  fit=13 full_refit_epoch=23/23 loss=0.02703

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=1/40 loss=5.01646 inner_val_loss=4.71075 inner_val_multiclass_log_loss=4.71066 best_multiclass_log_loss=4.71066 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=2/40 loss=3.86878 inner_val_loss=4.44417 inner_val_multiclass_log_loss=4.44408 best_multiclass_log_loss=4.44408 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=3/40 loss=2.90752 inner_val_loss=4.14764 inner_val_multiclass_log_loss=4.14766 best_multiclass_log_loss=4.14766 best_epoch=3 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=4/40 loss=2.12866 inner_val_loss=3.94066 inner_val_multiclass_log_loss=3.94066 best_multiclass_log_loss=3.94066 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=5/40 loss=1.49282 inner_val_loss=3.75263 inner_val_multiclass_log_loss=3.75265 best_multiclass_log_loss=3.75265 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=6/40 loss=1.04899 inner_val_loss=3.65415 inner_val_multiclass_log_loss=3.65412 best_multiclass_log_loss=3.65412 best_epoch=6 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=7/40 loss=0.73526 inner_val_loss=3.52214 inner_val_multiclass_log_loss=3.52224 best_multiclass_log_loss=3.52224 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=8/40 loss=0.51204 inner_val_loss=3.47120 inner_val_multiclass_log_loss=3.47106 best_multiclass_log_loss=3.47106 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=9/40 loss=0.37281 inner_val_loss=3.40877 inner_val_multiclass_log_loss=3.40885 best_multiclass_log_loss=3.40885 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=10/40 loss=0.27129 inner_val_loss=3.34535 inner_val_multiclass_log_loss=3.34534 best_multiclass_log_loss=3.34534 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=11/40 loss=0.21211 inner_val_loss=3.29210 inner_val_multiclass_log_loss=3.29214 best_multiclass_log_loss=3.29214 best_epoch=11 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=12/40 loss=0.15904 inner_val_loss=3.29345 inner_val_multiclass_log_loss=3.29349 best_multiclass_log_loss=3.29214 best_epoch=11 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=13/40 loss=0.13538 inner_val_loss=3.28735 inner_val_multiclass_log_loss=3.28731 best_multiclass_log_loss=3.28731 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=14/40 loss=0.10630 inner_val_loss=3.27568 inner_val_multiclass_log_loss=3.27573 best_multiclass_log_loss=3.27573 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=15/40 loss=0.09940 inner_val_loss=3.21260 inner_val_multiclass_log_loss=3.21262 best_multiclass_log_loss=3.21262 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=16/40 loss=0.07787 inner_val_loss=3.18888 inner_val_multiclass_log_loss=3.18890 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=17/40 loss=0.07906 inner_val_loss=3.19307 inner_val_multiclass_log_loss=3.19307 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=18/40 loss=0.07204 inner_val_loss=3.19766 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=19/40 loss=0.05085 inner_val_loss=3.18384 inner_val_multiclass_log_loss=3.18378 best_multiclass_log_loss=3.18378 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=20/40 loss=0.05369 inner_val_loss=3.15567 inner_val_multiclass_log_loss=3.15569 best_multiclass_log_loss=3.15569 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=21/40 loss=0.04779 inner_val_loss=3.12405 inner_val_multiclass_log_loss=3.12414 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=22/40 loss=0.04556 inner_val_loss=3.13617 inner_val_multiclass_log_loss=3.13619 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=23/40 loss=0.04344 inner_val_loss=3.14193 inner_val_multiclass_log_loss=3.14200 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=24/40 loss=0.04373 inner_val_loss=3.11872 inner_val_multiclass_log_loss=3.11861 best_multiclass_log_loss=3.11861 best_epoch=24 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=25/40 loss=0.04615 inner_val_loss=3.12620 inner_val_multiclass_log_loss=3.12624 best_multiclass_log_loss=3.11861 best_epoch=24 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=26/40 loss=0.03264 inner_val_loss=3.11736 inner_val_multiclass_log_loss=3.11731 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=27/40 loss=0.03728 inner_val_loss=3.12765 inner_val_multiclass_log_loss=3.12767 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=28/40 loss=0.04057 inner_val_loss=3.12603 inner_val_multiclass_log_loss=3.12602 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=29/40 loss=0.03249 inner_val_loss=3.11357 inner_val_multiclass_log_loss=3.11362 best_multiclass_log_loss=3.11362 best_epoch=29 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=30/40 loss=0.02746 inner_val_loss=3.11732 inner_val_multiclass_log_loss=3.11734 best_multiclass_log_loss=3.11362 best_epoch=29 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=31/40 loss=0.03100 inner_val_loss=3.07322 inner_val_multiclass_log_loss=3.07311 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=32/40 loss=0.02220 inner_val_loss=3.16694 inner_val_multiclass_log_loss=3.16686 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=33/40 loss=0.02371 inner_val_loss=3.12590 inner_val_multiclass_log_loss=3.12598 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=34/40 loss=0.02350 inner_val_loss=3.13255 inner_val_multiclass_log_loss=3.13257 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=35/40 loss=0.02824 inner_val_loss=3.09367 inner_val_multiclass_log_loss=3.09369 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2
  fit=14 epoch=36/40 loss=0.01611 inner_val_loss=3.10682 inner_val_multiclass_log_loss=3.10694 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 full_refit_epoch=1/31 loss=4.99808
  fit=14 full_refit_epoch=2/31 loss=3.82919
  fit=14 full_refit_epoch=3/31 loss=2.85763
  fit=14 full_refit_epoch=4/31 loss=2.06057
  fit=14 full_refit_epoch=5/31 loss=1.40719
  fit=14 full_refit_epoch=6/31 loss=0.97243
  fit=14 full_refit_epoch=7/31 loss=0.65619
  fit=14 full_refit_epoch=8/31 loss=0.44680
  fit=14 full_refit_epoch=9/31 loss=0.30461
  fit=14 full_refit_epoch=10/31 loss=0.22077
  fit=14 full_refit_epoch=11/31 loss=0.16654
  fit=14 full_refit_epoch=12/31 loss=0.12618
  fit=14 full_refit_epoch=13/31 loss=0.10949
  fit=14 full_refit_epoch=14/31 loss=0.08700
  fit=14 full_refit_epoch=15/31 loss=0.07265
  fit=14 full_refit_epoch=16/31 loss=0.06093
  fit=14 full_refit_epoch=17/31 loss=0.05244
  fit=14 full_refit_epoch=18/31 loss=0.05046
  fit=14 full_refit_epoch=19/31 loss=0.04169
  fit=14 full_refit_epoch=20/31 loss=0.03818
  fit=14 full_refit_epoch=21/31 loss=0.03367
  fit=14 full_refit_epoch=22/31 loss=0.03204
  fit=14 full_refit_epoch=23/31 loss=0.02956
  fit=14 full_refit_epoch=24/31 loss=0.02457
  fit=14 full_refit_epoch=25/31 loss=0.02339
  fit=14 full_refit_epoch=26/31 loss=0.02060
  fit=14 full_refit_epoch=27/31 loss=0.02051
  fit=14 full_refit_epoch=28/31 loss=0.01922
  fit=14 full_refit_epoch=29/31 loss=0.01719
  fit=14 full_refit_epoch=30/31 loss=0.01478
  fit=14 full_refit_epoch=31/31 loss=0.01511

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=1/40 loss=5.04749 inner_val_loss=4.81871 inner_val_multiclass_log_loss=4.81872 best_multiclass_log_loss=4.81872 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=2/40 loss=3.88437 inner_val_loss=4.47669 inner_val_multiclass_log_loss=4.47663 best_multiclass_log_loss=4.47663 best_epoch=2 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=3/40 loss=2.93474 inner_val_loss=4.15286 inner_val_multiclass_log_loss=4.15279 best_multiclass_log_loss=4.15279 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=4/40 loss=2.14449 inner_val_loss=3.83851 inner_val_multiclass_log_loss=3.83856 best_multiclass_log_loss=3.83856 best_epoch=4 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=5/40 loss=1.51164 inner_val_loss=3.63070 inner_val_multiclass_log_loss=3.63065 best_multiclass_log_loss=3.63065 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=6/40 loss=1.04807 inner_val_loss=3.45205 inner_val_multiclass_log_loss=3.45202 best_multiclass_log_loss=3.45202 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=7/40 loss=0.73374 inner_val_loss=3.31202 inner_val_multiclass_log_loss=3.31200 best_multiclass_log_loss=3.31200 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=8/40 loss=0.51416 inner_val_loss=3.22684 inner_val_multiclass_log_loss=3.22686 best_multiclass_log_loss=3.22686 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=9/40 loss=0.35244 inner_val_loss=3.17807 inner_val_multiclass_log_loss=3.17811 best_multiclass_log_loss=3.17811 best_epoch=9 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=10/40 loss=0.26490 inner_val_loss=3.14070 inner_val_multiclass_log_loss=3.14074 best_multiclass_log_loss=3.14074 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=11/40 loss=0.20512 inner_val_loss=3.08093 inner_val_multiclass_log_loss=3.08100 best_multiclass_log_loss=3.08100 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=12/40 loss=0.17152 inner_val_loss=3.03603 inner_val_multiclass_log_loss=3.03605 best_multiclass_log_loss=3.03605 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=13/40 loss=0.13419 inner_val_loss=3.00439 inner_val_multiclass_log_loss=3.00439 best_multiclass_log_loss=3.00439 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=14/40 loss=0.11156 inner_val_loss=2.97015 inner_val_multiclass_log_loss=2.97018 best_multiclass_log_loss=2.97018 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=15/40 loss=0.09839 inner_val_loss=2.98986 inner_val_multiclass_log_loss=2.98977 best_multiclass_log_loss=2.97018 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=16/40 loss=0.08324 inner_val_loss=2.95076 inner_val_multiclass_log_loss=2.95078 best_multiclass_log_loss=2.95078 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=17/40 loss=0.07261 inner_val_loss=2.92277 inner_val_multiclass_log_loss=2.92280 best_multiclass_log_loss=2.92280 best_epoch=17 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=18/40 loss=0.06728 inner_val_loss=2.90194 inner_val_multiclass_log_loss=2.90186 best_multiclass_log_loss=2.90186 best_epoch=18 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=19/40 loss=0.06306 inner_val_loss=2.92565 inner_val_multiclass_log_loss=2.92568 best_multiclass_log_loss=2.90186 best_epoch=18 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=20/40 loss=0.05421 inner_val_loss=2.87176 inner_val_multiclass_log_loss=2.87173 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=21/40 loss=0.05061 inner_val_loss=2.87800 inner_val_multiclass_log_loss=2.87795 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=22/40 loss=0.04280 inner_val_loss=2.87844 inner_val_multiclass_log_loss=2.87854 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=23/40 loss=0.04317 inner_val_loss=2.85119 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=24/40 loss=0.03681 inner_val_loss=2.86261 inner_val_multiclass_log_loss=2.86248 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=25/40 loss=0.03759 inner_val_loss=2.86437 inner_val_multiclass_log_loss=2.86436 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=26/40 loss=0.03727 inner_val_loss=2.84264 inner_val_multiclass_log_loss=2.84256 best_multiclass_log_loss=2.84256 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=27/40 loss=0.04750 inner_val_loss=2.78905 inner_val_multiclass_log_loss=2.78899 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=28/40 loss=0.02953 inner_val_loss=2.85267 inner_val_multiclass_log_loss=2.85263 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=29/40 loss=0.02476 inner_val_loss=2.85039 inner_val_multiclass_log_loss=2.85031 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=30/40 loss=0.04091 inner_val_loss=2.82130 inner_val_multiclass_log_loss=2.82136 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=31/40 loss=0.02443 inner_val_loss=2.81061 inner_val_multiclass_log_loss=2.81065 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.1
  fit=15 epoch=32/40 loss=0.02234 inner_val_loss=2.85927 inner_val_multiclass_log_loss=2.85927 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 full_refit_epoch=1/27 loss=5.01707
  fit=15 full_refit_epoch=2/27 loss=3.83853
  fit=15 full_refit_epoch=3/27 loss=2.83950
  fit=15 full_refit_epoch=4/27 loss=2.01059
  fit=15 full_refit_epoch=5/27 loss=1.42550
  fit=15 full_refit_epoch=6/27 loss=0.96100
  fit=15 full_refit_epoch=7/27 loss=0.63852
  fit=15 full_refit_epoch=8/27 loss=0.43575
  fit=15 full_refit_epoch=9/27 loss=0.29530
  fit=15 full_refit_epoch=10/27 loss=0.21542
  fit=15 full_refit_epoch=11/27 loss=0.16594
  fit=15 full_refit_epoch=12/27 loss=0.12619
  fit=15 full_refit_epoch=13/27 loss=0.10692
  fit=15 full_refit_epoch=14/27 loss=0.08452
  fit=15 full_refit_epoch=15/27 loss=0.07949
  fit=15 full_refit_epoch=16/27 loss=0.06535
  fit=15 full_refit_epoch=17/27 loss=0.05278
  fit=15 full_refit_epoch=18/27 loss=0.04622
  fit=15 full_refit_epoch=19/27 loss=0.04249
  fit=15 full_refit_epoch=20/27 loss=0.03969
  fit=15 full_refit_epoch=21/27 loss=0.03237
  fit=15 full_refit_epoch=22/27 loss=0.03002
  fit=15 full_refit_epoch=23/27 loss=0.02576
  fit=15 full_refit_epoch=24/27 loss=0.02408
  fit=15 full_refit_epoch=25/27 loss=0.02292
  fit=15 full_refit_epoch=26/27 loss=0.02128
  fit=15 full_refit_epoch=27/27 loss=0.02029

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=initial model=efficientnet_b0 metric=2.9845033042486517 error=None minutes=14.72
START seed=29 phase=initial_merge model=ensemble:resnet18+efficientnet_b0
END   seed=29 phase=initial_merge model=ensemble:resnet18+efficientnet_b0 metric=None error=AssertionError:  minutes=0.01
START seed=29 phase=initial_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=1/40 loss=4.79144 inner_val_loss=4.76133 inner_val_multiclass_log_loss=4.76143 best_multiclass_log_loss=4.76143 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=2/40 loss=4.62554 inner_val_loss=4.70355 inner_val_multiclass_log_loss=4.70364 best_multiclass_log_loss=4.70364 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=3/40 loss=4.45690 inner_val_loss=4.61165 inner_val_multiclass_log_loss=4.61160 best_multiclass_log_loss=4.61160 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=4/40 loss=4.26439 inner_val_loss=4.48426 inner_val_multiclass_log_loss=4.48426 best_multiclass_log_loss=4.48426 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=5/40 loss=4.04628 inner_val_loss=4.35704 inner_val_multiclass_log_loss=4.35702 best_multiclass_log_loss=4.35702 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=6/40 loss=3.82694 inner_val_loss=4.22893 inner_val_multiclass_log_loss=4.22889 best_multiclass_log_loss=4.22889 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=7/40 loss=3.58612 inner_val_loss=4.09031 inner_val_multiclass_log_loss=4.09028 best_multiclass_log_loss=4.09028 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=8/40 loss=3.37138 inner_val_loss=3.92341 inner_val_multiclass_log_loss=3.92337 best_multiclass_log_loss=3.92337 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=9/40 loss=3.16131 inner_val_loss=3.84799 inner_val_multiclass_log_loss=3.84804 best_multiclass_log_loss=3.84804 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=10/40 loss=2.93246 inner_val_loss=3.68492 inner_val_multiclass_log_loss=3.68490 best_multiclass_log_loss=3.68490 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=11/40 loss=2.71793 inner_val_loss=3.61770 inner_val_multiclass_log_loss=3.61779 best_multiclass_log_loss=3.61779 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=12/40 loss=2.51520 inner_val_loss=3.50337 inner_val_multiclass_log_loss=3.50331 best_multiclass_log_loss=3.50331 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=13/40 loss=2.31603 inner_val_loss=3.38420 inner_val_multiclass_log_loss=3.38421 best_multiclass_log_loss=3.38421 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=14/40 loss=2.13215 inner_val_loss=3.33402 inner_val_multiclass_log_loss=3.33402 best_multiclass_log_loss=3.33402 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=15/40 loss=1.94203 inner_val_loss=3.19962 inner_val_multiclass_log_loss=3.19959 best_multiclass_log_loss=3.19959 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=16/40 loss=1.77130 inner_val_loss=3.11036 inner_val_multiclass_log_loss=3.11039 best_multiclass_log_loss=3.11039 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=17/40 loss=1.61756 inner_val_loss=3.06941 inner_val_multiclass_log_loss=3.06935 best_multiclass_log_loss=3.06935 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=18/40 loss=1.46287 inner_val_loss=3.01414 inner_val_multiclass_log_loss=3.01415 best_multiclass_log_loss=3.01415 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=19/40 loss=1.31347 inner_val_loss=2.99891 inner_val_multiclass_log_loss=2.99883 best_multiclass_log_loss=2.99883 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=20/40 loss=1.18822 inner_val_loss=2.92087 inner_val_multiclass_log_loss=2.92080 best_multiclass_log_loss=2.92080 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=21/40 loss=1.05517 inner_val_loss=2.88822 inner_val_multiclass_log_loss=2.88816 best_multiclass_log_loss=2.88816 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=22/40 loss=0.95697 inner_val_loss=2.83501 inner_val_multiclass_log_loss=2.83497 best_multiclass_log_loss=2.83497 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=23/40 loss=0.87262 inner_val_loss=2.77049 inner_val_multiclass_log_loss=2.77046 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=24/40 loss=0.76393 inner_val_loss=2.77348 inner_val_multiclass_log_loss=2.77354 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=25/40 loss=0.68706 inner_val_loss=2.76672 inner_val_multiclass_log_loss=2.76677 best_multiclass_log_loss=2.76677 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=26/40 loss=0.61515 inner_val_loss=2.71639 inner_val_multiclass_log_loss=2.71637 best_multiclass_log_loss=2.71637 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=27/40 loss=0.52934 inner_val_loss=2.71243 inner_val_multiclass_log_loss=2.71235 best_multiclass_log_loss=2.71235 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=28/40 loss=0.48928 inner_val_loss=2.68442 inner_val_multiclass_log_loss=2.68437 best_multiclass_log_loss=2.68437 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=29/40 loss=0.43681 inner_val_loss=2.63053 inner_val_multiclass_log_loss=2.63058 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=30/40 loss=0.37328 inner_val_loss=2.72091 inner_val_multiclass_log_loss=2.72089 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=31/40 loss=0.33404 inner_val_loss=2.66172 inner_val_multiclass_log_loss=2.66172 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=32/40 loss=0.30090 inner_val_loss=2.67711 inner_val_multiclass_log_loss=2.67710 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=33/40 loss=0.26609 inner_val_loss=2.64585 inner_val_multiclass_log_loss=2.64582 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1
  fit=16 epoch=34/40 loss=0.23828 inner_val_loss=2.65238 inner_val_multiclass_log_loss=2.65240 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 full_refit_epoch=1/29 loss=4.78822
  fit=16 full_refit_epoch=2/29 loss=4.61409
  fit=16 full_refit_epoch=3/29 loss=4.43218
  fit=16 full_refit_epoch=4/29 loss=4.22360
  fit=16 full_refit_epoch=5/29 loss=3.98506
  fit=16 full_refit_epoch=6/29 loss=3.73938
  fit=16 full_refit_epoch=7/29 loss=3.49234
  fit=16 full_refit_epoch=8/29 loss=3.25799
  fit=16 full_refit_epoch=9/29 loss=3.02037
  fit=16 full_refit_epoch=10/29 loss=2.77619
  fit=16 full_refit_epoch=11/29 loss=2.57066
  fit=16 full_refit_epoch=12/29 loss=2.35277
  fit=16 full_refit_epoch=13/29 loss=2.14352
  fit=16 full_refit_epoch=14/29 loss=1.95123
  fit=16 full_refit_epoch=15/29 loss=1.76259
  fit=16 full_refit_epoch=16/29 loss=1.60713
  fit=16 full_refit_epoch=17/29 loss=1.43215
  fit=16 full_refit_epoch=18/29 loss=1.30671
  fit=16 full_refit_epoch=19/29 loss=1.15336
  fit=16 full_refit_epoch=20/29 loss=1.02409
  fit=16 full_refit_epoch=21/29 loss=0.90996
  fit=16 full_refit_epoch=22/29 loss=0.80927
  fit=16 full_refit_epoch=23/29 loss=0.70711
  fit=16 full_refit_epoch=24/29 loss=0.62528
  fit=16 full_refit_epoch=25/29 loss=0.54107
  fit=16 full_refit_epoch=26/29 loss=0.48100
  fit=16 full_refit_epoch=27/29 loss=0.41610
  fit=16 full_refit_epoch=28/29 loss=0.37348
  fit=16 full_refit_epoch=29/29 loss=0.32870

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=1/40 loss=4.77688 inner_val_loss=4.73210 inner_val_multiclass_log_loss=4.73224 best_multiclass_log_loss=4.73224 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=2/40 loss=4.60466 inner_val_loss=4.64713 inner_val_multiclass_log_loss=4.64698 best_multiclass_log_loss=4.64698 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=3/40 loss=4.43182 inner_val_loss=4.56443 inner_val_multiclass_log_loss=4.56453 best_multiclass_log_loss=4.56453 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=4/40 loss=4.24171 inner_val_loss=4.41614 inner_val_multiclass_log_loss=4.41620 best_multiclass_log_loss=4.41620 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=5/40 loss=4.02471 inner_val_loss=4.28676 inner_val_multiclass_log_loss=4.28664 best_multiclass_log_loss=4.28664 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=6/40 loss=3.79899 inner_val_loss=4.12236 inner_val_multiclass_log_loss=4.12235 best_multiclass_log_loss=4.12235 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=7/40 loss=3.57838 inner_val_loss=3.96545 inner_val_multiclass_log_loss=3.96543 best_multiclass_log_loss=3.96543 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=8/40 loss=3.32654 inner_val_loss=3.81237 inner_val_multiclass_log_loss=3.81239 best_multiclass_log_loss=3.81239 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=9/40 loss=3.10657 inner_val_loss=3.74201 inner_val_multiclass_log_loss=3.74201 best_multiclass_log_loss=3.74201 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=10/40 loss=2.88596 inner_val_loss=3.58560 inner_val_multiclass_log_loss=3.58566 best_multiclass_log_loss=3.58566 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=11/40 loss=2.65791 inner_val_loss=3.46592 inner_val_multiclass_log_loss=3.46595 best_multiclass_log_loss=3.46595 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=12/40 loss=2.44689 inner_val_loss=3.35923 inner_val_multiclass_log_loss=3.35918 best_multiclass_log_loss=3.35918 best_epoch=12 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=13/40 loss=2.27432 inner_val_loss=3.24337 inner_val_multiclass_log_loss=3.24334 best_multiclass_log_loss=3.24334 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=14/40 loss=2.07651 inner_val_loss=3.14473 inner_val_multiclass_log_loss=3.14488 best_multiclass_log_loss=3.14488 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=15/40 loss=1.89470 inner_val_loss=3.06804 inner_val_multiclass_log_loss=3.06804 best_multiclass_log_loss=3.06804 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=16/40 loss=1.73623 inner_val_loss=2.95022 inner_val_multiclass_log_loss=2.95029 best_multiclass_log_loss=2.95029 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=17/40 loss=1.55428 inner_val_loss=2.92689 inner_val_multiclass_log_loss=2.92689 best_multiclass_log_loss=2.92689 best_epoch=17 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=18/40 loss=1.41175 inner_val_loss=2.82146 inner_val_multiclass_log_loss=2.82155 best_multiclass_log_loss=2.82155 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=19/40 loss=1.26964 inner_val_loss=2.72490 inner_val_multiclass_log_loss=2.72484 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=20/40 loss=1.16999 inner_val_loss=2.75291 inner_val_multiclass_log_loss=2.75287 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=21/40 loss=1.03966 inner_val_loss=2.67443 inner_val_multiclass_log_loss=2.67446 best_multiclass_log_loss=2.67446 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=22/40 loss=0.91439 inner_val_loss=2.60952 inner_val_multiclass_log_loss=2.60943 best_multiclass_log_loss=2.60943 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=23/40 loss=0.83581 inner_val_loss=2.58285 inner_val_multiclass_log_loss=2.58288 best_multiclass_log_loss=2.58288 best_epoch=23 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=24/40 loss=0.74141 inner_val_loss=2.53561 inner_val_multiclass_log_loss=2.53560 best_multiclass_log_loss=2.53560 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=25/40 loss=0.66409 inner_val_loss=2.50372 inner_val_multiclass_log_loss=2.50371 best_multiclass_log_loss=2.50371 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=26/40 loss=0.57358 inner_val_loss=2.47309 inner_val_multiclass_log_loss=2.47307 best_multiclass_log_loss=2.47307 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=27/40 loss=0.50854 inner_val_loss=2.45066 inner_val_multiclass_log_loss=2.45066 best_multiclass_log_loss=2.45066 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=28/40 loss=0.45707 inner_val_loss=2.44689 inner_val_multiclass_log_loss=2.44685 best_multiclass_log_loss=2.44685 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=29/40 loss=0.40134 inner_val_loss=2.42541 inner_val_multiclass_log_loss=2.42539 best_multiclass_log_loss=2.42539 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=30/40 loss=0.36173 inner_val_loss=2.41848 inner_val_multiclass_log_loss=2.41857 best_multiclass_log_loss=2.41857 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=31/40 loss=0.31615 inner_val_loss=2.38013 inner_val_multiclass_log_loss=2.38011 best_multiclass_log_loss=2.38011 best_epoch=31 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=32/40 loss=0.28382 inner_val_loss=2.37641 inner_val_multiclass_log_loss=2.37642 best_multiclass_log_loss=2.37642 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=33/40 loss=0.26356 inner_val_loss=2.36904 inner_val_multiclass_log_loss=2.36903 best_multiclass_log_loss=2.36903 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=34/40 loss=0.23373 inner_val_loss=2.36645 inner_val_multiclass_log_loss=2.36651 best_multiclass_log_loss=2.36651 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=35/40 loss=0.21890 inner_val_loss=2.35982 inner_val_multiclass_log_loss=2.35984 best_multiclass_log_loss=2.35984 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=36/40 loss=0.18600 inner_val_loss=2.35639 inner_val_multiclass_log_loss=2.35638 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=37/40 loss=0.17461 inner_val_loss=2.36209 inner_val_multiclass_log_loss=2.36213 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=38/40 loss=0.14695 inner_val_loss=2.36564 inner_val_multiclass_log_loss=2.36560 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=39/40 loss=0.13963 inner_val_loss=2.32751 inner_val_multiclass_log_loss=2.32756 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.0
  fit=17 epoch=40/40 loss=0.13450 inner_val_loss=2.34288 inner_val_multiclass_log_loss=2.34286 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 full_refit_epoch=1/39 loss=4.77703
  fit=17 full_refit_epoch=2/39 loss=4.58965
  fit=17 full_refit_epoch=3/39 loss=4.40609
  fit=17 full_refit_epoch=4/39 loss=4.18434
  fit=17 full_refit_epoch=5/39 loss=3.94119
  fit=17 full_refit_epoch=6/39 loss=3.68977
  fit=17 full_refit_epoch=7/39 loss=3.44150
  fit=17 full_refit_epoch=8/39 loss=3.18243
  fit=17 full_refit_epoch=9/39 loss=2.94295
  fit=17 full_refit_epoch=10/39 loss=2.70540
  fit=17 full_refit_epoch=11/39 loss=2.47803
  fit=17 full_refit_epoch=12/39 loss=2.26517
  fit=17 full_refit_epoch=13/39 loss=2.05341
  fit=17 full_refit_epoch=14/39 loss=1.86164
  fit=17 full_refit_epoch=15/39 loss=1.71295
  fit=17 full_refit_epoch=16/39 loss=1.52613
  fit=17 full_refit_epoch=17/39 loss=1.34509
  fit=17 full_refit_epoch=18/39 loss=1.22839
  fit=17 full_refit_epoch=19/39 loss=1.07973
  fit=17 full_refit_epoch=20/39 loss=0.97077
  fit=17 full_refit_epoch=21/39 loss=0.85544
  fit=17 full_refit_epoch=22/39 loss=0.74625
  fit=17 full_refit_epoch=23/39 loss=0.66027
  fit=17 full_refit_epoch=24/39 loss=0.57647
  fit=17 full_refit_epoch=25/39 loss=0.50676
  fit=17 full_refit_epoch=26/39 loss=0.45746
  fit=17 full_refit_epoch=27/39 loss=0.38876
  fit=17 full_refit_epoch=28/39 loss=0.35025
  fit=17 full_refit_epoch=29/39 loss=0.29588
  fit=17 full_refit_epoch=30/39 loss=0.27610
  fit=17 full_refit_epoch=31/39 loss=0.23597
  fit=17 full_refit_epoch=32/39 loss=0.21136
  fit=17 full_refit_epoch=33/39 loss=0.18650
  fit=17 full_refit_epoch=34/39 loss=0.17262
  fit=17 full_refit_epoch=35/39 loss=0.14920
  fit=17 full_refit_epoch=36/39 loss=0.13083
  fit=17 full_refit_epoch=37/39 loss=0.11639
  fit=17 full_refit_epoch=38/39 loss=0.10687
  fit=17 full_refit_epoch=39/39 loss=0.09848

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=1/40 loss=4.78788 inner_val_loss=4.73453 inner_val_multiclass_log_loss=4.73440 best_multiclass_log_loss=4.73440 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=2/40 loss=4.62429 inner_val_loss=4.65916 inner_val_multiclass_log_loss=4.65916 best_multiclass_log_loss=4.65916 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=3/40 loss=4.46878 inner_val_loss=4.56776 inner_val_multiclass_log_loss=4.56775 best_multiclass_log_loss=4.56775 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=4/40 loss=4.28168 inner_val_loss=4.46579 inner_val_multiclass_log_loss=4.46588 best_multiclass_log_loss=4.46588 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=5/40 loss=4.08050 inner_val_loss=4.29853 inner_val_multiclass_log_loss=4.29854 best_multiclass_log_loss=4.29854 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=6/40 loss=3.86685 inner_val_loss=4.14481 inner_val_multiclass_log_loss=4.14487 best_multiclass_log_loss=4.14487 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=7/40 loss=3.62955 inner_val_loss=3.99955 inner_val_multiclass_log_loss=3.99964 best_multiclass_log_loss=3.99964 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=8/40 loss=3.40460 inner_val_loss=3.84375 inner_val_multiclass_log_loss=3.84382 best_multiclass_log_loss=3.84382 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=9/40 loss=3.17732 inner_val_loss=3.75653 inner_val_multiclass_log_loss=3.75648 best_multiclass_log_loss=3.75648 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=10/40 loss=2.95777 inner_val_loss=3.55647 inner_val_multiclass_log_loss=3.55653 best_multiclass_log_loss=3.55653 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=11/40 loss=2.73494 inner_val_loss=3.48144 inner_val_multiclass_log_loss=3.48145 best_multiclass_log_loss=3.48145 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=12/40 loss=2.52807 inner_val_loss=3.36669 inner_val_multiclass_log_loss=3.36679 best_multiclass_log_loss=3.36679 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=13/40 loss=2.32670 inner_val_loss=3.23321 inner_val_multiclass_log_loss=3.23324 best_multiclass_log_loss=3.23324 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=14/40 loss=2.14211 inner_val_loss=3.13339 inner_val_multiclass_log_loss=3.13334 best_multiclass_log_loss=3.13334 best_epoch=14 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=15/40 loss=1.97379 inner_val_loss=2.99862 inner_val_multiclass_log_loss=2.99856 best_multiclass_log_loss=2.99856 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=16/40 loss=1.79112 inner_val_loss=2.95137 inner_val_multiclass_log_loss=2.95135 best_multiclass_log_loss=2.95135 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=17/40 loss=1.64030 inner_val_loss=2.85254 inner_val_multiclass_log_loss=2.85257 best_multiclass_log_loss=2.85257 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=18/40 loss=1.47695 inner_val_loss=2.79063 inner_val_multiclass_log_loss=2.79060 best_multiclass_log_loss=2.79060 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=19/40 loss=1.34568 inner_val_loss=2.71051 inner_val_multiclass_log_loss=2.71048 best_multiclass_log_loss=2.71048 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=20/40 loss=1.20112 inner_val_loss=2.69370 inner_val_multiclass_log_loss=2.69368 best_multiclass_log_loss=2.69368 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=21/40 loss=1.08037 inner_val_loss=2.65799 inner_val_multiclass_log_loss=2.65796 best_multiclass_log_loss=2.65796 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=22/40 loss=0.98182 inner_val_loss=2.59564 inner_val_multiclass_log_loss=2.59567 best_multiclass_log_loss=2.59567 best_epoch=22 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=23/40 loss=0.87696 inner_val_loss=2.57080 inner_val_multiclass_log_loss=2.57078 best_multiclass_log_loss=2.57078 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=24/40 loss=0.77895 inner_val_loss=2.49865 inner_val_multiclass_log_loss=2.49860 best_multiclass_log_loss=2.49860 best_epoch=24 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=25/40 loss=0.69952 inner_val_loss=2.48903 inner_val_multiclass_log_loss=2.48896 best_multiclass_log_loss=2.48896 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=26/40 loss=0.62977 inner_val_loss=2.48067 inner_val_multiclass_log_loss=2.48063 best_multiclass_log_loss=2.48063 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=27/40 loss=0.54283 inner_val_loss=2.44089 inner_val_multiclass_log_loss=2.44091 best_multiclass_log_loss=2.44091 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=28/40 loss=0.48600 inner_val_loss=2.42942 inner_val_multiclass_log_loss=2.42940 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=29/40 loss=0.43038 inner_val_loss=2.44990 inner_val_multiclass_log_loss=2.44988 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=30/40 loss=0.38295 inner_val_loss=2.40124 inner_val_multiclass_log_loss=2.40129 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=31/40 loss=0.34102 inner_val_loss=2.42409 inner_val_multiclass_log_loss=2.42413 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=32/40 loss=0.29692 inner_val_loss=2.40238 inner_val_multiclass_log_loss=2.40230 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=33/40 loss=0.26235 inner_val_loss=2.34556 inner_val_multiclass_log_loss=2.34554 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=34/40 loss=0.24309 inner_val_loss=2.37027 inner_val_multiclass_log_loss=2.37025 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=35/40 loss=0.21402 inner_val_loss=2.33308 inner_val_multiclass_log_loss=2.33300 best_multiclass_log_loss=2.33300 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=36/40 loss=0.18834 inner_val_loss=2.32832 inner_val_multiclass_log_loss=2.32835 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=37/40 loss=0.17150 inner_val_loss=2.33830 inner_val_multiclass_log_loss=2.33827 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=38/40 loss=0.16646 inner_val_loss=2.34553 inner_val_multiclass_log_loss=2.34549 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=39/40 loss=0.14529 inner_val_loss=2.35859 inner_val_multiclass_log_loss=2.35854 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1
  fit=18 epoch=40/40 loss=0.12740 inner_val_loss=2.36939 inner_val_multiclass_log_loss=2.36934 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 full_refit_epoch=1/36 loss=4.78174
  fit=18 full_refit_epoch=2/36 loss=4.61084
  fit=18 full_refit_epoch=3/36 loss=4.43466
  fit=18 full_refit_epoch=4/36 loss=4.23122
  fit=18 full_refit_epoch=5/36 loss=4.00552
  fit=18 full_refit_epoch=6/36 loss=3.76720
  fit=18 full_refit_epoch=7/36 loss=3.51458
  fit=18 full_refit_epoch=8/36 loss=3.27506
  fit=18 full_refit_epoch=9/36 loss=3.02642
  fit=18 full_refit_epoch=10/36 loss=2.79304
  fit=18 full_refit_epoch=11/36 loss=2.57939
  fit=18 full_refit_epoch=12/36 loss=2.36072
  fit=18 full_refit_epoch=13/36 loss=2.15404
  fit=18 full_refit_epoch=14/36 loss=1.96215
  fit=18 full_refit_epoch=15/36 loss=1.78668
  fit=18 full_refit_epoch=16/36 loss=1.61511
  fit=18 full_refit_epoch=17/36 loss=1.45979
  fit=18 full_refit_epoch=18/36 loss=1.30436
  fit=18 full_refit_epoch=19/36 loss=1.17129
  fit=18 full_refit_epoch=20/36 loss=1.03604
  fit=18 full_refit_epoch=21/36 loss=0.93486
  fit=18 full_refit_epoch=22/36 loss=0.82323
  fit=18 full_refit_epoch=23/36 loss=0.73781
  fit=18 full_refit_epoch=24/36 loss=0.63958
  fit=18 full_refit_epoch=25/36 loss=0.55612
  fit=18 full_refit_epoch=26/36 loss=0.49764
  fit=18 full_refit_epoch=27/36 loss=0.43395
  fit=18 full_refit_epoch=28/36 loss=0.38153
  fit=18 full_refit_epoch=29/36 loss=0.33402
  fit=18 full_refit_epoch=30/36 loss=0.29779
  fit=18 full_refit_epoch=31/36 loss=0.26630
  fit=18 full_refit_epoch=32/36 loss=0.23283
  fit=18 full_refit_epoch=33/36 loss=0.20140
  fit=18 full_refit_epoch=34/36 loss=0.18013
  fit=18 full_refit_epoch=35/36 loss=0.16015
  fit=18 full_refit_epoch=36/36 loss=0.15038

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=1/40 loss=4.78972 inner_val_loss=4.78068 inner_val_multiclass_log_loss=4.78091 best_multiclass_log_loss=4.78091 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=2/40 loss=4.61644 inner_val_loss=4.70122 inner_val_multiclass_log_loss=4.70113 best_multiclass_log_loss=4.70113 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=3/40 loss=4.45221 inner_val_loss=4.62067 inner_val_multiclass_log_loss=4.62064 best_multiclass_log_loss=4.62064 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=4/40 loss=4.27089 inner_val_loss=4.47619 inner_val_multiclass_log_loss=4.47618 best_multiclass_log_loss=4.47618 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=5/40 loss=4.06268 inner_val_loss=4.36162 inner_val_multiclass_log_loss=4.36158 best_multiclass_log_loss=4.36158 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=6/40 loss=3.84209 inner_val_loss=4.26205 inner_val_multiclass_log_loss=4.26196 best_multiclass_log_loss=4.26196 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=7/40 loss=3.61849 inner_val_loss=4.08260 inner_val_multiclass_log_loss=4.08265 best_multiclass_log_loss=4.08265 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=8/40 loss=3.39831 inner_val_loss=3.93322 inner_val_multiclass_log_loss=3.93321 best_multiclass_log_loss=3.93321 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=9/40 loss=3.19004 inner_val_loss=3.87016 inner_val_multiclass_log_loss=3.87020 best_multiclass_log_loss=3.87020 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=10/40 loss=2.96517 inner_val_loss=3.75255 inner_val_multiclass_log_loss=3.75255 best_multiclass_log_loss=3.75255 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=11/40 loss=2.75054 inner_val_loss=3.67104 inner_val_multiclass_log_loss=3.67106 best_multiclass_log_loss=3.67106 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=12/40 loss=2.54064 inner_val_loss=3.57192 inner_val_multiclass_log_loss=3.57195 best_multiclass_log_loss=3.57195 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=13/40 loss=2.34203 inner_val_loss=3.46974 inner_val_multiclass_log_loss=3.46984 best_multiclass_log_loss=3.46984 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=14/40 loss=2.14699 inner_val_loss=3.39058 inner_val_multiclass_log_loss=3.39060 best_multiclass_log_loss=3.39060 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=15/40 loss=1.97566 inner_val_loss=3.22496 inner_val_multiclass_log_loss=3.22488 best_multiclass_log_loss=3.22488 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=16/40 loss=1.78328 inner_val_loss=3.20142 inner_val_multiclass_log_loss=3.20133 best_multiclass_log_loss=3.20133 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=17/40 loss=1.61451 inner_val_loss=3.10055 inner_val_multiclass_log_loss=3.10061 best_multiclass_log_loss=3.10061 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=18/40 loss=1.48052 inner_val_loss=3.06376 inner_val_multiclass_log_loss=3.06376 best_multiclass_log_loss=3.06376 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=19/40 loss=1.30872 inner_val_loss=2.99257 inner_val_multiclass_log_loss=2.99263 best_multiclass_log_loss=2.99263 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=20/40 loss=1.18439 inner_val_loss=2.97069 inner_val_multiclass_log_loss=2.97066 best_multiclass_log_loss=2.97066 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=21/40 loss=1.07813 inner_val_loss=2.89766 inner_val_multiclass_log_loss=2.89778 best_multiclass_log_loss=2.89778 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=22/40 loss=0.94472 inner_val_loss=2.84399 inner_val_multiclass_log_loss=2.84401 best_multiclass_log_loss=2.84401 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=23/40 loss=0.85215 inner_val_loss=2.81882 inner_val_multiclass_log_loss=2.81876 best_multiclass_log_loss=2.81876 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=24/40 loss=0.76193 inner_val_loss=2.78520 inner_val_multiclass_log_loss=2.78512 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=25/40 loss=0.67522 inner_val_loss=2.79527 inner_val_multiclass_log_loss=2.79529 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=26/40 loss=0.59620 inner_val_loss=2.76630 inner_val_multiclass_log_loss=2.76634 best_multiclass_log_loss=2.76634 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=27/40 loss=0.53659 inner_val_loss=2.73014 inner_val_multiclass_log_loss=2.73021 best_multiclass_log_loss=2.73021 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=28/40 loss=0.46902 inner_val_loss=2.68155 inner_val_multiclass_log_loss=2.68160 best_multiclass_log_loss=2.68160 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=29/40 loss=0.42078 inner_val_loss=2.66191 inner_val_multiclass_log_loss=2.66190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=30/40 loss=0.37526 inner_val_loss=2.67838 inner_val_multiclass_log_loss=2.67840 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=31/40 loss=0.32713 inner_val_loss=2.67195 inner_val_multiclass_log_loss=2.67190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=32/40 loss=0.29732 inner_val_loss=2.64314 inner_val_multiclass_log_loss=2.64318 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=33/40 loss=0.26400 inner_val_loss=2.64539 inner_val_multiclass_log_loss=2.64539 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=34/40 loss=0.22863 inner_val_loss=2.62849 inner_val_multiclass_log_loss=2.62847 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=35/40 loss=0.21273 inner_val_loss=2.68348 inner_val_multiclass_log_loss=2.68344 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=36/40 loss=0.18296 inner_val_loss=2.62064 inner_val_multiclass_log_loss=2.62070 best_multiclass_log_loss=2.62070 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=37/40 loss=0.16822 inner_val_loss=2.59413 inner_val_multiclass_log_loss=2.59413 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=38/40 loss=0.15150 inner_val_loss=2.62271 inner_val_multiclass_log_loss=2.62273 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=39/40 loss=0.14116 inner_val_loss=2.60107 inner_val_multiclass_log_loss=2.60106 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1
  fit=19 epoch=40/40 loss=0.12134 inner_val_loss=2.58163 inner_val_multiclass_log_loss=2.58163 best_multiclass_log_loss=2.58163 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 full_refit_epoch=1/40 loss=4.78354
  fit=19 full_refit_epoch=2/40 loss=4.60792
  fit=19 full_refit_epoch=3/40 loss=4.43281
  fit=19 full_refit_epoch=4/40 loss=4.22375
  fit=19 full_refit_epoch=5/40 loss=3.98823
  fit=19 full_refit_epoch=6/40 loss=3.75429
  fit=19 full_refit_epoch=7/40 loss=3.52034
  fit=19 full_refit_epoch=8/40 loss=3.27720
  fit=19 full_refit_epoch=9/40 loss=3.03494
  fit=19 full_refit_epoch=10/40 loss=2.80688
  fit=19 full_refit_epoch=11/40 loss=2.58710
  fit=19 full_refit_epoch=12/40 loss=2.35734
  fit=19 full_refit_epoch=13/40 loss=2.16211
  fit=19 full_refit_epoch=14/40 loss=1.95755
  fit=19 full_refit_epoch=15/40 loss=1.76778
  fit=19 full_refit_epoch=16/40 loss=1.59597
  fit=19 full_refit_epoch=17/40 loss=1.43546
  fit=19 full_refit_epoch=18/40 loss=1.29959
  fit=19 full_refit_epoch=19/40 loss=1.14497
  fit=19 full_refit_epoch=20/40 loss=1.00626
  fit=19 full_refit_epoch=21/40 loss=0.90324
  fit=19 full_refit_epoch=22/40 loss=0.80394
  fit=19 full_refit_epoch=23/40 loss=0.70506
  fit=19 full_refit_epoch=24/40 loss=0.60783
  fit=19 full_refit_epoch=25/40 loss=0.54702
  fit=19 full_refit_epoch=26/40 loss=0.47226
  fit=19 full_refit_epoch=27/40 loss=0.41576
  fit=19 full_refit_epoch=28/40 loss=0.36619
  fit=19 full_refit_epoch=29/40 loss=0.31657
  fit=19 full_refit_epoch=30/40 loss=0.27211
  fit=19 full_refit_epoch=31/40 loss=0.24408
  fit=19 full_refit_epoch=32/40 loss=0.21425
  fit=19 full_refit_epoch=33/40 loss=0.19270
  fit=19 full_refit_epoch=34/40 loss=0.17262
  fit=19 full_refit_epoch=35/40 loss=0.15522
  fit=19 full_refit_epoch=36/40 loss=0.13730
  fit=19 full_refit_epoch=37/40 loss=0.12264
  fit=19 full_refit_epoch=38/40 loss=0.11303
  fit=19 full_refit_epoch=39/40 loss=0.10542
  fit=19 full_refit_epoch=40/40 loss=0.09377

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=1/40 loss=4.77984 inner_val_loss=4.72068 inner_val_multiclass_log_loss=4.72080 best_multiclass_log_loss=4.72080 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=2/40 loss=4.61636 inner_val_loss=4.63699 inner_val_multiclass_log_loss=4.63693 best_multiclass_log_loss=4.63693 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=3/40 loss=4.45690 inner_val_loss=4.53775 inner_val_multiclass_log_loss=4.53788 best_multiclass_log_loss=4.53788 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=4/40 loss=4.27154 inner_val_loss=4.42661 inner_val_multiclass_log_loss=4.42666 best_multiclass_log_loss=4.42666 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=5/40 loss=4.07261 inner_val_loss=4.30221 inner_val_multiclass_log_loss=4.30233 best_multiclass_log_loss=4.30233 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=6/40 loss=3.86698 inner_val_loss=4.12875 inner_val_multiclass_log_loss=4.12878 best_multiclass_log_loss=4.12878 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=7/40 loss=3.63809 inner_val_loss=4.01937 inner_val_multiclass_log_loss=4.01942 best_multiclass_log_loss=4.01942 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=8/40 loss=3.41935 inner_val_loss=3.87518 inner_val_multiclass_log_loss=3.87534 best_multiclass_log_loss=3.87534 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=9/40 loss=3.18955 inner_val_loss=3.70662 inner_val_multiclass_log_loss=3.70651 best_multiclass_log_loss=3.70651 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=10/40 loss=2.97659 inner_val_loss=3.54444 inner_val_multiclass_log_loss=3.54442 best_multiclass_log_loss=3.54442 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=11/40 loss=2.76710 inner_val_loss=3.46261 inner_val_multiclass_log_loss=3.46251 best_multiclass_log_loss=3.46251 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=12/40 loss=2.57334 inner_val_loss=3.27116 inner_val_multiclass_log_loss=3.27115 best_multiclass_log_loss=3.27115 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=13/40 loss=2.36194 inner_val_loss=3.19750 inner_val_multiclass_log_loss=3.19768 best_multiclass_log_loss=3.19768 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=14/40 loss=2.17910 inner_val_loss=3.07389 inner_val_multiclass_log_loss=3.07391 best_multiclass_log_loss=3.07391 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=15/40 loss=1.99885 inner_val_loss=3.01897 inner_val_multiclass_log_loss=3.01895 best_multiclass_log_loss=3.01895 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=16/40 loss=1.82771 inner_val_loss=2.94047 inner_val_multiclass_log_loss=2.94037 best_multiclass_log_loss=2.94037 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=17/40 loss=1.65915 inner_val_loss=2.81063 inner_val_multiclass_log_loss=2.81061 best_multiclass_log_loss=2.81061 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=18/40 loss=1.51430 inner_val_loss=2.77291 inner_val_multiclass_log_loss=2.77299 best_multiclass_log_loss=2.77299 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=19/40 loss=1.36006 inner_val_loss=2.70794 inner_val_multiclass_log_loss=2.70795 best_multiclass_log_loss=2.70795 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=20/40 loss=1.24242 inner_val_loss=2.63758 inner_val_multiclass_log_loss=2.63757 best_multiclass_log_loss=2.63757 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=21/40 loss=1.10894 inner_val_loss=2.62117 inner_val_multiclass_log_loss=2.62113 best_multiclass_log_loss=2.62113 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=22/40 loss=0.99728 inner_val_loss=2.57374 inner_val_multiclass_log_loss=2.57372 best_multiclass_log_loss=2.57372 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=23/40 loss=0.89508 inner_val_loss=2.56801 inner_val_multiclass_log_loss=2.56802 best_multiclass_log_loss=2.56802 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=24/40 loss=0.79840 inner_val_loss=2.51540 inner_val_multiclass_log_loss=2.51532 best_multiclass_log_loss=2.51532 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=25/40 loss=0.70842 inner_val_loss=2.48709 inner_val_multiclass_log_loss=2.48713 best_multiclass_log_loss=2.48713 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=26/40 loss=0.63383 inner_val_loss=2.45845 inner_val_multiclass_log_loss=2.45841 best_multiclass_log_loss=2.45841 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=27/40 loss=0.57510 inner_val_loss=2.43780 inner_val_multiclass_log_loss=2.43789 best_multiclass_log_loss=2.43789 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=28/40 loss=0.49380 inner_val_loss=2.40752 inner_val_multiclass_log_loss=2.40752 best_multiclass_log_loss=2.40752 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=29/40 loss=0.43158 inner_val_loss=2.38063 inner_val_multiclass_log_loss=2.38061 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=30/40 loss=0.40393 inner_val_loss=2.40156 inner_val_multiclass_log_loss=2.40155 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=31/40 loss=0.34829 inner_val_loss=2.34321 inner_val_multiclass_log_loss=2.34324 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=32/40 loss=0.30293 inner_val_loss=2.34830 inner_val_multiclass_log_loss=2.34833 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=33/40 loss=0.27191 inner_val_loss=2.33435 inner_val_multiclass_log_loss=2.33438 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=34/40 loss=0.24077 inner_val_loss=2.36642 inner_val_multiclass_log_loss=2.36640 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=35/40 loss=0.21350 inner_val_loss=2.35795 inner_val_multiclass_log_loss=2.35801 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=36/40 loss=0.21089 inner_val_loss=2.32175 inner_val_multiclass_log_loss=2.32167 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=37/40 loss=0.17882 inner_val_loss=2.32570 inner_val_multiclass_log_loss=2.32573 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=38/40 loss=0.16260 inner_val_loss=2.31285 inner_val_multiclass_log_loss=2.31276 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=39/40 loss=0.14282 inner_val_loss=2.37636 inner_val_multiclass_log_loss=2.37630 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.0
  fit=20 epoch=40/40 loss=0.13584 inner_val_loss=2.33817 inner_val_multiclass_log_loss=2.33822 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 full_refit_epoch=1/38 loss=4.77285
  fit=20 full_refit_epoch=2/38 loss=4.60156
  fit=20 full_refit_epoch=3/38 loss=4.42367
  fit=20 full_refit_epoch=4/38 loss=4.21951
  fit=20 full_refit_epoch=5/38 loss=3.99543
  fit=20 full_refit_epoch=6/38 loss=3.76219
  fit=20 full_refit_epoch=7/38 loss=3.51045
  fit=20 full_refit_epoch=8/38 loss=3.26475
  fit=20 full_refit_epoch=9/38 loss=3.01855
  fit=20 full_refit_epoch=10/38 loss=2.79697
  fit=20 full_refit_epoch=11/38 loss=2.56724
  fit=20 full_refit_epoch=12/38 loss=2.34649
  fit=20 full_refit_epoch=13/38 loss=2.14739
  fit=20 full_refit_epoch=14/38 loss=1.94784
  fit=20 full_refit_epoch=15/38 loss=1.77608
  fit=20 full_refit_epoch=16/38 loss=1.58856
  fit=20 full_refit_epoch=17/38 loss=1.43336
  fit=20 full_refit_epoch=18/38 loss=1.28592
  fit=20 full_refit_epoch=19/38 loss=1.14915
  fit=20 full_refit_epoch=20/38 loss=1.01684
  fit=20 full_refit_epoch=21/38 loss=0.90502
  fit=20 full_refit_epoch=22/38 loss=0.79337
  fit=20 full_refit_epoch=23/38 loss=0.69822
  fit=20 full_refit_epoch=24/38 loss=0.61281
  fit=20 full_refit_epoch=25/38 loss=0.54337
  fit=20 full_refit_epoch=26/38 loss=0.47650
  fit=20 full_refit_epoch=27/38 loss=0.42055
  fit=20 full_refit_epoch=28/38 loss=0.35945
  fit=20 full_refit_epoch=29/38 loss=0.32238
  fit=20 full_refit_epoch=30/38 loss=0.28152
  fit=20 full_refit_epoch=31/38 loss=0.25445
  fit=20 full_refit_epoch=32/38 loss=0.21704
  fit=20 full_refit_epoch=33/38 loss=0.19919
  fit=20 full_refit_epoch=34/38 loss=0.17358
  fit=20 full_refit_epoch=35/38 loss=0.15832
  fit=20 full_refit_epoch=36/38 loss=0.14008
  fit=20 full_refit_epoch=37/38 loss=0.12395
  fit=20 full_refit_epoch=38/38 loss=0.11568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=initial_selected model=resnet18 metric=2.471291572428004 error=None minutes=13.14
START seed=29 phase=ablation model=pass

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=ablation model=pass metric=4.787491690627983 error=None minutes=0.23
START seed=29 phase=refinement model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=1/40 loss=5.02100 inner_val_loss=4.78337 inner_val_multiclass_log_loss=4.78327 best_multiclass_log_loss=4.78327 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=2/40 loss=3.87256 inner_val_loss=4.48209 inner_val_multiclass_log_loss=4.48205 best_multiclass_log_loss=4.48205 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=3/40 loss=2.92353 inner_val_loss=4.23134 inner_val_multiclass_log_loss=4.23137 best_multiclass_log_loss=4.23137 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=4/40 loss=2.11493 inner_val_loss=3.96919 inner_val_multiclass_log_loss=3.96931 best_multiclass_log_loss=3.96931 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=5/40 loss=1.47399 inner_val_loss=3.77509 inner_val_multiclass_log_loss=3.77514 best_multiclass_log_loss=3.77514 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=6/40 loss=1.04729 inner_val_loss=3.57786 inner_val_multiclass_log_loss=3.57778 best_multiclass_log_loss=3.57778 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=7/40 loss=0.69747 inner_val_loss=3.48617 inner_val_multiclass_log_loss=3.48619 best_multiclass_log_loss=3.48619 best_epoch=7 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=8/40 loss=0.50278 inner_val_loss=3.36251 inner_val_multiclass_log_loss=3.36246 best_multiclass_log_loss=3.36246 best_epoch=8 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=9/40 loss=0.36162 inner_val_loss=3.33188 inner_val_multiclass_log_loss=3.33183 best_multiclass_log_loss=3.33183 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=10/40 loss=0.25721 inner_val_loss=3.28651 inner_val_multiclass_log_loss=3.28647 best_multiclass_log_loss=3.28647 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=11/40 loss=0.19091 inner_val_loss=3.24312 inner_val_multiclass_log_loss=3.24315 best_multiclass_log_loss=3.24315 best_epoch=11 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=12/40 loss=0.15870 inner_val_loss=3.19438 inner_val_multiclass_log_loss=3.19431 best_multiclass_log_loss=3.19431 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=13/40 loss=0.12977 inner_val_loss=3.17543 inner_val_multiclass_log_loss=3.17544 best_multiclass_log_loss=3.17544 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=14/40 loss=0.11018 inner_val_loss=3.18009 inner_val_multiclass_log_loss=3.18016 best_multiclass_log_loss=3.17544 best_epoch=13 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=15/40 loss=0.10090 inner_val_loss=3.14716 inner_val_multiclass_log_loss=3.14715 best_multiclass_log_loss=3.14715 best_epoch=15 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=16/40 loss=0.08278 inner_val_loss=3.09490 inner_val_multiclass_log_loss=3.09486 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=17/40 loss=0.07331 inner_val_loss=3.11212 inner_val_multiclass_log_loss=3.11211 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=18/40 loss=0.06614 inner_val_loss=3.15242 inner_val_multiclass_log_loss=3.15243 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=19/40 loss=0.05272 inner_val_loss=3.12751 inner_val_multiclass_log_loss=3.12754 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=20/40 loss=0.05146 inner_val_loss=3.11677 inner_val_multiclass_log_loss=3.11675 best_multiclass_log_loss=3.09486 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=21/40 loss=0.04559 inner_val_loss=3.08631 inner_val_multiclass_log_loss=3.08622 best_multiclass_log_loss=3.08622 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=22/40 loss=0.04532 inner_val_loss=3.07370 inner_val_multiclass_log_loss=3.07371 best_multiclass_log_loss=3.07371 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=23/40 loss=0.05045 inner_val_loss=3.09611 inner_val_multiclass_log_loss=3.09614 best_multiclass_log_loss=3.07371 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=24/40 loss=0.03505 inner_val_loss=3.05473 inner_val_multiclass_log_loss=3.05463 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=25/40 loss=0.03975 inner_val_loss=3.07794 inner_val_multiclass_log_loss=3.07793 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=26/40 loss=0.04033 inner_val_loss=3.07039 inner_val_multiclass_log_loss=3.07035 best_multiclass_log_loss=3.05463 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=27/40 loss=0.03676 inner_val_loss=3.03101 inner_val_multiclass_log_loss=3.03099 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=28/40 loss=0.03001 inner_val_loss=3.03908 inner_val_multiclass_log_loss=3.03900 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=29/40 loss=0.03443 inner_val_loss=3.03278 inner_val_multiclass_log_loss=3.03281 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=30/40 loss=0.02742 inner_val_loss=3.06223 inner_val_multiclass_log_loss=3.06221 best_multiclass_log_loss=3.03099 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=31/40 loss=0.02591 inner_val_loss=3.02145 inner_val_multiclass_log_loss=3.02143 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=32/40 loss=0.02433 inner_val_loss=3.03211 inner_val_multiclass_log_loss=3.03209 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=33/40 loss=0.02665 inner_val_loss=3.02693 inner_val_multiclass_log_loss=3.02691 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=2.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=34/40 loss=0.02612 inner_val_loss=3.06065 inner_val_multiclass_log_loss=3.06064 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=35/40 loss=0.02708 inner_val_loss=3.02986 inner_val_multiclass_log_loss=3.02984 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=3.3
  fit=21 epoch=36/40 loss=0.02549 inner_val_loss=3.04284 inner_val_multiclass_log_loss=3.04280 best_multiclass_log_loss=3.02143 best_epoch=31 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 full_refit_epoch=1/31 loss=5.00139
  fit=21 full_refit_epoch=2/31 loss=3.84352
  fit=21 full_refit_epoch=3/31 loss=2.85575
  fit=21 full_refit_epoch=4/31 loss=2.04283
  fit=21 full_refit_epoch=5/31 loss=1.40794
  fit=21 full_refit_epoch=6/31 loss=0.96872
  fit=21 full_refit_epoch=7/31 loss=0.64211
  fit=21 full_refit_epoch=8/31 loss=0.45176
  fit=21 full_refit_epoch=9/31 loss=0.31685
  fit=21 full_refit_epoch=10/31 loss=0.21854
  fit=21 full_refit_epoch=11/31 loss=0.17218
  fit=21 full_refit_epoch=12/31 loss=0.13666
  fit=21 full_refit_epoch=13/31 loss=0.10461
  fit=21 full_refit_epoch=14/31 loss=0.08595
  fit=21 full_refit_epoch=15/31 loss=0.07387
  fit=21 full_refit_epoch=16/31 loss=0.06669
  fit=21 full_refit_epoch=17/31 loss=0.05321
  fit=21 full_refit_epoch=18/31 loss=0.05171
  fit=21 full_refit_epoch=19/31 loss=0.04069
  fit=21 full_refit_epoch=20/31 loss=0.03612
  fit=21 full_refit_epoch=21/31 loss=0.03302
  fit=21 full_refit_epoch=22/31 loss=0.03047
  fit=21 full_refit_epoch=23/31 loss=0.02655
  fit=21 full_refit_epoch=24/31 loss=0.02366
  fit=21 full_refit_epoch=25/31 loss=0.02182
  fit=21 full_refit_epoch=26/31 loss=0.02042
  fit=21 full_refit_epoch=27/31 loss=0.01822
  fit=21 full_refit_epoch=28/31 loss=0.01950
  fit=21 full_refit_epoch=29/31 loss=0.01738
  fit=21 full_refit_epoch=30/31 loss=0.01559
  fit=21 full_refit_epoch=31/31 loss=0.01436

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=1/40 loss=4.95998 inner_val_loss=4.68228 inner_val_multiclass_log_loss=4.68235 best_multiclass_log_loss=4.68235 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=2/40 loss=3.77159 inner_val_loss=4.36527 inner_val_multiclass_log_loss=4.36545 best_multiclass_log_loss=4.36545 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=3/40 loss=2.84222 inner_val_loss=4.05057 inner_val_multiclass_log_loss=4.05053 best_multiclass_log_loss=4.05053 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=4/40 loss=2.03547 inner_val_loss=3.79064 inner_val_multiclass_log_loss=3.79062 best_multiclass_log_loss=3.79062 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=5/40 loss=1.44016 inner_val_loss=3.62697 inner_val_multiclass_log_loss=3.62698 best_multiclass_log_loss=3.62698 best_epoch=5 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=6/40 loss=1.01564 inner_val_loss=3.49032 inner_val_multiclass_log_loss=3.49032 best_multiclass_log_loss=3.49032 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=7/40 loss=0.72444 inner_val_loss=3.35060 inner_val_multiclass_log_loss=3.35058 best_multiclass_log_loss=3.35058 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=8/40 loss=0.49946 inner_val_loss=3.28810 inner_val_multiclass_log_loss=3.28817 best_multiclass_log_loss=3.28817 best_epoch=8 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=9/40 loss=0.36389 inner_val_loss=3.24911 inner_val_multiclass_log_loss=3.24917 best_multiclass_log_loss=3.24917 best_epoch=9 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=10/40 loss=0.24461 inner_val_loss=3.16254 inner_val_multiclass_log_loss=3.16260 best_multiclass_log_loss=3.16260 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=11/40 loss=0.18992 inner_val_loss=3.13044 inner_val_multiclass_log_loss=3.13040 best_multiclass_log_loss=3.13040 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=12/40 loss=0.15069 inner_val_loss=3.11354 inner_val_multiclass_log_loss=3.11356 best_multiclass_log_loss=3.11356 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=13/40 loss=0.14095 inner_val_loss=3.07106 inner_val_multiclass_log_loss=3.07114 best_multiclass_log_loss=3.07114 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=14/40 loss=0.11642 inner_val_loss=3.09126 inner_val_multiclass_log_loss=3.09138 best_multiclass_log_loss=3.07114 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=15/40 loss=0.09857 inner_val_loss=2.97833 inner_val_multiclass_log_loss=2.97833 best_multiclass_log_loss=2.97833 best_epoch=15 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=16/40 loss=0.08564 inner_val_loss=2.91931 inner_val_multiclass_log_loss=2.91926 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=17/40 loss=0.06383 inner_val_loss=3.03987 inner_val_multiclass_log_loss=3.03989 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=18/40 loss=0.06642 inner_val_loss=2.98580 inner_val_multiclass_log_loss=2.98585 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=19/40 loss=0.05966 inner_val_loss=2.93723 inner_val_multiclass_log_loss=2.93714 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=20/40 loss=0.06922 inner_val_loss=2.96727 inner_val_multiclass_log_loss=2.96728 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.2
  fit=22 epoch=21/40 loss=0.05367 inner_val_loss=2.98030 inner_val_multiclass_log_loss=2.98028 best_multiclass_log_loss=2.91926 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 full_refit_epoch=1/16 loss=4.94496
  fit=22 full_refit_epoch=2/16 loss=3.75428
  fit=22 full_refit_epoch=3/16 loss=2.76960
  fit=22 full_refit_epoch=4/16 loss=1.97311
  fit=22 full_refit_epoch=5/16 loss=1.36724
  fit=22 full_refit_epoch=6/16 loss=0.94047
  fit=22 full_refit_epoch=7/16 loss=0.64077
  fit=22 full_refit_epoch=8/16 loss=0.42261
  fit=22 full_refit_epoch=9/16 loss=0.28528
  fit=22 full_refit_epoch=10/16 loss=0.21444
  fit=22 full_refit_epoch=11/16 loss=0.16258
  fit=22 full_refit_epoch=12/16 loss=0.12386
  fit=22 full_refit_epoch=13/16 loss=0.10125
  fit=22 full_refit_epoch=14/16 loss=0.08116
  fit=22 full_refit_epoch=15/16 loss=0.07681
  fit=22 full_refit_epoch=16/16 loss=0.06467

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=1/40 loss=5.01382 inner_val_loss=4.83018 inner_val_multiclass_log_loss=4.83014 best_multiclass_log_loss=4.83014 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=2/40 loss=3.87394 inner_val_loss=4.52617 inner_val_multiclass_log_loss=4.52617 best_multiclass_log_loss=4.52617 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=3/40 loss=2.95614 inner_val_loss=4.24006 inner_val_multiclass_log_loss=4.24010 best_multiclass_log_loss=4.24010 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=4/40 loss=2.15813 inner_val_loss=4.04224 inner_val_multiclass_log_loss=4.04221 best_multiclass_log_loss=4.04221 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=5/40 loss=1.55526 inner_val_loss=3.82327 inner_val_multiclass_log_loss=3.82331 best_multiclass_log_loss=3.82331 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=6/40 loss=1.10219 inner_val_loss=3.72264 inner_val_multiclass_log_loss=3.72258 best_multiclass_log_loss=3.72258 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=7/40 loss=0.74562 inner_val_loss=3.53901 inner_val_multiclass_log_loss=3.53902 best_multiclass_log_loss=3.53902 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=8/40 loss=0.54086 inner_val_loss=3.46953 inner_val_multiclass_log_loss=3.46958 best_multiclass_log_loss=3.46958 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=9/40 loss=0.38486 inner_val_loss=3.44521 inner_val_multiclass_log_loss=3.44516 best_multiclass_log_loss=3.44516 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=10/40 loss=0.27137 inner_val_loss=3.41685 inner_val_multiclass_log_loss=3.41685 best_multiclass_log_loss=3.41685 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=11/40 loss=0.22049 inner_val_loss=3.32103 inner_val_multiclass_log_loss=3.32104 best_multiclass_log_loss=3.32104 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=12/40 loss=0.17037 inner_val_loss=3.30205 inner_val_multiclass_log_loss=3.30204 best_multiclass_log_loss=3.30204 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=13/40 loss=0.13642 inner_val_loss=3.27293 inner_val_multiclass_log_loss=3.27300 best_multiclass_log_loss=3.27300 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=14/40 loss=0.10984 inner_val_loss=3.28362 inner_val_multiclass_log_loss=3.28362 best_multiclass_log_loss=3.27300 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=15/40 loss=0.10162 inner_val_loss=3.23432 inner_val_multiclass_log_loss=3.23444 best_multiclass_log_loss=3.23444 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=16/40 loss=0.08316 inner_val_loss=3.22857 inner_val_multiclass_log_loss=3.22860 best_multiclass_log_loss=3.22860 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=17/40 loss=0.07666 inner_val_loss=3.21848 inner_val_multiclass_log_loss=3.21847 best_multiclass_log_loss=3.21847 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=18/40 loss=0.06484 inner_val_loss=3.20966 inner_val_multiclass_log_loss=3.20964 best_multiclass_log_loss=3.20964 best_epoch=18 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=19/40 loss=0.06298 inner_val_loss=3.20902 inner_val_multiclass_log_loss=3.20901 best_multiclass_log_loss=3.20901 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=20/40 loss=0.05495 inner_val_loss=3.20852 inner_val_multiclass_log_loss=3.20846 best_multiclass_log_loss=3.20846 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=21/40 loss=0.04924 inner_val_loss=3.19677 inner_val_multiclass_log_loss=3.19675 best_multiclass_log_loss=3.19675 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=22/40 loss=0.04873 inner_val_loss=3.21843 inner_val_multiclass_log_loss=3.21846 best_multiclass_log_loss=3.19675 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=23/40 loss=0.04317 inner_val_loss=3.13414 inner_val_multiclass_log_loss=3.13417 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=24/40 loss=0.03744 inner_val_loss=3.14222 inner_val_multiclass_log_loss=3.14226 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=25/40 loss=0.03473 inner_val_loss=3.14247 inner_val_multiclass_log_loss=3.14256 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=26/40 loss=0.03297 inner_val_loss=3.18391 inner_val_multiclass_log_loss=3.18390 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=27/40 loss=0.02870 inner_val_loss=3.16270 inner_val_multiclass_log_loss=3.16263 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.3
  fit=23 epoch=28/40 loss=0.02833 inner_val_loss=3.14724 inner_val_multiclass_log_loss=3.14719 best_multiclass_log_loss=3.13417 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 full_refit_epoch=1/23 loss=4.99828
  fit=23 full_refit_epoch=2/23 loss=3.80875
  fit=23 full_refit_epoch=3/23 loss=2.84190
  fit=23 full_refit_epoch=4/23 loss=2.06904
  fit=23 full_refit_epoch=5/23 loss=1.46311
  fit=23 full_refit_epoch=6/23 loss=1.01374
  fit=23 full_refit_epoch=7/23 loss=0.68216
  fit=23 full_refit_epoch=8/23 loss=0.46436
  fit=23 full_refit_epoch=9/23 loss=0.31909
  fit=23 full_refit_epoch=10/23 loss=0.21868
  fit=23 full_refit_epoch=11/23 loss=0.17230
  fit=23 full_refit_epoch=12/23 loss=0.13999
  fit=23 full_refit_epoch=13/23 loss=0.11060
  fit=23 full_refit_epoch=14/23 loss=0.08966
  fit=23 full_refit_epoch=15/23 loss=0.07738
  fit=23 full_refit_epoch=16/23 loss=0.06555
  fit=23 full_refit_epoch=17/23 loss=0.05954
  fit=23 full_refit_epoch=18/23 loss=0.04987
  fit=23 full_refit_epoch=19/23 loss=0.04109
  fit=23 full_refit_epoch=20/23 loss=0.03629
  fit=23 full_refit_epoch=21/23 loss=0.03325
  fit=23 full_refit_epoch=22/23 loss=0.03119
  fit=23 full_refit_epoch=23/23 loss=0.02703

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=1/40 loss=5.01646 inner_val_loss=4.71075 inner_val_multiclass_log_loss=4.71066 best_multiclass_log_loss=4.71066 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=2/40 loss=3.86878 inner_val_loss=4.44417 inner_val_multiclass_log_loss=4.44408 best_multiclass_log_loss=4.44408 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=3/40 loss=2.90752 inner_val_loss=4.14764 inner_val_multiclass_log_loss=4.14766 best_multiclass_log_loss=4.14766 best_epoch=3 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=4/40 loss=2.12866 inner_val_loss=3.94066 inner_val_multiclass_log_loss=3.94066 best_multiclass_log_loss=3.94066 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=5/40 loss=1.49282 inner_val_loss=3.75263 inner_val_multiclass_log_loss=3.75265 best_multiclass_log_loss=3.75265 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=6/40 loss=1.04899 inner_val_loss=3.65415 inner_val_multiclass_log_loss=3.65412 best_multiclass_log_loss=3.65412 best_epoch=6 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=7/40 loss=0.73526 inner_val_loss=3.52214 inner_val_multiclass_log_loss=3.52224 best_multiclass_log_loss=3.52224 best_epoch=7 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=8/40 loss=0.51204 inner_val_loss=3.47120 inner_val_multiclass_log_loss=3.47106 best_multiclass_log_loss=3.47106 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=9/40 loss=0.37281 inner_val_loss=3.40877 inner_val_multiclass_log_loss=3.40885 best_multiclass_log_loss=3.40885 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=10/40 loss=0.27129 inner_val_loss=3.34535 inner_val_multiclass_log_loss=3.34534 best_multiclass_log_loss=3.34534 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=11/40 loss=0.21211 inner_val_loss=3.29210 inner_val_multiclass_log_loss=3.29214 best_multiclass_log_loss=3.29214 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=12/40 loss=0.15904 inner_val_loss=3.29345 inner_val_multiclass_log_loss=3.29349 best_multiclass_log_loss=3.29214 best_epoch=11 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=13/40 loss=0.13538 inner_val_loss=3.28735 inner_val_multiclass_log_loss=3.28731 best_multiclass_log_loss=3.28731 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=14/40 loss=0.10630 inner_val_loss=3.27568 inner_val_multiclass_log_loss=3.27573 best_multiclass_log_loss=3.27573 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=15/40 loss=0.09940 inner_val_loss=3.21260 inner_val_multiclass_log_loss=3.21262 best_multiclass_log_loss=3.21262 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=16/40 loss=0.07787 inner_val_loss=3.18888 inner_val_multiclass_log_loss=3.18890 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=17/40 loss=0.07906 inner_val_loss=3.19307 inner_val_multiclass_log_loss=3.19307 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=18/40 loss=0.07204 inner_val_loss=3.19766 inner_val_multiclass_log_loss=3.19763 best_multiclass_log_loss=3.18890 best_epoch=16 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=19/40 loss=0.05085 inner_val_loss=3.18384 inner_val_multiclass_log_loss=3.18378 best_multiclass_log_loss=3.18378 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=20/40 loss=0.05369 inner_val_loss=3.15567 inner_val_multiclass_log_loss=3.15569 best_multiclass_log_loss=3.15569 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=21/40 loss=0.04779 inner_val_loss=3.12405 inner_val_multiclass_log_loss=3.12414 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=22/40 loss=0.04556 inner_val_loss=3.13617 inner_val_multiclass_log_loss=3.13619 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=23/40 loss=0.04344 inner_val_loss=3.14193 inner_val_multiclass_log_loss=3.14200 best_multiclass_log_loss=3.12414 best_epoch=21 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=24/40 loss=0.04373 inner_val_loss=3.11872 inner_val_multiclass_log_loss=3.11861 best_multiclass_log_loss=3.11861 best_epoch=24 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=25/40 loss=0.04615 inner_val_loss=3.12620 inner_val_multiclass_log_loss=3.12624 best_multiclass_log_loss=3.11861 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=26/40 loss=0.03264 inner_val_loss=3.11736 inner_val_multiclass_log_loss=3.11731 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=27/40 loss=0.03728 inner_val_loss=3.12765 inner_val_multiclass_log_loss=3.12767 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=28/40 loss=0.04057 inner_val_loss=3.12603 inner_val_multiclass_log_loss=3.12602 best_multiclass_log_loss=3.11731 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=29/40 loss=0.03249 inner_val_loss=3.11357 inner_val_multiclass_log_loss=3.11362 best_multiclass_log_loss=3.11362 best_epoch=29 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=30/40 loss=0.02746 inner_val_loss=3.11732 inner_val_multiclass_log_loss=3.11734 best_multiclass_log_loss=3.11362 best_epoch=29 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=31/40 loss=0.03100 inner_val_loss=3.07322 inner_val_multiclass_log_loss=3.07311 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=32/40 loss=0.02220 inner_val_loss=3.16694 inner_val_multiclass_log_loss=3.16686 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=33/40 loss=0.02371 inner_val_loss=3.12590 inner_val_multiclass_log_loss=3.12598 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=34/40 loss=0.02350 inner_val_loss=3.13255 inner_val_multiclass_log_loss=3.13257 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=35/40 loss=0.02824 inner_val_loss=3.09367 inner_val_multiclass_log_loss=3.09369 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2
  fit=24 epoch=36/40 loss=0.01611 inner_val_loss=3.10682 inner_val_multiclass_log_loss=3.10694 best_multiclass_log_loss=3.07311 best_epoch=31 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 full_refit_epoch=1/31 loss=4.99808
  fit=24 full_refit_epoch=2/31 loss=3.82919
  fit=24 full_refit_epoch=3/31 loss=2.85763
  fit=24 full_refit_epoch=4/31 loss=2.06057
  fit=24 full_refit_epoch=5/31 loss=1.40719
  fit=24 full_refit_epoch=6/31 loss=0.97243
  fit=24 full_refit_epoch=7/31 loss=0.65619
  fit=24 full_refit_epoch=8/31 loss=0.44680
  fit=24 full_refit_epoch=9/31 loss=0.30461
  fit=24 full_refit_epoch=10/31 loss=0.22077
  fit=24 full_refit_epoch=11/31 loss=0.16654
  fit=24 full_refit_epoch=12/31 loss=0.12618
  fit=24 full_refit_epoch=13/31 loss=0.10949
  fit=24 full_refit_epoch=14/31 loss=0.08700
  fit=24 full_refit_epoch=15/31 loss=0.07265
  fit=24 full_refit_epoch=16/31 loss=0.06093
  fit=24 full_refit_epoch=17/31 loss=0.05244
  fit=24 full_refit_epoch=18/31 loss=0.05046
  fit=24 full_refit_epoch=19/31 loss=0.04169
  fit=24 full_refit_epoch=20/31 loss=0.03818
  fit=24 full_refit_epoch=21/31 loss=0.03367
  fit=24 full_refit_epoch=22/31 loss=0.03204
  fit=24 full_refit_epoch=23/31 loss=0.02956
  fit=24 full_refit_epoch=24/31 loss=0.02457
  fit=24 full_refit_epoch=25/31 loss=0.02339
  fit=24 full_refit_epoch=26/31 loss=0.02060
  fit=24 full_refit_epoch=27/31 loss=0.02051
  fit=24 full_refit_epoch=28/31 loss=0.01922
  fit=24 full_refit_epoch=29/31 loss=0.01719
  fit=24 full_refit_epoch=30/31 loss=0.01478
  fit=24 full_refit_epoch=31/31 loss=0.01511

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=1/40 loss=5.04749 inner_val_loss=4.81871 inner_val_multiclass_log_loss=4.81872 best_multiclass_log_loss=4.81872 best_epoch=1 seconds=3.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=2/40 loss=3.88437 inner_val_loss=4.47669 inner_val_multiclass_log_loss=4.47663 best_multiclass_log_loss=4.47663 best_epoch=2 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=3/40 loss=2.93474 inner_val_loss=4.15286 inner_val_multiclass_log_loss=4.15279 best_multiclass_log_loss=4.15279 best_epoch=3 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=4/40 loss=2.14449 inner_val_loss=3.83851 inner_val_multiclass_log_loss=3.83856 best_multiclass_log_loss=3.83856 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=5/40 loss=1.51164 inner_val_loss=3.63070 inner_val_multiclass_log_loss=3.63065 best_multiclass_log_loss=3.63065 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=6/40 loss=1.04807 inner_val_loss=3.45205 inner_val_multiclass_log_loss=3.45202 best_multiclass_log_loss=3.45202 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=7/40 loss=0.73374 inner_val_loss=3.31202 inner_val_multiclass_log_loss=3.31200 best_multiclass_log_loss=3.31200 best_epoch=7 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=8/40 loss=0.51416 inner_val_loss=3.22684 inner_val_multiclass_log_loss=3.22686 best_multiclass_log_loss=3.22686 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=9/40 loss=0.35244 inner_val_loss=3.17807 inner_val_multiclass_log_loss=3.17811 best_multiclass_log_loss=3.17811 best_epoch=9 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=10/40 loss=0.26490 inner_val_loss=3.14070 inner_val_multiclass_log_loss=3.14074 best_multiclass_log_loss=3.14074 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=11/40 loss=0.20512 inner_val_loss=3.08093 inner_val_multiclass_log_loss=3.08100 best_multiclass_log_loss=3.08100 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=12/40 loss=0.17152 inner_val_loss=3.03603 inner_val_multiclass_log_loss=3.03605 best_multiclass_log_loss=3.03605 best_epoch=12 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=13/40 loss=0.13419 inner_val_loss=3.00439 inner_val_multiclass_log_loss=3.00439 best_multiclass_log_loss=3.00439 best_epoch=13 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=14/40 loss=0.11156 inner_val_loss=2.97015 inner_val_multiclass_log_loss=2.97018 best_multiclass_log_loss=2.97018 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=15/40 loss=0.09839 inner_val_loss=2.98986 inner_val_multiclass_log_loss=2.98977 best_multiclass_log_loss=2.97018 best_epoch=14 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=16/40 loss=0.08324 inner_val_loss=2.95076 inner_val_multiclass_log_loss=2.95078 best_multiclass_log_loss=2.95078 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=17/40 loss=0.07261 inner_val_loss=2.92277 inner_val_multiclass_log_loss=2.92280 best_multiclass_log_loss=2.92280 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=18/40 loss=0.06728 inner_val_loss=2.90194 inner_val_multiclass_log_loss=2.90186 best_multiclass_log_loss=2.90186 best_epoch=18 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=19/40 loss=0.06306 inner_val_loss=2.92565 inner_val_multiclass_log_loss=2.92568 best_multiclass_log_loss=2.90186 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=20/40 loss=0.05421 inner_val_loss=2.87176 inner_val_multiclass_log_loss=2.87173 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=21/40 loss=0.05061 inner_val_loss=2.87800 inner_val_multiclass_log_loss=2.87795 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=22/40 loss=0.04280 inner_val_loss=2.87844 inner_val_multiclass_log_loss=2.87854 best_multiclass_log_loss=2.87173 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=23/40 loss=0.04317 inner_val_loss=2.85119 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=24/40 loss=0.03681 inner_val_loss=2.86261 inner_val_multiclass_log_loss=2.86248 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=25/40 loss=0.03759 inner_val_loss=2.86437 inner_val_multiclass_log_loss=2.86436 best_multiclass_log_loss=2.85113 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=26/40 loss=0.03727 inner_val_loss=2.84264 inner_val_multiclass_log_loss=2.84256 best_multiclass_log_loss=2.84256 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=27/40 loss=0.04750 inner_val_loss=2.78905 inner_val_multiclass_log_loss=2.78899 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=28/40 loss=0.02953 inner_val_loss=2.85267 inner_val_multiclass_log_loss=2.85263 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=29/40 loss=0.02476 inner_val_loss=2.85039 inner_val_multiclass_log_loss=2.85031 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=30/40 loss=0.04091 inner_val_loss=2.82130 inner_val_multiclass_log_loss=2.82136 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=31/40 loss=0.02443 inner_val_loss=2.81061 inner_val_multiclass_log_loss=2.81065 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.0
  fit=25 epoch=32/40 loss=0.02234 inner_val_loss=2.85927 inner_val_multiclass_log_loss=2.85927 best_multiclass_log_loss=2.78899 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 full_refit_epoch=1/27 loss=5.01707
  fit=25 full_refit_epoch=2/27 loss=3.83853
  fit=25 full_refit_epoch=3/27 loss=2.83950
  fit=25 full_refit_epoch=4/27 loss=2.01059
  fit=25 full_refit_epoch=5/27 loss=1.42550
  fit=25 full_refit_epoch=6/27 loss=0.96100
  fit=25 full_refit_epoch=7/27 loss=0.63852
  fit=25 full_refit_epoch=8/27 loss=0.43575
  fit=25 full_refit_epoch=9/27 loss=0.29530
  fit=25 full_refit_epoch=10/27 loss=0.21542
  fit=25 full_refit_epoch=11/27 loss=0.16594
  fit=25 full_refit_epoch=12/27 loss=0.12619
  fit=25 full_refit_epoch=13/27 loss=0.10692
  fit=25 full_refit_epoch=14/27 loss=0.08452
  fit=25 full_refit_epoch=15/27 loss=0.07949
  fit=25 full_refit_epoch=16/27 loss=0.06535
  fit=25 full_refit_epoch=17/27 loss=0.05278
  fit=25 full_refit_epoch=18/27 loss=0.04622
  fit=25 full_refit_epoch=19/27 loss=0.04249
  fit=25 full_refit_epoch=20/27 loss=0.03969
  fit=25 full_refit_epoch=21/27 loss=0.03237
  fit=25 full_refit_epoch=22/27 loss=0.03002
  fit=25 full_refit_epoch=23/27 loss=0.02576
  fit=25 full_refit_epoch=24/27 loss=0.02408
  fit=25 full_refit_epoch=25/27 loss=0.02292
  fit=25 full_refit_epoch=26/27 loss=0.02128
  fit=25 full_refit_epoch=27/27 loss=0.02029

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=refinement model=efficientnet_b0 metric=2.9845033042486517 error=None minutes=14.69
START seed=29 phase=refined_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=1/40 loss=4.79144 inner_val_loss=4.76133 inner_val_multiclass_log_loss=4.76143 best_multiclass_log_loss=4.76143 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=2/40 loss=4.62554 inner_val_loss=4.70355 inner_val_multiclass_log_loss=4.70364 best_multiclass_log_loss=4.70364 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=3/40 loss=4.45690 inner_val_loss=4.61165 inner_val_multiclass_log_loss=4.61160 best_multiclass_log_loss=4.61160 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=4/40 loss=4.26439 inner_val_loss=4.48426 inner_val_multiclass_log_loss=4.48426 best_multiclass_log_loss=4.48426 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=5/40 loss=4.04628 inner_val_loss=4.35704 inner_val_multiclass_log_loss=4.35702 best_multiclass_log_loss=4.35702 best_epoch=5 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=6/40 loss=3.82694 inner_val_loss=4.22893 inner_val_multiclass_log_loss=4.22889 best_multiclass_log_loss=4.22889 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=7/40 loss=3.58612 inner_val_loss=4.09031 inner_val_multiclass_log_loss=4.09028 best_multiclass_log_loss=4.09028 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=8/40 loss=3.37138 inner_val_loss=3.92341 inner_val_multiclass_log_loss=3.92337 best_multiclass_log_loss=3.92337 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=9/40 loss=3.16131 inner_val_loss=3.84799 inner_val_multiclass_log_loss=3.84804 best_multiclass_log_loss=3.84804 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=10/40 loss=2.93246 inner_val_loss=3.68492 inner_val_multiclass_log_loss=3.68490 best_multiclass_log_loss=3.68490 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=11/40 loss=2.71793 inner_val_loss=3.61770 inner_val_multiclass_log_loss=3.61779 best_multiclass_log_loss=3.61779 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=12/40 loss=2.51520 inner_val_loss=3.50337 inner_val_multiclass_log_loss=3.50331 best_multiclass_log_loss=3.50331 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=13/40 loss=2.31603 inner_val_loss=3.38420 inner_val_multiclass_log_loss=3.38421 best_multiclass_log_loss=3.38421 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=14/40 loss=2.13215 inner_val_loss=3.33402 inner_val_multiclass_log_loss=3.33402 best_multiclass_log_loss=3.33402 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=15/40 loss=1.94203 inner_val_loss=3.19962 inner_val_multiclass_log_loss=3.19959 best_multiclass_log_loss=3.19959 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=16/40 loss=1.77130 inner_val_loss=3.11036 inner_val_multiclass_log_loss=3.11039 best_multiclass_log_loss=3.11039 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=17/40 loss=1.61756 inner_val_loss=3.06941 inner_val_multiclass_log_loss=3.06935 best_multiclass_log_loss=3.06935 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=18/40 loss=1.46287 inner_val_loss=3.01414 inner_val_multiclass_log_loss=3.01415 best_multiclass_log_loss=3.01415 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=19/40 loss=1.31347 inner_val_loss=2.99891 inner_val_multiclass_log_loss=2.99883 best_multiclass_log_loss=2.99883 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=20/40 loss=1.18822 inner_val_loss=2.92087 inner_val_multiclass_log_loss=2.92080 best_multiclass_log_loss=2.92080 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=21/40 loss=1.05517 inner_val_loss=2.88822 inner_val_multiclass_log_loss=2.88816 best_multiclass_log_loss=2.88816 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=22/40 loss=0.95697 inner_val_loss=2.83501 inner_val_multiclass_log_loss=2.83497 best_multiclass_log_loss=2.83497 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=23/40 loss=0.87262 inner_val_loss=2.77049 inner_val_multiclass_log_loss=2.77046 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=24/40 loss=0.76393 inner_val_loss=2.77348 inner_val_multiclass_log_loss=2.77354 best_multiclass_log_loss=2.77046 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=25/40 loss=0.68706 inner_val_loss=2.76672 inner_val_multiclass_log_loss=2.76677 best_multiclass_log_loss=2.76677 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=26/40 loss=0.61515 inner_val_loss=2.71639 inner_val_multiclass_log_loss=2.71637 best_multiclass_log_loss=2.71637 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=27/40 loss=0.52934 inner_val_loss=2.71243 inner_val_multiclass_log_loss=2.71235 best_multiclass_log_loss=2.71235 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=28/40 loss=0.48928 inner_val_loss=2.68442 inner_val_multiclass_log_loss=2.68437 best_multiclass_log_loss=2.68437 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=29/40 loss=0.43681 inner_val_loss=2.63053 inner_val_multiclass_log_loss=2.63058 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=30/40 loss=0.37328 inner_val_loss=2.72091 inner_val_multiclass_log_loss=2.72089 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=31/40 loss=0.33404 inner_val_loss=2.66172 inner_val_multiclass_log_loss=2.66172 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=32/40 loss=0.30090 inner_val_loss=2.67711 inner_val_multiclass_log_loss=2.67710 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=33/40 loss=0.26609 inner_val_loss=2.64585 inner_val_multiclass_log_loss=2.64582 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1
  fit=26 epoch=34/40 loss=0.23828 inner_val_loss=2.65238 inner_val_multiclass_log_loss=2.65240 best_multiclass_log_loss=2.63058 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 full_refit_epoch=1/29 loss=4.78822
  fit=26 full_refit_epoch=2/29 loss=4.61409
  fit=26 full_refit_epoch=3/29 loss=4.43218
  fit=26 full_refit_epoch=4/29 loss=4.22360
  fit=26 full_refit_epoch=5/29 loss=3.98506
  fit=26 full_refit_epoch=6/29 loss=3.73938
  fit=26 full_refit_epoch=7/29 loss=3.49234
  fit=26 full_refit_epoch=8/29 loss=3.25799
  fit=26 full_refit_epoch=9/29 loss=3.02037
  fit=26 full_refit_epoch=10/29 loss=2.77619
  fit=26 full_refit_epoch=11/29 loss=2.57066
  fit=26 full_refit_epoch=12/29 loss=2.35277
  fit=26 full_refit_epoch=13/29 loss=2.14352
  fit=26 full_refit_epoch=14/29 loss=1.95123
  fit=26 full_refit_epoch=15/29 loss=1.76259
  fit=26 full_refit_epoch=16/29 loss=1.60713
  fit=26 full_refit_epoch=17/29 loss=1.43215
  fit=26 full_refit_epoch=18/29 loss=1.30671
  fit=26 full_refit_epoch=19/29 loss=1.15336
  fit=26 full_refit_epoch=20/29 loss=1.02409
  fit=26 full_refit_epoch=21/29 loss=0.90996
  fit=26 full_refit_epoch=22/29 loss=0.80927
  fit=26 full_refit_epoch=23/29 loss=0.70711
  fit=26 full_refit_epoch=24/29 loss=0.62528
  fit=26 full_refit_epoch=25/29 loss=0.54107
  fit=26 full_refit_epoch=26/29 loss=0.48100
  fit=26 full_refit_epoch=27/29 loss=0.41610
  fit=26 full_refit_epoch=28/29 loss=0.37348
  fit=26 full_refit_epoch=29/29 loss=0.32870

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=1/40 loss=4.77688 inner_val_loss=4.73210 inner_val_multiclass_log_loss=4.73224 best_multiclass_log_loss=4.73224 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=2/40 loss=4.60466 inner_val_loss=4.64713 inner_val_multiclass_log_loss=4.64698 best_multiclass_log_loss=4.64698 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=3/40 loss=4.43182 inner_val_loss=4.56443 inner_val_multiclass_log_loss=4.56453 best_multiclass_log_loss=4.56453 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=4/40 loss=4.24171 inner_val_loss=4.41614 inner_val_multiclass_log_loss=4.41620 best_multiclass_log_loss=4.41620 best_epoch=4 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=5/40 loss=4.02471 inner_val_loss=4.28676 inner_val_multiclass_log_loss=4.28664 best_multiclass_log_loss=4.28664 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=6/40 loss=3.79899 inner_val_loss=4.12236 inner_val_multiclass_log_loss=4.12235 best_multiclass_log_loss=4.12235 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=7/40 loss=3.57838 inner_val_loss=3.96545 inner_val_multiclass_log_loss=3.96543 best_multiclass_log_loss=3.96543 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=8/40 loss=3.32654 inner_val_loss=3.81237 inner_val_multiclass_log_loss=3.81239 best_multiclass_log_loss=3.81239 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=9/40 loss=3.10657 inner_val_loss=3.74201 inner_val_multiclass_log_loss=3.74201 best_multiclass_log_loss=3.74201 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=10/40 loss=2.88596 inner_val_loss=3.58560 inner_val_multiclass_log_loss=3.58566 best_multiclass_log_loss=3.58566 best_epoch=10 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=11/40 loss=2.65791 inner_val_loss=3.46592 inner_val_multiclass_log_loss=3.46595 best_multiclass_log_loss=3.46595 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=12/40 loss=2.44689 inner_val_loss=3.35923 inner_val_multiclass_log_loss=3.35918 best_multiclass_log_loss=3.35918 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=13/40 loss=2.27432 inner_val_loss=3.24337 inner_val_multiclass_log_loss=3.24334 best_multiclass_log_loss=3.24334 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=14/40 loss=2.07651 inner_val_loss=3.14473 inner_val_multiclass_log_loss=3.14488 best_multiclass_log_loss=3.14488 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=15/40 loss=1.89470 inner_val_loss=3.06804 inner_val_multiclass_log_loss=3.06804 best_multiclass_log_loss=3.06804 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=16/40 loss=1.73623 inner_val_loss=2.95022 inner_val_multiclass_log_loss=2.95029 best_multiclass_log_loss=2.95029 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=17/40 loss=1.55428 inner_val_loss=2.92689 inner_val_multiclass_log_loss=2.92689 best_multiclass_log_loss=2.92689 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=18/40 loss=1.41175 inner_val_loss=2.82146 inner_val_multiclass_log_loss=2.82155 best_multiclass_log_loss=2.82155 best_epoch=18 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=19/40 loss=1.26964 inner_val_loss=2.72490 inner_val_multiclass_log_loss=2.72484 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=20/40 loss=1.16999 inner_val_loss=2.75291 inner_val_multiclass_log_loss=2.75287 best_multiclass_log_loss=2.72484 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=21/40 loss=1.03966 inner_val_loss=2.67443 inner_val_multiclass_log_loss=2.67446 best_multiclass_log_loss=2.67446 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=22/40 loss=0.91439 inner_val_loss=2.60952 inner_val_multiclass_log_loss=2.60943 best_multiclass_log_loss=2.60943 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=23/40 loss=0.83581 inner_val_loss=2.58285 inner_val_multiclass_log_loss=2.58288 best_multiclass_log_loss=2.58288 best_epoch=23 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=24/40 loss=0.74141 inner_val_loss=2.53561 inner_val_multiclass_log_loss=2.53560 best_multiclass_log_loss=2.53560 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=25/40 loss=0.66409 inner_val_loss=2.50372 inner_val_multiclass_log_loss=2.50371 best_multiclass_log_loss=2.50371 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=26/40 loss=0.57358 inner_val_loss=2.47309 inner_val_multiclass_log_loss=2.47307 best_multiclass_log_loss=2.47307 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=27/40 loss=0.50854 inner_val_loss=2.45066 inner_val_multiclass_log_loss=2.45066 best_multiclass_log_loss=2.45066 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=28/40 loss=0.45707 inner_val_loss=2.44689 inner_val_multiclass_log_loss=2.44685 best_multiclass_log_loss=2.44685 best_epoch=28 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=29/40 loss=0.40134 inner_val_loss=2.42541 inner_val_multiclass_log_loss=2.42539 best_multiclass_log_loss=2.42539 best_epoch=29 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=30/40 loss=0.36173 inner_val_loss=2.41848 inner_val_multiclass_log_loss=2.41857 best_multiclass_log_loss=2.41857 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=31/40 loss=0.31615 inner_val_loss=2.38013 inner_val_multiclass_log_loss=2.38011 best_multiclass_log_loss=2.38011 best_epoch=31 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=32/40 loss=0.28382 inner_val_loss=2.37641 inner_val_multiclass_log_loss=2.37642 best_multiclass_log_loss=2.37642 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=33/40 loss=0.26356 inner_val_loss=2.36904 inner_val_multiclass_log_loss=2.36903 best_multiclass_log_loss=2.36903 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=34/40 loss=0.23373 inner_val_loss=2.36645 inner_val_multiclass_log_loss=2.36651 best_multiclass_log_loss=2.36651 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=35/40 loss=0.21890 inner_val_loss=2.35982 inner_val_multiclass_log_loss=2.35984 best_multiclass_log_loss=2.35984 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=36/40 loss=0.18600 inner_val_loss=2.35639 inner_val_multiclass_log_loss=2.35638 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=37/40 loss=0.17461 inner_val_loss=2.36209 inner_val_multiclass_log_loss=2.36213 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=38/40 loss=0.14695 inner_val_loss=2.36564 inner_val_multiclass_log_loss=2.36560 best_multiclass_log_loss=2.35638 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=39/40 loss=0.13963 inner_val_loss=2.32751 inner_val_multiclass_log_loss=2.32756 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1
  fit=27 epoch=40/40 loss=0.13450 inner_val_loss=2.34288 inner_val_multiclass_log_loss=2.34286 best_multiclass_log_loss=2.32756 best_epoch=39 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 full_refit_epoch=1/39 loss=4.77703
  fit=27 full_refit_epoch=2/39 loss=4.58965
  fit=27 full_refit_epoch=3/39 loss=4.40609
  fit=27 full_refit_epoch=4/39 loss=4.18434
  fit=27 full_refit_epoch=5/39 loss=3.94119
  fit=27 full_refit_epoch=6/39 loss=3.68977
  fit=27 full_refit_epoch=7/39 loss=3.44150
  fit=27 full_refit_epoch=8/39 loss=3.18243
  fit=27 full_refit_epoch=9/39 loss=2.94295
  fit=27 full_refit_epoch=10/39 loss=2.70540
  fit=27 full_refit_epoch=11/39 loss=2.47803
  fit=27 full_refit_epoch=12/39 loss=2.26517
  fit=27 full_refit_epoch=13/39 loss=2.05341
  fit=27 full_refit_epoch=14/39 loss=1.86164
  fit=27 full_refit_epoch=15/39 loss=1.71295
  fit=27 full_refit_epoch=16/39 loss=1.52613
  fit=27 full_refit_epoch=17/39 loss=1.34509
  fit=27 full_refit_epoch=18/39 loss=1.22839
  fit=27 full_refit_epoch=19/39 loss=1.07973
  fit=27 full_refit_epoch=20/39 loss=0.97077
  fit=27 full_refit_epoch=21/39 loss=0.85544
  fit=27 full_refit_epoch=22/39 loss=0.74625
  fit=27 full_refit_epoch=23/39 loss=0.66027
  fit=27 full_refit_epoch=24/39 loss=0.57647
  fit=27 full_refit_epoch=25/39 loss=0.50676
  fit=27 full_refit_epoch=26/39 loss=0.45746
  fit=27 full_refit_epoch=27/39 loss=0.38876
  fit=27 full_refit_epoch=28/39 loss=0.35025
  fit=27 full_refit_epoch=29/39 loss=0.29588
  fit=27 full_refit_epoch=30/39 loss=0.27610
  fit=27 full_refit_epoch=31/39 loss=0.23597
  fit=27 full_refit_epoch=32/39 loss=0.21136
  fit=27 full_refit_epoch=33/39 loss=0.18650
  fit=27 full_refit_epoch=34/39 loss=0.17262
  fit=27 full_refit_epoch=35/39 loss=0.14920
  fit=27 full_refit_epoch=36/39 loss=0.13083
  fit=27 full_refit_epoch=37/39 loss=0.11639
  fit=27 full_refit_epoch=38/39 loss=0.10687
  fit=27 full_refit_epoch=39/39 loss=0.09848

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=1/40 loss=4.78788 inner_val_loss=4.73453 inner_val_multiclass_log_loss=4.73440 best_multiclass_log_loss=4.73440 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=2/40 loss=4.62429 inner_val_loss=4.65916 inner_val_multiclass_log_loss=4.65916 best_multiclass_log_loss=4.65916 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=3/40 loss=4.46878 inner_val_loss=4.56776 inner_val_multiclass_log_loss=4.56775 best_multiclass_log_loss=4.56775 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=4/40 loss=4.28168 inner_val_loss=4.46579 inner_val_multiclass_log_loss=4.46588 best_multiclass_log_loss=4.46588 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=5/40 loss=4.08050 inner_val_loss=4.29853 inner_val_multiclass_log_loss=4.29854 best_multiclass_log_loss=4.29854 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=6/40 loss=3.86685 inner_val_loss=4.14481 inner_val_multiclass_log_loss=4.14487 best_multiclass_log_loss=4.14487 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=7/40 loss=3.62955 inner_val_loss=3.99955 inner_val_multiclass_log_loss=3.99964 best_multiclass_log_loss=3.99964 best_epoch=7 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=8/40 loss=3.40460 inner_val_loss=3.84375 inner_val_multiclass_log_loss=3.84382 best_multiclass_log_loss=3.84382 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=9/40 loss=3.17732 inner_val_loss=3.75653 inner_val_multiclass_log_loss=3.75648 best_multiclass_log_loss=3.75648 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=10/40 loss=2.95777 inner_val_loss=3.55647 inner_val_multiclass_log_loss=3.55653 best_multiclass_log_loss=3.55653 best_epoch=10 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=11/40 loss=2.73494 inner_val_loss=3.48144 inner_val_multiclass_log_loss=3.48145 best_multiclass_log_loss=3.48145 best_epoch=11 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=12/40 loss=2.52807 inner_val_loss=3.36669 inner_val_multiclass_log_loss=3.36679 best_multiclass_log_loss=3.36679 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=13/40 loss=2.32670 inner_val_loss=3.23321 inner_val_multiclass_log_loss=3.23324 best_multiclass_log_loss=3.23324 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=14/40 loss=2.14211 inner_val_loss=3.13339 inner_val_multiclass_log_loss=3.13334 best_multiclass_log_loss=3.13334 best_epoch=14 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=15/40 loss=1.97379 inner_val_loss=2.99862 inner_val_multiclass_log_loss=2.99856 best_multiclass_log_loss=2.99856 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=16/40 loss=1.79112 inner_val_loss=2.95137 inner_val_multiclass_log_loss=2.95135 best_multiclass_log_loss=2.95135 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=17/40 loss=1.64030 inner_val_loss=2.85254 inner_val_multiclass_log_loss=2.85257 best_multiclass_log_loss=2.85257 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=18/40 loss=1.47695 inner_val_loss=2.79063 inner_val_multiclass_log_loss=2.79060 best_multiclass_log_loss=2.79060 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=19/40 loss=1.34568 inner_val_loss=2.71051 inner_val_multiclass_log_loss=2.71048 best_multiclass_log_loss=2.71048 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=20/40 loss=1.20112 inner_val_loss=2.69370 inner_val_multiclass_log_loss=2.69368 best_multiclass_log_loss=2.69368 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=21/40 loss=1.08037 inner_val_loss=2.65799 inner_val_multiclass_log_loss=2.65796 best_multiclass_log_loss=2.65796 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=22/40 loss=0.98182 inner_val_loss=2.59564 inner_val_multiclass_log_loss=2.59567 best_multiclass_log_loss=2.59567 best_epoch=22 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=23/40 loss=0.87696 inner_val_loss=2.57080 inner_val_multiclass_log_loss=2.57078 best_multiclass_log_loss=2.57078 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=24/40 loss=0.77895 inner_val_loss=2.49865 inner_val_multiclass_log_loss=2.49860 best_multiclass_log_loss=2.49860 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=25/40 loss=0.69952 inner_val_loss=2.48903 inner_val_multiclass_log_loss=2.48896 best_multiclass_log_loss=2.48896 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=26/40 loss=0.62977 inner_val_loss=2.48067 inner_val_multiclass_log_loss=2.48063 best_multiclass_log_loss=2.48063 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=27/40 loss=0.54283 inner_val_loss=2.44089 inner_val_multiclass_log_loss=2.44091 best_multiclass_log_loss=2.44091 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=28/40 loss=0.48600 inner_val_loss=2.42942 inner_val_multiclass_log_loss=2.42940 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=29/40 loss=0.43038 inner_val_loss=2.44990 inner_val_multiclass_log_loss=2.44988 best_multiclass_log_loss=2.42940 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=30/40 loss=0.38295 inner_val_loss=2.40124 inner_val_multiclass_log_loss=2.40129 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=31/40 loss=0.34102 inner_val_loss=2.42409 inner_val_multiclass_log_loss=2.42413 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=32/40 loss=0.29692 inner_val_loss=2.40238 inner_val_multiclass_log_loss=2.40230 best_multiclass_log_loss=2.40129 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=33/40 loss=0.26235 inner_val_loss=2.34556 inner_val_multiclass_log_loss=2.34554 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=34/40 loss=0.24309 inner_val_loss=2.37027 inner_val_multiclass_log_loss=2.37025 best_multiclass_log_loss=2.34554 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=35/40 loss=0.21402 inner_val_loss=2.33308 inner_val_multiclass_log_loss=2.33300 best_multiclass_log_loss=2.33300 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=36/40 loss=0.18834 inner_val_loss=2.32832 inner_val_multiclass_log_loss=2.32835 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=37/40 loss=0.17150 inner_val_loss=2.33830 inner_val_multiclass_log_loss=2.33827 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=38/40 loss=0.16646 inner_val_loss=2.34553 inner_val_multiclass_log_loss=2.34549 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=39/40 loss=0.14529 inner_val_loss=2.35859 inner_val_multiclass_log_loss=2.35854 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1
  fit=28 epoch=40/40 loss=0.12740 inner_val_loss=2.36939 inner_val_multiclass_log_loss=2.36934 best_multiclass_log_loss=2.32835 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 full_refit_epoch=1/36 loss=4.78174
  fit=28 full_refit_epoch=2/36 loss=4.61084
  fit=28 full_refit_epoch=3/36 loss=4.43466
  fit=28 full_refit_epoch=4/36 loss=4.23122
  fit=28 full_refit_epoch=5/36 loss=4.00552
  fit=28 full_refit_epoch=6/36 loss=3.76720
  fit=28 full_refit_epoch=7/36 loss=3.51458
  fit=28 full_refit_epoch=8/36 loss=3.27506
  fit=28 full_refit_epoch=9/36 loss=3.02642
  fit=28 full_refit_epoch=10/36 loss=2.79304
  fit=28 full_refit_epoch=11/36 loss=2.57939
  fit=28 full_refit_epoch=12/36 loss=2.36072
  fit=28 full_refit_epoch=13/36 loss=2.15404
  fit=28 full_refit_epoch=14/36 loss=1.96215
  fit=28 full_refit_epoch=15/36 loss=1.78668
  fit=28 full_refit_epoch=16/36 loss=1.61511
  fit=28 full_refit_epoch=17/36 loss=1.45979
  fit=28 full_refit_epoch=18/36 loss=1.30436
  fit=28 full_refit_epoch=19/36 loss=1.17129
  fit=28 full_refit_epoch=20/36 loss=1.03604
  fit=28 full_refit_epoch=21/36 loss=0.93486
  fit=28 full_refit_epoch=22/36 loss=0.82323
  fit=28 full_refit_epoch=23/36 loss=0.73781
  fit=28 full_refit_epoch=24/36 loss=0.63958
  fit=28 full_refit_epoch=25/36 loss=0.55612
  fit=28 full_refit_epoch=26/36 loss=0.49764
  fit=28 full_refit_epoch=27/36 loss=0.43395
  fit=28 full_refit_epoch=28/36 loss=0.38153
  fit=28 full_refit_epoch=29/36 loss=0.33402
  fit=28 full_refit_epoch=30/36 loss=0.29779
  fit=28 full_refit_epoch=31/36 loss=0.26630
  fit=28 full_refit_epoch=32/36 loss=0.23283
  fit=28 full_refit_epoch=33/36 loss=0.20140
  fit=28 full_refit_epoch=34/36 loss=0.18013
  fit=28 full_refit_epoch=35/36 loss=0.16015
  fit=28 full_refit_epoch=36/36 loss=0.15038

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=1/40 loss=4.78972 inner_val_loss=4.78068 inner_val_multiclass_log_loss=4.78091 best_multiclass_log_loss=4.78091 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=2/40 loss=4.61644 inner_val_loss=4.70122 inner_val_multiclass_log_loss=4.70113 best_multiclass_log_loss=4.70113 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=3/40 loss=4.45221 inner_val_loss=4.62067 inner_val_multiclass_log_loss=4.62064 best_multiclass_log_loss=4.62064 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=4/40 loss=4.27089 inner_val_loss=4.47619 inner_val_multiclass_log_loss=4.47618 best_multiclass_log_loss=4.47618 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=5/40 loss=4.06268 inner_val_loss=4.36162 inner_val_multiclass_log_loss=4.36158 best_multiclass_log_loss=4.36158 best_epoch=5 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=6/40 loss=3.84209 inner_val_loss=4.26205 inner_val_multiclass_log_loss=4.26196 best_multiclass_log_loss=4.26196 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=7/40 loss=3.61849 inner_val_loss=4.08260 inner_val_multiclass_log_loss=4.08265 best_multiclass_log_loss=4.08265 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=8/40 loss=3.39831 inner_val_loss=3.93322 inner_val_multiclass_log_loss=3.93321 best_multiclass_log_loss=3.93321 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=9/40 loss=3.19004 inner_val_loss=3.87016 inner_val_multiclass_log_loss=3.87020 best_multiclass_log_loss=3.87020 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=10/40 loss=2.96517 inner_val_loss=3.75255 inner_val_multiclass_log_loss=3.75255 best_multiclass_log_loss=3.75255 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=11/40 loss=2.75054 inner_val_loss=3.67104 inner_val_multiclass_log_loss=3.67106 best_multiclass_log_loss=3.67106 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=12/40 loss=2.54064 inner_val_loss=3.57192 inner_val_multiclass_log_loss=3.57195 best_multiclass_log_loss=3.57195 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=13/40 loss=2.34203 inner_val_loss=3.46974 inner_val_multiclass_log_loss=3.46984 best_multiclass_log_loss=3.46984 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=14/40 loss=2.14699 inner_val_loss=3.39058 inner_val_multiclass_log_loss=3.39060 best_multiclass_log_loss=3.39060 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=15/40 loss=1.97566 inner_val_loss=3.22496 inner_val_multiclass_log_loss=3.22488 best_multiclass_log_loss=3.22488 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=16/40 loss=1.78328 inner_val_loss=3.20142 inner_val_multiclass_log_loss=3.20133 best_multiclass_log_loss=3.20133 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=17/40 loss=1.61451 inner_val_loss=3.10055 inner_val_multiclass_log_loss=3.10061 best_multiclass_log_loss=3.10061 best_epoch=17 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=18/40 loss=1.48052 inner_val_loss=3.06376 inner_val_multiclass_log_loss=3.06376 best_multiclass_log_loss=3.06376 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=19/40 loss=1.30872 inner_val_loss=2.99257 inner_val_multiclass_log_loss=2.99263 best_multiclass_log_loss=2.99263 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=20/40 loss=1.18439 inner_val_loss=2.97069 inner_val_multiclass_log_loss=2.97066 best_multiclass_log_loss=2.97066 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=21/40 loss=1.07813 inner_val_loss=2.89766 inner_val_multiclass_log_loss=2.89778 best_multiclass_log_loss=2.89778 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=22/40 loss=0.94472 inner_val_loss=2.84399 inner_val_multiclass_log_loss=2.84401 best_multiclass_log_loss=2.84401 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=23/40 loss=0.85215 inner_val_loss=2.81882 inner_val_multiclass_log_loss=2.81876 best_multiclass_log_loss=2.81876 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=24/40 loss=0.76193 inner_val_loss=2.78520 inner_val_multiclass_log_loss=2.78512 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=25/40 loss=0.67522 inner_val_loss=2.79527 inner_val_multiclass_log_loss=2.79529 best_multiclass_log_loss=2.78512 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=26/40 loss=0.59620 inner_val_loss=2.76630 inner_val_multiclass_log_loss=2.76634 best_multiclass_log_loss=2.76634 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=27/40 loss=0.53659 inner_val_loss=2.73014 inner_val_multiclass_log_loss=2.73021 best_multiclass_log_loss=2.73021 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=28/40 loss=0.46902 inner_val_loss=2.68155 inner_val_multiclass_log_loss=2.68160 best_multiclass_log_loss=2.68160 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=29/40 loss=0.42078 inner_val_loss=2.66191 inner_val_multiclass_log_loss=2.66190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=30/40 loss=0.37526 inner_val_loss=2.67838 inner_val_multiclass_log_loss=2.67840 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=31/40 loss=0.32713 inner_val_loss=2.67195 inner_val_multiclass_log_loss=2.67190 best_multiclass_log_loss=2.66190 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=32/40 loss=0.29732 inner_val_loss=2.64314 inner_val_multiclass_log_loss=2.64318 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=33/40 loss=0.26400 inner_val_loss=2.64539 inner_val_multiclass_log_loss=2.64539 best_multiclass_log_loss=2.64318 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=34/40 loss=0.22863 inner_val_loss=2.62849 inner_val_multiclass_log_loss=2.62847 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=35/40 loss=0.21273 inner_val_loss=2.68348 inner_val_multiclass_log_loss=2.68344 best_multiclass_log_loss=2.62847 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=36/40 loss=0.18296 inner_val_loss=2.62064 inner_val_multiclass_log_loss=2.62070 best_multiclass_log_loss=2.62070 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=37/40 loss=0.16822 inner_val_loss=2.59413 inner_val_multiclass_log_loss=2.59413 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=38/40 loss=0.15150 inner_val_loss=2.62271 inner_val_multiclass_log_loss=2.62273 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=39/40 loss=0.14116 inner_val_loss=2.60107 inner_val_multiclass_log_loss=2.60106 best_multiclass_log_loss=2.59413 best_epoch=37 seconds=2.1
  fit=29 epoch=40/40 loss=0.12134 inner_val_loss=2.58163 inner_val_multiclass_log_loss=2.58163 best_multiclass_log_loss=2.58163 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 full_refit_epoch=1/40 loss=4.78354
  fit=29 full_refit_epoch=2/40 loss=4.60792
  fit=29 full_refit_epoch=3/40 loss=4.43281
  fit=29 full_refit_epoch=4/40 loss=4.22375
  fit=29 full_refit_epoch=5/40 loss=3.98823
  fit=29 full_refit_epoch=6/40 loss=3.75429
  fit=29 full_refit_epoch=7/40 loss=3.52034
  fit=29 full_refit_epoch=8/40 loss=3.27720
  fit=29 full_refit_epoch=9/40 loss=3.03494
  fit=29 full_refit_epoch=10/40 loss=2.80688
  fit=29 full_refit_epoch=11/40 loss=2.58710
  fit=29 full_refit_epoch=12/40 loss=2.35734
  fit=29 full_refit_epoch=13/40 loss=2.16211
  fit=29 full_refit_epoch=14/40 loss=1.95755
  fit=29 full_refit_epoch=15/40 loss=1.76778
  fit=29 full_refit_epoch=16/40 loss=1.59597
  fit=29 full_refit_epoch=17/40 loss=1.43546
  fit=29 full_refit_epoch=18/40 loss=1.29959
  fit=29 full_refit_epoch=19/40 loss=1.14497
  fit=29 full_refit_epoch=20/40 loss=1.00626
  fit=29 full_refit_epoch=21/40 loss=0.90324
  fit=29 full_refit_epoch=22/40 loss=0.80394
  fit=29 full_refit_epoch=23/40 loss=0.70506
  fit=29 full_refit_epoch=24/40 loss=0.60783
  fit=29 full_refit_epoch=25/40 loss=0.54702
  fit=29 full_refit_epoch=26/40 loss=0.47226
  fit=29 full_refit_epoch=27/40 loss=0.41576
  fit=29 full_refit_epoch=28/40 loss=0.36619
  fit=29 full_refit_epoch=29/40 loss=0.31657
  fit=29 full_refit_epoch=30/40 loss=0.27211
  fit=29 full_refit_epoch=31/40 loss=0.24408
  fit=29 full_refit_epoch=32/40 loss=0.21425
  fit=29 full_refit_epoch=33/40 loss=0.19270
  fit=29 full_refit_epoch=34/40 loss=0.17262
  fit=29 full_refit_epoch=35/40 loss=0.15522
  fit=29 full_refit_epoch=36/40 loss=0.13730
  fit=29 full_refit_epoch=37/40 loss=0.12264
  fit=29 full_refit_epoch=38/40 loss=0.11303
  fit=29 full_refit_epoch=39/40 loss=0.10542
  fit=29 full_refit_epoch=40/40 loss=0.09377

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=1/40 loss=4.77984 inner_val_loss=4.72068 inner_val_multiclass_log_loss=4.72080 best_multiclass_log_loss=4.72080 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=2/40 loss=4.61636 inner_val_loss=4.63699 inner_val_multiclass_log_loss=4.63693 best_multiclass_log_loss=4.63693 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=3/40 loss=4.45690 inner_val_loss=4.53775 inner_val_multiclass_log_loss=4.53788 best_multiclass_log_loss=4.53788 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=4/40 loss=4.27154 inner_val_loss=4.42661 inner_val_multiclass_log_loss=4.42666 best_multiclass_log_loss=4.42666 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=5/40 loss=4.07261 inner_val_loss=4.30221 inner_val_multiclass_log_loss=4.30233 best_multiclass_log_loss=4.30233 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=6/40 loss=3.86698 inner_val_loss=4.12875 inner_val_multiclass_log_loss=4.12878 best_multiclass_log_loss=4.12878 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=7/40 loss=3.63809 inner_val_loss=4.01937 inner_val_multiclass_log_loss=4.01942 best_multiclass_log_loss=4.01942 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=8/40 loss=3.41935 inner_val_loss=3.87518 inner_val_multiclass_log_loss=3.87534 best_multiclass_log_loss=3.87534 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=9/40 loss=3.18955 inner_val_loss=3.70662 inner_val_multiclass_log_loss=3.70651 best_multiclass_log_loss=3.70651 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=10/40 loss=2.97659 inner_val_loss=3.54444 inner_val_multiclass_log_loss=3.54442 best_multiclass_log_loss=3.54442 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=11/40 loss=2.76710 inner_val_loss=3.46261 inner_val_multiclass_log_loss=3.46251 best_multiclass_log_loss=3.46251 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=12/40 loss=2.57334 inner_val_loss=3.27116 inner_val_multiclass_log_loss=3.27115 best_multiclass_log_loss=3.27115 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=13/40 loss=2.36194 inner_val_loss=3.19750 inner_val_multiclass_log_loss=3.19768 best_multiclass_log_loss=3.19768 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=14/40 loss=2.17910 inner_val_loss=3.07389 inner_val_multiclass_log_loss=3.07391 best_multiclass_log_loss=3.07391 best_epoch=14 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=15/40 loss=1.99885 inner_val_loss=3.01897 inner_val_multiclass_log_loss=3.01895 best_multiclass_log_loss=3.01895 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=16/40 loss=1.82771 inner_val_loss=2.94047 inner_val_multiclass_log_loss=2.94037 best_multiclass_log_loss=2.94037 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=17/40 loss=1.65915 inner_val_loss=2.81063 inner_val_multiclass_log_loss=2.81061 best_multiclass_log_loss=2.81061 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=18/40 loss=1.51430 inner_val_loss=2.77291 inner_val_multiclass_log_loss=2.77299 best_multiclass_log_loss=2.77299 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=19/40 loss=1.36006 inner_val_loss=2.70794 inner_val_multiclass_log_loss=2.70795 best_multiclass_log_loss=2.70795 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=20/40 loss=1.24242 inner_val_loss=2.63758 inner_val_multiclass_log_loss=2.63757 best_multiclass_log_loss=2.63757 best_epoch=20 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=21/40 loss=1.10894 inner_val_loss=2.62117 inner_val_multiclass_log_loss=2.62113 best_multiclass_log_loss=2.62113 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=22/40 loss=0.99728 inner_val_loss=2.57374 inner_val_multiclass_log_loss=2.57372 best_multiclass_log_loss=2.57372 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=23/40 loss=0.89508 inner_val_loss=2.56801 inner_val_multiclass_log_loss=2.56802 best_multiclass_log_loss=2.56802 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=24/40 loss=0.79840 inner_val_loss=2.51540 inner_val_multiclass_log_loss=2.51532 best_multiclass_log_loss=2.51532 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=25/40 loss=0.70842 inner_val_loss=2.48709 inner_val_multiclass_log_loss=2.48713 best_multiclass_log_loss=2.48713 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=26/40 loss=0.63383 inner_val_loss=2.45845 inner_val_multiclass_log_loss=2.45841 best_multiclass_log_loss=2.45841 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=27/40 loss=0.57510 inner_val_loss=2.43780 inner_val_multiclass_log_loss=2.43789 best_multiclass_log_loss=2.43789 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=28/40 loss=0.49380 inner_val_loss=2.40752 inner_val_multiclass_log_loss=2.40752 best_multiclass_log_loss=2.40752 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=29/40 loss=0.43158 inner_val_loss=2.38063 inner_val_multiclass_log_loss=2.38061 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=30/40 loss=0.40393 inner_val_loss=2.40156 inner_val_multiclass_log_loss=2.40155 best_multiclass_log_loss=2.38061 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=31/40 loss=0.34829 inner_val_loss=2.34321 inner_val_multiclass_log_loss=2.34324 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=32/40 loss=0.30293 inner_val_loss=2.34830 inner_val_multiclass_log_loss=2.34833 best_multiclass_log_loss=2.34324 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=33/40 loss=0.27191 inner_val_loss=2.33435 inner_val_multiclass_log_loss=2.33438 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=34/40 loss=0.24077 inner_val_loss=2.36642 inner_val_multiclass_log_loss=2.36640 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=35/40 loss=0.21350 inner_val_loss=2.35795 inner_val_multiclass_log_loss=2.35801 best_multiclass_log_loss=2.33438 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=36/40 loss=0.21089 inner_val_loss=2.32175 inner_val_multiclass_log_loss=2.32167 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=37/40 loss=0.17882 inner_val_loss=2.32570 inner_val_multiclass_log_loss=2.32573 best_multiclass_log_loss=2.32167 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=38/40 loss=0.16260 inner_val_loss=2.31285 inner_val_multiclass_log_loss=2.31276 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=39/40 loss=0.14282 inner_val_loss=2.37636 inner_val_multiclass_log_loss=2.37630 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1
  fit=30 epoch=40/40 loss=0.13584 inner_val_loss=2.33817 inner_val_multiclass_log_loss=2.33822 best_multiclass_log_loss=2.31276 best_epoch=38 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 full_refit_epoch=1/38 loss=4.77285
  fit=30 full_refit_epoch=2/38 loss=4.60156
  fit=30 full_refit_epoch=3/38 loss=4.42367
  fit=30 full_refit_epoch=4/38 loss=4.21951
  fit=30 full_refit_epoch=5/38 loss=3.99543
  fit=30 full_refit_epoch=6/38 loss=3.76219
  fit=30 full_refit_epoch=7/38 loss=3.51045
  fit=30 full_refit_epoch=8/38 loss=3.26475
  fit=30 full_refit_epoch=9/38 loss=3.01855
  fit=30 full_refit_epoch=10/38 loss=2.79697
  fit=30 full_refit_epoch=11/38 loss=2.56724
  fit=30 full_refit_epoch=12/38 loss=2.34649
  fit=30 full_refit_epoch=13/38 loss=2.14739
  fit=30 full_refit_epoch=14/38 loss=1.94784
  fit=30 full_refit_epoch=15/38 loss=1.77608
  fit=30 full_refit_epoch=16/38 loss=1.58856
  fit=30 full_refit_epoch=17/38 loss=1.43336
  fit=30 full_refit_epoch=18/38 loss=1.28592
  fit=30 full_refit_epoch=19/38 loss=1.14915
  fit=30 full_refit_epoch=20/38 loss=1.01684
  fit=30 full_refit_epoch=21/38 loss=0.90502
  fit=30 full_refit_epoch=22/38 loss=0.79337
  fit=30 full_refit_epoch=23/38 loss=0.69822
  fit=30 full_refit_epoch=24/38 loss=0.61281
  fit=30 full_refit_epoch=25/38 loss=0.54337
  fit=30 full_refit_epoch=26/38 loss=0.47650
  fit=30 full_refit_epoch=27/38 loss=0.42055
  fit=30 full_refit_epoch=28/38 loss=0.35945
  fit=30 full_refit_epoch=29/38 loss=0.32238
  fit=30 full_refit_epoch=30/38 loss=0.28152
  fit=30 full_refit_epoch=31/38 loss=0.25445
  fit=30 full_refit_epoch=32/38 loss=0.21704
  fit=30 full_refit_epoch=33/38 loss=0.19919
  fit=30 full_refit_epoch=34/38 loss=0.17358
  fit=30 full_refit_epoch=35/38 loss=0.15832
  fit=30 full_refit_epoch=36/38 loss=0.14008
  fit=30 full_refit_epoch=37/38 loss=0.12395
  fit=30 full_refit_epoch=38/38 loss=0.11568

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=29 phase=refined_selected model=resnet18 metric=2.471291572428004 error=None minutes=13.20

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

START seed=47 phase=baseline model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.79604 inner_val_loss=4.73218 inner_val_multiclass_log_loss=4.73214 best_multiclass_log_loss=4.73214 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=4.63253 inner_val_loss=4.67259 inner_val_multiclass_log_loss=4.67259 best_multiclass_log_loss=4.67259 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=4.47386 inner_val_loss=4.55970 inner_val_multiclass_log_loss=4.55970 best_multiclass_log_loss=4.55970 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=4.28732 inner_val_loss=4.44825 inner_val_multiclass_log_loss=4.44823 best_multiclass_log_loss=4.44823 best_epoch=4 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=4.06886 inner_val_loss=4.33298 inner_val_multiclass_log_loss=4.33294 best_multiclass_log_loss=4.33294 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=3.84643 inner_val_loss=4.13359 inner_val_multiclass_log_loss=4.13362 best_multiclass_log_loss=4.13362 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=3.62140 inner_val_loss=3.97734 inner_val_multiclass_log_loss=3.97734 best_multiclass_log_loss=3.97734 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=3.39511 inner_val_loss=3.88827 inner_val_multiclass_log_loss=3.88824 best_multiclass_log_loss=3.88824 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=3.16729 inner_val_loss=3.77547 inner_val_multiclass_log_loss=3.77555 best_multiclass_log_loss=3.77555 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=2.95336 inner_val_loss=3.69540 inner_val_multiclass_log_loss=3.69537 best_multiclass_log_loss=3.69537 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=2.73357 inner_val_loss=3.54863 inner_val_multiclass_log_loss=3.54857 best_multiclass_log_loss=3.54857 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=2.52061 inner_val_loss=3.44390 inner_val_multiclass_log_loss=3.44381 best_multiclass_log_loss=3.44381 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=2.32619 inner_val_loss=3.36695 inner_val_multiclass_log_loss=3.36690 best_multiclass_log_loss=3.36690 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=2.14268 inner_val_loss=3.29173 inner_val_multiclass_log_loss=3.29171 best_multiclass_log_loss=3.29171 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=15/40 loss=1.97246 inner_val_loss=3.19012 inner_val_multiclass_log_loss=3.19021 best_multiclass_log_loss=3.19021 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=16/40 loss=1.78584 inner_val_loss=3.08207 inner_val_multiclass_log_loss=3.08204 best_multiclass_log_loss=3.08204 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=17/40 loss=1.62255 inner_val_loss=3.02023 inner_val_multiclass_log_loss=3.02023 best_multiclass_log_loss=3.02023 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=18/40 loss=1.47096 inner_val_loss=2.96257 inner_val_multiclass_log_loss=2.96259 best_multiclass_log_loss=2.96259 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=19/40 loss=1.34683 inner_val_loss=2.88782 inner_val_multiclass_log_loss=2.88782 best_multiclass_log_loss=2.88782 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=20/40 loss=1.18152 inner_val_loss=2.87635 inner_val_multiclass_log_loss=2.87630 best_multiclass_log_loss=2.87630 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=21/40 loss=1.07280 inner_val_loss=2.82962 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=22/40 loss=0.96276 inner_val_loss=2.76426 inner_val_multiclass_log_loss=2.76424 best_multiclass_log_loss=2.76424 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=23/40 loss=0.85255 inner_val_loss=2.74589 inner_val_multiclass_log_loss=2.74593 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=24/40 loss=0.76815 inner_val_loss=2.76247 inner_val_multiclass_log_loss=2.76242 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=25/40 loss=0.66728 inner_val_loss=2.70668 inner_val_multiclass_log_loss=2.70668 best_multiclass_log_loss=2.70668 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=26/40 loss=0.60636 inner_val_loss=2.70543 inner_val_multiclass_log_loss=2.70541 best_multiclass_log_loss=2.70541 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=27/40 loss=0.52941 inner_val_loss=2.68617 inner_val_multiclass_log_loss=2.68613 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=28/40 loss=0.48062 inner_val_loss=2.69317 inner_val_multiclass_log_loss=2.69317 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=29/40 loss=0.41842 inner_val_loss=2.66156 inner_val_multiclass_log_loss=2.66154 best_multiclass_log_loss=2.66154 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=30/40 loss=0.36864 inner_val_loss=2.65680 inner_val_multiclass_log_loss=2.65670 best_multiclass_log_loss=2.65670 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=31/40 loss=0.32602 inner_val_loss=2.63176 inner_val_multiclass_log_loss=2.63183 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=32/40 loss=0.30625 inner_val_loss=2.66063 inner_val_multiclass_log_loss=2.66061 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=33/40 loss=0.26540 inner_val_loss=2.63391 inner_val_multiclass_log_loss=2.63389 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=34/40 loss=0.24684 inner_val_loss=2.62465 inner_val_multiclass_log_loss=2.62469 best_multiclass_log_loss=2.62469 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=35/40 loss=0.20674 inner_val_loss=2.61135 inner_val_multiclass_log_loss=2.61138 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=36/40 loss=0.19393 inner_val_loss=2.64488 inner_val_multiclass_log_loss=2.64494 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=37/40 loss=0.16779 inner_val_loss=2.61169 inner_val_multiclass_log_loss=2.61176 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=38/40 loss=0.14916 inner_val_loss=2.62670 inner_val_multiclass_log_loss=2.62673 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=39/40 loss=0.14285 inner_val_loss=2.61079 inner_val_multiclass_log_loss=2.61077 best_multiclass_log_loss=2.61077 best_epoch=39 seconds=2.1
  fit=1 epoch=40/40 loss=0.12808 inner_val_loss=2.59991 inner_val_multiclass_log_loss=2.59992 best_multiclass_log_loss=2.59992 best_epoch=40 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/40 loss=4.79128
  fit=1 full_refit_epoch=2/40 loss=4.61581
  fit=1 full_refit_epoch=3/40 loss=4.43444
  fit=1 full_refit_epoch=4/40 loss=4.22564
  fit=1 full_refit_epoch=5/40 loss=3.98810
  fit=1 full_refit_epoch=6/40 loss=3.73859
  fit=1 full_refit_epoch=7/40 loss=3.49443
  fit=1 full_refit_epoch=8/40 loss=3.24746
  fit=1 full_refit_epoch=9/40 loss=3.01506
  fit=1 full_refit_epoch=10/40 loss=2.79312
  fit=1 full_refit_epoch=11/40 loss=2.56534
  fit=1 full_refit_epoch=12/40 loss=2.36016
  fit=1 full_refit_epoch=13/40 loss=2.15093
  fit=1 full_refit_epoch=14/40 loss=1.96154
  fit=1 full_refit_epoch=15/40 loss=1.77583
  fit=1 full_refit_epoch=16/40 loss=1.60714
  fit=1 full_refit_epoch=17/40 loss=1.44926
  fit=1 full_refit_epoch=18/40 loss=1.28955
  fit=1 full_refit_epoch=19/40 loss=1.15900
  fit=1 full_refit_epoch=20/40 loss=1.04187
  fit=1 full_refit_epoch=21/40 loss=0.92192
  fit=1 full_refit_epoch=22/40 loss=0.79462
  fit=1 full_refit_epoch=23/40 loss=0.71547
  fit=1 full_refit_epoch=24/40 loss=0.62853
  fit=1 full_refit_epoch=25/40 loss=0.55656
  fit=1 full_refit_epoch=26/40 loss=0.47864
  fit=1 full_refit_epoch=27/40 loss=0.42339
  fit=1 full_refit_epoch=28/40 loss=0.38009
  fit=1 full_refit_epoch=29/40 loss=0.32500
  fit=1 full_refit_epoch=30/40 loss=0.30116
  fit=1 full_refit_epoch=31/40 loss=0.24874
  fit=1 full_refit_epoch=32/40 loss=0.21832
  fit=1 full_refit_epoch=33/40 loss=0.19626
  fit=1 full_refit_epoch=34/40 loss=0.17990
  fit=1 full_refit_epoch=35/40 loss=0.15856
  fit=1 full_refit_epoch=36/40 loss=0.14075
  fit=1 full_refit_epoch=37/40 loss=0.12563
  fit=1 full_refit_epoch=38/40 loss=0.10919
  fit=1 full_refit_epoch=39/40 loss=0.10192
  fit=1 full_refit_epoch=40/40 loss=0.09188

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=1/40 loss=4.78529 inner_val_loss=4.74350 inner_val_multiclass_log_loss=4.74344 best_multiclass_log_loss=4.74344 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=2/40 loss=4.61759 inner_val_loss=4.66598 inner_val_multiclass_log_loss=4.66596 best_multiclass_log_loss=4.66596 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=3/40 loss=4.44644 inner_val_loss=4.56246 inner_val_multiclass_log_loss=4.56251 best_multiclass_log_loss=4.56251 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=4/40 loss=4.25722 inner_val_loss=4.46757 inner_val_multiclass_log_loss=4.46770 best_multiclass_log_loss=4.46770 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=5/40 loss=4.05331 inner_val_loss=4.32690 inner_val_multiclass_log_loss=4.32679 best_multiclass_log_loss=4.32679 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=6/40 loss=3.81373 inner_val_loss=4.18748 inner_val_multiclass_log_loss=4.18753 best_multiclass_log_loss=4.18753 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=7/40 loss=3.59817 inner_val_loss=4.05102 inner_val_multiclass_log_loss=4.05097 best_multiclass_log_loss=4.05097 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=8/40 loss=3.36733 inner_val_loss=3.88468 inner_val_multiclass_log_loss=3.88461 best_multiclass_log_loss=3.88461 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=9/40 loss=3.15824 inner_val_loss=3.79493 inner_val_multiclass_log_loss=3.79483 best_multiclass_log_loss=3.79483 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=10/40 loss=2.94215 inner_val_loss=3.64514 inner_val_multiclass_log_loss=3.64511 best_multiclass_log_loss=3.64511 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=11/40 loss=2.73160 inner_val_loss=3.58555 inner_val_multiclass_log_loss=3.58546 best_multiclass_log_loss=3.58546 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=12/40 loss=2.50724 inner_val_loss=3.40191 inner_val_multiclass_log_loss=3.40197 best_multiclass_log_loss=3.40197 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=13/40 loss=2.30979 inner_val_loss=3.28591 inner_val_multiclass_log_loss=3.28586 best_multiclass_log_loss=3.28586 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=14/40 loss=2.13234 inner_val_loss=3.23486 inner_val_multiclass_log_loss=3.23487 best_multiclass_log_loss=3.23487 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=15/40 loss=1.94883 inner_val_loss=3.08468 inner_val_multiclass_log_loss=3.08474 best_multiclass_log_loss=3.08474 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=16/40 loss=1.78527 inner_val_loss=2.99771 inner_val_multiclass_log_loss=2.99765 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=17/40 loss=1.62082 inner_val_loss=3.00123 inner_val_multiclass_log_loss=3.00123 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=18/40 loss=1.45911 inner_val_loss=2.90762 inner_val_multiclass_log_loss=2.90759 best_multiclass_log_loss=2.90759 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=19/40 loss=1.33887 inner_val_loss=2.81714 inner_val_multiclass_log_loss=2.81714 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=20/40 loss=1.20626 inner_val_loss=2.82729 inner_val_multiclass_log_loss=2.82734 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=21/40 loss=1.07785 inner_val_loss=2.74942 inner_val_multiclass_log_loss=2.74944 best_multiclass_log_loss=2.74944 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=22/40 loss=0.96543 inner_val_loss=2.68896 inner_val_multiclass_log_loss=2.68888 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=23/40 loss=0.85024 inner_val_loss=2.74155 inner_val_multiclass_log_loss=2.74154 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=24/40 loss=0.76864 inner_val_loss=2.66937 inner_val_multiclass_log_loss=2.66942 best_multiclass_log_loss=2.66942 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=25/40 loss=0.68431 inner_val_loss=2.63966 inner_val_multiclass_log_loss=2.63964 best_multiclass_log_loss=2.63964 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=26/40 loss=0.58750 inner_val_loss=2.63823 inner_val_multiclass_log_loss=2.63818 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=27/40 loss=0.51989 inner_val_loss=2.64882 inner_val_multiclass_log_loss=2.64874 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=28/40 loss=0.45891 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60250 best_multiclass_log_loss=2.60250 best_epoch=28 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=29/40 loss=0.41438 inner_val_loss=2.58168 inner_val_multiclass_log_loss=2.58177 best_multiclass_log_loss=2.58177 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=30/40 loss=0.36284 inner_val_loss=2.57724 inner_val_multiclass_log_loss=2.57728 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=31/40 loss=0.33492 inner_val_loss=2.57963 inner_val_multiclass_log_loss=2.57971 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=32/40 loss=0.28502 inner_val_loss=2.55369 inner_val_multiclass_log_loss=2.55378 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=33/40 loss=0.27036 inner_val_loss=2.56817 inner_val_multiclass_log_loss=2.56822 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=34/40 loss=0.22846 inner_val_loss=2.53099 inner_val_multiclass_log_loss=2.53092 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=35/40 loss=0.21733 inner_val_loss=2.57357 inner_val_multiclass_log_loss=2.57348 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=36/40 loss=0.18244 inner_val_loss=2.54892 inner_val_multiclass_log_loss=2.54897 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=37/40 loss=0.17517 inner_val_loss=2.54703 inner_val_multiclass_log_loss=2.54705 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 epoch=38/40 loss=0.15172 inner_val_loss=2.54890 inner_val_multiclass_log_loss=2.54889 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0
  fit=2 epoch=39/40 loss=0.13926 inner_val_loss=2.53601 inner_val_multiclass_log_loss=2.53600 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=2 full_refit_epoch=1/34 loss=4.77779
  fit=2 full_refit_epoch=2/34 loss=4.60078
  fit=2 full_refit_epoch=3/34 loss=4.41295
  fit=2 full_refit_epoch=4/34 loss=4.19824
  fit=2 full_refit_epoch=5/34 loss=3.95991
  fit=2 full_refit_epoch=6/34 loss=3.72031
  fit=2 full_refit_epoch=7/34 loss=3.47218
  fit=2 full_refit_epoch=8/34 loss=3.24296
  fit=2 full_refit_epoch=9/34 loss=2.99698
  fit=2 full_refit_epoch=10/34 loss=2.77741
  fit=2 full_refit_epoch=11/34 loss=2.54338
  fit=2 full_refit_epoch=12/34 loss=2.33114
  fit=2 full_refit_epoch=13/34 loss=2.12232
  fit=2 full_refit_epoch=14/34 loss=1.93304
  fit=2 full_refit_epoch=15/34 loss=1.75879
  fit=2 full_refit_epoch=16/34 loss=1.57506
  fit=2 full_refit_epoch=17/34 loss=1.41415
  fit=2 full_refit_epoch=18/34 loss=1.27479
  fit=2 full_refit_epoch=19/34 loss=1.13539
  fit=2 full_refit_epoch=20/34 loss=1.02070
  fit=2 full_refit_epoch=21/34 loss=0.89572
  fit=2 full_refit_epoch=22/34 loss=0.78825
  fit=2 full_refit_epoch=23/34 loss=0.69082
  fit=2 full_refit_epoch=24/34 loss=0.59551
  fit=2 full_refit_epoch=25/34 loss=0.53715
  fit=2 full_refit_epoch=26/34 loss=0.47102
  fit=2 full_refit_epoch=27/34 loss=0.41062
  fit=2 full_refit_epoch=28/34 loss=0.35460
  fit=2 full_refit_epoch=29/34 loss=0.31392
  fit=2 full_refit_epoch=30/34 loss=0.27658
  fit=2 full_refit_epoch=31/34 loss=0.24613
  fit=2 full_refit_epoch=32/34 loss=0.21734
  fit=2 full_refit_epoch=33/34 loss=0.19095
  fit=2 full_refit_epoch=34/34 loss=0.17254

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=1/40 loss=4.78598 inner_val_loss=4.74895 inner_val_multiclass_log_loss=4.74886 best_multiclass_log_loss=4.74886 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=2/40 loss=4.61747 inner_val_loss=4.67133 inner_val_multiclass_log_loss=4.67137 best_multiclass_log_loss=4.67137 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=3/40 loss=4.44421 inner_val_loss=4.58167 inner_val_multiclass_log_loss=4.58166 best_multiclass_log_loss=4.58166 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=4/40 loss=4.25613 inner_val_loss=4.44833 inner_val_multiclass_log_loss=4.44822 best_multiclass_log_loss=4.44822 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=5/40 loss=4.03231 inner_val_loss=4.29905 inner_val_multiclass_log_loss=4.29900 best_multiclass_log_loss=4.29900 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=6/40 loss=3.80887 inner_val_loss=4.16650 inner_val_multiclass_log_loss=4.16655 best_multiclass_log_loss=4.16655 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=7/40 loss=3.58425 inner_val_loss=4.07659 inner_val_multiclass_log_loss=4.07661 best_multiclass_log_loss=4.07661 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=8/40 loss=3.36133 inner_val_loss=3.91148 inner_val_multiclass_log_loss=3.91148 best_multiclass_log_loss=3.91148 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=9/40 loss=3.13965 inner_val_loss=3.69225 inner_val_multiclass_log_loss=3.69228 best_multiclass_log_loss=3.69228 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=10/40 loss=2.92091 inner_val_loss=3.63148 inner_val_multiclass_log_loss=3.63156 best_multiclass_log_loss=3.63156 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=11/40 loss=2.70039 inner_val_loss=3.50666 inner_val_multiclass_log_loss=3.50662 best_multiclass_log_loss=3.50662 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=12/40 loss=2.50043 inner_val_loss=3.37099 inner_val_multiclass_log_loss=3.37102 best_multiclass_log_loss=3.37102 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=13/40 loss=2.29484 inner_val_loss=3.26625 inner_val_multiclass_log_loss=3.26612 best_multiclass_log_loss=3.26612 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=14/40 loss=2.12114 inner_val_loss=3.16823 inner_val_multiclass_log_loss=3.16824 best_multiclass_log_loss=3.16824 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=15/40 loss=1.93977 inner_val_loss=3.08539 inner_val_multiclass_log_loss=3.08539 best_multiclass_log_loss=3.08539 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=16/40 loss=1.76654 inner_val_loss=2.99735 inner_val_multiclass_log_loss=2.99742 best_multiclass_log_loss=2.99742 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=17/40 loss=1.60779 inner_val_loss=2.89870 inner_val_multiclass_log_loss=2.89881 best_multiclass_log_loss=2.89881 best_epoch=17 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=18/40 loss=1.45640 inner_val_loss=2.85110 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=19/40 loss=1.30639 inner_val_loss=2.77251 inner_val_multiclass_log_loss=2.77241 best_multiclass_log_loss=2.77241 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=20/40 loss=1.16936 inner_val_loss=2.75131 inner_val_multiclass_log_loss=2.75130 best_multiclass_log_loss=2.75130 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=21/40 loss=1.05572 inner_val_loss=2.69500 inner_val_multiclass_log_loss=2.69506 best_multiclass_log_loss=2.69506 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=22/40 loss=0.94055 inner_val_loss=2.67022 inner_val_multiclass_log_loss=2.67029 best_multiclass_log_loss=2.67029 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=23/40 loss=0.85175 inner_val_loss=2.59384 inner_val_multiclass_log_loss=2.59380 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=24/40 loss=0.75602 inner_val_loss=2.59947 inner_val_multiclass_log_loss=2.59943 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=25/40 loss=0.66566 inner_val_loss=2.57623 inner_val_multiclass_log_loss=2.57619 best_multiclass_log_loss=2.57619 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=26/40 loss=0.58957 inner_val_loss=2.56685 inner_val_multiclass_log_loss=2.56687 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=27/40 loss=0.52900 inner_val_loss=2.57257 inner_val_multiclass_log_loss=2.57252 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=28/40 loss=0.46072 inner_val_loss=2.54440 inner_val_multiclass_log_loss=2.54439 best_multiclass_log_loss=2.54439 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=29/40 loss=0.41680 inner_val_loss=2.51023 inner_val_multiclass_log_loss=2.51027 best_multiclass_log_loss=2.51027 best_epoch=29 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=30/40 loss=0.35341 inner_val_loss=2.48075 inner_val_multiclass_log_loss=2.48079 best_multiclass_log_loss=2.48079 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=31/40 loss=0.32624 inner_val_loss=2.47039 inner_val_multiclass_log_loss=2.47038 best_multiclass_log_loss=2.47038 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=32/40 loss=0.29237 inner_val_loss=2.45936 inner_val_multiclass_log_loss=2.45932 best_multiclass_log_loss=2.45932 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=33/40 loss=0.26956 inner_val_loss=2.44038 inner_val_multiclass_log_loss=2.44039 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=34/40 loss=0.23673 inner_val_loss=2.44873 inner_val_multiclass_log_loss=2.44875 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=35/40 loss=0.20594 inner_val_loss=2.43773 inner_val_multiclass_log_loss=2.43777 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=36/40 loss=0.18920 inner_val_loss=2.46623 inner_val_multiclass_log_loss=2.46618 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=37/40 loss=0.17468 inner_val_loss=2.42681 inner_val_multiclass_log_loss=2.42687 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=38/40 loss=0.16045 inner_val_loss=2.43230 inner_val_multiclass_log_loss=2.43224 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 epoch=39/40 loss=0.13876 inner_val_loss=2.42945 inner_val_multiclass_log_loss=2.42945 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1
  fit=3 epoch=40/40 loss=0.12840 inner_val_loss=2.42231 inner_val_multiclass_log_loss=2.42228 best_multiclass_log_loss=2.42228 best_epoch=40 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=3 full_refit_epoch=1/40 loss=4.77988
  fit=3 full_refit_epoch=2/40 loss=4.60904
  fit=3 full_refit_epoch=3/40 loss=4.42586
  fit=3 full_refit_epoch=4/40 loss=4.21264
  fit=3 full_refit_epoch=5/40 loss=3.98115
  fit=3 full_refit_epoch=6/40 loss=3.72980
  fit=3 full_refit_epoch=7/40 loss=3.48740
  fit=3 full_refit_epoch=8/40 loss=3.24153
  fit=3 full_refit_epoch=9/40 loss=3.01609
  fit=3 full_refit_epoch=10/40 loss=2.77404
  fit=3 full_refit_epoch=11/40 loss=2.54436
  fit=3 full_refit_epoch=12/40 loss=2.33251
  fit=3 full_refit_epoch=13/40 loss=2.12541
  fit=3 full_refit_epoch=14/40 loss=1.94018
  fit=3 full_refit_epoch=15/40 loss=1.74784
  fit=3 full_refit_epoch=16/40 loss=1.57977
  fit=3 full_refit_epoch=17/40 loss=1.41598
  fit=3 full_refit_epoch=18/40 loss=1.28322
  fit=3 full_refit_epoch=19/40 loss=1.12908
  fit=3 full_refit_epoch=20/40 loss=1.00664
  fit=3 full_refit_epoch=21/40 loss=0.89356
  fit=3 full_refit_epoch=22/40 loss=0.79305
  fit=3 full_refit_epoch=23/40 loss=0.70667
  fit=3 full_refit_epoch=24/40 loss=0.60575
  fit=3 full_refit_epoch=25/40 loss=0.53220
  fit=3 full_refit_epoch=26/40 loss=0.47780
  fit=3 full_refit_epoch=27/40 loss=0.41461
  fit=3 full_refit_epoch=28/40 loss=0.36608
  fit=3 full_refit_epoch=29/40 loss=0.32224
  fit=3 full_refit_epoch=30/40 loss=0.27960
  fit=3 full_refit_epoch=31/40 loss=0.25322
  fit=3 full_refit_epoch=32/40 loss=0.21666
  fit=3 full_refit_epoch=33/40 loss=0.19701
  fit=3 full_refit_epoch=34/40 loss=0.17425
  fit=3 full_refit_epoch=35/40 loss=0.15471
  fit=3 full_refit_epoch=36/40 loss=0.13652
  fit=3 full_refit_epoch=37/40 loss=0.12648
  fit=3 full_refit_epoch=38/40 loss=0.10761
  fit=3 full_refit_epoch=39/40 loss=0.10610
  fit=3 full_refit_epoch=40/40 loss=0.09535

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=1/40 loss=4.78616 inner_val_loss=4.72490 inner_val_multiclass_log_loss=4.72474 best_multiclass_log_loss=4.72474 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=2/40 loss=4.61983 inner_val_loss=4.62753 inner_val_multiclass_log_loss=4.62759 best_multiclass_log_loss=4.62759 best_epoch=2 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=3/40 loss=4.45797 inner_val_loss=4.54643 inner_val_multiclass_log_loss=4.54643 best_multiclass_log_loss=4.54643 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=4/40 loss=4.28081 inner_val_loss=4.46488 inner_val_multiclass_log_loss=4.46488 best_multiclass_log_loss=4.46488 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=5/40 loss=4.08048 inner_val_loss=4.31625 inner_val_multiclass_log_loss=4.31634 best_multiclass_log_loss=4.31634 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=6/40 loss=3.86825 inner_val_loss=4.18847 inner_val_multiclass_log_loss=4.18838 best_multiclass_log_loss=4.18838 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=7/40 loss=3.64301 inner_val_loss=4.05750 inner_val_multiclass_log_loss=4.05740 best_multiclass_log_loss=4.05740 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=8/40 loss=3.40436 inner_val_loss=3.87396 inner_val_multiclass_log_loss=3.87396 best_multiclass_log_loss=3.87396 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=9/40 loss=3.19662 inner_val_loss=3.75727 inner_val_multiclass_log_loss=3.75729 best_multiclass_log_loss=3.75729 best_epoch=9 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=10/40 loss=2.97522 inner_val_loss=3.66436 inner_val_multiclass_log_loss=3.66434 best_multiclass_log_loss=3.66434 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=11/40 loss=2.74266 inner_val_loss=3.47013 inner_val_multiclass_log_loss=3.47004 best_multiclass_log_loss=3.47004 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=12/40 loss=2.55972 inner_val_loss=3.33333 inner_val_multiclass_log_loss=3.33334 best_multiclass_log_loss=3.33334 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=13/40 loss=2.35769 inner_val_loss=3.28423 inner_val_multiclass_log_loss=3.28425 best_multiclass_log_loss=3.28425 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=14/40 loss=2.16565 inner_val_loss=3.15414 inner_val_multiclass_log_loss=3.15408 best_multiclass_log_loss=3.15408 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=15/40 loss=1.98688 inner_val_loss=3.07231 inner_val_multiclass_log_loss=3.07231 best_multiclass_log_loss=3.07231 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=16/40 loss=1.81668 inner_val_loss=3.00154 inner_val_multiclass_log_loss=3.00149 best_multiclass_log_loss=3.00149 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=17/40 loss=1.66713 inner_val_loss=2.92328 inner_val_multiclass_log_loss=2.92325 best_multiclass_log_loss=2.92325 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=18/40 loss=1.52455 inner_val_loss=2.86711 inner_val_multiclass_log_loss=2.86716 best_multiclass_log_loss=2.86716 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=19/40 loss=1.35649 inner_val_loss=2.82959 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=20/40 loss=1.23937 inner_val_loss=2.70085 inner_val_multiclass_log_loss=2.70082 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=21/40 loss=1.11458 inner_val_loss=2.73949 inner_val_multiclass_log_loss=2.73944 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=22/40 loss=1.00135 inner_val_loss=2.69911 inner_val_multiclass_log_loss=2.69906 best_multiclass_log_loss=2.69906 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=23/40 loss=0.90562 inner_val_loss=2.60998 inner_val_multiclass_log_loss=2.60992 best_multiclass_log_loss=2.60992 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=24/40 loss=0.79425 inner_val_loss=2.60439 inner_val_multiclass_log_loss=2.60439 best_multiclass_log_loss=2.60439 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=25/40 loss=0.70615 inner_val_loss=2.58918 inner_val_multiclass_log_loss=2.58917 best_multiclass_log_loss=2.58917 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=26/40 loss=0.63300 inner_val_loss=2.53947 inner_val_multiclass_log_loss=2.53950 best_multiclass_log_loss=2.53950 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=27/40 loss=0.56248 inner_val_loss=2.49854 inner_val_multiclass_log_loss=2.49855 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=28/40 loss=0.50699 inner_val_loss=2.51626 inner_val_multiclass_log_loss=2.51622 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=29/40 loss=0.44951 inner_val_loss=2.53317 inner_val_multiclass_log_loss=2.53312 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=30/40 loss=0.40239 inner_val_loss=2.50438 inner_val_multiclass_log_loss=2.50445 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=31/40 loss=0.35139 inner_val_loss=2.49836 inner_val_multiclass_log_loss=2.49834 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=32/40 loss=0.31519 inner_val_loss=2.49952 inner_val_multiclass_log_loss=2.49954 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=33/40 loss=0.28856 inner_val_loss=2.42672 inner_val_multiclass_log_loss=2.42672 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=34/40 loss=0.25429 inner_val_loss=2.45267 inner_val_multiclass_log_loss=2.45271 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=35/40 loss=0.22645 inner_val_loss=2.42072 inner_val_multiclass_log_loss=2.42068 best_multiclass_log_loss=2.42068 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=36/40 loss=0.20706 inner_val_loss=2.41048 inner_val_multiclass_log_loss=2.41044 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=37/40 loss=0.18824 inner_val_loss=2.41161 inner_val_multiclass_log_loss=2.41162 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=38/40 loss=0.17108 inner_val_loss=2.45061 inner_val_multiclass_log_loss=2.45059 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 epoch=39/40 loss=0.14891 inner_val_loss=2.41139 inner_val_multiclass_log_loss=2.41135 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0
  fit=4 epoch=40/40 loss=0.13585 inner_val_loss=2.40886 inner_val_multiclass_log_loss=2.40889 best_multiclass_log_loss=2.40889 best_epoch=40 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=4 full_refit_epoch=1/40 loss=4.78382
  fit=4 full_refit_epoch=2/40 loss=4.60593
  fit=4 full_refit_epoch=3/40 loss=4.42989
  fit=4 full_refit_epoch=4/40 loss=4.22715
  fit=4 full_refit_epoch=5/40 loss=3.99684
  fit=4 full_refit_epoch=6/40 loss=3.75249
  fit=4 full_refit_epoch=7/40 loss=3.51416
  fit=4 full_refit_epoch=8/40 loss=3.26404
  fit=4 full_refit_epoch=9/40 loss=3.02605
  fit=4 full_refit_epoch=10/40 loss=2.79345
  fit=4 full_refit_epoch=11/40 loss=2.56204
  fit=4 full_refit_epoch=12/40 loss=2.36419
  fit=4 full_refit_epoch=13/40 loss=2.15368
  fit=4 full_refit_epoch=14/40 loss=1.96638
  fit=4 full_refit_epoch=15/40 loss=1.78290
  fit=4 full_refit_epoch=16/40 loss=1.62735
  fit=4 full_refit_epoch=17/40 loss=1.46567
  fit=4 full_refit_epoch=18/40 loss=1.31435
  fit=4 full_refit_epoch=19/40 loss=1.17849
  fit=4 full_refit_epoch=20/40 loss=1.04482
  fit=4 full_refit_epoch=21/40 loss=0.93599
  fit=4 full_refit_epoch=22/40 loss=0.82802
  fit=4 full_refit_epoch=23/40 loss=0.73241
  fit=4 full_refit_epoch=24/40 loss=0.64588
  fit=4 full_refit_epoch=25/40 loss=0.57137
  fit=4 full_refit_epoch=26/40 loss=0.49800
  fit=4 full_refit_epoch=27/40 loss=0.43521
  fit=4 full_refit_epoch=28/40 loss=0.39097
  fit=4 full_refit_epoch=29/40 loss=0.35223
  fit=4 full_refit_epoch=30/40 loss=0.30540
  fit=4 full_refit_epoch=31/40 loss=0.26708
  fit=4 full_refit_epoch=32/40 loss=0.23549
  fit=4 full_refit_epoch=33/40 loss=0.20737
  fit=4 full_refit_epoch=34/40 loss=0.18645
  fit=4 full_refit_epoch=35/40 loss=0.16723
  fit=4 full_refit_epoch=36/40 loss=0.14765
  fit=4 full_refit_epoch=37/40 loss=0.13257
  fit=4 full_refit_epoch=38/40 loss=0.12424
  fit=4 full_refit_epoch=39/40 loss=0.10739
  fit=4 full_refit_epoch=40/40 loss=0.09676

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=1/40 loss=4.78442 inner_val_loss=4.74988 inner_val_multiclass_log_loss=4.74991 best_multiclass_log_loss=4.74991 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=2/40 loss=4.61357 inner_val_loss=4.68988 inner_val_multiclass_log_loss=4.68997 best_multiclass_log_loss=4.68997 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=3/40 loss=4.45425 inner_val_loss=4.60145 inner_val_multiclass_log_loss=4.60136 best_multiclass_log_loss=4.60136 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=4/40 loss=4.27011 inner_val_loss=4.52010 inner_val_multiclass_log_loss=4.52011 best_multiclass_log_loss=4.52011 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=5/40 loss=4.06233 inner_val_loss=4.37511 inner_val_multiclass_log_loss=4.37502 best_multiclass_log_loss=4.37502 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=6/40 loss=3.84104 inner_val_loss=4.32146 inner_val_multiclass_log_loss=4.32137 best_multiclass_log_loss=4.32137 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=7/40 loss=3.61124 inner_val_loss=4.14104 inner_val_multiclass_log_loss=4.14106 best_multiclass_log_loss=4.14106 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=8/40 loss=3.37444 inner_val_loss=4.03238 inner_val_multiclass_log_loss=4.03227 best_multiclass_log_loss=4.03227 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=9/40 loss=3.14614 inner_val_loss=3.91143 inner_val_multiclass_log_loss=3.91143 best_multiclass_log_loss=3.91143 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=10/40 loss=2.93865 inner_val_loss=3.75981 inner_val_multiclass_log_loss=3.75985 best_multiclass_log_loss=3.75985 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=11/40 loss=2.71751 inner_val_loss=3.61725 inner_val_multiclass_log_loss=3.61727 best_multiclass_log_loss=3.61727 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=12/40 loss=2.51761 inner_val_loss=3.57008 inner_val_multiclass_log_loss=3.57002 best_multiclass_log_loss=3.57002 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=13/40 loss=2.31109 inner_val_loss=3.41362 inner_val_multiclass_log_loss=3.41353 best_multiclass_log_loss=3.41353 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=14/40 loss=2.13010 inner_val_loss=3.35824 inner_val_multiclass_log_loss=3.35825 best_multiclass_log_loss=3.35825 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=15/40 loss=1.95083 inner_val_loss=3.24787 inner_val_multiclass_log_loss=3.24785 best_multiclass_log_loss=3.24785 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=16/40 loss=1.78590 inner_val_loss=3.11615 inner_val_multiclass_log_loss=3.11605 best_multiclass_log_loss=3.11605 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=17/40 loss=1.61995 inner_val_loss=3.10558 inner_val_multiclass_log_loss=3.10559 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=18/40 loss=1.45544 inner_val_loss=3.12725 inner_val_multiclass_log_loss=3.12726 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=19/40 loss=1.31723 inner_val_loss=2.96704 inner_val_multiclass_log_loss=2.96702 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=20/40 loss=1.17842 inner_val_loss=3.05234 inner_val_multiclass_log_loss=3.05228 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=21/40 loss=1.06264 inner_val_loss=2.95265 inner_val_multiclass_log_loss=2.95266 best_multiclass_log_loss=2.95266 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=22/40 loss=0.95244 inner_val_loss=2.91211 inner_val_multiclass_log_loss=2.91221 best_multiclass_log_loss=2.91221 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=23/40 loss=0.84644 inner_val_loss=2.89159 inner_val_multiclass_log_loss=2.89156 best_multiclass_log_loss=2.89156 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=24/40 loss=0.76082 inner_val_loss=2.88187 inner_val_multiclass_log_loss=2.88200 best_multiclass_log_loss=2.88200 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=25/40 loss=0.67191 inner_val_loss=2.84233 inner_val_multiclass_log_loss=2.84237 best_multiclass_log_loss=2.84237 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=26/40 loss=0.60417 inner_val_loss=2.77625 inner_val_multiclass_log_loss=2.77628 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=27/40 loss=0.52400 inner_val_loss=2.81227 inner_val_multiclass_log_loss=2.81225 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=28/40 loss=0.46472 inner_val_loss=2.74761 inner_val_multiclass_log_loss=2.74756 best_multiclass_log_loss=2.74756 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=29/40 loss=0.40611 inner_val_loss=2.74257 inner_val_multiclass_log_loss=2.74254 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=30/40 loss=0.36938 inner_val_loss=2.75965 inner_val_multiclass_log_loss=2.75972 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=31/40 loss=0.32566 inner_val_loss=2.72053 inner_val_multiclass_log_loss=2.72051 best_multiclass_log_loss=2.72051 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=32/40 loss=0.30059 inner_val_loss=2.69751 inner_val_multiclass_log_loss=2.69749 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=33/40 loss=0.27015 inner_val_loss=2.74933 inner_val_multiclass_log_loss=2.74931 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=34/40 loss=0.23087 inner_val_loss=2.77536 inner_val_multiclass_log_loss=2.77540 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=35/40 loss=0.20538 inner_val_loss=2.74973 inner_val_multiclass_log_loss=2.74970 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 epoch=36/40 loss=0.18884 inner_val_loss=2.75416 inner_val_multiclass_log_loss=2.75420 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0
  fit=5 epoch=37/40 loss=0.16183 inner_val_loss=2.72750 inner_val_multiclass_log_loss=2.72753 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=5 full_refit_epoch=1/32 loss=4.77728
  fit=5 full_refit_epoch=2/32 loss=4.61421
  fit=5 full_refit_epoch=3/32 loss=4.44084
  fit=5 full_refit_epoch=4/32 loss=4.24429
  fit=5 full_refit_epoch=5/32 loss=4.01696
  fit=5 full_refit_epoch=6/32 loss=3.77332
  fit=5 full_refit_epoch=7/32 loss=3.51979
  fit=5 full_refit_epoch=8/32 loss=3.26840
  fit=5 full_refit_epoch=9/32 loss=3.03903
  fit=5 full_refit_epoch=10/32 loss=2.81296
  fit=5 full_refit_epoch=11/32 loss=2.58932
  fit=5 full_refit_epoch=12/32 loss=2.37527
  fit=5 full_refit_epoch=13/32 loss=2.16968
  fit=5 full_refit_epoch=14/32 loss=1.98022
  fit=5 full_refit_epoch=15/32 loss=1.79258
  fit=5 full_refit_epoch=16/32 loss=1.62738
  fit=5 full_refit_epoch=17/32 loss=1.46720
  fit=5 full_refit_epoch=18/32 loss=1.31258
  fit=5 full_refit_epoch=19/32 loss=1.17510
  fit=5 full_refit_epoch=20/32 loss=1.05290
  fit=5 full_refit_epoch=21/32 loss=0.92468
  fit=5 full_refit_epoch=22/32 loss=0.81936
  fit=5 full_refit_epoch=23/32 loss=0.72419
  fit=5 full_refit_epoch=24/32 loss=0.63480
  fit=5 full_refit_epoch=25/32 loss=0.55535
  fit=5 full_refit_epoch=26/32 loss=0.48229
  fit=5 full_refit_epoch=27/32 loss=0.42661
  fit=5 full_refit_epoch=28/32 loss=0.37705
  fit=5 full_refit_epoch=29/32 loss=0.31890
  fit=5 full_refit_epoch=30/32 loss=0.28566
  fit=5 full_refit_epoch=31/32 loss=0.26161
  fit=5 full_refit_epoch=32/32 loss=0.22707

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=baseline model=resnet18 metric=2.464116220981177 error=None minutes=13.22
START seed=47 phase=initial model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=1/40 loss=4.79604 inner_val_loss=4.73218 inner_val_multiclass_log_loss=4.73214 best_multiclass_log_loss=4.73214 best_epoch=1 seconds=2.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=2/40 loss=4.63253 inner_val_loss=4.67259 inner_val_multiclass_log_loss=4.67259 best_multiclass_log_loss=4.67259 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=3/40 loss=4.47386 inner_val_loss=4.55970 inner_val_multiclass_log_loss=4.55970 best_multiclass_log_loss=4.55970 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=4/40 loss=4.28732 inner_val_loss=4.44825 inner_val_multiclass_log_loss=4.44823 best_multiclass_log_loss=4.44823 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=5/40 loss=4.06886 inner_val_loss=4.33298 inner_val_multiclass_log_loss=4.33294 best_multiclass_log_loss=4.33294 best_epoch=5 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=6/40 loss=3.84643 inner_val_loss=4.13359 inner_val_multiclass_log_loss=4.13362 best_multiclass_log_loss=4.13362 best_epoch=6 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=7/40 loss=3.62140 inner_val_loss=3.97734 inner_val_multiclass_log_loss=3.97734 best_multiclass_log_loss=3.97734 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=8/40 loss=3.39511 inner_val_loss=3.88827 inner_val_multiclass_log_loss=3.88824 best_multiclass_log_loss=3.88824 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=9/40 loss=3.16729 inner_val_loss=3.77547 inner_val_multiclass_log_loss=3.77555 best_multiclass_log_loss=3.77555 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=10/40 loss=2.95336 inner_val_loss=3.69540 inner_val_multiclass_log_loss=3.69537 best_multiclass_log_loss=3.69537 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=11/40 loss=2.73357 inner_val_loss=3.54863 inner_val_multiclass_log_loss=3.54857 best_multiclass_log_loss=3.54857 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=12/40 loss=2.52061 inner_val_loss=3.44390 inner_val_multiclass_log_loss=3.44381 best_multiclass_log_loss=3.44381 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=13/40 loss=2.32619 inner_val_loss=3.36695 inner_val_multiclass_log_loss=3.36690 best_multiclass_log_loss=3.36690 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=14/40 loss=2.14268 inner_val_loss=3.29173 inner_val_multiclass_log_loss=3.29171 best_multiclass_log_loss=3.29171 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=15/40 loss=1.97246 inner_val_loss=3.19012 inner_val_multiclass_log_loss=3.19021 best_multiclass_log_loss=3.19021 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=16/40 loss=1.78584 inner_val_loss=3.08207 inner_val_multiclass_log_loss=3.08204 best_multiclass_log_loss=3.08204 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=17/40 loss=1.62255 inner_val_loss=3.02023 inner_val_multiclass_log_loss=3.02023 best_multiclass_log_loss=3.02023 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=18/40 loss=1.47096 inner_val_loss=2.96257 inner_val_multiclass_log_loss=2.96259 best_multiclass_log_loss=2.96259 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=19/40 loss=1.34683 inner_val_loss=2.88782 inner_val_multiclass_log_loss=2.88782 best_multiclass_log_loss=2.88782 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=20/40 loss=1.18152 inner_val_loss=2.87635 inner_val_multiclass_log_loss=2.87630 best_multiclass_log_loss=2.87630 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=21/40 loss=1.07280 inner_val_loss=2.82962 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=22/40 loss=0.96276 inner_val_loss=2.76426 inner_val_multiclass_log_loss=2.76424 best_multiclass_log_loss=2.76424 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=23/40 loss=0.85255 inner_val_loss=2.74589 inner_val_multiclass_log_loss=2.74593 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=24/40 loss=0.76815 inner_val_loss=2.76247 inner_val_multiclass_log_loss=2.76242 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=25/40 loss=0.66728 inner_val_loss=2.70668 inner_val_multiclass_log_loss=2.70668 best_multiclass_log_loss=2.70668 best_epoch=25 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=26/40 loss=0.60636 inner_val_loss=2.70543 inner_val_multiclass_log_loss=2.70541 best_multiclass_log_loss=2.70541 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=27/40 loss=0.52941 inner_val_loss=2.68617 inner_val_multiclass_log_loss=2.68613 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=28/40 loss=0.48062 inner_val_loss=2.69317 inner_val_multiclass_log_loss=2.69317 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=29/40 loss=0.41842 inner_val_loss=2.66156 inner_val_multiclass_log_loss=2.66154 best_multiclass_log_loss=2.66154 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=30/40 loss=0.36864 inner_val_loss=2.65680 inner_val_multiclass_log_loss=2.65670 best_multiclass_log_loss=2.65670 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=31/40 loss=0.32602 inner_val_loss=2.63176 inner_val_multiclass_log_loss=2.63183 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=32/40 loss=0.30625 inner_val_loss=2.66063 inner_val_multiclass_log_loss=2.66061 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=33/40 loss=0.26540 inner_val_loss=2.63391 inner_val_multiclass_log_loss=2.63389 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=34/40 loss=0.24684 inner_val_loss=2.62465 inner_val_multiclass_log_loss=2.62469 best_multiclass_log_loss=2.62469 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=35/40 loss=0.20674 inner_val_loss=2.61135 inner_val_multiclass_log_loss=2.61138 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=36/40 loss=0.19393 inner_val_loss=2.64488 inner_val_multiclass_log_loss=2.64494 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=37/40 loss=0.16779 inner_val_loss=2.61169 inner_val_multiclass_log_loss=2.61176 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=38/40 loss=0.14916 inner_val_loss=2.62670 inner_val_multiclass_log_loss=2.62673 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 epoch=39/40 loss=0.14285 inner_val_loss=2.61079 inner_val_multiclass_log_loss=2.61077 best_multiclass_log_loss=2.61077 best_epoch=39 seconds=2.1
  fit=6 epoch=40/40 loss=0.12808 inner_val_loss=2.59991 inner_val_multiclass_log_loss=2.59992 best_multiclass_log_loss=2.59992 best_epoch=40 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=6 full_refit_epoch=1/40 loss=4.79128
  fit=6 full_refit_epoch=2/40 loss=4.61581
  fit=6 full_refit_epoch=3/40 loss=4.43444
  fit=6 full_refit_epoch=4/40 loss=4.22564
  fit=6 full_refit_epoch=5/40 loss=3.98810
  fit=6 full_refit_epoch=6/40 loss=3.73859
  fit=6 full_refit_epoch=7/40 loss=3.49443
  fit=6 full_refit_epoch=8/40 loss=3.24746
  fit=6 full_refit_epoch=9/40 loss=3.01506
  fit=6 full_refit_epoch=10/40 loss=2.79312
  fit=6 full_refit_epoch=11/40 loss=2.56534
  fit=6 full_refit_epoch=12/40 loss=2.36016
  fit=6 full_refit_epoch=13/40 loss=2.15093
  fit=6 full_refit_epoch=14/40 loss=1.96154
  fit=6 full_refit_epoch=15/40 loss=1.77583
  fit=6 full_refit_epoch=16/40 loss=1.60714
  fit=6 full_refit_epoch=17/40 loss=1.44926
  fit=6 full_refit_epoch=18/40 loss=1.28955
  fit=6 full_refit_epoch=19/40 loss=1.15900
  fit=6 full_refit_epoch=20/40 loss=1.04187
  fit=6 full_refit_epoch=21/40 loss=0.92192
  fit=6 full_refit_epoch=22/40 loss=0.79462
  fit=6 full_refit_epoch=23/40 loss=0.71547
  fit=6 full_refit_epoch=24/40 loss=0.62853
  fit=6 full_refit_epoch=25/40 loss=0.55656
  fit=6 full_refit_epoch=26/40 loss=0.47864
  fit=6 full_refit_epoch=27/40 loss=0.42339
  fit=6 full_refit_epoch=28/40 loss=0.38009
  fit=6 full_refit_epoch=29/40 loss=0.32500
  fit=6 full_refit_epoch=30/40 loss=0.30116
  fit=6 full_refit_epoch=31/40 loss=0.24874
  fit=6 full_refit_epoch=32/40 loss=0.21832
  fit=6 full_refit_epoch=33/40 loss=0.19626
  fit=6 full_refit_epoch=34/40 loss=0.17990
  fit=6 full_refit_epoch=35/40 loss=0.15856
  fit=6 full_refit_epoch=36/40 loss=0.14075
  fit=6 full_refit_epoch=37/40 loss=0.12563
  fit=6 full_refit_epoch=38/40 loss=0.10919
  fit=6 full_refit_epoch=39/40 loss=0.10192
  fit=6 full_refit_epoch=40/40 loss=0.09188

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=1/40 loss=4.78529 inner_val_loss=4.74350 inner_val_multiclass_log_loss=4.74344 best_multiclass_log_loss=4.74344 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=2/40 loss=4.61759 inner_val_loss=4.66598 inner_val_multiclass_log_loss=4.66596 best_multiclass_log_loss=4.66596 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=3/40 loss=4.44644 inner_val_loss=4.56246 inner_val_multiclass_log_loss=4.56251 best_multiclass_log_loss=4.56251 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=4/40 loss=4.25722 inner_val_loss=4.46757 inner_val_multiclass_log_loss=4.46770 best_multiclass_log_loss=4.46770 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=5/40 loss=4.05331 inner_val_loss=4.32690 inner_val_multiclass_log_loss=4.32679 best_multiclass_log_loss=4.32679 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=6/40 loss=3.81373 inner_val_loss=4.18748 inner_val_multiclass_log_loss=4.18753 best_multiclass_log_loss=4.18753 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=7/40 loss=3.59817 inner_val_loss=4.05102 inner_val_multiclass_log_loss=4.05097 best_multiclass_log_loss=4.05097 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=8/40 loss=3.36733 inner_val_loss=3.88468 inner_val_multiclass_log_loss=3.88461 best_multiclass_log_loss=3.88461 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=9/40 loss=3.15824 inner_val_loss=3.79493 inner_val_multiclass_log_loss=3.79483 best_multiclass_log_loss=3.79483 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=10/40 loss=2.94215 inner_val_loss=3.64514 inner_val_multiclass_log_loss=3.64511 best_multiclass_log_loss=3.64511 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=11/40 loss=2.73160 inner_val_loss=3.58555 inner_val_multiclass_log_loss=3.58546 best_multiclass_log_loss=3.58546 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=12/40 loss=2.50724 inner_val_loss=3.40191 inner_val_multiclass_log_loss=3.40197 best_multiclass_log_loss=3.40197 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=13/40 loss=2.30979 inner_val_loss=3.28591 inner_val_multiclass_log_loss=3.28586 best_multiclass_log_loss=3.28586 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=14/40 loss=2.13234 inner_val_loss=3.23486 inner_val_multiclass_log_loss=3.23487 best_multiclass_log_loss=3.23487 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=15/40 loss=1.94883 inner_val_loss=3.08468 inner_val_multiclass_log_loss=3.08474 best_multiclass_log_loss=3.08474 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=16/40 loss=1.78527 inner_val_loss=2.99771 inner_val_multiclass_log_loss=2.99765 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=17/40 loss=1.62082 inner_val_loss=3.00123 inner_val_multiclass_log_loss=3.00123 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=18/40 loss=1.45911 inner_val_loss=2.90762 inner_val_multiclass_log_loss=2.90759 best_multiclass_log_loss=2.90759 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=19/40 loss=1.33887 inner_val_loss=2.81714 inner_val_multiclass_log_loss=2.81714 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=20/40 loss=1.20626 inner_val_loss=2.82729 inner_val_multiclass_log_loss=2.82734 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=21/40 loss=1.07785 inner_val_loss=2.74942 inner_val_multiclass_log_loss=2.74944 best_multiclass_log_loss=2.74944 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=22/40 loss=0.96543 inner_val_loss=2.68896 inner_val_multiclass_log_loss=2.68888 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=23/40 loss=0.85024 inner_val_loss=2.74155 inner_val_multiclass_log_loss=2.74154 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=24/40 loss=0.76864 inner_val_loss=2.66937 inner_val_multiclass_log_loss=2.66942 best_multiclass_log_loss=2.66942 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=25/40 loss=0.68431 inner_val_loss=2.63966 inner_val_multiclass_log_loss=2.63964 best_multiclass_log_loss=2.63964 best_epoch=25 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=26/40 loss=0.58750 inner_val_loss=2.63823 inner_val_multiclass_log_loss=2.63818 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=27/40 loss=0.51989 inner_val_loss=2.64882 inner_val_multiclass_log_loss=2.64874 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=28/40 loss=0.45891 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60250 best_multiclass_log_loss=2.60250 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=29/40 loss=0.41438 inner_val_loss=2.58168 inner_val_multiclass_log_loss=2.58177 best_multiclass_log_loss=2.58177 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=30/40 loss=0.36284 inner_val_loss=2.57724 inner_val_multiclass_log_loss=2.57728 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=31/40 loss=0.33492 inner_val_loss=2.57963 inner_val_multiclass_log_loss=2.57971 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=32/40 loss=0.28502 inner_val_loss=2.55369 inner_val_multiclass_log_loss=2.55378 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=33/40 loss=0.27036 inner_val_loss=2.56817 inner_val_multiclass_log_loss=2.56822 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=34/40 loss=0.22846 inner_val_loss=2.53099 inner_val_multiclass_log_loss=2.53092 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=35/40 loss=0.21733 inner_val_loss=2.57357 inner_val_multiclass_log_loss=2.57348 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=36/40 loss=0.18244 inner_val_loss=2.54892 inner_val_multiclass_log_loss=2.54897 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=37/40 loss=0.17517 inner_val_loss=2.54703 inner_val_multiclass_log_loss=2.54705 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 epoch=38/40 loss=0.15172 inner_val_loss=2.54890 inner_val_multiclass_log_loss=2.54889 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0
  fit=7 epoch=39/40 loss=0.13926 inner_val_loss=2.53601 inner_val_multiclass_log_loss=2.53600 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=7 full_refit_epoch=1/34 loss=4.77779
  fit=7 full_refit_epoch=2/34 loss=4.60078
  fit=7 full_refit_epoch=3/34 loss=4.41295
  fit=7 full_refit_epoch=4/34 loss=4.19824
  fit=7 full_refit_epoch=5/34 loss=3.95991
  fit=7 full_refit_epoch=6/34 loss=3.72031
  fit=7 full_refit_epoch=7/34 loss=3.47218
  fit=7 full_refit_epoch=8/34 loss=3.24296
  fit=7 full_refit_epoch=9/34 loss=2.99698
  fit=7 full_refit_epoch=10/34 loss=2.77741
  fit=7 full_refit_epoch=11/34 loss=2.54338
  fit=7 full_refit_epoch=12/34 loss=2.33114
  fit=7 full_refit_epoch=13/34 loss=2.12232
  fit=7 full_refit_epoch=14/34 loss=1.93304
  fit=7 full_refit_epoch=15/34 loss=1.75879
  fit=7 full_refit_epoch=16/34 loss=1.57506
  fit=7 full_refit_epoch=17/34 loss=1.41415
  fit=7 full_refit_epoch=18/34 loss=1.27479
  fit=7 full_refit_epoch=19/34 loss=1.13539
  fit=7 full_refit_epoch=20/34 loss=1.02070
  fit=7 full_refit_epoch=21/34 loss=0.89572
  fit=7 full_refit_epoch=22/34 loss=0.78825
  fit=7 full_refit_epoch=23/34 loss=0.69082
  fit=7 full_refit_epoch=24/34 loss=0.59551
  fit=7 full_refit_epoch=25/34 loss=0.53715
  fit=7 full_refit_epoch=26/34 loss=0.47102
  fit=7 full_refit_epoch=27/34 loss=0.41062
  fit=7 full_refit_epoch=28/34 loss=0.35460
  fit=7 full_refit_epoch=29/34 loss=0.31392
  fit=7 full_refit_epoch=30/34 loss=0.27658
  fit=7 full_refit_epoch=31/34 loss=0.24613
  fit=7 full_refit_epoch=32/34 loss=0.21734
  fit=7 full_refit_epoch=33/34 loss=0.19095
  fit=7 full_refit_epoch=34/34 loss=0.17254

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=1/40 loss=4.78598 inner_val_loss=4.74895 inner_val_multiclass_log_loss=4.74886 best_multiclass_log_loss=4.74886 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=2/40 loss=4.61747 inner_val_loss=4.67133 inner_val_multiclass_log_loss=4.67137 best_multiclass_log_loss=4.67137 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=3/40 loss=4.44421 inner_val_loss=4.58167 inner_val_multiclass_log_loss=4.58166 best_multiclass_log_loss=4.58166 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=4/40 loss=4.25613 inner_val_loss=4.44833 inner_val_multiclass_log_loss=4.44822 best_multiclass_log_loss=4.44822 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=5/40 loss=4.03231 inner_val_loss=4.29905 inner_val_multiclass_log_loss=4.29900 best_multiclass_log_loss=4.29900 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=6/40 loss=3.80887 inner_val_loss=4.16650 inner_val_multiclass_log_loss=4.16655 best_multiclass_log_loss=4.16655 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=7/40 loss=3.58425 inner_val_loss=4.07659 inner_val_multiclass_log_loss=4.07661 best_multiclass_log_loss=4.07661 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=8/40 loss=3.36133 inner_val_loss=3.91148 inner_val_multiclass_log_loss=3.91148 best_multiclass_log_loss=3.91148 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=9/40 loss=3.13965 inner_val_loss=3.69225 inner_val_multiclass_log_loss=3.69228 best_multiclass_log_loss=3.69228 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=10/40 loss=2.92091 inner_val_loss=3.63148 inner_val_multiclass_log_loss=3.63156 best_multiclass_log_loss=3.63156 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=11/40 loss=2.70039 inner_val_loss=3.50666 inner_val_multiclass_log_loss=3.50662 best_multiclass_log_loss=3.50662 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=12/40 loss=2.50043 inner_val_loss=3.37099 inner_val_multiclass_log_loss=3.37102 best_multiclass_log_loss=3.37102 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=13/40 loss=2.29484 inner_val_loss=3.26625 inner_val_multiclass_log_loss=3.26612 best_multiclass_log_loss=3.26612 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=14/40 loss=2.12114 inner_val_loss=3.16823 inner_val_multiclass_log_loss=3.16824 best_multiclass_log_loss=3.16824 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=15/40 loss=1.93977 inner_val_loss=3.08539 inner_val_multiclass_log_loss=3.08539 best_multiclass_log_loss=3.08539 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=16/40 loss=1.76654 inner_val_loss=2.99735 inner_val_multiclass_log_loss=2.99742 best_multiclass_log_loss=2.99742 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=17/40 loss=1.60779 inner_val_loss=2.89870 inner_val_multiclass_log_loss=2.89881 best_multiclass_log_loss=2.89881 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=18/40 loss=1.45640 inner_val_loss=2.85110 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=19/40 loss=1.30639 inner_val_loss=2.77251 inner_val_multiclass_log_loss=2.77241 best_multiclass_log_loss=2.77241 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=20/40 loss=1.16936 inner_val_loss=2.75131 inner_val_multiclass_log_loss=2.75130 best_multiclass_log_loss=2.75130 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=21/40 loss=1.05572 inner_val_loss=2.69500 inner_val_multiclass_log_loss=2.69506 best_multiclass_log_loss=2.69506 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=22/40 loss=0.94055 inner_val_loss=2.67022 inner_val_multiclass_log_loss=2.67029 best_multiclass_log_loss=2.67029 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=23/40 loss=0.85175 inner_val_loss=2.59384 inner_val_multiclass_log_loss=2.59380 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=24/40 loss=0.75602 inner_val_loss=2.59947 inner_val_multiclass_log_loss=2.59943 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=25/40 loss=0.66566 inner_val_loss=2.57623 inner_val_multiclass_log_loss=2.57619 best_multiclass_log_loss=2.57619 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=26/40 loss=0.58957 inner_val_loss=2.56685 inner_val_multiclass_log_loss=2.56687 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=27/40 loss=0.52900 inner_val_loss=2.57257 inner_val_multiclass_log_loss=2.57252 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=28/40 loss=0.46072 inner_val_loss=2.54440 inner_val_multiclass_log_loss=2.54439 best_multiclass_log_loss=2.54439 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=29/40 loss=0.41680 inner_val_loss=2.51023 inner_val_multiclass_log_loss=2.51027 best_multiclass_log_loss=2.51027 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=30/40 loss=0.35341 inner_val_loss=2.48075 inner_val_multiclass_log_loss=2.48079 best_multiclass_log_loss=2.48079 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=31/40 loss=0.32624 inner_val_loss=2.47039 inner_val_multiclass_log_loss=2.47038 best_multiclass_log_loss=2.47038 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=32/40 loss=0.29237 inner_val_loss=2.45936 inner_val_multiclass_log_loss=2.45932 best_multiclass_log_loss=2.45932 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=33/40 loss=0.26956 inner_val_loss=2.44038 inner_val_multiclass_log_loss=2.44039 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=34/40 loss=0.23673 inner_val_loss=2.44873 inner_val_multiclass_log_loss=2.44875 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=35/40 loss=0.20594 inner_val_loss=2.43773 inner_val_multiclass_log_loss=2.43777 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=36/40 loss=0.18920 inner_val_loss=2.46623 inner_val_multiclass_log_loss=2.46618 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=37/40 loss=0.17468 inner_val_loss=2.42681 inner_val_multiclass_log_loss=2.42687 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=38/40 loss=0.16045 inner_val_loss=2.43230 inner_val_multiclass_log_loss=2.43224 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 epoch=39/40 loss=0.13876 inner_val_loss=2.42945 inner_val_multiclass_log_loss=2.42945 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0
  fit=8 epoch=40/40 loss=0.12840 inner_val_loss=2.42231 inner_val_multiclass_log_loss=2.42228 best_multiclass_log_loss=2.42228 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=8 full_refit_epoch=1/40 loss=4.77988
  fit=8 full_refit_epoch=2/40 loss=4.60904
  fit=8 full_refit_epoch=3/40 loss=4.42586
  fit=8 full_refit_epoch=4/40 loss=4.21264
  fit=8 full_refit_epoch=5/40 loss=3.98115
  fit=8 full_refit_epoch=6/40 loss=3.72980
  fit=8 full_refit_epoch=7/40 loss=3.48740
  fit=8 full_refit_epoch=8/40 loss=3.24153
  fit=8 full_refit_epoch=9/40 loss=3.01609
  fit=8 full_refit_epoch=10/40 loss=2.77404
  fit=8 full_refit_epoch=11/40 loss=2.54436
  fit=8 full_refit_epoch=12/40 loss=2.33251
  fit=8 full_refit_epoch=13/40 loss=2.12541
  fit=8 full_refit_epoch=14/40 loss=1.94018
  fit=8 full_refit_epoch=15/40 loss=1.74784
  fit=8 full_refit_epoch=16/40 loss=1.57977
  fit=8 full_refit_epoch=17/40 loss=1.41598
  fit=8 full_refit_epoch=18/40 loss=1.28322
  fit=8 full_refit_epoch=19/40 loss=1.12908
  fit=8 full_refit_epoch=20/40 loss=1.00664
  fit=8 full_refit_epoch=21/40 loss=0.89356
  fit=8 full_refit_epoch=22/40 loss=0.79305
  fit=8 full_refit_epoch=23/40 loss=0.70667
  fit=8 full_refit_epoch=24/40 loss=0.60575
  fit=8 full_refit_epoch=25/40 loss=0.53220
  fit=8 full_refit_epoch=26/40 loss=0.47780
  fit=8 full_refit_epoch=27/40 loss=0.41461
  fit=8 full_refit_epoch=28/40 loss=0.36608
  fit=8 full_refit_epoch=29/40 loss=0.32224
  fit=8 full_refit_epoch=30/40 loss=0.27960
  fit=8 full_refit_epoch=31/40 loss=0.25322
  fit=8 full_refit_epoch=32/40 loss=0.21666
  fit=8 full_refit_epoch=33/40 loss=0.19701
  fit=8 full_refit_epoch=34/40 loss=0.17425
  fit=8 full_refit_epoch=35/40 loss=0.15471
  fit=8 full_refit_epoch=36/40 loss=0.13652
  fit=8 full_refit_epoch=37/40 loss=0.12648
  fit=8 full_refit_epoch=38/40 loss=0.10761
  fit=8 full_refit_epoch=39/40 loss=0.10610
  fit=8 full_refit_epoch=40/40 loss=0.09535

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=1/40 loss=4.78616 inner_val_loss=4.72490 inner_val_multiclass_log_loss=4.72474 best_multiclass_log_loss=4.72474 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=2/40 loss=4.61983 inner_val_loss=4.62753 inner_val_multiclass_log_loss=4.62759 best_multiclass_log_loss=4.62759 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=3/40 loss=4.45797 inner_val_loss=4.54643 inner_val_multiclass_log_loss=4.54643 best_multiclass_log_loss=4.54643 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=4/40 loss=4.28081 inner_val_loss=4.46488 inner_val_multiclass_log_loss=4.46488 best_multiclass_log_loss=4.46488 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=5/40 loss=4.08048 inner_val_loss=4.31625 inner_val_multiclass_log_loss=4.31634 best_multiclass_log_loss=4.31634 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=6/40 loss=3.86825 inner_val_loss=4.18847 inner_val_multiclass_log_loss=4.18838 best_multiclass_log_loss=4.18838 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=7/40 loss=3.64301 inner_val_loss=4.05750 inner_val_multiclass_log_loss=4.05740 best_multiclass_log_loss=4.05740 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=8/40 loss=3.40436 inner_val_loss=3.87396 inner_val_multiclass_log_loss=3.87396 best_multiclass_log_loss=3.87396 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=9/40 loss=3.19662 inner_val_loss=3.75727 inner_val_multiclass_log_loss=3.75729 best_multiclass_log_loss=3.75729 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=10/40 loss=2.97522 inner_val_loss=3.66436 inner_val_multiclass_log_loss=3.66434 best_multiclass_log_loss=3.66434 best_epoch=10 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=11/40 loss=2.74266 inner_val_loss=3.47013 inner_val_multiclass_log_loss=3.47004 best_multiclass_log_loss=3.47004 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=12/40 loss=2.55972 inner_val_loss=3.33333 inner_val_multiclass_log_loss=3.33334 best_multiclass_log_loss=3.33334 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=13/40 loss=2.35769 inner_val_loss=3.28423 inner_val_multiclass_log_loss=3.28425 best_multiclass_log_loss=3.28425 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=14/40 loss=2.16565 inner_val_loss=3.15414 inner_val_multiclass_log_loss=3.15408 best_multiclass_log_loss=3.15408 best_epoch=14 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=15/40 loss=1.98688 inner_val_loss=3.07231 inner_val_multiclass_log_loss=3.07231 best_multiclass_log_loss=3.07231 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=16/40 loss=1.81668 inner_val_loss=3.00154 inner_val_multiclass_log_loss=3.00149 best_multiclass_log_loss=3.00149 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=17/40 loss=1.66713 inner_val_loss=2.92328 inner_val_multiclass_log_loss=2.92325 best_multiclass_log_loss=2.92325 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=18/40 loss=1.52455 inner_val_loss=2.86711 inner_val_multiclass_log_loss=2.86716 best_multiclass_log_loss=2.86716 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=19/40 loss=1.35649 inner_val_loss=2.82959 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=20/40 loss=1.23937 inner_val_loss=2.70085 inner_val_multiclass_log_loss=2.70082 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=21/40 loss=1.11458 inner_val_loss=2.73949 inner_val_multiclass_log_loss=2.73944 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=22/40 loss=1.00135 inner_val_loss=2.69911 inner_val_multiclass_log_loss=2.69906 best_multiclass_log_loss=2.69906 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=23/40 loss=0.90562 inner_val_loss=2.60998 inner_val_multiclass_log_loss=2.60992 best_multiclass_log_loss=2.60992 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=24/40 loss=0.79425 inner_val_loss=2.60439 inner_val_multiclass_log_loss=2.60439 best_multiclass_log_loss=2.60439 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=25/40 loss=0.70615 inner_val_loss=2.58918 inner_val_multiclass_log_loss=2.58917 best_multiclass_log_loss=2.58917 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=26/40 loss=0.63300 inner_val_loss=2.53947 inner_val_multiclass_log_loss=2.53950 best_multiclass_log_loss=2.53950 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=27/40 loss=0.56248 inner_val_loss=2.49854 inner_val_multiclass_log_loss=2.49855 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=28/40 loss=0.50699 inner_val_loss=2.51626 inner_val_multiclass_log_loss=2.51622 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=29/40 loss=0.44951 inner_val_loss=2.53317 inner_val_multiclass_log_loss=2.53312 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=30/40 loss=0.40239 inner_val_loss=2.50438 inner_val_multiclass_log_loss=2.50445 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=31/40 loss=0.35139 inner_val_loss=2.49836 inner_val_multiclass_log_loss=2.49834 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=32/40 loss=0.31519 inner_val_loss=2.49952 inner_val_multiclass_log_loss=2.49954 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=33/40 loss=0.28856 inner_val_loss=2.42672 inner_val_multiclass_log_loss=2.42672 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=34/40 loss=0.25429 inner_val_loss=2.45267 inner_val_multiclass_log_loss=2.45271 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=35/40 loss=0.22645 inner_val_loss=2.42072 inner_val_multiclass_log_loss=2.42068 best_multiclass_log_loss=2.42068 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=36/40 loss=0.20706 inner_val_loss=2.41048 inner_val_multiclass_log_loss=2.41044 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=37/40 loss=0.18824 inner_val_loss=2.41161 inner_val_multiclass_log_loss=2.41162 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=38/40 loss=0.17108 inner_val_loss=2.45061 inner_val_multiclass_log_loss=2.45059 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 epoch=39/40 loss=0.14891 inner_val_loss=2.41139 inner_val_multiclass_log_loss=2.41135 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0
  fit=9 epoch=40/40 loss=0.13585 inner_val_loss=2.40886 inner_val_multiclass_log_loss=2.40889 best_multiclass_log_loss=2.40889 best_epoch=40 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=9 full_refit_epoch=1/40 loss=4.78382
  fit=9 full_refit_epoch=2/40 loss=4.60593
  fit=9 full_refit_epoch=3/40 loss=4.42989
  fit=9 full_refit_epoch=4/40 loss=4.22715
  fit=9 full_refit_epoch=5/40 loss=3.99684
  fit=9 full_refit_epoch=6/40 loss=3.75249
  fit=9 full_refit_epoch=7/40 loss=3.51416
  fit=9 full_refit_epoch=8/40 loss=3.26404
  fit=9 full_refit_epoch=9/40 loss=3.02605
  fit=9 full_refit_epoch=10/40 loss=2.79345
  fit=9 full_refit_epoch=11/40 loss=2.56204
  fit=9 full_refit_epoch=12/40 loss=2.36419
  fit=9 full_refit_epoch=13/40 loss=2.15368
  fit=9 full_refit_epoch=14/40 loss=1.96638
  fit=9 full_refit_epoch=15/40 loss=1.78290
  fit=9 full_refit_epoch=16/40 loss=1.62735
  fit=9 full_refit_epoch=17/40 loss=1.46567
  fit=9 full_refit_epoch=18/40 loss=1.31435
  fit=9 full_refit_epoch=19/40 loss=1.17849
  fit=9 full_refit_epoch=20/40 loss=1.04482
  fit=9 full_refit_epoch=21/40 loss=0.93599
  fit=9 full_refit_epoch=22/40 loss=0.82802
  fit=9 full_refit_epoch=23/40 loss=0.73241
  fit=9 full_refit_epoch=24/40 loss=0.64588
  fit=9 full_refit_epoch=25/40 loss=0.57137
  fit=9 full_refit_epoch=26/40 loss=0.49800
  fit=9 full_refit_epoch=27/40 loss=0.43521
  fit=9 full_refit_epoch=28/40 loss=0.39097
  fit=9 full_refit_epoch=29/40 loss=0.35223
  fit=9 full_refit_epoch=30/40 loss=0.30540
  fit=9 full_refit_epoch=31/40 loss=0.26708
  fit=9 full_refit_epoch=32/40 loss=0.23549
  fit=9 full_refit_epoch=33/40 loss=0.20737
  fit=9 full_refit_epoch=34/40 loss=0.18645
  fit=9 full_refit_epoch=35/40 loss=0.16723
  fit=9 full_refit_epoch=36/40 loss=0.14765
  fit=9 full_refit_epoch=37/40 loss=0.13257
  fit=9 full_refit_epoch=38/40 loss=0.12424
  fit=9 full_refit_epoch=39/40 loss=0.10739
  fit=9 full_refit_epoch=40/40 loss=0.09676

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=1/40 loss=4.78442 inner_val_loss=4.74988 inner_val_multiclass_log_loss=4.74991 best_multiclass_log_loss=4.74991 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=2/40 loss=4.61357 inner_val_loss=4.68988 inner_val_multiclass_log_loss=4.68997 best_multiclass_log_loss=4.68997 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=3/40 loss=4.45425 inner_val_loss=4.60145 inner_val_multiclass_log_loss=4.60136 best_multiclass_log_loss=4.60136 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=4/40 loss=4.27011 inner_val_loss=4.52010 inner_val_multiclass_log_loss=4.52011 best_multiclass_log_loss=4.52011 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=5/40 loss=4.06233 inner_val_loss=4.37511 inner_val_multiclass_log_loss=4.37502 best_multiclass_log_loss=4.37502 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=6/40 loss=3.84104 inner_val_loss=4.32146 inner_val_multiclass_log_loss=4.32137 best_multiclass_log_loss=4.32137 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=7/40 loss=3.61124 inner_val_loss=4.14104 inner_val_multiclass_log_loss=4.14106 best_multiclass_log_loss=4.14106 best_epoch=7 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=8/40 loss=3.37444 inner_val_loss=4.03238 inner_val_multiclass_log_loss=4.03227 best_multiclass_log_loss=4.03227 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=9/40 loss=3.14614 inner_val_loss=3.91143 inner_val_multiclass_log_loss=3.91143 best_multiclass_log_loss=3.91143 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=10/40 loss=2.93865 inner_val_loss=3.75981 inner_val_multiclass_log_loss=3.75985 best_multiclass_log_loss=3.75985 best_epoch=10 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=11/40 loss=2.71751 inner_val_loss=3.61725 inner_val_multiclass_log_loss=3.61727 best_multiclass_log_loss=3.61727 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=12/40 loss=2.51761 inner_val_loss=3.57008 inner_val_multiclass_log_loss=3.57002 best_multiclass_log_loss=3.57002 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=13/40 loss=2.31109 inner_val_loss=3.41362 inner_val_multiclass_log_loss=3.41353 best_multiclass_log_loss=3.41353 best_epoch=13 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=14/40 loss=2.13010 inner_val_loss=3.35824 inner_val_multiclass_log_loss=3.35825 best_multiclass_log_loss=3.35825 best_epoch=14 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=15/40 loss=1.95083 inner_val_loss=3.24787 inner_val_multiclass_log_loss=3.24785 best_multiclass_log_loss=3.24785 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=16/40 loss=1.78590 inner_val_loss=3.11615 inner_val_multiclass_log_loss=3.11605 best_multiclass_log_loss=3.11605 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=17/40 loss=1.61995 inner_val_loss=3.10558 inner_val_multiclass_log_loss=3.10559 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=18/40 loss=1.45544 inner_val_loss=3.12725 inner_val_multiclass_log_loss=3.12726 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=19/40 loss=1.31723 inner_val_loss=2.96704 inner_val_multiclass_log_loss=2.96702 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=20/40 loss=1.17842 inner_val_loss=3.05234 inner_val_multiclass_log_loss=3.05228 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=21/40 loss=1.06264 inner_val_loss=2.95265 inner_val_multiclass_log_loss=2.95266 best_multiclass_log_loss=2.95266 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=22/40 loss=0.95244 inner_val_loss=2.91211 inner_val_multiclass_log_loss=2.91221 best_multiclass_log_loss=2.91221 best_epoch=22 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=23/40 loss=0.84644 inner_val_loss=2.89159 inner_val_multiclass_log_loss=2.89156 best_multiclass_log_loss=2.89156 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=24/40 loss=0.76082 inner_val_loss=2.88187 inner_val_multiclass_log_loss=2.88200 best_multiclass_log_loss=2.88200 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=25/40 loss=0.67191 inner_val_loss=2.84233 inner_val_multiclass_log_loss=2.84237 best_multiclass_log_loss=2.84237 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=26/40 loss=0.60417 inner_val_loss=2.77625 inner_val_multiclass_log_loss=2.77628 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=27/40 loss=0.52400 inner_val_loss=2.81227 inner_val_multiclass_log_loss=2.81225 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=28/40 loss=0.46472 inner_val_loss=2.74761 inner_val_multiclass_log_loss=2.74756 best_multiclass_log_loss=2.74756 best_epoch=28 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=29/40 loss=0.40611 inner_val_loss=2.74257 inner_val_multiclass_log_loss=2.74254 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=30/40 loss=0.36938 inner_val_loss=2.75965 inner_val_multiclass_log_loss=2.75972 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=31/40 loss=0.32566 inner_val_loss=2.72053 inner_val_multiclass_log_loss=2.72051 best_multiclass_log_loss=2.72051 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=32/40 loss=0.30059 inner_val_loss=2.69751 inner_val_multiclass_log_loss=2.69749 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=33/40 loss=0.27015 inner_val_loss=2.74933 inner_val_multiclass_log_loss=2.74931 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=34/40 loss=0.23087 inner_val_loss=2.77536 inner_val_multiclass_log_loss=2.77540 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=35/40 loss=0.20538 inner_val_loss=2.74973 inner_val_multiclass_log_loss=2.74970 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 epoch=36/40 loss=0.18884 inner_val_loss=2.75416 inner_val_multiclass_log_loss=2.75420 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0
  fit=10 epoch=37/40 loss=0.16183 inner_val_loss=2.72750 inner_val_multiclass_log_loss=2.72753 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=10 full_refit_epoch=1/32 loss=4.77728
  fit=10 full_refit_epoch=2/32 loss=4.61421
  fit=10 full_refit_epoch=3/32 loss=4.44084
  fit=10 full_refit_epoch=4/32 loss=4.24429
  fit=10 full_refit_epoch=5/32 loss=4.01696
  fit=10 full_refit_epoch=6/32 loss=3.77332
  fit=10 full_refit_epoch=7/32 loss=3.51979
  fit=10 full_refit_epoch=8/32 loss=3.26840
  fit=10 full_refit_epoch=9/32 loss=3.03903
  fit=10 full_refit_epoch=10/32 loss=2.81296
  fit=10 full_refit_epoch=11/32 loss=2.58932
  fit=10 full_refit_epoch=12/32 loss=2.37527
  fit=10 full_refit_epoch=13/32 loss=2.16968
  fit=10 full_refit_epoch=14/32 loss=1.98022
  fit=10 full_refit_epoch=15/32 loss=1.79258
  fit=10 full_refit_epoch=16/32 loss=1.62738
  fit=10 full_refit_epoch=17/32 loss=1.46720
  fit=10 full_refit_epoch=18/32 loss=1.31258
  fit=10 full_refit_epoch=19/32 loss=1.17510
  fit=10 full_refit_epoch=20/32 loss=1.05290
  fit=10 full_refit_epoch=21/32 loss=0.92468
  fit=10 full_refit_epoch=22/32 loss=0.81936
  fit=10 full_refit_epoch=23/32 loss=0.72419
  fit=10 full_refit_epoch=24/32 loss=0.63480
  fit=10 full_refit_epoch=25/32 loss=0.55535
  fit=10 full_refit_epoch=26/32 loss=0.48229
  fit=10 full_refit_epoch=27/32 loss=0.42661
  fit=10 full_refit_epoch=28/32 loss=0.37705
  fit=10 full_refit_epoch=29/32 loss=0.31890
  fit=10 full_refit_epoch=30/32 loss=0.28566
  fit=10 full_refit_epoch=31/32 loss=0.26161
  fit=10 full_refit_epoch=32/32 loss=0.22707

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=initial model=resnet18 metric=2.464116220981177 error=None minutes=13.15
START seed=47 phase=initial model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=1/40 loss=5.01010 inner_val_loss=4.80068 inner_val_multiclass_log_loss=4.80060 best_multiclass_log_loss=4.80060 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=2/40 loss=3.86606 inner_val_loss=4.45876 inner_val_multiclass_log_loss=4.45880 best_multiclass_log_loss=4.45880 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=3/40 loss=2.92148 inner_val_loss=4.11238 inner_val_multiclass_log_loss=4.11225 best_multiclass_log_loss=4.11225 best_epoch=3 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=4/40 loss=2.11127 inner_val_loss=3.86819 inner_val_multiclass_log_loss=3.86822 best_multiclass_log_loss=3.86822 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=5/40 loss=1.48764 inner_val_loss=3.68414 inner_val_multiclass_log_loss=3.68418 best_multiclass_log_loss=3.68418 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=6/40 loss=1.05689 inner_val_loss=3.49516 inner_val_multiclass_log_loss=3.49521 best_multiclass_log_loss=3.49521 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=7/40 loss=0.71140 inner_val_loss=3.34357 inner_val_multiclass_log_loss=3.34358 best_multiclass_log_loss=3.34358 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=8/40 loss=0.49035 inner_val_loss=3.27626 inner_val_multiclass_log_loss=3.27629 best_multiclass_log_loss=3.27629 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=9/40 loss=0.35021 inner_val_loss=3.25475 inner_val_multiclass_log_loss=3.25468 best_multiclass_log_loss=3.25468 best_epoch=9 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=10/40 loss=0.26594 inner_val_loss=3.21665 inner_val_multiclass_log_loss=3.21665 best_multiclass_log_loss=3.21665 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=11/40 loss=0.20252 inner_val_loss=3.15687 inner_val_multiclass_log_loss=3.15686 best_multiclass_log_loss=3.15686 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=12/40 loss=0.15865 inner_val_loss=3.08151 inner_val_multiclass_log_loss=3.08153 best_multiclass_log_loss=3.08153 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=13/40 loss=0.12785 inner_val_loss=3.07211 inner_val_multiclass_log_loss=3.07216 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=14/40 loss=0.10510 inner_val_loss=3.08785 inner_val_multiclass_log_loss=3.08783 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=15/40 loss=0.08510 inner_val_loss=3.08263 inner_val_multiclass_log_loss=3.08265 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=16/40 loss=0.08460 inner_val_loss=3.07192 inner_val_multiclass_log_loss=3.07196 best_multiclass_log_loss=3.07196 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=17/40 loss=0.07478 inner_val_loss=3.04369 inner_val_multiclass_log_loss=3.04378 best_multiclass_log_loss=3.04378 best_epoch=17 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=18/40 loss=0.06367 inner_val_loss=2.98642 inner_val_multiclass_log_loss=2.98641 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=19/40 loss=0.06794 inner_val_loss=2.98767 inner_val_multiclass_log_loss=2.98764 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=20/40 loss=0.04836 inner_val_loss=2.99491 inner_val_multiclass_log_loss=2.99492 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=21/40 loss=0.04701 inner_val_loss=2.97468 inner_val_multiclass_log_loss=2.97462 best_multiclass_log_loss=2.97462 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=22/40 loss=0.04027 inner_val_loss=2.97743 inner_val_multiclass_log_loss=2.97751 best_multiclass_log_loss=2.97462 best_epoch=21 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=23/40 loss=0.04057 inner_val_loss=2.92894 inner_val_multiclass_log_loss=2.92900 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=24/40 loss=0.03630 inner_val_loss=2.95130 inner_val_multiclass_log_loss=2.95126 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=25/40 loss=0.03352 inner_val_loss=2.96364 inner_val_multiclass_log_loss=2.96357 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=26/40 loss=0.03007 inner_val_loss=2.91611 inner_val_multiclass_log_loss=2.91617 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=27/40 loss=0.03253 inner_val_loss=2.92490 inner_val_multiclass_log_loss=2.92486 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=28/40 loss=0.03118 inner_val_loss=2.94123 inner_val_multiclass_log_loss=2.94135 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=29/40 loss=0.03109 inner_val_loss=2.90074 inner_val_multiclass_log_loss=2.90077 best_multiclass_log_loss=2.90077 best_epoch=29 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=30/40 loss=0.02353 inner_val_loss=2.88433 inner_val_multiclass_log_loss=2.88431 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=31/40 loss=0.01862 inner_val_loss=2.91946 inner_val_multiclass_log_loss=2.91947 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=32/40 loss=0.02842 inner_val_loss=2.94810 inner_val_multiclass_log_loss=2.94814 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=33/40 loss=0.01988 inner_val_loss=2.90140 inner_val_multiclass_log_loss=2.90133 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 epoch=34/40 loss=0.02532 inner_val_loss=2.90284 inner_val_multiclass_log_loss=2.90280 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.0
  fit=11 epoch=35/40 loss=0.01641 inner_val_loss=2.89318 inner_val_multiclass_log_loss=2.89317 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=11 full_refit_epoch=1/30 loss=4.97104
  fit=11 full_refit_epoch=2/30 loss=3.79284
  fit=11 full_refit_epoch=3/30 loss=2.79163
  fit=11 full_refit_epoch=4/30 loss=1.97404
  fit=11 full_refit_epoch=5/30 loss=1.39008
  fit=11 full_refit_epoch=6/30 loss=0.92452
  fit=11 full_refit_epoch=7/30 loss=0.62449
  fit=11 full_refit_epoch=8/30 loss=0.41424
  fit=11 full_refit_epoch=9/30 loss=0.28214
  fit=11 full_refit_epoch=10/30 loss=0.21174
  fit=11 full_refit_epoch=11/30 loss=0.15753
  fit=11 full_refit_epoch=12/30 loss=0.12486
  fit=11 full_refit_epoch=13/30 loss=0.09789
  fit=11 full_refit_epoch=14/30 loss=0.08348
  fit=11 full_refit_epoch=15/30 loss=0.07206
  fit=11 full_refit_epoch=16/30 loss=0.06392
  fit=11 full_refit_epoch=17/30 loss=0.05052
  fit=11 full_refit_epoch=18/30 loss=0.04391
  fit=11 full_refit_epoch=19/30 loss=0.04142
  fit=11 full_refit_epoch=20/30 loss=0.03857
  fit=11 full_refit_epoch=21/30 loss=0.03237
  fit=11 full_refit_epoch=22/30 loss=0.02738
  fit=11 full_refit_epoch=23/30 loss=0.02653
  fit=11 full_refit_epoch=24/30 loss=0.02426
  fit=11 full_refit_epoch=25/30 loss=0.02314
  fit=11 full_refit_epoch=26/30 loss=0.01994
  fit=11 full_refit_epoch=27/30 loss=0.01859
  fit=11 full_refit_epoch=28/30 loss=0.01889
  fit=11 full_refit_epoch=29/30 loss=0.01694
  fit=11 full_refit_epoch=30/30 loss=0.01770

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=1/40 loss=4.97853 inner_val_loss=4.82274 inner_val_multiclass_log_loss=4.82261 best_multiclass_log_loss=4.82261 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=2/40 loss=3.80224 inner_val_loss=4.51570 inner_val_multiclass_log_loss=4.51573 best_multiclass_log_loss=4.51573 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=3/40 loss=2.83644 inner_val_loss=4.18771 inner_val_multiclass_log_loss=4.18763 best_multiclass_log_loss=4.18763 best_epoch=3 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=4/40 loss=2.04215 inner_val_loss=3.93679 inner_val_multiclass_log_loss=3.93676 best_multiclass_log_loss=3.93676 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=5/40 loss=1.48743 inner_val_loss=3.73534 inner_val_multiclass_log_loss=3.73535 best_multiclass_log_loss=3.73535 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=6/40 loss=1.02682 inner_val_loss=3.57692 inner_val_multiclass_log_loss=3.57679 best_multiclass_log_loss=3.57679 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=7/40 loss=0.67756 inner_val_loss=3.39418 inner_val_multiclass_log_loss=3.39421 best_multiclass_log_loss=3.39421 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=8/40 loss=0.49210 inner_val_loss=3.30826 inner_val_multiclass_log_loss=3.30835 best_multiclass_log_loss=3.30835 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=9/40 loss=0.35624 inner_val_loss=3.24481 inner_val_multiclass_log_loss=3.24488 best_multiclass_log_loss=3.24488 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=10/40 loss=0.25484 inner_val_loss=3.22805 inner_val_multiclass_log_loss=3.22796 best_multiclass_log_loss=3.22796 best_epoch=10 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=11/40 loss=0.21448 inner_val_loss=3.21863 inner_val_multiclass_log_loss=3.21858 best_multiclass_log_loss=3.21858 best_epoch=11 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=12/40 loss=0.15821 inner_val_loss=3.12964 inner_val_multiclass_log_loss=3.12965 best_multiclass_log_loss=3.12965 best_epoch=12 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=13/40 loss=0.13378 inner_val_loss=3.10256 inner_val_multiclass_log_loss=3.10258 best_multiclass_log_loss=3.10258 best_epoch=13 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=14/40 loss=0.10728 inner_val_loss=3.08182 inner_val_multiclass_log_loss=3.08175 best_multiclass_log_loss=3.08175 best_epoch=14 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=15/40 loss=0.10725 inner_val_loss=3.05171 inner_val_multiclass_log_loss=3.05171 best_multiclass_log_loss=3.05171 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=16/40 loss=0.08221 inner_val_loss=3.04101 inner_val_multiclass_log_loss=3.04105 best_multiclass_log_loss=3.04105 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=17/40 loss=0.07468 inner_val_loss=3.02810 inner_val_multiclass_log_loss=3.02820 best_multiclass_log_loss=3.02820 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=18/40 loss=0.06218 inner_val_loss=3.03901 inner_val_multiclass_log_loss=3.03903 best_multiclass_log_loss=3.02820 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=19/40 loss=0.06554 inner_val_loss=3.01746 inner_val_multiclass_log_loss=3.01749 best_multiclass_log_loss=3.01749 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=20/40 loss=0.05798 inner_val_loss=3.05144 inner_val_multiclass_log_loss=3.05147 best_multiclass_log_loss=3.01749 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=21/40 loss=0.05249 inner_val_loss=2.98748 inner_val_multiclass_log_loss=2.98754 best_multiclass_log_loss=2.98754 best_epoch=21 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=22/40 loss=0.06121 inner_val_loss=2.98020 inner_val_multiclass_log_loss=2.98020 best_multiclass_log_loss=2.98020 best_epoch=22 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=23/40 loss=0.04624 inner_val_loss=2.97715 inner_val_multiclass_log_loss=2.97715 best_multiclass_log_loss=2.97715 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=24/40 loss=0.04318 inner_val_loss=2.95488 inner_val_multiclass_log_loss=2.95491 best_multiclass_log_loss=2.95491 best_epoch=24 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=25/40 loss=0.04004 inner_val_loss=2.94355 inner_val_multiclass_log_loss=2.94349 best_multiclass_log_loss=2.94349 best_epoch=25 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=26/40 loss=0.03721 inner_val_loss=2.95222 inner_val_multiclass_log_loss=2.95214 best_multiclass_log_loss=2.94349 best_epoch=25 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=27/40 loss=0.03983 inner_val_loss=2.93778 inner_val_multiclass_log_loss=2.93779 best_multiclass_log_loss=2.93779 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=28/40 loss=0.03033 inner_val_loss=2.93094 inner_val_multiclass_log_loss=2.93090 best_multiclass_log_loss=2.93090 best_epoch=28 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=29/40 loss=0.02639 inner_val_loss=2.94501 inner_val_multiclass_log_loss=2.94492 best_multiclass_log_loss=2.93090 best_epoch=28 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=30/40 loss=0.02605 inner_val_loss=2.87976 inner_val_multiclass_log_loss=2.87973 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=31/40 loss=0.02403 inner_val_loss=2.88979 inner_val_multiclass_log_loss=2.88973 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=32/40 loss=0.02041 inner_val_loss=2.89035 inner_val_multiclass_log_loss=2.89034 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=33/40 loss=0.04041 inner_val_loss=2.92775 inner_val_multiclass_log_loss=2.92774 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 epoch=34/40 loss=0.02739 inner_val_loss=2.91699 inner_val_multiclass_log_loss=2.91689 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0
  fit=12 epoch=35/40 loss=0.02424 inner_val_loss=2.88624 inner_val_multiclass_log_loss=2.88624 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=12 full_refit_epoch=1/30 loss=4.95701
  fit=12 full_refit_epoch=2/30 loss=3.76389
  fit=12 full_refit_epoch=3/30 loss=2.76631
  fit=12 full_refit_epoch=4/30 loss=1.97034
  fit=12 full_refit_epoch=5/30 loss=1.37501
  fit=12 full_refit_epoch=6/30 loss=0.92699
  fit=12 full_refit_epoch=7/30 loss=0.63547
  fit=12 full_refit_epoch=8/30 loss=0.42337
  fit=12 full_refit_epoch=9/30 loss=0.29723
  fit=12 full_refit_epoch=10/30 loss=0.21330
  fit=12 full_refit_epoch=11/30 loss=0.16205
  fit=12 full_refit_epoch=12/30 loss=0.12810
  fit=12 full_refit_epoch=13/30 loss=0.10264
  fit=12 full_refit_epoch=14/30 loss=0.08207
  fit=12 full_refit_epoch=15/30 loss=0.07589
  fit=12 full_refit_epoch=16/30 loss=0.05841
  fit=12 full_refit_epoch=17/30 loss=0.04985
  fit=12 full_refit_epoch=18/30 loss=0.04473
  fit=12 full_refit_epoch=19/30 loss=0.03919
  fit=12 full_refit_epoch=20/30 loss=0.03725
  fit=12 full_refit_epoch=21/30 loss=0.03176
  fit=12 full_refit_epoch=22/30 loss=0.02904
  fit=12 full_refit_epoch=23/30 loss=0.02649
  fit=12 full_refit_epoch=24/30 loss=0.02302
  fit=12 full_refit_epoch=25/30 loss=0.02214
  fit=12 full_refit_epoch=26/30 loss=0.02007
  fit=12 full_refit_epoch=27/30 loss=0.01857
  fit=12 full_refit_epoch=28/30 loss=0.01774
  fit=12 full_refit_epoch=29/30 loss=0.01611
  fit=12 full_refit_epoch=30/30 loss=0.01531

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=1/40 loss=5.01676 inner_val_loss=4.79880 inner_val_multiclass_log_loss=4.79885 best_multiclass_log_loss=4.79885 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=2/40 loss=3.80691 inner_val_loss=4.51623 inner_val_multiclass_log_loss=4.51620 best_multiclass_log_loss=4.51620 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=3/40 loss=2.86201 inner_val_loss=4.11611 inner_val_multiclass_log_loss=4.11622 best_multiclass_log_loss=4.11622 best_epoch=3 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=4/40 loss=2.07205 inner_val_loss=3.82281 inner_val_multiclass_log_loss=3.82290 best_multiclass_log_loss=3.82290 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=5/40 loss=1.44820 inner_val_loss=3.62108 inner_val_multiclass_log_loss=3.62105 best_multiclass_log_loss=3.62105 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=6/40 loss=1.02230 inner_val_loss=3.44531 inner_val_multiclass_log_loss=3.44531 best_multiclass_log_loss=3.44531 best_epoch=6 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=7/40 loss=0.72771 inner_val_loss=3.36164 inner_val_multiclass_log_loss=3.36169 best_multiclass_log_loss=3.36169 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=8/40 loss=0.48160 inner_val_loss=3.23977 inner_val_multiclass_log_loss=3.23984 best_multiclass_log_loss=3.23984 best_epoch=8 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=9/40 loss=0.35689 inner_val_loss=3.14501 inner_val_multiclass_log_loss=3.14506 best_multiclass_log_loss=3.14506 best_epoch=9 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=10/40 loss=0.25234 inner_val_loss=3.09822 inner_val_multiclass_log_loss=3.09819 best_multiclass_log_loss=3.09819 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=11/40 loss=0.19780 inner_val_loss=3.06664 inner_val_multiclass_log_loss=3.06666 best_multiclass_log_loss=3.06666 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=12/40 loss=0.15111 inner_val_loss=3.01875 inner_val_multiclass_log_loss=3.01873 best_multiclass_log_loss=3.01873 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=13/40 loss=0.12057 inner_val_loss=2.99054 inner_val_multiclass_log_loss=2.99054 best_multiclass_log_loss=2.99054 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=14/40 loss=0.11119 inner_val_loss=2.92545 inner_val_multiclass_log_loss=2.92545 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=15/40 loss=0.09669 inner_val_loss=2.93029 inner_val_multiclass_log_loss=2.93027 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=16/40 loss=0.08153 inner_val_loss=2.94174 inner_val_multiclass_log_loss=2.94174 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=17/40 loss=0.08088 inner_val_loss=2.88128 inner_val_multiclass_log_loss=2.88141 best_multiclass_log_loss=2.88141 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=18/40 loss=0.06766 inner_val_loss=2.89064 inner_val_multiclass_log_loss=2.89066 best_multiclass_log_loss=2.88141 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=19/40 loss=0.05888 inner_val_loss=2.86098 inner_val_multiclass_log_loss=2.86090 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=20/40 loss=0.04984 inner_val_loss=2.86946 inner_val_multiclass_log_loss=2.86940 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=21/40 loss=0.04524 inner_val_loss=2.87298 inner_val_multiclass_log_loss=2.87305 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=22/40 loss=0.04623 inner_val_loss=2.86256 inner_val_multiclass_log_loss=2.86264 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=23/40 loss=0.04556 inner_val_loss=2.79280 inner_val_multiclass_log_loss=2.79277 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=24/40 loss=0.04645 inner_val_loss=2.86354 inner_val_multiclass_log_loss=2.86351 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=25/40 loss=0.03811 inner_val_loss=2.87722 inner_val_multiclass_log_loss=2.87727 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=26/40 loss=0.03437 inner_val_loss=2.86250 inner_val_multiclass_log_loss=2.86249 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 epoch=27/40 loss=0.03223 inner_val_loss=2.93675 inner_val_multiclass_log_loss=2.93669 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.2
  fit=13 epoch=28/40 loss=0.03493 inner_val_loss=2.86849 inner_val_multiclass_log_loss=2.86851 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=13 full_refit_epoch=1/23 loss=4.97264
  fit=13 full_refit_epoch=2/23 loss=3.79471
  fit=13 full_refit_epoch=3/23 loss=2.81100
  fit=13 full_refit_epoch=4/23 loss=1.99287
  fit=13 full_refit_epoch=5/23 loss=1.39035
  fit=13 full_refit_epoch=6/23 loss=0.94705
  fit=13 full_refit_epoch=7/23 loss=0.63439
  fit=13 full_refit_epoch=8/23 loss=0.42073
  fit=13 full_refit_epoch=9/23 loss=0.31329
  fit=13 full_refit_epoch=10/23 loss=0.21250
  fit=13 full_refit_epoch=11/23 loss=0.15894
  fit=13 full_refit_epoch=12/23 loss=0.12872
  fit=13 full_refit_epoch=13/23 loss=0.10318
  fit=13 full_refit_epoch=14/23 loss=0.08752
  fit=13 full_refit_epoch=15/23 loss=0.07252
  fit=13 full_refit_epoch=16/23 loss=0.06406
  fit=13 full_refit_epoch=17/23 loss=0.05577
  fit=13 full_refit_epoch=18/23 loss=0.05109
  fit=13 full_refit_epoch=19/23 loss=0.04319
  fit=13 full_refit_epoch=20/23 loss=0.03615
  fit=13 full_refit_epoch=21/23 loss=0.03439
  fit=13 full_refit_epoch=22/23 loss=0.03117
  fit=13 full_refit_epoch=23/23 loss=0.02994

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=1/40 loss=4.98019 inner_val_loss=4.80112 inner_val_multiclass_log_loss=4.80111 best_multiclass_log_loss=4.80111 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=2/40 loss=3.83545 inner_val_loss=4.38068 inner_val_multiclass_log_loss=4.38072 best_multiclass_log_loss=4.38072 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=3/40 loss=2.85394 inner_val_loss=4.08940 inner_val_multiclass_log_loss=4.08944 best_multiclass_log_loss=4.08944 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=4/40 loss=2.10510 inner_val_loss=3.80768 inner_val_multiclass_log_loss=3.80774 best_multiclass_log_loss=3.80774 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=5/40 loss=1.48305 inner_val_loss=3.61064 inner_val_multiclass_log_loss=3.61058 best_multiclass_log_loss=3.61058 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=6/40 loss=0.99575 inner_val_loss=3.43767 inner_val_multiclass_log_loss=3.43759 best_multiclass_log_loss=3.43759 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=7/40 loss=0.69398 inner_val_loss=3.31066 inner_val_multiclass_log_loss=3.31061 best_multiclass_log_loss=3.31061 best_epoch=7 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=8/40 loss=0.48288 inner_val_loss=3.24260 inner_val_multiclass_log_loss=3.24255 best_multiclass_log_loss=3.24255 best_epoch=8 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=9/40 loss=0.35200 inner_val_loss=3.15228 inner_val_multiclass_log_loss=3.15232 best_multiclass_log_loss=3.15232 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=10/40 loss=0.25655 inner_val_loss=3.12074 inner_val_multiclass_log_loss=3.12082 best_multiclass_log_loss=3.12082 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=11/40 loss=0.20205 inner_val_loss=3.06036 inner_val_multiclass_log_loss=3.06030 best_multiclass_log_loss=3.06030 best_epoch=11 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=12/40 loss=0.17252 inner_val_loss=3.05890 inner_val_multiclass_log_loss=3.05901 best_multiclass_log_loss=3.05901 best_epoch=12 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=13/40 loss=0.12944 inner_val_loss=3.04077 inner_val_multiclass_log_loss=3.04078 best_multiclass_log_loss=3.04078 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=14/40 loss=0.10360 inner_val_loss=3.02117 inner_val_multiclass_log_loss=3.02102 best_multiclass_log_loss=3.02102 best_epoch=14 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=15/40 loss=0.09986 inner_val_loss=2.99078 inner_val_multiclass_log_loss=2.99081 best_multiclass_log_loss=2.99081 best_epoch=15 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=16/40 loss=0.08945 inner_val_loss=2.98474 inner_val_multiclass_log_loss=2.98470 best_multiclass_log_loss=2.98470 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=17/40 loss=0.08664 inner_val_loss=2.95091 inner_val_multiclass_log_loss=2.95088 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=18/40 loss=0.07508 inner_val_loss=2.97918 inner_val_multiclass_log_loss=2.97926 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=19/40 loss=0.05799 inner_val_loss=2.98011 inner_val_multiclass_log_loss=2.98012 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=20/40 loss=0.05265 inner_val_loss=2.93493 inner_val_multiclass_log_loss=2.93487 best_multiclass_log_loss=2.93487 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=21/40 loss=0.05421 inner_val_loss=2.92046 inner_val_multiclass_log_loss=2.92049 best_multiclass_log_loss=2.92049 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=22/40 loss=0.04896 inner_val_loss=2.89906 inner_val_multiclass_log_loss=2.89899 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=23/40 loss=0.04702 inner_val_loss=2.92943 inner_val_multiclass_log_loss=2.92939 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=24/40 loss=0.03694 inner_val_loss=2.97597 inner_val_multiclass_log_loss=2.97602 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=25/40 loss=0.03457 inner_val_loss=2.94485 inner_val_multiclass_log_loss=2.94488 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=26/40 loss=0.03043 inner_val_loss=2.91487 inner_val_multiclass_log_loss=2.91489 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=27/40 loss=0.03084 inner_val_loss=2.87474 inner_val_multiclass_log_loss=2.87473 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=28/40 loss=0.02971 inner_val_loss=2.91254 inner_val_multiclass_log_loss=2.91250 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=29/40 loss=0.02888 inner_val_loss=2.91208 inner_val_multiclass_log_loss=2.91214 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=30/40 loss=0.02872 inner_val_loss=2.92271 inner_val_multiclass_log_loss=2.92271 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 epoch=31/40 loss=0.02441 inner_val_loss=2.92348 inner_val_multiclass_log_loss=2.92349 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.0
  fit=14 epoch=32/40 loss=0.03908 inner_val_loss=2.95038 inner_val_multiclass_log_loss=2.95038 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=14 full_refit_epoch=1/27 loss=4.96757
  fit=14 full_refit_epoch=2/27 loss=3.78009
  fit=14 full_refit_epoch=3/27 loss=2.79538
  fit=14 full_refit_epoch=4/27 loss=1.98783
  fit=14 full_refit_epoch=5/27 loss=1.38019
  fit=14 full_refit_epoch=6/27 loss=0.93883
  fit=14 full_refit_epoch=7/27 loss=0.64393
  fit=14 full_refit_epoch=8/27 loss=0.43505
  fit=14 full_refit_epoch=9/27 loss=0.31168
  fit=14 full_refit_epoch=10/27 loss=0.21197
  fit=14 full_refit_epoch=11/27 loss=0.16040
  fit=14 full_refit_epoch=12/27 loss=0.13273
  fit=14 full_refit_epoch=13/27 loss=0.09999
  fit=14 full_refit_epoch=14/27 loss=0.08581
  fit=14 full_refit_epoch=15/27 loss=0.07211
  fit=14 full_refit_epoch=16/27 loss=0.06771
  fit=14 full_refit_epoch=17/27 loss=0.05184
  fit=14 full_refit_epoch=18/27 loss=0.04838
  fit=14 full_refit_epoch=19/27 loss=0.04290
  fit=14 full_refit_epoch=20/27 loss=0.03667
  fit=14 full_refit_epoch=21/27 loss=0.03470
  fit=14 full_refit_epoch=22/27 loss=0.03014
  fit=14 full_refit_epoch=23/27 loss=0.02907
  fit=14 full_refit_epoch=24/27 loss=0.02482
  fit=14 full_refit_epoch=25/27 loss=0.02303
  fit=14 full_refit_epoch=26/27 loss=0.02001
  fit=14 full_refit_epoch=27/27 loss=0.01816

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=1/40 loss=4.98315 inner_val_loss=4.87857 inner_val_multiclass_log_loss=4.87864 best_multiclass_log_loss=4.87864 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=2/40 loss=3.79959 inner_val_loss=4.61240 inner_val_multiclass_log_loss=4.61237 best_multiclass_log_loss=4.61237 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=3/40 loss=2.87593 inner_val_loss=4.32853 inner_val_multiclass_log_loss=4.32851 best_multiclass_log_loss=4.32851 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=4/40 loss=2.08456 inner_val_loss=4.10305 inner_val_multiclass_log_loss=4.10312 best_multiclass_log_loss=4.10312 best_epoch=4 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=5/40 loss=1.47750 inner_val_loss=3.91342 inner_val_multiclass_log_loss=3.91342 best_multiclass_log_loss=3.91342 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=6/40 loss=1.05178 inner_val_loss=3.77663 inner_val_multiclass_log_loss=3.77666 best_multiclass_log_loss=3.77666 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=7/40 loss=0.70019 inner_val_loss=3.60753 inner_val_multiclass_log_loss=3.60750 best_multiclass_log_loss=3.60750 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=8/40 loss=0.50536 inner_val_loss=3.56600 inner_val_multiclass_log_loss=3.56610 best_multiclass_log_loss=3.56610 best_epoch=8 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=9/40 loss=0.35118 inner_val_loss=3.51525 inner_val_multiclass_log_loss=3.51517 best_multiclass_log_loss=3.51517 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=10/40 loss=0.27375 inner_val_loss=3.45606 inner_val_multiclass_log_loss=3.45601 best_multiclass_log_loss=3.45601 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=11/40 loss=0.20011 inner_val_loss=3.40658 inner_val_multiclass_log_loss=3.40653 best_multiclass_log_loss=3.40653 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=12/40 loss=0.17257 inner_val_loss=3.39790 inner_val_multiclass_log_loss=3.39797 best_multiclass_log_loss=3.39797 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=13/40 loss=0.12595 inner_val_loss=3.37083 inner_val_multiclass_log_loss=3.37092 best_multiclass_log_loss=3.37092 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=14/40 loss=0.11311 inner_val_loss=3.33538 inner_val_multiclass_log_loss=3.33535 best_multiclass_log_loss=3.33535 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=15/40 loss=0.10580 inner_val_loss=3.30966 inner_val_multiclass_log_loss=3.30965 best_multiclass_log_loss=3.30965 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=16/40 loss=0.09065 inner_val_loss=3.27146 inner_val_multiclass_log_loss=3.27146 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=17/40 loss=0.07366 inner_val_loss=3.29281 inner_val_multiclass_log_loss=3.29286 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=18/40 loss=0.05955 inner_val_loss=3.30540 inner_val_multiclass_log_loss=3.30539 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=19/40 loss=0.06046 inner_val_loss=3.25990 inner_val_multiclass_log_loss=3.25991 best_multiclass_log_loss=3.25991 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=20/40 loss=0.05431 inner_val_loss=3.24322 inner_val_multiclass_log_loss=3.24322 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=21/40 loss=0.04827 inner_val_loss=3.25760 inner_val_multiclass_log_loss=3.25765 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=22/40 loss=0.04249 inner_val_loss=3.25500 inner_val_multiclass_log_loss=3.25499 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=23/40 loss=0.03823 inner_val_loss=3.25148 inner_val_multiclass_log_loss=3.25146 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 epoch=24/40 loss=0.03670 inner_val_loss=3.26316 inner_val_multiclass_log_loss=3.26307 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0
  fit=15 epoch=25/40 loss=0.03862 inner_val_loss=3.26267 inner_val_multiclass_log_loss=3.26266 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=15 full_refit_epoch=1/20 loss=4.95468
  fit=15 full_refit_epoch=2/20 loss=3.78333
  fit=15 full_refit_epoch=3/20 loss=2.79303
  fit=15 full_refit_epoch=4/20 loss=1.99956
  fit=15 full_refit_epoch=5/20 loss=1.41169
  fit=15 full_refit_epoch=6/20 loss=0.94167
  fit=15 full_refit_epoch=7/20 loss=0.64497
  fit=15 full_refit_epoch=8/20 loss=0.43648
  fit=15 full_refit_epoch=9/20 loss=0.31866
  fit=15 full_refit_epoch=10/20 loss=0.22920
  fit=15 full_refit_epoch=11/20 loss=0.16224
  fit=15 full_refit_epoch=12/20 loss=0.13304
  fit=15 full_refit_epoch=13/20 loss=0.10434
  fit=15 full_refit_epoch=14/20 loss=0.08762
  fit=15 full_refit_epoch=15/20 loss=0.07141
  fit=15 full_refit_epoch=16/20 loss=0.06351
  fit=15 full_refit_epoch=17/20 loss=0.05367
  fit=15 full_refit_epoch=18/20 loss=0.04474
  fit=15 full_refit_epoch=19/20 loss=0.03982
  fit=15 full_refit_epoch=20/20 loss=0.03946

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=initial model=efficientnet_b0 metric=2.9808095613000827 error=None minutes=14.83
START seed=47 phase=initial_merge model=ensemble:resnet18+efficientnet_b0
END   seed=47 phase=initial_merge model=ensemble:resnet18+efficientnet_b0 metric=None error=AssertionError:  minutes=0.01
START seed=47 phase=initial_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=1/40 loss=4.79604 inner_val_loss=4.73218 inner_val_multiclass_log_loss=4.73214 best_multiclass_log_loss=4.73214 best_epoch=1 seconds=2.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=2/40 loss=4.63253 inner_val_loss=4.67259 inner_val_multiclass_log_loss=4.67259 best_multiclass_log_loss=4.67259 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=3/40 loss=4.47386 inner_val_loss=4.55970 inner_val_multiclass_log_loss=4.55970 best_multiclass_log_loss=4.55970 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=4/40 loss=4.28732 inner_val_loss=4.44825 inner_val_multiclass_log_loss=4.44823 best_multiclass_log_loss=4.44823 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=5/40 loss=4.06886 inner_val_loss=4.33298 inner_val_multiclass_log_loss=4.33294 best_multiclass_log_loss=4.33294 best_epoch=5 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=6/40 loss=3.84643 inner_val_loss=4.13359 inner_val_multiclass_log_loss=4.13362 best_multiclass_log_loss=4.13362 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=7/40 loss=3.62140 inner_val_loss=3.97734 inner_val_multiclass_log_loss=3.97734 best_multiclass_log_loss=3.97734 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=8/40 loss=3.39511 inner_val_loss=3.88827 inner_val_multiclass_log_loss=3.88824 best_multiclass_log_loss=3.88824 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=9/40 loss=3.16729 inner_val_loss=3.77547 inner_val_multiclass_log_loss=3.77555 best_multiclass_log_loss=3.77555 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=10/40 loss=2.95336 inner_val_loss=3.69540 inner_val_multiclass_log_loss=3.69537 best_multiclass_log_loss=3.69537 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=11/40 loss=2.73357 inner_val_loss=3.54863 inner_val_multiclass_log_loss=3.54857 best_multiclass_log_loss=3.54857 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=12/40 loss=2.52061 inner_val_loss=3.44390 inner_val_multiclass_log_loss=3.44381 best_multiclass_log_loss=3.44381 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=13/40 loss=2.32619 inner_val_loss=3.36695 inner_val_multiclass_log_loss=3.36690 best_multiclass_log_loss=3.36690 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=14/40 loss=2.14268 inner_val_loss=3.29173 inner_val_multiclass_log_loss=3.29171 best_multiclass_log_loss=3.29171 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=15/40 loss=1.97246 inner_val_loss=3.19012 inner_val_multiclass_log_loss=3.19021 best_multiclass_log_loss=3.19021 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=16/40 loss=1.78584 inner_val_loss=3.08207 inner_val_multiclass_log_loss=3.08204 best_multiclass_log_loss=3.08204 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=17/40 loss=1.62255 inner_val_loss=3.02023 inner_val_multiclass_log_loss=3.02023 best_multiclass_log_loss=3.02023 best_epoch=17 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=18/40 loss=1.47096 inner_val_loss=2.96257 inner_val_multiclass_log_loss=2.96259 best_multiclass_log_loss=2.96259 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=19/40 loss=1.34683 inner_val_loss=2.88782 inner_val_multiclass_log_loss=2.88782 best_multiclass_log_loss=2.88782 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=20/40 loss=1.18152 inner_val_loss=2.87635 inner_val_multiclass_log_loss=2.87630 best_multiclass_log_loss=2.87630 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=21/40 loss=1.07280 inner_val_loss=2.82962 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=22/40 loss=0.96276 inner_val_loss=2.76426 inner_val_multiclass_log_loss=2.76424 best_multiclass_log_loss=2.76424 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=23/40 loss=0.85255 inner_val_loss=2.74589 inner_val_multiclass_log_loss=2.74593 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=24/40 loss=0.76815 inner_val_loss=2.76247 inner_val_multiclass_log_loss=2.76242 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=25/40 loss=0.66728 inner_val_loss=2.70668 inner_val_multiclass_log_loss=2.70668 best_multiclass_log_loss=2.70668 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=26/40 loss=0.60636 inner_val_loss=2.70543 inner_val_multiclass_log_loss=2.70541 best_multiclass_log_loss=2.70541 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=27/40 loss=0.52941 inner_val_loss=2.68617 inner_val_multiclass_log_loss=2.68613 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=28/40 loss=0.48062 inner_val_loss=2.69317 inner_val_multiclass_log_loss=2.69317 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=29/40 loss=0.41842 inner_val_loss=2.66156 inner_val_multiclass_log_loss=2.66154 best_multiclass_log_loss=2.66154 best_epoch=29 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=30/40 loss=0.36864 inner_val_loss=2.65680 inner_val_multiclass_log_loss=2.65670 best_multiclass_log_loss=2.65670 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=31/40 loss=0.32602 inner_val_loss=2.63176 inner_val_multiclass_log_loss=2.63183 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=32/40 loss=0.30625 inner_val_loss=2.66063 inner_val_multiclass_log_loss=2.66061 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=33/40 loss=0.26540 inner_val_loss=2.63391 inner_val_multiclass_log_loss=2.63389 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=34/40 loss=0.24684 inner_val_loss=2.62465 inner_val_multiclass_log_loss=2.62469 best_multiclass_log_loss=2.62469 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=35/40 loss=0.20674 inner_val_loss=2.61135 inner_val_multiclass_log_loss=2.61138 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=36/40 loss=0.19393 inner_val_loss=2.64488 inner_val_multiclass_log_loss=2.64494 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=37/40 loss=0.16779 inner_val_loss=2.61169 inner_val_multiclass_log_loss=2.61176 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=38/40 loss=0.14916 inner_val_loss=2.62670 inner_val_multiclass_log_loss=2.62673 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 epoch=39/40 loss=0.14285 inner_val_loss=2.61079 inner_val_multiclass_log_loss=2.61077 best_multiclass_log_loss=2.61077 best_epoch=39 seconds=2.1
  fit=16 epoch=40/40 loss=0.12808 inner_val_loss=2.59991 inner_val_multiclass_log_loss=2.59992 best_multiclass_log_loss=2.59992 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=16 full_refit_epoch=1/40 loss=4.79128
  fit=16 full_refit_epoch=2/40 loss=4.61581
  fit=16 full_refit_epoch=3/40 loss=4.43444
  fit=16 full_refit_epoch=4/40 loss=4.22564
  fit=16 full_refit_epoch=5/40 loss=3.98810
  fit=16 full_refit_epoch=6/40 loss=3.73859
  fit=16 full_refit_epoch=7/40 loss=3.49443
  fit=16 full_refit_epoch=8/40 loss=3.24746
  fit=16 full_refit_epoch=9/40 loss=3.01506
  fit=16 full_refit_epoch=10/40 loss=2.79312
  fit=16 full_refit_epoch=11/40 loss=2.56534
  fit=16 full_refit_epoch=12/40 loss=2.36016
  fit=16 full_refit_epoch=13/40 loss=2.15093
  fit=16 full_refit_epoch=14/40 loss=1.96154
  fit=16 full_refit_epoch=15/40 loss=1.77583
  fit=16 full_refit_epoch=16/40 loss=1.60714
  fit=16 full_refit_epoch=17/40 loss=1.44926
  fit=16 full_refit_epoch=18/40 loss=1.28955
  fit=16 full_refit_epoch=19/40 loss=1.15900
  fit=16 full_refit_epoch=20/40 loss=1.04187
  fit=16 full_refit_epoch=21/40 loss=0.92192
  fit=16 full_refit_epoch=22/40 loss=0.79462
  fit=16 full_refit_epoch=23/40 loss=0.71547
  fit=16 full_refit_epoch=24/40 loss=0.62853
  fit=16 full_refit_epoch=25/40 loss=0.55656
  fit=16 full_refit_epoch=26/40 loss=0.47864
  fit=16 full_refit_epoch=27/40 loss=0.42339
  fit=16 full_refit_epoch=28/40 loss=0.38009
  fit=16 full_refit_epoch=29/40 loss=0.32500
  fit=16 full_refit_epoch=30/40 loss=0.30116
  fit=16 full_refit_epoch=31/40 loss=0.24874
  fit=16 full_refit_epoch=32/40 loss=0.21832
  fit=16 full_refit_epoch=33/40 loss=0.19626
  fit=16 full_refit_epoch=34/40 loss=0.17990
  fit=16 full_refit_epoch=35/40 loss=0.15856
  fit=16 full_refit_epoch=36/40 loss=0.14075
  fit=16 full_refit_epoch=37/40 loss=0.12563
  fit=16 full_refit_epoch=38/40 loss=0.10919
  fit=16 full_refit_epoch=39/40 loss=0.10192
  fit=16 full_refit_epoch=40/40 loss=0.09188

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=1/40 loss=4.78529 inner_val_loss=4.74350 inner_val_multiclass_log_loss=4.74344 best_multiclass_log_loss=4.74344 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=2/40 loss=4.61759 inner_val_loss=4.66598 inner_val_multiclass_log_loss=4.66596 best_multiclass_log_loss=4.66596 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=3/40 loss=4.44644 inner_val_loss=4.56246 inner_val_multiclass_log_loss=4.56251 best_multiclass_log_loss=4.56251 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=4/40 loss=4.25722 inner_val_loss=4.46757 inner_val_multiclass_log_loss=4.46770 best_multiclass_log_loss=4.46770 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=5/40 loss=4.05331 inner_val_loss=4.32690 inner_val_multiclass_log_loss=4.32679 best_multiclass_log_loss=4.32679 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=6/40 loss=3.81373 inner_val_loss=4.18748 inner_val_multiclass_log_loss=4.18753 best_multiclass_log_loss=4.18753 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=7/40 loss=3.59817 inner_val_loss=4.05102 inner_val_multiclass_log_loss=4.05097 best_multiclass_log_loss=4.05097 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=8/40 loss=3.36733 inner_val_loss=3.88468 inner_val_multiclass_log_loss=3.88461 best_multiclass_log_loss=3.88461 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=9/40 loss=3.15824 inner_val_loss=3.79493 inner_val_multiclass_log_loss=3.79483 best_multiclass_log_loss=3.79483 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=10/40 loss=2.94215 inner_val_loss=3.64514 inner_val_multiclass_log_loss=3.64511 best_multiclass_log_loss=3.64511 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=11/40 loss=2.73160 inner_val_loss=3.58555 inner_val_multiclass_log_loss=3.58546 best_multiclass_log_loss=3.58546 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=12/40 loss=2.50724 inner_val_loss=3.40191 inner_val_multiclass_log_loss=3.40197 best_multiclass_log_loss=3.40197 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=13/40 loss=2.30979 inner_val_loss=3.28591 inner_val_multiclass_log_loss=3.28586 best_multiclass_log_loss=3.28586 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=14/40 loss=2.13234 inner_val_loss=3.23486 inner_val_multiclass_log_loss=3.23487 best_multiclass_log_loss=3.23487 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=15/40 loss=1.94883 inner_val_loss=3.08468 inner_val_multiclass_log_loss=3.08474 best_multiclass_log_loss=3.08474 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=16/40 loss=1.78527 inner_val_loss=2.99771 inner_val_multiclass_log_loss=2.99765 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=17/40 loss=1.62082 inner_val_loss=3.00123 inner_val_multiclass_log_loss=3.00123 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=18/40 loss=1.45911 inner_val_loss=2.90762 inner_val_multiclass_log_loss=2.90759 best_multiclass_log_loss=2.90759 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=19/40 loss=1.33887 inner_val_loss=2.81714 inner_val_multiclass_log_loss=2.81714 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=20/40 loss=1.20626 inner_val_loss=2.82729 inner_val_multiclass_log_loss=2.82734 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=21/40 loss=1.07785 inner_val_loss=2.74942 inner_val_multiclass_log_loss=2.74944 best_multiclass_log_loss=2.74944 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=22/40 loss=0.96543 inner_val_loss=2.68896 inner_val_multiclass_log_loss=2.68888 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=23/40 loss=0.85024 inner_val_loss=2.74155 inner_val_multiclass_log_loss=2.74154 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=24/40 loss=0.76864 inner_val_loss=2.66937 inner_val_multiclass_log_loss=2.66942 best_multiclass_log_loss=2.66942 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=25/40 loss=0.68431 inner_val_loss=2.63966 inner_val_multiclass_log_loss=2.63964 best_multiclass_log_loss=2.63964 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=26/40 loss=0.58750 inner_val_loss=2.63823 inner_val_multiclass_log_loss=2.63818 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=27/40 loss=0.51989 inner_val_loss=2.64882 inner_val_multiclass_log_loss=2.64874 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=28/40 loss=0.45891 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60250 best_multiclass_log_loss=2.60250 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=29/40 loss=0.41438 inner_val_loss=2.58168 inner_val_multiclass_log_loss=2.58177 best_multiclass_log_loss=2.58177 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=30/40 loss=0.36284 inner_val_loss=2.57724 inner_val_multiclass_log_loss=2.57728 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=31/40 loss=0.33492 inner_val_loss=2.57963 inner_val_multiclass_log_loss=2.57971 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=32/40 loss=0.28502 inner_val_loss=2.55369 inner_val_multiclass_log_loss=2.55378 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=33/40 loss=0.27036 inner_val_loss=2.56817 inner_val_multiclass_log_loss=2.56822 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=34/40 loss=0.22846 inner_val_loss=2.53099 inner_val_multiclass_log_loss=2.53092 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=35/40 loss=0.21733 inner_val_loss=2.57357 inner_val_multiclass_log_loss=2.57348 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=36/40 loss=0.18244 inner_val_loss=2.54892 inner_val_multiclass_log_loss=2.54897 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=37/40 loss=0.17517 inner_val_loss=2.54703 inner_val_multiclass_log_loss=2.54705 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 epoch=38/40 loss=0.15172 inner_val_loss=2.54890 inner_val_multiclass_log_loss=2.54889 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0
  fit=17 epoch=39/40 loss=0.13926 inner_val_loss=2.53601 inner_val_multiclass_log_loss=2.53600 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=17 full_refit_epoch=1/34 loss=4.77779
  fit=17 full_refit_epoch=2/34 loss=4.60078
  fit=17 full_refit_epoch=3/34 loss=4.41295
  fit=17 full_refit_epoch=4/34 loss=4.19824
  fit=17 full_refit_epoch=5/34 loss=3.95991
  fit=17 full_refit_epoch=6/34 loss=3.72031
  fit=17 full_refit_epoch=7/34 loss=3.47218
  fit=17 full_refit_epoch=8/34 loss=3.24296
  fit=17 full_refit_epoch=9/34 loss=2.99698
  fit=17 full_refit_epoch=10/34 loss=2.77741
  fit=17 full_refit_epoch=11/34 loss=2.54338
  fit=17 full_refit_epoch=12/34 loss=2.33114
  fit=17 full_refit_epoch=13/34 loss=2.12232
  fit=17 full_refit_epoch=14/34 loss=1.93304
  fit=17 full_refit_epoch=15/34 loss=1.75879
  fit=17 full_refit_epoch=16/34 loss=1.57506
  fit=17 full_refit_epoch=17/34 loss=1.41415
  fit=17 full_refit_epoch=18/34 loss=1.27479
  fit=17 full_refit_epoch=19/34 loss=1.13539
  fit=17 full_refit_epoch=20/34 loss=1.02070
  fit=17 full_refit_epoch=21/34 loss=0.89572
  fit=17 full_refit_epoch=22/34 loss=0.78825
  fit=17 full_refit_epoch=23/34 loss=0.69082
  fit=17 full_refit_epoch=24/34 loss=0.59551
  fit=17 full_refit_epoch=25/34 loss=0.53715
  fit=17 full_refit_epoch=26/34 loss=0.47102
  fit=17 full_refit_epoch=27/34 loss=0.41062
  fit=17 full_refit_epoch=28/34 loss=0.35460
  fit=17 full_refit_epoch=29/34 loss=0.31392
  fit=17 full_refit_epoch=30/34 loss=0.27658
  fit=17 full_refit_epoch=31/34 loss=0.24613
  fit=17 full_refit_epoch=32/34 loss=0.21734
  fit=17 full_refit_epoch=33/34 loss=0.19095
  fit=17 full_refit_epoch=34/34 loss=0.17254

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=1/40 loss=4.78598 inner_val_loss=4.74895 inner_val_multiclass_log_loss=4.74886 best_multiclass_log_loss=4.74886 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=2/40 loss=4.61747 inner_val_loss=4.67133 inner_val_multiclass_log_loss=4.67137 best_multiclass_log_loss=4.67137 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=3/40 loss=4.44421 inner_val_loss=4.58167 inner_val_multiclass_log_loss=4.58166 best_multiclass_log_loss=4.58166 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=4/40 loss=4.25613 inner_val_loss=4.44833 inner_val_multiclass_log_loss=4.44822 best_multiclass_log_loss=4.44822 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=5/40 loss=4.03231 inner_val_loss=4.29905 inner_val_multiclass_log_loss=4.29900 best_multiclass_log_loss=4.29900 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=6/40 loss=3.80887 inner_val_loss=4.16650 inner_val_multiclass_log_loss=4.16655 best_multiclass_log_loss=4.16655 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=7/40 loss=3.58425 inner_val_loss=4.07659 inner_val_multiclass_log_loss=4.07661 best_multiclass_log_loss=4.07661 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=8/40 loss=3.36133 inner_val_loss=3.91148 inner_val_multiclass_log_loss=3.91148 best_multiclass_log_loss=3.91148 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=9/40 loss=3.13965 inner_val_loss=3.69225 inner_val_multiclass_log_loss=3.69228 best_multiclass_log_loss=3.69228 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=10/40 loss=2.92091 inner_val_loss=3.63148 inner_val_multiclass_log_loss=3.63156 best_multiclass_log_loss=3.63156 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=11/40 loss=2.70039 inner_val_loss=3.50666 inner_val_multiclass_log_loss=3.50662 best_multiclass_log_loss=3.50662 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=12/40 loss=2.50043 inner_val_loss=3.37099 inner_val_multiclass_log_loss=3.37102 best_multiclass_log_loss=3.37102 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=13/40 loss=2.29484 inner_val_loss=3.26625 inner_val_multiclass_log_loss=3.26612 best_multiclass_log_loss=3.26612 best_epoch=13 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=14/40 loss=2.12114 inner_val_loss=3.16823 inner_val_multiclass_log_loss=3.16824 best_multiclass_log_loss=3.16824 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=15/40 loss=1.93977 inner_val_loss=3.08539 inner_val_multiclass_log_loss=3.08539 best_multiclass_log_loss=3.08539 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=16/40 loss=1.76654 inner_val_loss=2.99735 inner_val_multiclass_log_loss=2.99742 best_multiclass_log_loss=2.99742 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=17/40 loss=1.60779 inner_val_loss=2.89870 inner_val_multiclass_log_loss=2.89881 best_multiclass_log_loss=2.89881 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=18/40 loss=1.45640 inner_val_loss=2.85110 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=19/40 loss=1.30639 inner_val_loss=2.77251 inner_val_multiclass_log_loss=2.77241 best_multiclass_log_loss=2.77241 best_epoch=19 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=20/40 loss=1.16936 inner_val_loss=2.75131 inner_val_multiclass_log_loss=2.75130 best_multiclass_log_loss=2.75130 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=21/40 loss=1.05572 inner_val_loss=2.69500 inner_val_multiclass_log_loss=2.69506 best_multiclass_log_loss=2.69506 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=22/40 loss=0.94055 inner_val_loss=2.67022 inner_val_multiclass_log_loss=2.67029 best_multiclass_log_loss=2.67029 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=23/40 loss=0.85175 inner_val_loss=2.59384 inner_val_multiclass_log_loss=2.59380 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=24/40 loss=0.75602 inner_val_loss=2.59947 inner_val_multiclass_log_loss=2.59943 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=25/40 loss=0.66566 inner_val_loss=2.57623 inner_val_multiclass_log_loss=2.57619 best_multiclass_log_loss=2.57619 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=26/40 loss=0.58957 inner_val_loss=2.56685 inner_val_multiclass_log_loss=2.56687 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=27/40 loss=0.52900 inner_val_loss=2.57257 inner_val_multiclass_log_loss=2.57252 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=28/40 loss=0.46072 inner_val_loss=2.54440 inner_val_multiclass_log_loss=2.54439 best_multiclass_log_loss=2.54439 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=29/40 loss=0.41680 inner_val_loss=2.51023 inner_val_multiclass_log_loss=2.51027 best_multiclass_log_loss=2.51027 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=30/40 loss=0.35341 inner_val_loss=2.48075 inner_val_multiclass_log_loss=2.48079 best_multiclass_log_loss=2.48079 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=31/40 loss=0.32624 inner_val_loss=2.47039 inner_val_multiclass_log_loss=2.47038 best_multiclass_log_loss=2.47038 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=32/40 loss=0.29237 inner_val_loss=2.45936 inner_val_multiclass_log_loss=2.45932 best_multiclass_log_loss=2.45932 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=33/40 loss=0.26956 inner_val_loss=2.44038 inner_val_multiclass_log_loss=2.44039 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=34/40 loss=0.23673 inner_val_loss=2.44873 inner_val_multiclass_log_loss=2.44875 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=35/40 loss=0.20594 inner_val_loss=2.43773 inner_val_multiclass_log_loss=2.43777 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=36/40 loss=0.18920 inner_val_loss=2.46623 inner_val_multiclass_log_loss=2.46618 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=37/40 loss=0.17468 inner_val_loss=2.42681 inner_val_multiclass_log_loss=2.42687 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=38/40 loss=0.16045 inner_val_loss=2.43230 inner_val_multiclass_log_loss=2.43224 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 epoch=39/40 loss=0.13876 inner_val_loss=2.42945 inner_val_multiclass_log_loss=2.42945 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1
  fit=18 epoch=40/40 loss=0.12840 inner_val_loss=2.42231 inner_val_multiclass_log_loss=2.42228 best_multiclass_log_loss=2.42228 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=18 full_refit_epoch=1/40 loss=4.77988
  fit=18 full_refit_epoch=2/40 loss=4.60904
  fit=18 full_refit_epoch=3/40 loss=4.42586
  fit=18 full_refit_epoch=4/40 loss=4.21264
  fit=18 full_refit_epoch=5/40 loss=3.98115
  fit=18 full_refit_epoch=6/40 loss=3.72980
  fit=18 full_refit_epoch=7/40 loss=3.48740
  fit=18 full_refit_epoch=8/40 loss=3.24153
  fit=18 full_refit_epoch=9/40 loss=3.01609
  fit=18 full_refit_epoch=10/40 loss=2.77404
  fit=18 full_refit_epoch=11/40 loss=2.54436
  fit=18 full_refit_epoch=12/40 loss=2.33251
  fit=18 full_refit_epoch=13/40 loss=2.12541
  fit=18 full_refit_epoch=14/40 loss=1.94018
  fit=18 full_refit_epoch=15/40 loss=1.74784
  fit=18 full_refit_epoch=16/40 loss=1.57977
  fit=18 full_refit_epoch=17/40 loss=1.41598
  fit=18 full_refit_epoch=18/40 loss=1.28322
  fit=18 full_refit_epoch=19/40 loss=1.12908
  fit=18 full_refit_epoch=20/40 loss=1.00664
  fit=18 full_refit_epoch=21/40 loss=0.89356
  fit=18 full_refit_epoch=22/40 loss=0.79305
  fit=18 full_refit_epoch=23/40 loss=0.70667
  fit=18 full_refit_epoch=24/40 loss=0.60575
  fit=18 full_refit_epoch=25/40 loss=0.53220
  fit=18 full_refit_epoch=26/40 loss=0.47780
  fit=18 full_refit_epoch=27/40 loss=0.41461
  fit=18 full_refit_epoch=28/40 loss=0.36608
  fit=18 full_refit_epoch=29/40 loss=0.32224
  fit=18 full_refit_epoch=30/40 loss=0.27960
  fit=18 full_refit_epoch=31/40 loss=0.25322
  fit=18 full_refit_epoch=32/40 loss=0.21666
  fit=18 full_refit_epoch=33/40 loss=0.19701
  fit=18 full_refit_epoch=34/40 loss=0.17425
  fit=18 full_refit_epoch=35/40 loss=0.15471
  fit=18 full_refit_epoch=36/40 loss=0.13652
  fit=18 full_refit_epoch=37/40 loss=0.12648
  fit=18 full_refit_epoch=38/40 loss=0.10761
  fit=18 full_refit_epoch=39/40 loss=0.10610
  fit=18 full_refit_epoch=40/40 loss=0.09535

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=1/40 loss=4.78616 inner_val_loss=4.72490 inner_val_multiclass_log_loss=4.72474 best_multiclass_log_loss=4.72474 best_epoch=1 seconds=2.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=2/40 loss=4.61983 inner_val_loss=4.62753 inner_val_multiclass_log_loss=4.62759 best_multiclass_log_loss=4.62759 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=3/40 loss=4.45797 inner_val_loss=4.54643 inner_val_multiclass_log_loss=4.54643 best_multiclass_log_loss=4.54643 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=4/40 loss=4.28081 inner_val_loss=4.46488 inner_val_multiclass_log_loss=4.46488 best_multiclass_log_loss=4.46488 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=5/40 loss=4.08048 inner_val_loss=4.31625 inner_val_multiclass_log_loss=4.31634 best_multiclass_log_loss=4.31634 best_epoch=5 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=6/40 loss=3.86825 inner_val_loss=4.18847 inner_val_multiclass_log_loss=4.18838 best_multiclass_log_loss=4.18838 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=7/40 loss=3.64301 inner_val_loss=4.05750 inner_val_multiclass_log_loss=4.05740 best_multiclass_log_loss=4.05740 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=8/40 loss=3.40436 inner_val_loss=3.87396 inner_val_multiclass_log_loss=3.87396 best_multiclass_log_loss=3.87396 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=9/40 loss=3.19662 inner_val_loss=3.75727 inner_val_multiclass_log_loss=3.75729 best_multiclass_log_loss=3.75729 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=10/40 loss=2.97522 inner_val_loss=3.66436 inner_val_multiclass_log_loss=3.66434 best_multiclass_log_loss=3.66434 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=11/40 loss=2.74266 inner_val_loss=3.47013 inner_val_multiclass_log_loss=3.47004 best_multiclass_log_loss=3.47004 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=12/40 loss=2.55972 inner_val_loss=3.33333 inner_val_multiclass_log_loss=3.33334 best_multiclass_log_loss=3.33334 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=13/40 loss=2.35769 inner_val_loss=3.28423 inner_val_multiclass_log_loss=3.28425 best_multiclass_log_loss=3.28425 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=14/40 loss=2.16565 inner_val_loss=3.15414 inner_val_multiclass_log_loss=3.15408 best_multiclass_log_loss=3.15408 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=15/40 loss=1.98688 inner_val_loss=3.07231 inner_val_multiclass_log_loss=3.07231 best_multiclass_log_loss=3.07231 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=16/40 loss=1.81668 inner_val_loss=3.00154 inner_val_multiclass_log_loss=3.00149 best_multiclass_log_loss=3.00149 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=17/40 loss=1.66713 inner_val_loss=2.92328 inner_val_multiclass_log_loss=2.92325 best_multiclass_log_loss=2.92325 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=18/40 loss=1.52455 inner_val_loss=2.86711 inner_val_multiclass_log_loss=2.86716 best_multiclass_log_loss=2.86716 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=19/40 loss=1.35649 inner_val_loss=2.82959 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=20/40 loss=1.23937 inner_val_loss=2.70085 inner_val_multiclass_log_loss=2.70082 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=21/40 loss=1.11458 inner_val_loss=2.73949 inner_val_multiclass_log_loss=2.73944 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=22/40 loss=1.00135 inner_val_loss=2.69911 inner_val_multiclass_log_loss=2.69906 best_multiclass_log_loss=2.69906 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=23/40 loss=0.90562 inner_val_loss=2.60998 inner_val_multiclass_log_loss=2.60992 best_multiclass_log_loss=2.60992 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=24/40 loss=0.79425 inner_val_loss=2.60439 inner_val_multiclass_log_loss=2.60439 best_multiclass_log_loss=2.60439 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=25/40 loss=0.70615 inner_val_loss=2.58918 inner_val_multiclass_log_loss=2.58917 best_multiclass_log_loss=2.58917 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=26/40 loss=0.63300 inner_val_loss=2.53947 inner_val_multiclass_log_loss=2.53950 best_multiclass_log_loss=2.53950 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=27/40 loss=0.56248 inner_val_loss=2.49854 inner_val_multiclass_log_loss=2.49855 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=28/40 loss=0.50699 inner_val_loss=2.51626 inner_val_multiclass_log_loss=2.51622 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=29/40 loss=0.44951 inner_val_loss=2.53317 inner_val_multiclass_log_loss=2.53312 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=30/40 loss=0.40239 inner_val_loss=2.50438 inner_val_multiclass_log_loss=2.50445 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=31/40 loss=0.35139 inner_val_loss=2.49836 inner_val_multiclass_log_loss=2.49834 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=32/40 loss=0.31519 inner_val_loss=2.49952 inner_val_multiclass_log_loss=2.49954 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=33/40 loss=0.28856 inner_val_loss=2.42672 inner_val_multiclass_log_loss=2.42672 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=34/40 loss=0.25429 inner_val_loss=2.45267 inner_val_multiclass_log_loss=2.45271 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=35/40 loss=0.22645 inner_val_loss=2.42072 inner_val_multiclass_log_loss=2.42068 best_multiclass_log_loss=2.42068 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=36/40 loss=0.20706 inner_val_loss=2.41048 inner_val_multiclass_log_loss=2.41044 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=37/40 loss=0.18824 inner_val_loss=2.41161 inner_val_multiclass_log_loss=2.41162 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=38/40 loss=0.17108 inner_val_loss=2.45061 inner_val_multiclass_log_loss=2.45059 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 epoch=39/40 loss=0.14891 inner_val_loss=2.41139 inner_val_multiclass_log_loss=2.41135 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.1
  fit=19 epoch=40/40 loss=0.13585 inner_val_loss=2.40886 inner_val_multiclass_log_loss=2.40889 best_multiclass_log_loss=2.40889 best_epoch=40 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=19 full_refit_epoch=1/40 loss=4.78382
  fit=19 full_refit_epoch=2/40 loss=4.60593
  fit=19 full_refit_epoch=3/40 loss=4.42989
  fit=19 full_refit_epoch=4/40 loss=4.22715
  fit=19 full_refit_epoch=5/40 loss=3.99684
  fit=19 full_refit_epoch=6/40 loss=3.75249
  fit=19 full_refit_epoch=7/40 loss=3.51416
  fit=19 full_refit_epoch=8/40 loss=3.26404
  fit=19 full_refit_epoch=9/40 loss=3.02605
  fit=19 full_refit_epoch=10/40 loss=2.79345
  fit=19 full_refit_epoch=11/40 loss=2.56204
  fit=19 full_refit_epoch=12/40 loss=2.36419
  fit=19 full_refit_epoch=13/40 loss=2.15368
  fit=19 full_refit_epoch=14/40 loss=1.96638
  fit=19 full_refit_epoch=15/40 loss=1.78290
  fit=19 full_refit_epoch=16/40 loss=1.62735
  fit=19 full_refit_epoch=17/40 loss=1.46567
  fit=19 full_refit_epoch=18/40 loss=1.31435
  fit=19 full_refit_epoch=19/40 loss=1.17849
  fit=19 full_refit_epoch=20/40 loss=1.04482
  fit=19 full_refit_epoch=21/40 loss=0.93599
  fit=19 full_refit_epoch=22/40 loss=0.82802
  fit=19 full_refit_epoch=23/40 loss=0.73241
  fit=19 full_refit_epoch=24/40 loss=0.64588
  fit=19 full_refit_epoch=25/40 loss=0.57137
  fit=19 full_refit_epoch=26/40 loss=0.49800
  fit=19 full_refit_epoch=27/40 loss=0.43521
  fit=19 full_refit_epoch=28/40 loss=0.39097
  fit=19 full_refit_epoch=29/40 loss=0.35223
  fit=19 full_refit_epoch=30/40 loss=0.30540
  fit=19 full_refit_epoch=31/40 loss=0.26708
  fit=19 full_refit_epoch=32/40 loss=0.23549
  fit=19 full_refit_epoch=33/40 loss=0.20737
  fit=19 full_refit_epoch=34/40 loss=0.18645
  fit=19 full_refit_epoch=35/40 loss=0.16723
  fit=19 full_refit_epoch=36/40 loss=0.14765
  fit=19 full_refit_epoch=37/40 loss=0.13257
  fit=19 full_refit_epoch=38/40 loss=0.12424
  fit=19 full_refit_epoch=39/40 loss=0.10739
  fit=19 full_refit_epoch=40/40 loss=0.09676

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=1/40 loss=4.78442 inner_val_loss=4.74988 inner_val_multiclass_log_loss=4.74991 best_multiclass_log_loss=4.74991 best_epoch=1 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=2/40 loss=4.61357 inner_val_loss=4.68988 inner_val_multiclass_log_loss=4.68997 best_multiclass_log_loss=4.68997 best_epoch=2 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=3/40 loss=4.45425 inner_val_loss=4.60145 inner_val_multiclass_log_loss=4.60136 best_multiclass_log_loss=4.60136 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=4/40 loss=4.27011 inner_val_loss=4.52010 inner_val_multiclass_log_loss=4.52011 best_multiclass_log_loss=4.52011 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=5/40 loss=4.06233 inner_val_loss=4.37511 inner_val_multiclass_log_loss=4.37502 best_multiclass_log_loss=4.37502 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=6/40 loss=3.84104 inner_val_loss=4.32146 inner_val_multiclass_log_loss=4.32137 best_multiclass_log_loss=4.32137 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=7/40 loss=3.61124 inner_val_loss=4.14104 inner_val_multiclass_log_loss=4.14106 best_multiclass_log_loss=4.14106 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=8/40 loss=3.37444 inner_val_loss=4.03238 inner_val_multiclass_log_loss=4.03227 best_multiclass_log_loss=4.03227 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=9/40 loss=3.14614 inner_val_loss=3.91143 inner_val_multiclass_log_loss=3.91143 best_multiclass_log_loss=3.91143 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=10/40 loss=2.93865 inner_val_loss=3.75981 inner_val_multiclass_log_loss=3.75985 best_multiclass_log_loss=3.75985 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=11/40 loss=2.71751 inner_val_loss=3.61725 inner_val_multiclass_log_loss=3.61727 best_multiclass_log_loss=3.61727 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=12/40 loss=2.51761 inner_val_loss=3.57008 inner_val_multiclass_log_loss=3.57002 best_multiclass_log_loss=3.57002 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=13/40 loss=2.31109 inner_val_loss=3.41362 inner_val_multiclass_log_loss=3.41353 best_multiclass_log_loss=3.41353 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=14/40 loss=2.13010 inner_val_loss=3.35824 inner_val_multiclass_log_loss=3.35825 best_multiclass_log_loss=3.35825 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=15/40 loss=1.95083 inner_val_loss=3.24787 inner_val_multiclass_log_loss=3.24785 best_multiclass_log_loss=3.24785 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=16/40 loss=1.78590 inner_val_loss=3.11615 inner_val_multiclass_log_loss=3.11605 best_multiclass_log_loss=3.11605 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=17/40 loss=1.61995 inner_val_loss=3.10558 inner_val_multiclass_log_loss=3.10559 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=18/40 loss=1.45544 inner_val_loss=3.12725 inner_val_multiclass_log_loss=3.12726 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=19/40 loss=1.31723 inner_val_loss=2.96704 inner_val_multiclass_log_loss=2.96702 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=20/40 loss=1.17842 inner_val_loss=3.05234 inner_val_multiclass_log_loss=3.05228 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=21/40 loss=1.06264 inner_val_loss=2.95265 inner_val_multiclass_log_loss=2.95266 best_multiclass_log_loss=2.95266 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=22/40 loss=0.95244 inner_val_loss=2.91211 inner_val_multiclass_log_loss=2.91221 best_multiclass_log_loss=2.91221 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=23/40 loss=0.84644 inner_val_loss=2.89159 inner_val_multiclass_log_loss=2.89156 best_multiclass_log_loss=2.89156 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=24/40 loss=0.76082 inner_val_loss=2.88187 inner_val_multiclass_log_loss=2.88200 best_multiclass_log_loss=2.88200 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=25/40 loss=0.67191 inner_val_loss=2.84233 inner_val_multiclass_log_loss=2.84237 best_multiclass_log_loss=2.84237 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=26/40 loss=0.60417 inner_val_loss=2.77625 inner_val_multiclass_log_loss=2.77628 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=27/40 loss=0.52400 inner_val_loss=2.81227 inner_val_multiclass_log_loss=2.81225 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=28/40 loss=0.46472 inner_val_loss=2.74761 inner_val_multiclass_log_loss=2.74756 best_multiclass_log_loss=2.74756 best_epoch=28 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=29/40 loss=0.40611 inner_val_loss=2.74257 inner_val_multiclass_log_loss=2.74254 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=30/40 loss=0.36938 inner_val_loss=2.75965 inner_val_multiclass_log_loss=2.75972 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=31/40 loss=0.32566 inner_val_loss=2.72053 inner_val_multiclass_log_loss=2.72051 best_multiclass_log_loss=2.72051 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=32/40 loss=0.30059 inner_val_loss=2.69751 inner_val_multiclass_log_loss=2.69749 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=33/40 loss=0.27015 inner_val_loss=2.74933 inner_val_multiclass_log_loss=2.74931 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=34/40 loss=0.23087 inner_val_loss=2.77536 inner_val_multiclass_log_loss=2.77540 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=35/40 loss=0.20538 inner_val_loss=2.74973 inner_val_multiclass_log_loss=2.74970 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 epoch=36/40 loss=0.18884 inner_val_loss=2.75416 inner_val_multiclass_log_loss=2.75420 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0
  fit=20 epoch=37/40 loss=0.16183 inner_val_loss=2.72750 inner_val_multiclass_log_loss=2.72753 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=20 full_refit_epoch=1/32 loss=4.77728
  fit=20 full_refit_epoch=2/32 loss=4.61421
  fit=20 full_refit_epoch=3/32 loss=4.44084
  fit=20 full_refit_epoch=4/32 loss=4.24429
  fit=20 full_refit_epoch=5/32 loss=4.01696
  fit=20 full_refit_epoch=6/32 loss=3.77332
  fit=20 full_refit_epoch=7/32 loss=3.51979
  fit=20 full_refit_epoch=8/32 loss=3.26840
  fit=20 full_refit_epoch=9/32 loss=3.03903
  fit=20 full_refit_epoch=10/32 loss=2.81296
  fit=20 full_refit_epoch=11/32 loss=2.58932
  fit=20 full_refit_epoch=12/32 loss=2.37527
  fit=20 full_refit_epoch=13/32 loss=2.16968
  fit=20 full_refit_epoch=14/32 loss=1.98022
  fit=20 full_refit_epoch=15/32 loss=1.79258
  fit=20 full_refit_epoch=16/32 loss=1.62738
  fit=20 full_refit_epoch=17/32 loss=1.46720
  fit=20 full_refit_epoch=18/32 loss=1.31258
  fit=20 full_refit_epoch=19/32 loss=1.17510
  fit=20 full_refit_epoch=20/32 loss=1.05290
  fit=20 full_refit_epoch=21/32 loss=0.92468
  fit=20 full_refit_epoch=22/32 loss=0.81936
  fit=20 full_refit_epoch=23/32 loss=0.72419
  fit=20 full_refit_epoch=24/32 loss=0.63480
  fit=20 full_refit_epoch=25/32 loss=0.55535
  fit=20 full_refit_epoch=26/32 loss=0.48229
  fit=20 full_refit_epoch=27/32 loss=0.42661
  fit=20 full_refit_epoch=28/32 loss=0.37705
  fit=20 full_refit_epoch=29/32 loss=0.31890
  fit=20 full_refit_epoch=30/32 loss=0.28566
  fit=20 full_refit_epoch=31/32 loss=0.26161
  fit=20 full_refit_epoch=32/32 loss=0.22707

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=initial_selected model=resnet18 metric=2.464116220981177 error=None minutes=13.20
START seed=47 phase=ablation model=pass

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=ablation model=pass metric=4.787491690627983 error=None minutes=0.23
START seed=47 phase=refinement model=efficientnet_b0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=1/40 loss=5.01010 inner_val_loss=4.80068 inner_val_multiclass_log_loss=4.80060 best_multiclass_log_loss=4.80060 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=2/40 loss=3.86606 inner_val_loss=4.45876 inner_val_multiclass_log_loss=4.45880 best_multiclass_log_loss=4.45880 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=3/40 loss=2.92148 inner_val_loss=4.11238 inner_val_multiclass_log_loss=4.11225 best_multiclass_log_loss=4.11225 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=4/40 loss=2.11127 inner_val_loss=3.86819 inner_val_multiclass_log_loss=3.86822 best_multiclass_log_loss=3.86822 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=5/40 loss=1.48764 inner_val_loss=3.68414 inner_val_multiclass_log_loss=3.68418 best_multiclass_log_loss=3.68418 best_epoch=5 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=6/40 loss=1.05689 inner_val_loss=3.49516 inner_val_multiclass_log_loss=3.49521 best_multiclass_log_loss=3.49521 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=7/40 loss=0.71140 inner_val_loss=3.34357 inner_val_multiclass_log_loss=3.34358 best_multiclass_log_loss=3.34358 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=8/40 loss=0.49035 inner_val_loss=3.27626 inner_val_multiclass_log_loss=3.27629 best_multiclass_log_loss=3.27629 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=9/40 loss=0.35021 inner_val_loss=3.25475 inner_val_multiclass_log_loss=3.25468 best_multiclass_log_loss=3.25468 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=10/40 loss=0.26594 inner_val_loss=3.21665 inner_val_multiclass_log_loss=3.21665 best_multiclass_log_loss=3.21665 best_epoch=10 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=11/40 loss=0.20252 inner_val_loss=3.15687 inner_val_multiclass_log_loss=3.15686 best_multiclass_log_loss=3.15686 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=12/40 loss=0.15865 inner_val_loss=3.08151 inner_val_multiclass_log_loss=3.08153 best_multiclass_log_loss=3.08153 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=13/40 loss=0.12785 inner_val_loss=3.07211 inner_val_multiclass_log_loss=3.07216 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=14/40 loss=0.10510 inner_val_loss=3.08785 inner_val_multiclass_log_loss=3.08783 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=15/40 loss=0.08510 inner_val_loss=3.08263 inner_val_multiclass_log_loss=3.08265 best_multiclass_log_loss=3.07216 best_epoch=13 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=16/40 loss=0.08460 inner_val_loss=3.07192 inner_val_multiclass_log_loss=3.07196 best_multiclass_log_loss=3.07196 best_epoch=16 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=17/40 loss=0.07478 inner_val_loss=3.04369 inner_val_multiclass_log_loss=3.04378 best_multiclass_log_loss=3.04378 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=18/40 loss=0.06367 inner_val_loss=2.98642 inner_val_multiclass_log_loss=2.98641 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=19/40 loss=0.06794 inner_val_loss=2.98767 inner_val_multiclass_log_loss=2.98764 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=20/40 loss=0.04836 inner_val_loss=2.99491 inner_val_multiclass_log_loss=2.99492 best_multiclass_log_loss=2.98641 best_epoch=18 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=21/40 loss=0.04701 inner_val_loss=2.97468 inner_val_multiclass_log_loss=2.97462 best_multiclass_log_loss=2.97462 best_epoch=21 seconds=2.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=22/40 loss=0.04027 inner_val_loss=2.97743 inner_val_multiclass_log_loss=2.97751 best_multiclass_log_loss=2.97462 best_epoch=21 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=23/40 loss=0.04057 inner_val_loss=2.92894 inner_val_multiclass_log_loss=2.92900 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=24/40 loss=0.03630 inner_val_loss=2.95130 inner_val_multiclass_log_loss=2.95126 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=25/40 loss=0.03352 inner_val_loss=2.96364 inner_val_multiclass_log_loss=2.96357 best_multiclass_log_loss=2.92900 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=26/40 loss=0.03007 inner_val_loss=2.91611 inner_val_multiclass_log_loss=2.91617 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=27/40 loss=0.03253 inner_val_loss=2.92490 inner_val_multiclass_log_loss=2.92486 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=28/40 loss=0.03118 inner_val_loss=2.94123 inner_val_multiclass_log_loss=2.94135 best_multiclass_log_loss=2.91617 best_epoch=26 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=29/40 loss=0.03109 inner_val_loss=2.90074 inner_val_multiclass_log_loss=2.90077 best_multiclass_log_loss=2.90077 best_epoch=29 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=30/40 loss=0.02353 inner_val_loss=2.88433 inner_val_multiclass_log_loss=2.88431 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=31/40 loss=0.01862 inner_val_loss=2.91946 inner_val_multiclass_log_loss=2.91947 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=32/40 loss=0.02842 inner_val_loss=2.94810 inner_val_multiclass_log_loss=2.94814 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=33/40 loss=0.01988 inner_val_loss=2.90140 inner_val_multiclass_log_loss=2.90133 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 epoch=34/40 loss=0.02532 inner_val_loss=2.90284 inner_val_multiclass_log_loss=2.90280 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.2
  fit=21 epoch=35/40 loss=0.01641 inner_val_loss=2.89318 inner_val_multiclass_log_loss=2.89317 best_multiclass_log_loss=2.88431 best_epoch=30 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=21 full_refit_epoch=1/30 loss=4.97104
  fit=21 full_refit_epoch=2/30 loss=3.79284
  fit=21 full_refit_epoch=3/30 loss=2.79163
  fit=21 full_refit_epoch=4/30 loss=1.97404
  fit=21 full_refit_epoch=5/30 loss=1.39008
  fit=21 full_refit_epoch=6/30 loss=0.92452
  fit=21 full_refit_epoch=7/30 loss=0.62449
  fit=21 full_refit_epoch=8/30 loss=0.41424
  fit=21 full_refit_epoch=9/30 loss=0.28214
  fit=21 full_refit_epoch=10/30 loss=0.21174
  fit=21 full_refit_epoch=11/30 loss=0.15753
  fit=21 full_refit_epoch=12/30 loss=0.12486
  fit=21 full_refit_epoch=13/30 loss=0.09789
  fit=21 full_refit_epoch=14/30 loss=0.08348
  fit=21 full_refit_epoch=15/30 loss=0.07206
  fit=21 full_refit_epoch=16/30 loss=0.06392
  fit=21 full_refit_epoch=17/30 loss=0.05052
  fit=21 full_refit_epoch=18/30 loss=0.04391
  fit=21 full_refit_epoch=19/30 loss=0.04142
  fit=21 full_refit_epoch=20/30 loss=0.03857
  fit=21 full_refit_epoch=21/30 loss=0.03237
  fit=21 full_refit_epoch=22/30 loss=0.02738
  fit=21 full_refit_epoch=23/30 loss=0.02653
  fit=21 full_refit_epoch=24/30 loss=0.02426
  fit=21 full_refit_epoch=25/30 loss=0.02314
  fit=21 full_refit_epoch=26/30 loss=0.01994
  fit=21 full_refit_epoch=27/30 loss=0.01859
  fit=21 full_refit_epoch=28/30 loss=0.01889
  fit=21 full_refit_epoch=29/30 loss=0.01694
  fit=21 full_refit_epoch=30/30 loss=0.01770

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=1/40 loss=4.97853 inner_val_loss=4.82274 inner_val_multiclass_log_loss=4.82261 best_multiclass_log_loss=4.82261 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=2/40 loss=3.80224 inner_val_loss=4.51570 inner_val_multiclass_log_loss=4.51573 best_multiclass_log_loss=4.51573 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=3/40 loss=2.83644 inner_val_loss=4.18771 inner_val_multiclass_log_loss=4.18763 best_multiclass_log_loss=4.18763 best_epoch=3 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=4/40 loss=2.04215 inner_val_loss=3.93679 inner_val_multiclass_log_loss=3.93676 best_multiclass_log_loss=3.93676 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=5/40 loss=1.48743 inner_val_loss=3.73534 inner_val_multiclass_log_loss=3.73535 best_multiclass_log_loss=3.73535 best_epoch=5 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=6/40 loss=1.02682 inner_val_loss=3.57692 inner_val_multiclass_log_loss=3.57679 best_multiclass_log_loss=3.57679 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=7/40 loss=0.67756 inner_val_loss=3.39418 inner_val_multiclass_log_loss=3.39421 best_multiclass_log_loss=3.39421 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=8/40 loss=0.49210 inner_val_loss=3.30826 inner_val_multiclass_log_loss=3.30835 best_multiclass_log_loss=3.30835 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=9/40 loss=0.35624 inner_val_loss=3.24481 inner_val_multiclass_log_loss=3.24488 best_multiclass_log_loss=3.24488 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=10/40 loss=0.25484 inner_val_loss=3.22805 inner_val_multiclass_log_loss=3.22796 best_multiclass_log_loss=3.22796 best_epoch=10 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=11/40 loss=0.21448 inner_val_loss=3.21863 inner_val_multiclass_log_loss=3.21858 best_multiclass_log_loss=3.21858 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=12/40 loss=0.15821 inner_val_loss=3.12964 inner_val_multiclass_log_loss=3.12965 best_multiclass_log_loss=3.12965 best_epoch=12 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=13/40 loss=0.13378 inner_val_loss=3.10256 inner_val_multiclass_log_loss=3.10258 best_multiclass_log_loss=3.10258 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=14/40 loss=0.10728 inner_val_loss=3.08182 inner_val_multiclass_log_loss=3.08175 best_multiclass_log_loss=3.08175 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=15/40 loss=0.10725 inner_val_loss=3.05171 inner_val_multiclass_log_loss=3.05171 best_multiclass_log_loss=3.05171 best_epoch=15 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=16/40 loss=0.08221 inner_val_loss=3.04101 inner_val_multiclass_log_loss=3.04105 best_multiclass_log_loss=3.04105 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=17/40 loss=0.07468 inner_val_loss=3.02810 inner_val_multiclass_log_loss=3.02820 best_multiclass_log_loss=3.02820 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=18/40 loss=0.06218 inner_val_loss=3.03901 inner_val_multiclass_log_loss=3.03903 best_multiclass_log_loss=3.02820 best_epoch=17 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=19/40 loss=0.06554 inner_val_loss=3.01746 inner_val_multiclass_log_loss=3.01749 best_multiclass_log_loss=3.01749 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=20/40 loss=0.05798 inner_val_loss=3.05144 inner_val_multiclass_log_loss=3.05147 best_multiclass_log_loss=3.01749 best_epoch=19 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=21/40 loss=0.05249 inner_val_loss=2.98748 inner_val_multiclass_log_loss=2.98754 best_multiclass_log_loss=2.98754 best_epoch=21 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=22/40 loss=0.06121 inner_val_loss=2.98020 inner_val_multiclass_log_loss=2.98020 best_multiclass_log_loss=2.98020 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=23/40 loss=0.04624 inner_val_loss=2.97715 inner_val_multiclass_log_loss=2.97715 best_multiclass_log_loss=2.97715 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=24/40 loss=0.04318 inner_val_loss=2.95488 inner_val_multiclass_log_loss=2.95491 best_multiclass_log_loss=2.95491 best_epoch=24 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=25/40 loss=0.04004 inner_val_loss=2.94355 inner_val_multiclass_log_loss=2.94349 best_multiclass_log_loss=2.94349 best_epoch=25 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=26/40 loss=0.03721 inner_val_loss=2.95222 inner_val_multiclass_log_loss=2.95214 best_multiclass_log_loss=2.94349 best_epoch=25 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=27/40 loss=0.03983 inner_val_loss=2.93778 inner_val_multiclass_log_loss=2.93779 best_multiclass_log_loss=2.93779 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=28/40 loss=0.03033 inner_val_loss=2.93094 inner_val_multiclass_log_loss=2.93090 best_multiclass_log_loss=2.93090 best_epoch=28 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=29/40 loss=0.02639 inner_val_loss=2.94501 inner_val_multiclass_log_loss=2.94492 best_multiclass_log_loss=2.93090 best_epoch=28 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=30/40 loss=0.02605 inner_val_loss=2.87976 inner_val_multiclass_log_loss=2.87973 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=31/40 loss=0.02403 inner_val_loss=2.88979 inner_val_multiclass_log_loss=2.88973 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=32/40 loss=0.02041 inner_val_loss=2.89035 inner_val_multiclass_log_loss=2.89034 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=33/40 loss=0.04041 inner_val_loss=2.92775 inner_val_multiclass_log_loss=2.92774 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 epoch=34/40 loss=0.02739 inner_val_loss=2.91699 inner_val_multiclass_log_loss=2.91689 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0
  fit=22 epoch=35/40 loss=0.02424 inner_val_loss=2.88624 inner_val_multiclass_log_loss=2.88624 best_multiclass_log_loss=2.87973 best_epoch=30 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=22 full_refit_epoch=1/30 loss=4.95701
  fit=22 full_refit_epoch=2/30 loss=3.76389
  fit=22 full_refit_epoch=3/30 loss=2.76631
  fit=22 full_refit_epoch=4/30 loss=1.97034
  fit=22 full_refit_epoch=5/30 loss=1.37501
  fit=22 full_refit_epoch=6/30 loss=0.92699
  fit=22 full_refit_epoch=7/30 loss=0.63547
  fit=22 full_refit_epoch=8/30 loss=0.42337
  fit=22 full_refit_epoch=9/30 loss=0.29723
  fit=22 full_refit_epoch=10/30 loss=0.21330
  fit=22 full_refit_epoch=11/30 loss=0.16205
  fit=22 full_refit_epoch=12/30 loss=0.12810
  fit=22 full_refit_epoch=13/30 loss=0.10264
  fit=22 full_refit_epoch=14/30 loss=0.08207
  fit=22 full_refit_epoch=15/30 loss=0.07589
  fit=22 full_refit_epoch=16/30 loss=0.05841
  fit=22 full_refit_epoch=17/30 loss=0.04985
  fit=22 full_refit_epoch=18/30 loss=0.04473
  fit=22 full_refit_epoch=19/30 loss=0.03919
  fit=22 full_refit_epoch=20/30 loss=0.03725
  fit=22 full_refit_epoch=21/30 loss=0.03176
  fit=22 full_refit_epoch=22/30 loss=0.02904
  fit=22 full_refit_epoch=23/30 loss=0.02649
  fit=22 full_refit_epoch=24/30 loss=0.02302
  fit=22 full_refit_epoch=25/30 loss=0.02214
  fit=22 full_refit_epoch=26/30 loss=0.02007
  fit=22 full_refit_epoch=27/30 loss=0.01857
  fit=22 full_refit_epoch=28/30 loss=0.01774
  fit=22 full_refit_epoch=29/30 loss=0.01611
  fit=22 full_refit_epoch=30/30 loss=0.01531

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=1/40 loss=5.01676 inner_val_loss=4.79880 inner_val_multiclass_log_loss=4.79885 best_multiclass_log_loss=4.79885 best_epoch=1 seconds=3.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=2/40 loss=3.80691 inner_val_loss=4.51623 inner_val_multiclass_log_loss=4.51620 best_multiclass_log_loss=4.51620 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=3/40 loss=2.86201 inner_val_loss=4.11611 inner_val_multiclass_log_loss=4.11622 best_multiclass_log_loss=4.11622 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=4/40 loss=2.07205 inner_val_loss=3.82281 inner_val_multiclass_log_loss=3.82290 best_multiclass_log_loss=3.82290 best_epoch=4 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=5/40 loss=1.44820 inner_val_loss=3.62108 inner_val_multiclass_log_loss=3.62105 best_multiclass_log_loss=3.62105 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=6/40 loss=1.02230 inner_val_loss=3.44531 inner_val_multiclass_log_loss=3.44531 best_multiclass_log_loss=3.44531 best_epoch=6 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=7/40 loss=0.72771 inner_val_loss=3.36164 inner_val_multiclass_log_loss=3.36169 best_multiclass_log_loss=3.36169 best_epoch=7 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=8/40 loss=0.48160 inner_val_loss=3.23977 inner_val_multiclass_log_loss=3.23984 best_multiclass_log_loss=3.23984 best_epoch=8 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=9/40 loss=0.35689 inner_val_loss=3.14501 inner_val_multiclass_log_loss=3.14506 best_multiclass_log_loss=3.14506 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=10/40 loss=0.25234 inner_val_loss=3.09822 inner_val_multiclass_log_loss=3.09819 best_multiclass_log_loss=3.09819 best_epoch=10 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=11/40 loss=0.19780 inner_val_loss=3.06664 inner_val_multiclass_log_loss=3.06666 best_multiclass_log_loss=3.06666 best_epoch=11 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=12/40 loss=0.15111 inner_val_loss=3.01875 inner_val_multiclass_log_loss=3.01873 best_multiclass_log_loss=3.01873 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=13/40 loss=0.12057 inner_val_loss=2.99054 inner_val_multiclass_log_loss=2.99054 best_multiclass_log_loss=2.99054 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=14/40 loss=0.11119 inner_val_loss=2.92545 inner_val_multiclass_log_loss=2.92545 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=15/40 loss=0.09669 inner_val_loss=2.93029 inner_val_multiclass_log_loss=2.93027 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=16/40 loss=0.08153 inner_val_loss=2.94174 inner_val_multiclass_log_loss=2.94174 best_multiclass_log_loss=2.92545 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=17/40 loss=0.08088 inner_val_loss=2.88128 inner_val_multiclass_log_loss=2.88141 best_multiclass_log_loss=2.88141 best_epoch=17 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=18/40 loss=0.06766 inner_val_loss=2.89064 inner_val_multiclass_log_loss=2.89066 best_multiclass_log_loss=2.88141 best_epoch=17 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=19/40 loss=0.05888 inner_val_loss=2.86098 inner_val_multiclass_log_loss=2.86090 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=20/40 loss=0.04984 inner_val_loss=2.86946 inner_val_multiclass_log_loss=2.86940 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=21/40 loss=0.04524 inner_val_loss=2.87298 inner_val_multiclass_log_loss=2.87305 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=22/40 loss=0.04623 inner_val_loss=2.86256 inner_val_multiclass_log_loss=2.86264 best_multiclass_log_loss=2.86090 best_epoch=19 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=23/40 loss=0.04556 inner_val_loss=2.79280 inner_val_multiclass_log_loss=2.79277 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=24/40 loss=0.04645 inner_val_loss=2.86354 inner_val_multiclass_log_loss=2.86351 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=25/40 loss=0.03811 inner_val_loss=2.87722 inner_val_multiclass_log_loss=2.87727 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=26/40 loss=0.03437 inner_val_loss=2.86250 inner_val_multiclass_log_loss=2.86249 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 epoch=27/40 loss=0.03223 inner_val_loss=2.93675 inner_val_multiclass_log_loss=2.93669 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0
  fit=23 epoch=28/40 loss=0.03493 inner_val_loss=2.86849 inner_val_multiclass_log_loss=2.86851 best_multiclass_log_loss=2.79277 best_epoch=23 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=23 full_refit_epoch=1/23 loss=4.97264
  fit=23 full_refit_epoch=2/23 loss=3.79471
  fit=23 full_refit_epoch=3/23 loss=2.81100
  fit=23 full_refit_epoch=4/23 loss=1.99287
  fit=23 full_refit_epoch=5/23 loss=1.39035
  fit=23 full_refit_epoch=6/23 loss=0.94705
  fit=23 full_refit_epoch=7/23 loss=0.63439
  fit=23 full_refit_epoch=8/23 loss=0.42073
  fit=23 full_refit_epoch=9/23 loss=0.31329
  fit=23 full_refit_epoch=10/23 loss=0.21250
  fit=23 full_refit_epoch=11/23 loss=0.15894
  fit=23 full_refit_epoch=12/23 loss=0.12872
  fit=23 full_refit_epoch=13/23 loss=0.10318
  fit=23 full_refit_epoch=14/23 loss=0.08752
  fit=23 full_refit_epoch=15/23 loss=0.07252
  fit=23 full_refit_epoch=16/23 loss=0.06406
  fit=23 full_refit_epoch=17/23 loss=0.05577
  fit=23 full_refit_epoch=18/23 loss=0.05109
  fit=23 full_refit_epoch=19/23 loss=0.04319
  fit=23 full_refit_epoch=20/23 loss=0.03615
  fit=23 full_refit_epoch=21/23 loss=0.03439
  fit=23 full_refit_epoch=22/23 loss=0.03117
  fit=23 full_refit_epoch=23/23 loss=0.02994

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=1/40 loss=4.98019 inner_val_loss=4.80112 inner_val_multiclass_log_loss=4.80111 best_multiclass_log_loss=4.80111 best_epoch=1 seconds=3.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=2/40 loss=3.83545 inner_val_loss=4.38068 inner_val_multiclass_log_loss=4.38072 best_multiclass_log_loss=4.38072 best_epoch=2 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=3/40 loss=2.85394 inner_val_loss=4.08940 inner_val_multiclass_log_loss=4.08944 best_multiclass_log_loss=4.08944 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=4/40 loss=2.10510 inner_val_loss=3.80768 inner_val_multiclass_log_loss=3.80774 best_multiclass_log_loss=3.80774 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=5/40 loss=1.48305 inner_val_loss=3.61064 inner_val_multiclass_log_loss=3.61058 best_multiclass_log_loss=3.61058 best_epoch=5 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=6/40 loss=0.99575 inner_val_loss=3.43767 inner_val_multiclass_log_loss=3.43759 best_multiclass_log_loss=3.43759 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=7/40 loss=0.69398 inner_val_loss=3.31066 inner_val_multiclass_log_loss=3.31061 best_multiclass_log_loss=3.31061 best_epoch=7 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=8/40 loss=0.48288 inner_val_loss=3.24260 inner_val_multiclass_log_loss=3.24255 best_multiclass_log_loss=3.24255 best_epoch=8 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=9/40 loss=0.35200 inner_val_loss=3.15228 inner_val_multiclass_log_loss=3.15232 best_multiclass_log_loss=3.15232 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=10/40 loss=0.25655 inner_val_loss=3.12074 inner_val_multiclass_log_loss=3.12082 best_multiclass_log_loss=3.12082 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=11/40 loss=0.20205 inner_val_loss=3.06036 inner_val_multiclass_log_loss=3.06030 best_multiclass_log_loss=3.06030 best_epoch=11 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=12/40 loss=0.17252 inner_val_loss=3.05890 inner_val_multiclass_log_loss=3.05901 best_multiclass_log_loss=3.05901 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=13/40 loss=0.12944 inner_val_loss=3.04077 inner_val_multiclass_log_loss=3.04078 best_multiclass_log_loss=3.04078 best_epoch=13 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=14/40 loss=0.10360 inner_val_loss=3.02117 inner_val_multiclass_log_loss=3.02102 best_multiclass_log_loss=3.02102 best_epoch=14 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=15/40 loss=0.09986 inner_val_loss=2.99078 inner_val_multiclass_log_loss=2.99081 best_multiclass_log_loss=2.99081 best_epoch=15 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=16/40 loss=0.08945 inner_val_loss=2.98474 inner_val_multiclass_log_loss=2.98470 best_multiclass_log_loss=2.98470 best_epoch=16 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=17/40 loss=0.08664 inner_val_loss=2.95091 inner_val_multiclass_log_loss=2.95088 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=18/40 loss=0.07508 inner_val_loss=2.97918 inner_val_multiclass_log_loss=2.97926 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=19/40 loss=0.05799 inner_val_loss=2.98011 inner_val_multiclass_log_loss=2.98012 best_multiclass_log_loss=2.95088 best_epoch=17 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=20/40 loss=0.05265 inner_val_loss=2.93493 inner_val_multiclass_log_loss=2.93487 best_multiclass_log_loss=2.93487 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=21/40 loss=0.05421 inner_val_loss=2.92046 inner_val_multiclass_log_loss=2.92049 best_multiclass_log_loss=2.92049 best_epoch=21 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=22/40 loss=0.04896 inner_val_loss=2.89906 inner_val_multiclass_log_loss=2.89899 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=23/40 loss=0.04702 inner_val_loss=2.92943 inner_val_multiclass_log_loss=2.92939 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=24/40 loss=0.03694 inner_val_loss=2.97597 inner_val_multiclass_log_loss=2.97602 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=25/40 loss=0.03457 inner_val_loss=2.94485 inner_val_multiclass_log_loss=2.94488 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=26/40 loss=0.03043 inner_val_loss=2.91487 inner_val_multiclass_log_loss=2.91489 best_multiclass_log_loss=2.89899 best_epoch=22 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=27/40 loss=0.03084 inner_val_loss=2.87474 inner_val_multiclass_log_loss=2.87473 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=28/40 loss=0.02971 inner_val_loss=2.91254 inner_val_multiclass_log_loss=2.91250 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=29/40 loss=0.02888 inner_val_loss=2.91208 inner_val_multiclass_log_loss=2.91214 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=30/40 loss=0.02872 inner_val_loss=2.92271 inner_val_multiclass_log_loss=2.92271 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 epoch=31/40 loss=0.02441 inner_val_loss=2.92348 inner_val_multiclass_log_loss=2.92349 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=2.9
  fit=24 epoch=32/40 loss=0.03908 inner_val_loss=2.95038 inner_val_multiclass_log_loss=2.95038 best_multiclass_log_loss=2.87473 best_epoch=27 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=24 full_refit_epoch=1/27 loss=4.96757
  fit=24 full_refit_epoch=2/27 loss=3.78009
  fit=24 full_refit_epoch=3/27 loss=2.79538
  fit=24 full_refit_epoch=4/27 loss=1.98783
  fit=24 full_refit_epoch=5/27 loss=1.38019
  fit=24 full_refit_epoch=6/27 loss=0.93883
  fit=24 full_refit_epoch=7/27 loss=0.64393
  fit=24 full_refit_epoch=8/27 loss=0.43505
  fit=24 full_refit_epoch=9/27 loss=0.31168
  fit=24 full_refit_epoch=10/27 loss=0.21197
  fit=24 full_refit_epoch=11/27 loss=0.16040
  fit=24 full_refit_epoch=12/27 loss=0.13273
  fit=24 full_refit_epoch=13/27 loss=0.09999
  fit=24 full_refit_epoch=14/27 loss=0.08581
  fit=24 full_refit_epoch=15/27 loss=0.07211
  fit=24 full_refit_epoch=16/27 loss=0.06771
  fit=24 full_refit_epoch=17/27 loss=0.05184
  fit=24 full_refit_epoch=18/27 loss=0.04838
  fit=24 full_refit_epoch=19/27 loss=0.04290
  fit=24 full_refit_epoch=20/27 loss=0.03667
  fit=24 full_refit_epoch=21/27 loss=0.03470
  fit=24 full_refit_epoch=22/27 loss=0.03014
  fit=24 full_refit_epoch=23/27 loss=0.02907
  fit=24 full_refit_epoch=24/27 loss=0.02482
  fit=24 full_refit_epoch=25/27 loss=0.02303
  fit=24 full_refit_epoch=26/27 loss=0.02001
  fit=24 full_refit_epoch=27/27 loss=0.01816

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=1/40 loss=4.98315 inner_val_loss=4.87857 inner_val_multiclass_log_loss=4.87864 best_multiclass_log_loss=4.87864 best_epoch=1 seconds=3.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=2/40 loss=3.79959 inner_val_loss=4.61240 inner_val_multiclass_log_loss=4.61237 best_multiclass_log_loss=4.61237 best_epoch=2 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=3/40 loss=2.87593 inner_val_loss=4.32853 inner_val_multiclass_log_loss=4.32851 best_multiclass_log_loss=4.32851 best_epoch=3 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=4/40 loss=2.08456 inner_val_loss=4.10305 inner_val_multiclass_log_loss=4.10312 best_multiclass_log_loss=4.10312 best_epoch=4 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=5/40 loss=1.47750 inner_val_loss=3.91342 inner_val_multiclass_log_loss=3.91342 best_multiclass_log_loss=3.91342 best_epoch=5 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=6/40 loss=1.05178 inner_val_loss=3.77663 inner_val_multiclass_log_loss=3.77666 best_multiclass_log_loss=3.77666 best_epoch=6 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=7/40 loss=0.70019 inner_val_loss=3.60753 inner_val_multiclass_log_loss=3.60750 best_multiclass_log_loss=3.60750 best_epoch=7 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=8/40 loss=0.50536 inner_val_loss=3.56600 inner_val_multiclass_log_loss=3.56610 best_multiclass_log_loss=3.56610 best_epoch=8 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=9/40 loss=0.35118 inner_val_loss=3.51525 inner_val_multiclass_log_loss=3.51517 best_multiclass_log_loss=3.51517 best_epoch=9 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=10/40 loss=0.27375 inner_val_loss=3.45606 inner_val_multiclass_log_loss=3.45601 best_multiclass_log_loss=3.45601 best_epoch=10 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=11/40 loss=0.20011 inner_val_loss=3.40658 inner_val_multiclass_log_loss=3.40653 best_multiclass_log_loss=3.40653 best_epoch=11 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=12/40 loss=0.17257 inner_val_loss=3.39790 inner_val_multiclass_log_loss=3.39797 best_multiclass_log_loss=3.39797 best_epoch=12 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=13/40 loss=0.12595 inner_val_loss=3.37083 inner_val_multiclass_log_loss=3.37092 best_multiclass_log_loss=3.37092 best_epoch=13 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=14/40 loss=0.11311 inner_val_loss=3.33538 inner_val_multiclass_log_loss=3.33535 best_multiclass_log_loss=3.33535 best_epoch=14 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=15/40 loss=0.10580 inner_val_loss=3.30966 inner_val_multiclass_log_loss=3.30965 best_multiclass_log_loss=3.30965 best_epoch=15 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=16/40 loss=0.09065 inner_val_loss=3.27146 inner_val_multiclass_log_loss=3.27146 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=17/40 loss=0.07366 inner_val_loss=3.29281 inner_val_multiclass_log_loss=3.29286 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=18/40 loss=0.05955 inner_val_loss=3.30540 inner_val_multiclass_log_loss=3.30539 best_multiclass_log_loss=3.27146 best_epoch=16 seconds=2.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=19/40 loss=0.06046 inner_val_loss=3.25990 inner_val_multiclass_log_loss=3.25991 best_multiclass_log_loss=3.25991 best_epoch=19 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=20/40 loss=0.05431 inner_val_loss=3.24322 inner_val_multiclass_log_loss=3.24322 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=21/40 loss=0.04827 inner_val_loss=3.25760 inner_val_multiclass_log_loss=3.25765 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=22/40 loss=0.04249 inner_val_loss=3.25500 inner_val_multiclass_log_loss=3.25499 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=23/40 loss=0.03823 inner_val_loss=3.25148 inner_val_multiclass_log_loss=3.25146 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 epoch=24/40 loss=0.03670 inner_val_loss=3.26316 inner_val_multiclass_log_loss=3.26307 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.2
  fit=25 epoch=25/40 loss=0.03862 inner_val_loss=3.26267 inner_val_multiclass_log_loss=3.26266 best_multiclass_log_loss=3.24322 best_epoch=20 seconds=3.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=25 full_refit_epoch=1/20 loss=4.95468
  fit=25 full_refit_epoch=2/20 loss=3.78333
  fit=25 full_refit_epoch=3/20 loss=2.79303
  fit=25 full_refit_epoch=4/20 loss=1.99956
  fit=25 full_refit_epoch=5/20 loss=1.41169
  fit=25 full_refit_epoch=6/20 loss=0.94167
  fit=25 full_refit_epoch=7/20 loss=0.64497
  fit=25 full_refit_epoch=8/20 loss=0.43648
  fit=25 full_refit_epoch=9/20 loss=0.31866
  fit=25 full_refit_epoch=10/20 loss=0.22920
  fit=25 full_refit_epoch=11/20 loss=0.16224
  fit=25 full_refit_epoch=12/20 loss=0.13304
  fit=25 full_refit_epoch=13/20 loss=0.10434
  fit=25 full_refit_epoch=14/20 loss=0.08762
  fit=25 full_refit_epoch=15/20 loss=0.07141
  fit=25 full_refit_epoch=16/20 loss=0.06351
  fit=25 full_refit_epoch=17/20 loss=0.05367
  fit=25 full_refit_epoch=18/20 loss=0.04474
  fit=25 full_refit_epoch=19/20 loss=0.03982
  fit=25 full_refit_epoch=20/20 loss=0.03946

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=refinement model=efficientnet_b0 metric=2.9808095613000827 error=None minutes=14.78
START seed=47 phase=refined_selected model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=1/40 loss=4.79604 inner_val_loss=4.73218 inner_val_multiclass_log_loss=4.73214 best_multiclass_log_loss=4.73214 best_epoch=1 seconds=2.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=2/40 loss=4.63253 inner_val_loss=4.67259 inner_val_multiclass_log_loss=4.67259 best_multiclass_log_loss=4.67259 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=3/40 loss=4.47386 inner_val_loss=4.55970 inner_val_multiclass_log_loss=4.55970 best_multiclass_log_loss=4.55970 best_epoch=3 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=4/40 loss=4.28732 inner_val_loss=4.44825 inner_val_multiclass_log_loss=4.44823 best_multiclass_log_loss=4.44823 best_epoch=4 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=5/40 loss=4.06886 inner_val_loss=4.33298 inner_val_multiclass_log_loss=4.33294 best_multiclass_log_loss=4.33294 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=6/40 loss=3.84643 inner_val_loss=4.13359 inner_val_multiclass_log_loss=4.13362 best_multiclass_log_loss=4.13362 best_epoch=6 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=7/40 loss=3.62140 inner_val_loss=3.97734 inner_val_multiclass_log_loss=3.97734 best_multiclass_log_loss=3.97734 best_epoch=7 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=8/40 loss=3.39511 inner_val_loss=3.88827 inner_val_multiclass_log_loss=3.88824 best_multiclass_log_loss=3.88824 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=9/40 loss=3.16729 inner_val_loss=3.77547 inner_val_multiclass_log_loss=3.77555 best_multiclass_log_loss=3.77555 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=10/40 loss=2.95336 inner_val_loss=3.69540 inner_val_multiclass_log_loss=3.69537 best_multiclass_log_loss=3.69537 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=11/40 loss=2.73357 inner_val_loss=3.54863 inner_val_multiclass_log_loss=3.54857 best_multiclass_log_loss=3.54857 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=12/40 loss=2.52061 inner_val_loss=3.44390 inner_val_multiclass_log_loss=3.44381 best_multiclass_log_loss=3.44381 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=13/40 loss=2.32619 inner_val_loss=3.36695 inner_val_multiclass_log_loss=3.36690 best_multiclass_log_loss=3.36690 best_epoch=13 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=14/40 loss=2.14268 inner_val_loss=3.29173 inner_val_multiclass_log_loss=3.29171 best_multiclass_log_loss=3.29171 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=15/40 loss=1.97246 inner_val_loss=3.19012 inner_val_multiclass_log_loss=3.19021 best_multiclass_log_loss=3.19021 best_epoch=15 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=16/40 loss=1.78584 inner_val_loss=3.08207 inner_val_multiclass_log_loss=3.08204 best_multiclass_log_loss=3.08204 best_epoch=16 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=17/40 loss=1.62255 inner_val_loss=3.02023 inner_val_multiclass_log_loss=3.02023 best_multiclass_log_loss=3.02023 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=18/40 loss=1.47096 inner_val_loss=2.96257 inner_val_multiclass_log_loss=2.96259 best_multiclass_log_loss=2.96259 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=19/40 loss=1.34683 inner_val_loss=2.88782 inner_val_multiclass_log_loss=2.88782 best_multiclass_log_loss=2.88782 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=20/40 loss=1.18152 inner_val_loss=2.87635 inner_val_multiclass_log_loss=2.87630 best_multiclass_log_loss=2.87630 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=21/40 loss=1.07280 inner_val_loss=2.82962 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=22/40 loss=0.96276 inner_val_loss=2.76426 inner_val_multiclass_log_loss=2.76424 best_multiclass_log_loss=2.76424 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=23/40 loss=0.85255 inner_val_loss=2.74589 inner_val_multiclass_log_loss=2.74593 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=24/40 loss=0.76815 inner_val_loss=2.76247 inner_val_multiclass_log_loss=2.76242 best_multiclass_log_loss=2.74593 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=25/40 loss=0.66728 inner_val_loss=2.70668 inner_val_multiclass_log_loss=2.70668 best_multiclass_log_loss=2.70668 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=26/40 loss=0.60636 inner_val_loss=2.70543 inner_val_multiclass_log_loss=2.70541 best_multiclass_log_loss=2.70541 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=27/40 loss=0.52941 inner_val_loss=2.68617 inner_val_multiclass_log_loss=2.68613 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=28/40 loss=0.48062 inner_val_loss=2.69317 inner_val_multiclass_log_loss=2.69317 best_multiclass_log_loss=2.68613 best_epoch=27 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=29/40 loss=0.41842 inner_val_loss=2.66156 inner_val_multiclass_log_loss=2.66154 best_multiclass_log_loss=2.66154 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=30/40 loss=0.36864 inner_val_loss=2.65680 inner_val_multiclass_log_loss=2.65670 best_multiclass_log_loss=2.65670 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=31/40 loss=0.32602 inner_val_loss=2.63176 inner_val_multiclass_log_loss=2.63183 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=32/40 loss=0.30625 inner_val_loss=2.66063 inner_val_multiclass_log_loss=2.66061 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=33/40 loss=0.26540 inner_val_loss=2.63391 inner_val_multiclass_log_loss=2.63389 best_multiclass_log_loss=2.63183 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=34/40 loss=0.24684 inner_val_loss=2.62465 inner_val_multiclass_log_loss=2.62469 best_multiclass_log_loss=2.62469 best_epoch=34 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=35/40 loss=0.20674 inner_val_loss=2.61135 inner_val_multiclass_log_loss=2.61138 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=36/40 loss=0.19393 inner_val_loss=2.64488 inner_val_multiclass_log_loss=2.64494 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=37/40 loss=0.16779 inner_val_loss=2.61169 inner_val_multiclass_log_loss=2.61176 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=38/40 loss=0.14916 inner_val_loss=2.62670 inner_val_multiclass_log_loss=2.62673 best_multiclass_log_loss=2.61138 best_epoch=35 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 epoch=39/40 loss=0.14285 inner_val_loss=2.61079 inner_val_multiclass_log_loss=2.61077 best_multiclass_log_loss=2.61077 best_epoch=39 seconds=2.1
  fit=26 epoch=40/40 loss=0.12808 inner_val_loss=2.59991 inner_val_multiclass_log_loss=2.59992 best_multiclass_log_loss=2.59992 best_epoch=40 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=26 full_refit_epoch=1/40 loss=4.79128
  fit=26 full_refit_epoch=2/40 loss=4.61581
  fit=26 full_refit_epoch=3/40 loss=4.43444
  fit=26 full_refit_epoch=4/40 loss=4.22564
  fit=26 full_refit_epoch=5/40 loss=3.98810
  fit=26 full_refit_epoch=6/40 loss=3.73859
  fit=26 full_refit_epoch=7/40 loss=3.49443
  fit=26 full_refit_epoch=8/40 loss=3.24746
  fit=26 full_refit_epoch=9/40 loss=3.01506
  fit=26 full_refit_epoch=10/40 loss=2.79312
  fit=26 full_refit_epoch=11/40 loss=2.56534
  fit=26 full_refit_epoch=12/40 loss=2.36016
  fit=26 full_refit_epoch=13/40 loss=2.15093
  fit=26 full_refit_epoch=14/40 loss=1.96154
  fit=26 full_refit_epoch=15/40 loss=1.77583
  fit=26 full_refit_epoch=16/40 loss=1.60714
  fit=26 full_refit_epoch=17/40 loss=1.44926
  fit=26 full_refit_epoch=18/40 loss=1.28955
  fit=26 full_refit_epoch=19/40 loss=1.15900
  fit=26 full_refit_epoch=20/40 loss=1.04187
  fit=26 full_refit_epoch=21/40 loss=0.92192
  fit=26 full_refit_epoch=22/40 loss=0.79462
  fit=26 full_refit_epoch=23/40 loss=0.71547
  fit=26 full_refit_epoch=24/40 loss=0.62853
  fit=26 full_refit_epoch=25/40 loss=0.55656
  fit=26 full_refit_epoch=26/40 loss=0.47864
  fit=26 full_refit_epoch=27/40 loss=0.42339
  fit=26 full_refit_epoch=28/40 loss=0.38009
  fit=26 full_refit_epoch=29/40 loss=0.32500
  fit=26 full_refit_epoch=30/40 loss=0.30116
  fit=26 full_refit_epoch=31/40 loss=0.24874
  fit=26 full_refit_epoch=32/40 loss=0.21832
  fit=26 full_refit_epoch=33/40 loss=0.19626
  fit=26 full_refit_epoch=34/40 loss=0.17990
  fit=26 full_refit_epoch=35/40 loss=0.15856
  fit=26 full_refit_epoch=36/40 loss=0.14075
  fit=26 full_refit_epoch=37/40 loss=0.12563
  fit=26 full_refit_epoch=38/40 loss=0.10919
  fit=26 full_refit_epoch=39/40 loss=0.10192
  fit=26 full_refit_epoch=40/40 loss=0.09188

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=1/40 loss=4.78529 inner_val_loss=4.74350 inner_val_multiclass_log_loss=4.74344 best_multiclass_log_loss=4.74344 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=2/40 loss=4.61759 inner_val_loss=4.66598 inner_val_multiclass_log_loss=4.66596 best_multiclass_log_loss=4.66596 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=3/40 loss=4.44644 inner_val_loss=4.56246 inner_val_multiclass_log_loss=4.56251 best_multiclass_log_loss=4.56251 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=4/40 loss=4.25722 inner_val_loss=4.46757 inner_val_multiclass_log_loss=4.46770 best_multiclass_log_loss=4.46770 best_epoch=4 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=5/40 loss=4.05331 inner_val_loss=4.32690 inner_val_multiclass_log_loss=4.32679 best_multiclass_log_loss=4.32679 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=6/40 loss=3.81373 inner_val_loss=4.18748 inner_val_multiclass_log_loss=4.18753 best_multiclass_log_loss=4.18753 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=7/40 loss=3.59817 inner_val_loss=4.05102 inner_val_multiclass_log_loss=4.05097 best_multiclass_log_loss=4.05097 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=8/40 loss=3.36733 inner_val_loss=3.88468 inner_val_multiclass_log_loss=3.88461 best_multiclass_log_loss=3.88461 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=9/40 loss=3.15824 inner_val_loss=3.79493 inner_val_multiclass_log_loss=3.79483 best_multiclass_log_loss=3.79483 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=10/40 loss=2.94215 inner_val_loss=3.64514 inner_val_multiclass_log_loss=3.64511 best_multiclass_log_loss=3.64511 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=11/40 loss=2.73160 inner_val_loss=3.58555 inner_val_multiclass_log_loss=3.58546 best_multiclass_log_loss=3.58546 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=12/40 loss=2.50724 inner_val_loss=3.40191 inner_val_multiclass_log_loss=3.40197 best_multiclass_log_loss=3.40197 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=13/40 loss=2.30979 inner_val_loss=3.28591 inner_val_multiclass_log_loss=3.28586 best_multiclass_log_loss=3.28586 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=14/40 loss=2.13234 inner_val_loss=3.23486 inner_val_multiclass_log_loss=3.23487 best_multiclass_log_loss=3.23487 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=15/40 loss=1.94883 inner_val_loss=3.08468 inner_val_multiclass_log_loss=3.08474 best_multiclass_log_loss=3.08474 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=16/40 loss=1.78527 inner_val_loss=2.99771 inner_val_multiclass_log_loss=2.99765 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=17/40 loss=1.62082 inner_val_loss=3.00123 inner_val_multiclass_log_loss=3.00123 best_multiclass_log_loss=2.99765 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=18/40 loss=1.45911 inner_val_loss=2.90762 inner_val_multiclass_log_loss=2.90759 best_multiclass_log_loss=2.90759 best_epoch=18 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=19/40 loss=1.33887 inner_val_loss=2.81714 inner_val_multiclass_log_loss=2.81714 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=20/40 loss=1.20626 inner_val_loss=2.82729 inner_val_multiclass_log_loss=2.82734 best_multiclass_log_loss=2.81714 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=21/40 loss=1.07785 inner_val_loss=2.74942 inner_val_multiclass_log_loss=2.74944 best_multiclass_log_loss=2.74944 best_epoch=21 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=22/40 loss=0.96543 inner_val_loss=2.68896 inner_val_multiclass_log_loss=2.68888 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=23/40 loss=0.85024 inner_val_loss=2.74155 inner_val_multiclass_log_loss=2.74154 best_multiclass_log_loss=2.68888 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=24/40 loss=0.76864 inner_val_loss=2.66937 inner_val_multiclass_log_loss=2.66942 best_multiclass_log_loss=2.66942 best_epoch=24 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=25/40 loss=0.68431 inner_val_loss=2.63966 inner_val_multiclass_log_loss=2.63964 best_multiclass_log_loss=2.63964 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=26/40 loss=0.58750 inner_val_loss=2.63823 inner_val_multiclass_log_loss=2.63818 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=27/40 loss=0.51989 inner_val_loss=2.64882 inner_val_multiclass_log_loss=2.64874 best_multiclass_log_loss=2.63818 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=28/40 loss=0.45891 inner_val_loss=2.60257 inner_val_multiclass_log_loss=2.60250 best_multiclass_log_loss=2.60250 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=29/40 loss=0.41438 inner_val_loss=2.58168 inner_val_multiclass_log_loss=2.58177 best_multiclass_log_loss=2.58177 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=30/40 loss=0.36284 inner_val_loss=2.57724 inner_val_multiclass_log_loss=2.57728 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=31/40 loss=0.33492 inner_val_loss=2.57963 inner_val_multiclass_log_loss=2.57971 best_multiclass_log_loss=2.57728 best_epoch=30 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=32/40 loss=0.28502 inner_val_loss=2.55369 inner_val_multiclass_log_loss=2.55378 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=33/40 loss=0.27036 inner_val_loss=2.56817 inner_val_multiclass_log_loss=2.56822 best_multiclass_log_loss=2.55378 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=34/40 loss=0.22846 inner_val_loss=2.53099 inner_val_multiclass_log_loss=2.53092 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=35/40 loss=0.21733 inner_val_loss=2.57357 inner_val_multiclass_log_loss=2.57348 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=36/40 loss=0.18244 inner_val_loss=2.54892 inner_val_multiclass_log_loss=2.54897 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=37/40 loss=0.17517 inner_val_loss=2.54703 inner_val_multiclass_log_loss=2.54705 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 epoch=38/40 loss=0.15172 inner_val_loss=2.54890 inner_val_multiclass_log_loss=2.54889 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0
  fit=27 epoch=39/40 loss=0.13926 inner_val_loss=2.53601 inner_val_multiclass_log_loss=2.53600 best_multiclass_log_loss=2.53092 best_epoch=34 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=27 full_refit_epoch=1/34 loss=4.77779
  fit=27 full_refit_epoch=2/34 loss=4.60078
  fit=27 full_refit_epoch=3/34 loss=4.41295
  fit=27 full_refit_epoch=4/34 loss=4.19824
  fit=27 full_refit_epoch=5/34 loss=3.95991
  fit=27 full_refit_epoch=6/34 loss=3.72031
  fit=27 full_refit_epoch=7/34 loss=3.47218
  fit=27 full_refit_epoch=8/34 loss=3.24296
  fit=27 full_refit_epoch=9/34 loss=2.99698
  fit=27 full_refit_epoch=10/34 loss=2.77741
  fit=27 full_refit_epoch=11/34 loss=2.54338
  fit=27 full_refit_epoch=12/34 loss=2.33114
  fit=27 full_refit_epoch=13/34 loss=2.12232
  fit=27 full_refit_epoch=14/34 loss=1.93304
  fit=27 full_refit_epoch=15/34 loss=1.75879
  fit=27 full_refit_epoch=16/34 loss=1.57506
  fit=27 full_refit_epoch=17/34 loss=1.41415
  fit=27 full_refit_epoch=18/34 loss=1.27479
  fit=27 full_refit_epoch=19/34 loss=1.13539
  fit=27 full_refit_epoch=20/34 loss=1.02070
  fit=27 full_refit_epoch=21/34 loss=0.89572
  fit=27 full_refit_epoch=22/34 loss=0.78825
  fit=27 full_refit_epoch=23/34 loss=0.69082
  fit=27 full_refit_epoch=24/34 loss=0.59551
  fit=27 full_refit_epoch=25/34 loss=0.53715
  fit=27 full_refit_epoch=26/34 loss=0.47102
  fit=27 full_refit_epoch=27/34 loss=0.41062
  fit=27 full_refit_epoch=28/34 loss=0.35460
  fit=27 full_refit_epoch=29/34 loss=0.31392
  fit=27 full_refit_epoch=30/34 loss=0.27658
  fit=27 full_refit_epoch=31/34 loss=0.24613
  fit=27 full_refit_epoch=32/34 loss=0.21734
  fit=27 full_refit_epoch=33/34 loss=0.19095
  fit=27 full_refit_epoch=34/34 loss=0.17254

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=1/40 loss=4.78598 inner_val_loss=4.74895 inner_val_multiclass_log_loss=4.74886 best_multiclass_log_loss=4.74886 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=2/40 loss=4.61747 inner_val_loss=4.67133 inner_val_multiclass_log_loss=4.67137 best_multiclass_log_loss=4.67137 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=3/40 loss=4.44421 inner_val_loss=4.58167 inner_val_multiclass_log_loss=4.58166 best_multiclass_log_loss=4.58166 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=4/40 loss=4.25613 inner_val_loss=4.44833 inner_val_multiclass_log_loss=4.44822 best_multiclass_log_loss=4.44822 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=5/40 loss=4.03231 inner_val_loss=4.29905 inner_val_multiclass_log_loss=4.29900 best_multiclass_log_loss=4.29900 best_epoch=5 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=6/40 loss=3.80887 inner_val_loss=4.16650 inner_val_multiclass_log_loss=4.16655 best_multiclass_log_loss=4.16655 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=7/40 loss=3.58425 inner_val_loss=4.07659 inner_val_multiclass_log_loss=4.07661 best_multiclass_log_loss=4.07661 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=8/40 loss=3.36133 inner_val_loss=3.91148 inner_val_multiclass_log_loss=3.91148 best_multiclass_log_loss=3.91148 best_epoch=8 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=9/40 loss=3.13965 inner_val_loss=3.69225 inner_val_multiclass_log_loss=3.69228 best_multiclass_log_loss=3.69228 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=10/40 loss=2.92091 inner_val_loss=3.63148 inner_val_multiclass_log_loss=3.63156 best_multiclass_log_loss=3.63156 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=11/40 loss=2.70039 inner_val_loss=3.50666 inner_val_multiclass_log_loss=3.50662 best_multiclass_log_loss=3.50662 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=12/40 loss=2.50043 inner_val_loss=3.37099 inner_val_multiclass_log_loss=3.37102 best_multiclass_log_loss=3.37102 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=13/40 loss=2.29484 inner_val_loss=3.26625 inner_val_multiclass_log_loss=3.26612 best_multiclass_log_loss=3.26612 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=14/40 loss=2.12114 inner_val_loss=3.16823 inner_val_multiclass_log_loss=3.16824 best_multiclass_log_loss=3.16824 best_epoch=14 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=15/40 loss=1.93977 inner_val_loss=3.08539 inner_val_multiclass_log_loss=3.08539 best_multiclass_log_loss=3.08539 best_epoch=15 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=16/40 loss=1.76654 inner_val_loss=2.99735 inner_val_multiclass_log_loss=2.99742 best_multiclass_log_loss=2.99742 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=17/40 loss=1.60779 inner_val_loss=2.89870 inner_val_multiclass_log_loss=2.89881 best_multiclass_log_loss=2.89881 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=18/40 loss=1.45640 inner_val_loss=2.85110 inner_val_multiclass_log_loss=2.85113 best_multiclass_log_loss=2.85113 best_epoch=18 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=19/40 loss=1.30639 inner_val_loss=2.77251 inner_val_multiclass_log_loss=2.77241 best_multiclass_log_loss=2.77241 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=20/40 loss=1.16936 inner_val_loss=2.75131 inner_val_multiclass_log_loss=2.75130 best_multiclass_log_loss=2.75130 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=21/40 loss=1.05572 inner_val_loss=2.69500 inner_val_multiclass_log_loss=2.69506 best_multiclass_log_loss=2.69506 best_epoch=21 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=22/40 loss=0.94055 inner_val_loss=2.67022 inner_val_multiclass_log_loss=2.67029 best_multiclass_log_loss=2.67029 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=23/40 loss=0.85175 inner_val_loss=2.59384 inner_val_multiclass_log_loss=2.59380 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=24/40 loss=0.75602 inner_val_loss=2.59947 inner_val_multiclass_log_loss=2.59943 best_multiclass_log_loss=2.59380 best_epoch=23 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=25/40 loss=0.66566 inner_val_loss=2.57623 inner_val_multiclass_log_loss=2.57619 best_multiclass_log_loss=2.57619 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=26/40 loss=0.58957 inner_val_loss=2.56685 inner_val_multiclass_log_loss=2.56687 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=27/40 loss=0.52900 inner_val_loss=2.57257 inner_val_multiclass_log_loss=2.57252 best_multiclass_log_loss=2.56687 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=28/40 loss=0.46072 inner_val_loss=2.54440 inner_val_multiclass_log_loss=2.54439 best_multiclass_log_loss=2.54439 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=29/40 loss=0.41680 inner_val_loss=2.51023 inner_val_multiclass_log_loss=2.51027 best_multiclass_log_loss=2.51027 best_epoch=29 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=30/40 loss=0.35341 inner_val_loss=2.48075 inner_val_multiclass_log_loss=2.48079 best_multiclass_log_loss=2.48079 best_epoch=30 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=31/40 loss=0.32624 inner_val_loss=2.47039 inner_val_multiclass_log_loss=2.47038 best_multiclass_log_loss=2.47038 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=32/40 loss=0.29237 inner_val_loss=2.45936 inner_val_multiclass_log_loss=2.45932 best_multiclass_log_loss=2.45932 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=33/40 loss=0.26956 inner_val_loss=2.44038 inner_val_multiclass_log_loss=2.44039 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=34/40 loss=0.23673 inner_val_loss=2.44873 inner_val_multiclass_log_loss=2.44875 best_multiclass_log_loss=2.44039 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=35/40 loss=0.20594 inner_val_loss=2.43773 inner_val_multiclass_log_loss=2.43777 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=36/40 loss=0.18920 inner_val_loss=2.46623 inner_val_multiclass_log_loss=2.46618 best_multiclass_log_loss=2.43777 best_epoch=35 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=37/40 loss=0.17468 inner_val_loss=2.42681 inner_val_multiclass_log_loss=2.42687 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=38/40 loss=0.16045 inner_val_loss=2.43230 inner_val_multiclass_log_loss=2.43224 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 epoch=39/40 loss=0.13876 inner_val_loss=2.42945 inner_val_multiclass_log_loss=2.42945 best_multiclass_log_loss=2.42687 best_epoch=37 seconds=2.1
  fit=28 epoch=40/40 loss=0.12840 inner_val_loss=2.42231 inner_val_multiclass_log_loss=2.42228 best_multiclass_log_loss=2.42228 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=28 full_refit_epoch=1/40 loss=4.77988
  fit=28 full_refit_epoch=2/40 loss=4.60904
  fit=28 full_refit_epoch=3/40 loss=4.42586
  fit=28 full_refit_epoch=4/40 loss=4.21264
  fit=28 full_refit_epoch=5/40 loss=3.98115
  fit=28 full_refit_epoch=6/40 loss=3.72980
  fit=28 full_refit_epoch=7/40 loss=3.48740
  fit=28 full_refit_epoch=8/40 loss=3.24153
  fit=28 full_refit_epoch=9/40 loss=3.01609
  fit=28 full_refit_epoch=10/40 loss=2.77404
  fit=28 full_refit_epoch=11/40 loss=2.54436
  fit=28 full_refit_epoch=12/40 loss=2.33251
  fit=28 full_refit_epoch=13/40 loss=2.12541
  fit=28 full_refit_epoch=14/40 loss=1.94018
  fit=28 full_refit_epoch=15/40 loss=1.74784
  fit=28 full_refit_epoch=16/40 loss=1.57977
  fit=28 full_refit_epoch=17/40 loss=1.41598
  fit=28 full_refit_epoch=18/40 loss=1.28322
  fit=28 full_refit_epoch=19/40 loss=1.12908
  fit=28 full_refit_epoch=20/40 loss=1.00664
  fit=28 full_refit_epoch=21/40 loss=0.89356
  fit=28 full_refit_epoch=22/40 loss=0.79305
  fit=28 full_refit_epoch=23/40 loss=0.70667
  fit=28 full_refit_epoch=24/40 loss=0.60575
  fit=28 full_refit_epoch=25/40 loss=0.53220
  fit=28 full_refit_epoch=26/40 loss=0.47780
  fit=28 full_refit_epoch=27/40 loss=0.41461
  fit=28 full_refit_epoch=28/40 loss=0.36608
  fit=28 full_refit_epoch=29/40 loss=0.32224
  fit=28 full_refit_epoch=30/40 loss=0.27960
  fit=28 full_refit_epoch=31/40 loss=0.25322
  fit=28 full_refit_epoch=32/40 loss=0.21666
  fit=28 full_refit_epoch=33/40 loss=0.19701
  fit=28 full_refit_epoch=34/40 loss=0.17425
  fit=28 full_refit_epoch=35/40 loss=0.15471
  fit=28 full_refit_epoch=36/40 loss=0.13652
  fit=28 full_refit_epoch=37/40 loss=0.12648
  fit=28 full_refit_epoch=38/40 loss=0.10761
  fit=28 full_refit_epoch=39/40 loss=0.10610
  fit=28 full_refit_epoch=40/40 loss=0.09535

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=1/40 loss=4.78616 inner_val_loss=4.72490 inner_val_multiclass_log_loss=4.72474 best_multiclass_log_loss=4.72474 best_epoch=1 seconds=2.4

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=2/40 loss=4.61983 inner_val_loss=4.62753 inner_val_multiclass_log_loss=4.62759 best_multiclass_log_loss=4.62759 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=3/40 loss=4.45797 inner_val_loss=4.54643 inner_val_multiclass_log_loss=4.54643 best_multiclass_log_loss=4.54643 best_epoch=3 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=4/40 loss=4.28081 inner_val_loss=4.46488 inner_val_multiclass_log_loss=4.46488 best_multiclass_log_loss=4.46488 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=5/40 loss=4.08048 inner_val_loss=4.31625 inner_val_multiclass_log_loss=4.31634 best_multiclass_log_loss=4.31634 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=6/40 loss=3.86825 inner_val_loss=4.18847 inner_val_multiclass_log_loss=4.18838 best_multiclass_log_loss=4.18838 best_epoch=6 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=7/40 loss=3.64301 inner_val_loss=4.05750 inner_val_multiclass_log_loss=4.05740 best_multiclass_log_loss=4.05740 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=8/40 loss=3.40436 inner_val_loss=3.87396 inner_val_multiclass_log_loss=3.87396 best_multiclass_log_loss=3.87396 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=9/40 loss=3.19662 inner_val_loss=3.75727 inner_val_multiclass_log_loss=3.75729 best_multiclass_log_loss=3.75729 best_epoch=9 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=10/40 loss=2.97522 inner_val_loss=3.66436 inner_val_multiclass_log_loss=3.66434 best_multiclass_log_loss=3.66434 best_epoch=10 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=11/40 loss=2.74266 inner_val_loss=3.47013 inner_val_multiclass_log_loss=3.47004 best_multiclass_log_loss=3.47004 best_epoch=11 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=12/40 loss=2.55972 inner_val_loss=3.33333 inner_val_multiclass_log_loss=3.33334 best_multiclass_log_loss=3.33334 best_epoch=12 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=13/40 loss=2.35769 inner_val_loss=3.28423 inner_val_multiclass_log_loss=3.28425 best_multiclass_log_loss=3.28425 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=14/40 loss=2.16565 inner_val_loss=3.15414 inner_val_multiclass_log_loss=3.15408 best_multiclass_log_loss=3.15408 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=15/40 loss=1.98688 inner_val_loss=3.07231 inner_val_multiclass_log_loss=3.07231 best_multiclass_log_loss=3.07231 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=16/40 loss=1.81668 inner_val_loss=3.00154 inner_val_multiclass_log_loss=3.00149 best_multiclass_log_loss=3.00149 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=17/40 loss=1.66713 inner_val_loss=2.92328 inner_val_multiclass_log_loss=2.92325 best_multiclass_log_loss=2.92325 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=18/40 loss=1.52455 inner_val_loss=2.86711 inner_val_multiclass_log_loss=2.86716 best_multiclass_log_loss=2.86716 best_epoch=18 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=19/40 loss=1.35649 inner_val_loss=2.82959 inner_val_multiclass_log_loss=2.82956 best_multiclass_log_loss=2.82956 best_epoch=19 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=20/40 loss=1.23937 inner_val_loss=2.70085 inner_val_multiclass_log_loss=2.70082 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=21/40 loss=1.11458 inner_val_loss=2.73949 inner_val_multiclass_log_loss=2.73944 best_multiclass_log_loss=2.70082 best_epoch=20 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=22/40 loss=1.00135 inner_val_loss=2.69911 inner_val_multiclass_log_loss=2.69906 best_multiclass_log_loss=2.69906 best_epoch=22 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=23/40 loss=0.90562 inner_val_loss=2.60998 inner_val_multiclass_log_loss=2.60992 best_multiclass_log_loss=2.60992 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=24/40 loss=0.79425 inner_val_loss=2.60439 inner_val_multiclass_log_loss=2.60439 best_multiclass_log_loss=2.60439 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=25/40 loss=0.70615 inner_val_loss=2.58918 inner_val_multiclass_log_loss=2.58917 best_multiclass_log_loss=2.58917 best_epoch=25 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=26/40 loss=0.63300 inner_val_loss=2.53947 inner_val_multiclass_log_loss=2.53950 best_multiclass_log_loss=2.53950 best_epoch=26 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=27/40 loss=0.56248 inner_val_loss=2.49854 inner_val_multiclass_log_loss=2.49855 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=28/40 loss=0.50699 inner_val_loss=2.51626 inner_val_multiclass_log_loss=2.51622 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=29/40 loss=0.44951 inner_val_loss=2.53317 inner_val_multiclass_log_loss=2.53312 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=30/40 loss=0.40239 inner_val_loss=2.50438 inner_val_multiclass_log_loss=2.50445 best_multiclass_log_loss=2.49855 best_epoch=27 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=31/40 loss=0.35139 inner_val_loss=2.49836 inner_val_multiclass_log_loss=2.49834 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=32/40 loss=0.31519 inner_val_loss=2.49952 inner_val_multiclass_log_loss=2.49954 best_multiclass_log_loss=2.49834 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=33/40 loss=0.28856 inner_val_loss=2.42672 inner_val_multiclass_log_loss=2.42672 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=34/40 loss=0.25429 inner_val_loss=2.45267 inner_val_multiclass_log_loss=2.45271 best_multiclass_log_loss=2.42672 best_epoch=33 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=35/40 loss=0.22645 inner_val_loss=2.42072 inner_val_multiclass_log_loss=2.42068 best_multiclass_log_loss=2.42068 best_epoch=35 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=36/40 loss=0.20706 inner_val_loss=2.41048 inner_val_multiclass_log_loss=2.41044 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=37/40 loss=0.18824 inner_val_loss=2.41161 inner_val_multiclass_log_loss=2.41162 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=38/40 loss=0.17108 inner_val_loss=2.45061 inner_val_multiclass_log_loss=2.45059 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 epoch=39/40 loss=0.14891 inner_val_loss=2.41139 inner_val_multiclass_log_loss=2.41135 best_multiclass_log_loss=2.41044 best_epoch=36 seconds=2.0
  fit=29 epoch=40/40 loss=0.13585 inner_val_loss=2.40886 inner_val_multiclass_log_loss=2.40889 best_multiclass_log_loss=2.40889 best_epoch=40 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=29 full_refit_epoch=1/40 loss=4.78382
  fit=29 full_refit_epoch=2/40 loss=4.60593
  fit=29 full_refit_epoch=3/40 loss=4.42989
  fit=29 full_refit_epoch=4/40 loss=4.22715
  fit=29 full_refit_epoch=5/40 loss=3.99684
  fit=29 full_refit_epoch=6/40 loss=3.75249
  fit=29 full_refit_epoch=7/40 loss=3.51416
  fit=29 full_refit_epoch=8/40 loss=3.26404
  fit=29 full_refit_epoch=9/40 loss=3.02605
  fit=29 full_refit_epoch=10/40 loss=2.79345
  fit=29 full_refit_epoch=11/40 loss=2.56204
  fit=29 full_refit_epoch=12/40 loss=2.36419
  fit=29 full_refit_epoch=13/40 loss=2.15368
  fit=29 full_refit_epoch=14/40 loss=1.96638
  fit=29 full_refit_epoch=15/40 loss=1.78290
  fit=29 full_refit_epoch=16/40 loss=1.62735
  fit=29 full_refit_epoch=17/40 loss=1.46567
  fit=29 full_refit_epoch=18/40 loss=1.31435
  fit=29 full_refit_epoch=19/40 loss=1.17849
  fit=29 full_refit_epoch=20/40 loss=1.04482
  fit=29 full_refit_epoch=21/40 loss=0.93599
  fit=29 full_refit_epoch=22/40 loss=0.82802
  fit=29 full_refit_epoch=23/40 loss=0.73241
  fit=29 full_refit_epoch=24/40 loss=0.64588
  fit=29 full_refit_epoch=25/40 loss=0.57137
  fit=29 full_refit_epoch=26/40 loss=0.49800
  fit=29 full_refit_epoch=27/40 loss=0.43521
  fit=29 full_refit_epoch=28/40 loss=0.39097
  fit=29 full_refit_epoch=29/40 loss=0.35223
  fit=29 full_refit_epoch=30/40 loss=0.30540
  fit=29 full_refit_epoch=31/40 loss=0.26708
  fit=29 full_refit_epoch=32/40 loss=0.23549
  fit=29 full_refit_epoch=33/40 loss=0.20737
  fit=29 full_refit_epoch=34/40 loss=0.18645
  fit=29 full_refit_epoch=35/40 loss=0.16723
  fit=29 full_refit_epoch=36/40 loss=0.14765
  fit=29 full_refit_epoch=37/40 loss=0.13257
  fit=29 full_refit_epoch=38/40 loss=0.12424
  fit=29 full_refit_epoch=39/40 loss=0.10739
  fit=29 full_refit_epoch=40/40 loss=0.09676

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=1/40 loss=4.78442 inner_val_loss=4.74988 inner_val_multiclass_log_loss=4.74991 best_multiclass_log_loss=4.74991 best_epoch=1 seconds=2.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=2/40 loss=4.61357 inner_val_loss=4.68988 inner_val_multiclass_log_loss=4.68997 best_multiclass_log_loss=4.68997 best_epoch=2 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=3/40 loss=4.45425 inner_val_loss=4.60145 inner_val_multiclass_log_loss=4.60136 best_multiclass_log_loss=4.60136 best_epoch=3 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=4/40 loss=4.27011 inner_val_loss=4.52010 inner_val_multiclass_log_loss=4.52011 best_multiclass_log_loss=4.52011 best_epoch=4 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=5/40 loss=4.06233 inner_val_loss=4.37511 inner_val_multiclass_log_loss=4.37502 best_multiclass_log_loss=4.37502 best_epoch=5 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=6/40 loss=3.84104 inner_val_loss=4.32146 inner_val_multiclass_log_loss=4.32137 best_multiclass_log_loss=4.32137 best_epoch=6 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=7/40 loss=3.61124 inner_val_loss=4.14104 inner_val_multiclass_log_loss=4.14106 best_multiclass_log_loss=4.14106 best_epoch=7 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=8/40 loss=3.37444 inner_val_loss=4.03238 inner_val_multiclass_log_loss=4.03227 best_multiclass_log_loss=4.03227 best_epoch=8 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=9/40 loss=3.14614 inner_val_loss=3.91143 inner_val_multiclass_log_loss=3.91143 best_multiclass_log_loss=3.91143 best_epoch=9 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=10/40 loss=2.93865 inner_val_loss=3.75981 inner_val_multiclass_log_loss=3.75985 best_multiclass_log_loss=3.75985 best_epoch=10 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=11/40 loss=2.71751 inner_val_loss=3.61725 inner_val_multiclass_log_loss=3.61727 best_multiclass_log_loss=3.61727 best_epoch=11 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=12/40 loss=2.51761 inner_val_loss=3.57008 inner_val_multiclass_log_loss=3.57002 best_multiclass_log_loss=3.57002 best_epoch=12 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=13/40 loss=2.31109 inner_val_loss=3.41362 inner_val_multiclass_log_loss=3.41353 best_multiclass_log_loss=3.41353 best_epoch=13 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=14/40 loss=2.13010 inner_val_loss=3.35824 inner_val_multiclass_log_loss=3.35825 best_multiclass_log_loss=3.35825 best_epoch=14 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=15/40 loss=1.95083 inner_val_loss=3.24787 inner_val_multiclass_log_loss=3.24785 best_multiclass_log_loss=3.24785 best_epoch=15 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=16/40 loss=1.78590 inner_val_loss=3.11615 inner_val_multiclass_log_loss=3.11605 best_multiclass_log_loss=3.11605 best_epoch=16 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=17/40 loss=1.61995 inner_val_loss=3.10558 inner_val_multiclass_log_loss=3.10559 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=18/40 loss=1.45544 inner_val_loss=3.12725 inner_val_multiclass_log_loss=3.12726 best_multiclass_log_loss=3.10559 best_epoch=17 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=19/40 loss=1.31723 inner_val_loss=2.96704 inner_val_multiclass_log_loss=2.96702 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=20/40 loss=1.17842 inner_val_loss=3.05234 inner_val_multiclass_log_loss=3.05228 best_multiclass_log_loss=2.96702 best_epoch=19 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=21/40 loss=1.06264 inner_val_loss=2.95265 inner_val_multiclass_log_loss=2.95266 best_multiclass_log_loss=2.95266 best_epoch=21 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=22/40 loss=0.95244 inner_val_loss=2.91211 inner_val_multiclass_log_loss=2.91221 best_multiclass_log_loss=2.91221 best_epoch=22 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=23/40 loss=0.84644 inner_val_loss=2.89159 inner_val_multiclass_log_loss=2.89156 best_multiclass_log_loss=2.89156 best_epoch=23 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=24/40 loss=0.76082 inner_val_loss=2.88187 inner_val_multiclass_log_loss=2.88200 best_multiclass_log_loss=2.88200 best_epoch=24 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=25/40 loss=0.67191 inner_val_loss=2.84233 inner_val_multiclass_log_loss=2.84237 best_multiclass_log_loss=2.84237 best_epoch=25 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=26/40 loss=0.60417 inner_val_loss=2.77625 inner_val_multiclass_log_loss=2.77628 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=27/40 loss=0.52400 inner_val_loss=2.81227 inner_val_multiclass_log_loss=2.81225 best_multiclass_log_loss=2.77628 best_epoch=26 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=28/40 loss=0.46472 inner_val_loss=2.74761 inner_val_multiclass_log_loss=2.74756 best_multiclass_log_loss=2.74756 best_epoch=28 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=29/40 loss=0.40611 inner_val_loss=2.74257 inner_val_multiclass_log_loss=2.74254 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=30/40 loss=0.36938 inner_val_loss=2.75965 inner_val_multiclass_log_loss=2.75972 best_multiclass_log_loss=2.74254 best_epoch=29 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=31/40 loss=0.32566 inner_val_loss=2.72053 inner_val_multiclass_log_loss=2.72051 best_multiclass_log_loss=2.72051 best_epoch=31 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=32/40 loss=0.30059 inner_val_loss=2.69751 inner_val_multiclass_log_loss=2.69749 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=1.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=33/40 loss=0.27015 inner_val_loss=2.74933 inner_val_multiclass_log_loss=2.74931 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=34/40 loss=0.23087 inner_val_loss=2.77536 inner_val_multiclass_log_loss=2.77540 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=35/40 loss=0.20538 inner_val_loss=2.74973 inner_val_multiclass_log_loss=2.74970 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 epoch=36/40 loss=0.18884 inner_val_loss=2.75416 inner_val_multiclass_log_loss=2.75420 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.1
  fit=30 epoch=37/40 loss=0.16183 inner_val_loss=2.72750 inner_val_multiclass_log_loss=2.72753 best_multiclass_log_loss=2.69749 best_epoch=32 seconds=2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=30 full_refit_epoch=1/32 loss=4.77728
  fit=30 full_refit_epoch=2/32 loss=4.61421
  fit=30 full_refit_epoch=3/32 loss=4.44084
  fit=30 full_refit_epoch=4/32 loss=4.24429
  fit=30 full_refit_epoch=5/32 loss=4.01696
  fit=30 full_refit_epoch=6/32 loss=3.77332
  fit=30 full_refit_epoch=7/32 loss=3.51979
  fit=30 full_refit_epoch=8/32 loss=3.26840
  fit=30 full_refit_epoch=9/32 loss=3.03903
  fit=30 full_refit_epoch=10/32 loss=2.81296
  fit=30 full_refit_epoch=11/32 loss=2.58932
  fit=30 full_refit_epoch=12/32 loss=2.37527
  fit=30 full_refit_epoch=13/32 loss=2.16968
  fit=30 full_refit_epoch=14/32 loss=1.98022
  fit=30 full_refit_epoch=15/32 loss=1.79258
  fit=30 full_refit_epoch=16/32 loss=1.62738
  fit=30 full_refit_epoch=17/32 loss=1.46720
  fit=30 full_refit_epoch=18/32 loss=1.31258
  fit=30 full_refit_epoch=19/32 loss=1.17510
  fit=30 full_refit_epoch=20/32 loss=1.05290
  fit=30 full_refit_epoch=21/32 loss=0.92468
  fit=30 full_refit_epoch=22/32 loss=0.81936
  fit=30 full_refit_epoch=23/32 loss=0.72419
  fit=30 full_refit_epoch=24/32 loss=0.63480
  fit=30 full_refit_epoch=25/32 loss=0.55535
  fit=30 full_refit_epoch=26/32 loss=0.48229
  fit=30 full_refit_epoch=27/32 loss=0.42661
  fit=30 full_refit_epoch=28/32 loss=0.37705
  fit=30 full_refit_epoch=29/32 loss=0.31890
  fit=30 full_refit_epoch=30/32 loss=0.28566
  fit=30 full_refit_epoch=31/32 loss=0.26161
  fit=30 full_refit_epoch=32/32 loss=0.22707

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

END   seed=47 phase=refined_selected model=resnet18 metric=2.464116220981177 error=None minutes=13.21

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

    seed               arm  metric_value
0     13          baseline      2.458749
1     13   mlestar_initial      2.458749
2     13   mlestar_refined      2.458749
3     13  mlestar_ensemble      2.458749
4     29          baseline      2.471292
5     29   mlestar_initial      2.471292
6     29   mlestar_refined      2.471292
7     29  mlestar_ensemble      2.471292
8     47          baseline      2.464116
9     47   mlestar_initial      2.464116
10    47   mlestar_refined      2.464116
11    47  mlestar_ensemble      2.464116

                      mean       std  count
arm
baseline          2.464719  0.006293      3
mlestar_ensemble  2.464719  0.006293      3
mlestar_initial   2.464719  0.006293      3
mlestar_refined   2.464719  0.006293      3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

,seed,baseline_weight,refined_weight,refined_model,reconstructed_oof_score
0,13,0.0,1.0,resnet18,2.458749
1,29,0.0,1.0,resnet18,2.471292
2,47,0.0,1.0,resnet18,2.464116

Final fit: benchmark=dog_breed seed=13 model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.60680 inner_val_loss=4.19246 inner_val_multiclass_log_loss=4.19242 best_multiclass_log_loss=4.19242 best_epoch=1 seconds=10.3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=3.79280 inner_val_loss=3.30781 inner_val_multiclass_log_loss=3.30777 best_multiclass_log_loss=3.30777 best_epoch=2 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=2.96371 inner_val_loss=2.59994 inner_val_multiclass_log_loss=2.59994 best_multiclass_log_loss=2.59994 best_epoch=3 seconds=9.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=2.34844 inner_val_loss=2.17816 inner_val_multiclass_log_loss=2.17819 best_multiclass_log_loss=2.17819 best_epoch=4 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=1.93043 inner_val_loss=1.88863 inner_val_multiclass_log_loss=1.88862 best_multiclass_log_loss=1.88862 best_epoch=5 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=1.60426 inner_val_loss=1.74739 inner_val_multiclass_log_loss=1.74736 best_multiclass_log_loss=1.74736 best_epoch=6 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=1.35186 inner_val_loss=1.61101 inner_val_multiclass_log_loss=1.61104 best_multiclass_log_loss=1.61104 best_epoch=7 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=1.15069 inner_val_loss=1.52745 inner_val_multiclass_log_loss=1.52744 best_multiclass_log_loss=1.52744 best_epoch=8 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=0.97437 inner_val_loss=1.49378 inner_val_multiclass_log_loss=1.49377 best_multiclass_log_loss=1.49377 best_epoch=9 seconds=10.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=0.81960 inner_val_loss=1.47315 inner_val_multiclass_log_loss=1.47314 best_multiclass_log_loss=1.47314 best_epoch=10 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=0.68851 inner_val_loss=1.51972 inner_val_multiclass_log_loss=1.51972 best_multiclass_log_loss=1.47314 best_epoch=10 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=0.56993 inner_val_loss=1.43257 inner_val_multiclass_log_loss=1.43257 best_multiclass_log_loss=1.43257 best_epoch=12 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=0.46434 inner_val_loss=1.41208 inner_val_multiclass_log_loss=1.41211 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=0.38583 inner_val_loss=1.44328 inner_val_multiclass_log_loss=1.44324 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=15/40 loss=0.30429 inner_val_loss=1.45040 inner_val_multiclass_log_loss=1.45038 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=16/40 loss=0.25121 inner_val_loss=1.44728 inner_val_multiclass_log_loss=1.44718 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=17/40 loss=0.20540 inner_val_loss=1.47029 inner_val_multiclass_log_loss=1.47000 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=9.9
  fit=1 epoch=18/40 loss=0.15864 inner_val_loss=1.51957 inner_val_multiclass_log_loss=1.51959 best_multiclass_log_loss=1.41211 best_epoch=13 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/13 loss=4.58925
  fit=1 full_refit_epoch=2/13 loss=3.73122
  fit=1 full_refit_epoch=3/13 loss=2.88436
  fit=1 full_refit_epoch=4/13 loss=2.27739
  fit=1 full_refit_epoch=5/13 loss=1.85635
  fit=1 full_refit_epoch=6/13 loss=1.55904
  fit=1 full_refit_epoch=7/13 loss=1.30434
  fit=1 full_refit_epoch=8/13 loss=1.10861
  fit=1 full_refit_epoch=9/13 loss=0.93180
  fit=1 full_refit_epoch=10/13 loss=0.78620
  fit=1 full_refit_epoch=11/13 loss=0.65594
  fit=1 full_refit_epoch=12/13 loss=0.54916
  fit=1 full_refit_epoch=13/13 loss=0.44264
Final fit: benchmark=dog_breed seed=29 model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.60106 inner_val_loss=4.21555 inner_val_multiclass_log_loss=4.21556 best_multiclass_log_loss=4.21556 best_epoch=1 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=3.80610 inner_val_loss=3.39894 inner_val_multiclass_log_loss=3.39890 best_multiclass_log_loss=3.39890 best_epoch=2 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=2.98774 inner_val_loss=2.73224 inner_val_multiclass_log_loss=2.73218 best_multiclass_log_loss=2.73218 best_epoch=3 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=2.36769 inner_val_loss=2.26940 inner_val_multiclass_log_loss=2.26939 best_multiclass_log_loss=2.26939 best_epoch=4 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=1.92950 inner_val_loss=2.05123 inner_val_multiclass_log_loss=2.05126 best_multiclass_log_loss=2.05126 best_epoch=5 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=1.61442 inner_val_loss=1.88093 inner_val_multiclass_log_loss=1.88095 best_multiclass_log_loss=1.88095 best_epoch=6 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=1.36082 inner_val_loss=1.76771 inner_val_multiclass_log_loss=1.76772 best_multiclass_log_loss=1.76772 best_epoch=7 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=1.14975 inner_val_loss=1.69943 inner_val_multiclass_log_loss=1.69946 best_multiclass_log_loss=1.69946 best_epoch=8 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=0.97523 inner_val_loss=1.68706 inner_val_multiclass_log_loss=1.68706 best_multiclass_log_loss=1.68706 best_epoch=9 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=0.81194 inner_val_loss=1.65686 inner_val_multiclass_log_loss=1.65686 best_multiclass_log_loss=1.65686 best_epoch=10 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=0.68407 inner_val_loss=1.61629 inner_val_multiclass_log_loss=1.61629 best_multiclass_log_loss=1.61629 best_epoch=11 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=0.56395 inner_val_loss=1.60739 inner_val_multiclass_log_loss=1.60736 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=0.46851 inner_val_loss=1.64411 inner_val_multiclass_log_loss=1.64409 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=0.37862 inner_val_loss=1.62601 inner_val_multiclass_log_loss=1.62605 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=15/40 loss=0.30851 inner_val_loss=1.64783 inner_val_multiclass_log_loss=1.64784 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=16/40 loss=0.24888 inner_val_loss=1.65458 inner_val_multiclass_log_loss=1.65458 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=10.0
  fit=1 epoch=17/40 loss=0.19380 inner_val_loss=1.67784 inner_val_multiclass_log_loss=1.67779 best_multiclass_log_loss=1.60736 best_epoch=12 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/12 loss=4.58832
  fit=1 full_refit_epoch=2/12 loss=3.74247
  fit=1 full_refit_epoch=3/12 loss=2.91390
  fit=1 full_refit_epoch=4/12 loss=2.30014
  fit=1 full_refit_epoch=5/12 loss=1.88323
  fit=1 full_refit_epoch=6/12 loss=1.57344
  fit=1 full_refit_epoch=7/12 loss=1.32564
  fit=1 full_refit_epoch=8/12 loss=1.11698
  fit=1 full_refit_epoch=9/12 loss=0.95817
  fit=1 full_refit_epoch=10/12 loss=0.78910
  fit=1 full_refit_epoch=11/12 loss=0.65655
  fit=1 full_refit_epoch=12/12 loss=0.54209
Final fit: benchmark=dog_breed seed=47 model=resnet18

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=1/40 loss=4.60564 inner_val_loss=4.30379 inner_val_multiclass_log_loss=4.30382 best_multiclass_log_loss=4.30382 best_epoch=1 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=2/40 loss=3.82003 inner_val_loss=3.38845 inner_val_multiclass_log_loss=3.38839 best_multiclass_log_loss=3.38839 best_epoch=2 seconds=9.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=3/40 loss=3.00805 inner_val_loss=2.75820 inner_val_multiclass_log_loss=2.75825 best_multiclass_log_loss=2.75825 best_epoch=3 seconds=9.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=4/40 loss=2.39132 inner_val_loss=2.32856 inner_val_multiclass_log_loss=2.32855 best_multiclass_log_loss=2.32855 best_epoch=4 seconds=9.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=5/40 loss=1.96583 inner_val_loss=2.04890 inner_val_multiclass_log_loss=2.04890 best_multiclass_log_loss=2.04890 best_epoch=5 seconds=9.6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=6/40 loss=1.63796 inner_val_loss=1.87070 inner_val_multiclass_log_loss=1.87069 best_multiclass_log_loss=1.87069 best_epoch=6 seconds=9.5

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=7/40 loss=1.38248 inner_val_loss=1.74436 inner_val_multiclass_log_loss=1.74439 best_multiclass_log_loss=1.74439 best_epoch=7 seconds=9.7

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=8/40 loss=1.17279 inner_val_loss=1.66363 inner_val_multiclass_log_loss=1.66362 best_multiclass_log_loss=1.66362 best_epoch=8 seconds=9.9

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=9/40 loss=0.98924 inner_val_loss=1.65098 inner_val_multiclass_log_loss=1.65100 best_multiclass_log_loss=1.65100 best_epoch=9 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=10/40 loss=0.83472 inner_val_loss=1.59955 inner_val_multiclass_log_loss=1.59952 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=11/40 loss=0.69434 inner_val_loss=1.60062 inner_val_multiclass_log_loss=1.60061 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=10.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=12/40 loss=0.57967 inner_val_loss=1.60504 inner_val_multiclass_log_loss=1.60509 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=13/40 loss=0.47246 inner_val_loss=1.60493 inner_val_multiclass_log_loss=1.60493 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=10.2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 epoch=14/40 loss=0.38468 inner_val_loss=1.61686 inner_val_multiclass_log_loss=1.61686 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=9.6
  fit=1 epoch=15/40 loss=0.31532 inner_val_loss=1.61672 inner_val_multiclass_log_loss=1.61668 best_multiclass_log_loss=1.59952 best_epoch=10 seconds=9.8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(

  fit=1 full_refit_epoch=1/10 loss=4.58790
  fit=1 full_refit_epoch=2/10 loss=3.74897
  fit=1 full_refit_epoch=3/10 loss=2.91265
  fit=1 full_refit_epoch=4/10 loss=2.30865
  fit=1 full_refit_epoch=5/10 loss=1.88453
  fit=1 full_refit_epoch=6/10 loss=1.56782
  fit=1 full_refit_epoch=7/10 loss=1.32425
  fit=1 full_refit_epoch=8/10 loss=1.11588
  fit=1 full_refit_epoch=9/10 loss=0.95090
  fit=1 full_refit_epoch=10/10 loss=0.79122

,artifact,best_inner_validation_loss,best_inner_validation_metric,best_inner_validation_metric_name,best_inner_validation_qwk,candidate_id,criterion,dataset_rows,fit_number,inner_fit_rows,inner_validation_rows,max_epochs,metric_greater_is_better,model,phase,refit_on_all_training_rows,seed,selected_epoch,stopped_early
0,final_seed_13/epoch_selection.json,1.412081,1.412111,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,10222,1,9722,500,40,False,resnet18,final_full_data,True,13,13,True
1,final_seed_29/epoch_selection.json,1.607388,1.607358,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,10222,1,9722,500,40,False,resnet18,final_full_data,True,29,12,True
2,final_seed_47/epoch_selection.json,1.599553,1.599523,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,10222,1,9722,500,40,False,resnet18,final_full_data,True,47,10,True
3,seed_13/epoch_selection.json,2.503143,2.503141,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,1,1800,200,40,False,resnet18,baseline,True,13,38,True
4,seed_13/epoch_selection.json,2.499692,2.499633,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,2,1800,200,40,False,resnet18,baseline,True,14,38,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,seed_47/epoch_selection.json,2.599911,2.599916,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,26,1800,200,40,False,resnet18,refined_selected,True,47,40,False
89,seed_47/epoch_selection.json,2.530993,2.530922,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,27,1800,200,40,False,resnet18,refined_selected,True,48,34,True
90,seed_47/epoch_selection.json,2.422311,2.422285,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,28,1800,200,40,False,resnet18,refined_selected,True,49,40,False
91,seed_47/epoch_selection.json,2.408862,2.408886,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,29,1800,200,40,False,resnet18,refined_selected,True,50,40,False
92,seed_47/epoch_selection.json,2.697509,2.697490,multiclass_log_loss,None,resnet18,minimum inner-validation multiclass_log_loss,2000,30,1800,200,40,False,resnet18,refined_selected,True,51,32,True

                                  median       mean  min  max  count
phase            model
baseline         resnet18           38.0  37.000000   29   40     15
final_full_data  resnet18           12.0  11.666667   10   13      3
initial          efficientnet_b0    27.0  25.600000   16   31     15
                 resnet18           38.0  37.000000   29   40     15
initial_selected resnet18           38.0  37.000000   29   40     15
refined_selected resnet18           38.0  37.000000   29   40     15
refinement       efficientnet_b0    27.0  25.600000   16   31     15

Epoch-selection evidence: /content/drive/MyDrive/mlestar-runs/dog_breed/selected_epochs.csv
Validated dog_breed submission: rows=10357, columns=121

,id,affenpinscher,afghan_hound,african_hunting_dog,airedale,american_staffordshire_terrier,appenzeller,australian_terrier,basenji,basset,...,toy_poodle,toy_terrier,vizsla,walker_hound,weimaraner,welsh_springer_spaniel,west_highland_white_terrier,whippet,wire-haired_fox_terrier,yorkshire_terrier
0,000621fb3cbb32d8935728e48679680e,0.000321,0.005648,0.000056,0.000022,0.000143,0.000152,0.000068,8.635768e-05,0.000313,...,0.000180,0.000537,0.000024,0.000149,0.000058,0.000535,0.000037,0.000456,0.000115,0.000522
1,00102ee9d8eb90812350685311fe5890,0.000103,0.000114,0.000062,0.000048,0.000433,0.000119,0.000251,3.191163e-04,0.000026,...,0.000767,0.000390,0.000033,0.000071,0.000163,0.000041,0.018326,0.000125,0.000584,0.000219
2,0012a730dfa437f5f3613fb75efcd4ce,0.000033,0.126507,0.000061,0.000064,0.000200,0.000031,0.000019,1.709111e-05,0.000260,...,0.000204,0.000063,0.000022,0.000449,0.002044,0.002678,0.003558,0.003914,0.001852,0.000083
3,001510bc8570bbeee98c8d80c8a95ec1,0.003607,0.035428,0.001344,0.002456,0.008212,0.004932,0.002095,2.394399e-02,0.005560,...,0.000525,0.001905,0.006635,0.002863,0.047651,0.002256,0.002261,0.049849,0.001953,0.003492
4,001a5f3114548acdefa3d4da05474c2e,0.001742,0.000703,0.000151,0.000012,0.000022,0.000007,0.000349,4.151546e-07,0.000012,...,0.000284,0.000005,0.000003,0.000001,0.000011,0.000004,0.000080,0.000040,0.000039,0.001020

Successfully submitted to Dog Breed Identification

  0%|          | 0.00/26.5M [00:00<?, ?B/s]
  5%|▍         | 1.27M/26.5M [00:00<00:16, 1.60MB/s]
  6%|▌         | 1.64M/26.5M [00:01<00:16, 1.53MB/s]
  8%|▊         | 2.14M/26.5M [00:01<00:15, 1.64MB/s]
 49%|████▉     | 13.0M/26.5M [00:01<00:00, 14.3MB/s]
 61%|██████    | 16.0M/26.5M [00:01<00:00, 14.0MB/s]
 73%|███████▎  | 19.3M/26.5M [00:02<00:00, 15.6MB/s]
 85%|████████▌ | 22.6M/26.5M [00:02<00:00, 18.0MB/s]
 97%|█████████▋| 25.8M/26.5M [00:02<00:00, 18.9MB/s]
100%|██████████| 26.5M/26.5M [00:03<00:00, 7.90MB/s]

{
  "benchmark": "dog_breed",
  "stage": "complete",
  "success": true,
  "oof_epoch_protocol": "mle_inner_official_metric_selected_epochs",
  "resumed_oof": false,
  "final_protocol": "per-seed mlestar_ensemble OOF weights, then 3-seed mean; mle_inner_official_metric_selected_epochs",
  "ensemble_plans": [
    {
      "seed": 13,
      "weights": {
        "baseline": 0.0,
        "refined": 1.0
      },
      "oof_score": 2.4587492901316517,
      "baseline_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "baseline-resnet18-3c1ad4d909ab",
        "fold_scores": [
          2.4366314194960377,
          2.3971329613217276,
          2.4403789880930518,
          2.527589765829054,
          2.492054281769369
        ],
        "metric_value": 2.4587492901316477,
        "oof_path": "baseline_resnet18_13/oof.csv",
        "parent_experiment_id": null,
        "phase": "baseline",
        "seed": 13,
        "test_path": null
      },
      "refined_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "refined_selected-resnet18-d732ddbefc73",
        "fold_scores": [
          2.4366314194960377,
          2.3971329613217276,
          2.4403789880930518,
          2.527589765829054,
          2.492054281769369
        ],
        "metric_value": 2.4587492901316477,
        "oof_path": "refined_selected_resnet18_13/oof.csv",
        "parent_experiment_id": null,
        "phase": "refined_selected",
        "seed": 13,
        "test_path": null
      },
      "baseline_model": "resnet18",
      "refined_model": "resnet18"
    },
    {
      "seed": 29,
      "weights": {
        "baseline": 0.0,
        "refined": 1.0
      },
      "oof_score": 2.471291572428008,
      "baseline_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "baseline-resnet18-3aecaa23dd37",
        "fold_scores": [
          2.5034823265078345,
          2.5448896810359782,
          2.4221589927836384,
          2.4556801800922834,
          2.4301949259166244
        ],
        "metric_value": 2.471291572428004,
        "oof_path": "baseline_resnet18_29/oof.csv",
        "parent_experiment_id": null,
        "phase": "baseline",
        "seed": 29,
        "test_path": null
      },
      "refined_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "refined_selected-resnet18-8d905f86948f",
        "fold_scores": [
          2.5034823265078345,
          2.5448896810359782,
          2.4221589927836384,
          2.4556801800922834,
          2.4301949259166244
        ],
        "metric_value": 2.471291572428004,
        "oof_path": "refined_selected_resnet18_29/oof.csv",
        "parent_experiment_id": null,
        "phase": "refined_selected",
        "seed": 29,
        "test_path": null
      },
      "baseline_model": "resnet18",
      "refined_model": "resnet18"
    },
    {
      "seed": 47,
      "weights": {
        "baseline": 0.0,
        "refined": 1.0
      },
      "oof_score": 2.4641162209811815,
      "baseline_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "baseline-resnet18-d7f8c6687e81",
        "fold_scores": [
          2.464489538238152,
          2.5323782104341706,
          2.4743984253578475,
          2.4184101707450507,
          2.430871181213489
        ],
        "metric_value": 2.464116220981177,
        "oof_path": "baseline_resnet18_47/oof.csv",
        "parent_experiment_id": null,
        "phase": "baseline",
        "seed": 47,
        "test_path": null
      },
      "refined_receipt": {
        "candidate_id": "resnet18",
        "error": null,
        "experiment_id": "refined_selected-resnet18-b59261d6f68d",
        "fold_scores": [
          2.464489538238152,
          2.5323782104341706,
          2.4743984253578475,
          2.4184101707450507,
          2.430871181213489
        ],
        "metric_value": 2.464116220981177,
        "oof_path": "refined_selected_resnet18_47/oof.csv",
        "parent_experiment_id": null,
        "phase": "refined_selected",
        "seed": 47,
        "test_path": null
      },
      "baseline_model": "resnet18",
      "refined_model": "resnet18"
    }
  ],
  "epoch_selection": {
    "method": "minimum multiclass_log_loss on an inner split of each training fold",
    "evidence_path": "/content/drive/MyDrive/mlestar-runs/dog_breed/selected_epochs.csv",
    "records": [
      {
        "artifact": "final_seed_13/epoch_selection.json",
        "best_inner_validation_loss": 1.4120807723999023,
        "best_inner_validation_metric": 1.4121109541476422,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 10222,
        "fit_number": 1,
        "inner_fit_rows": 9722,
        "inner_validation_rows": 500,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "final_full_data",
        "refit_on_all_training_rows": true,
        "seed": 13,
        "selected_epoch": 13,
        "stopped_early": true
      },
      {
        "artifact": "final_seed_29/epoch_selection.json",
        "best_inner_validation_loss": 1.6073876180648803,
        "best_inner_validation_metric": 1.6073579520627237,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 10222,
        "fit_number": 1,
        "inner_fit_rows": 9722,
        "inner_validation_rows": 500,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "final_full_data",
        "refit_on_all_training_rows": true,
        "seed": 29,
        "selected_epoch": 12,
        "stopped_early": true
      },
      {
        "artifact": "final_seed_47/epoch_selection.json",
        "best_inner_validation_loss": 1.5995530157089233,
        "best_inner_validation_metric": 1.5995227591664967,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 10222,
        "fit_number": 1,
        "inner_fit_rows": 9722,
        "inner_validation_rows": 500,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "final_full_data",
        "refit_on_all_training_rows": true,
        "seed": 47,
        "selected_epoch": 10,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.5031433868408204,
        "best_inner_validation_metric": 2.503141401467351,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 1,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "baseline",
        "refit_on_all_training_rows": true,
        "seed": 13,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.4996921539306642,
        "best_inner_validation_metric": 2.499632943533425,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 2,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "baseline",
        "refit_on_all_training_rows": true,
        "seed": 14,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.4180946350097656,
        "best_inner_validation_metric": 2.4180620427454773,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 3,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "baseline",
        "refit_on_all_training_rows": true,
        "seed": 15,
        "selected_epoch": 37,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.504302978515625,
        "best_inner_validation_metric": 2.504293896598515,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 4,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "baseline",
        "refit_on_all_training_rows": true,
        "seed": 16,
        "selected_epoch": 36,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.704184875488281,
        "best_inner_validation_metric": 2.7042126554856827,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 5,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "baseline",
        "refit_on_all_training_rows": true,
        "seed": 17,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.5031433868408204,
        "best_inner_validation_metric": 2.503141401467351,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 6,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 13,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.4996921539306642,
        "best_inner_validation_metric": 2.499632943533425,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 7,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 14,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.4180946350097656,
        "best_inner_validation_metric": 2.4180620427454773,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 8,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 15,
        "selected_epoch": 37,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.504302978515625,
        "best_inner_validation_metric": 2.504293896598515,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 9,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 16,
        "selected_epoch": 36,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.704184875488281,
        "best_inner_validation_metric": 2.7042126554856827,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 10,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 17,
        "selected_epoch": 38,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 3.1505674362182616,
        "best_inner_validation_metric": 3.1506292064692643,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "efficientnet_b0",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 11,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "efficientnet_b0",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 13,
        "selected_epoch": 30,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 3.0183952903747557,
        "best_inner_validation_metric": 3.01851132403967,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "efficientnet_b0",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 12,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "efficientnet_b0",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 14,
        "selected_epoch": 22,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.759132080078125,
        "best_inner_validation_metric": 2.759123103760088,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "efficientnet_b0",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 13,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "efficientnet_b0",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 15,
        "selected_epoch": 29,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 3.29206298828125,
        "best_inner_validation_metric": 3.2921735867042026,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "efficientnet_b0",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 14,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "efficientnet_b0",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 16,
        "selected_epoch": 21,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 3.2569498443603515,
        "best_inner_validation_metric": 3.2568681833241637,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "efficientnet_b0",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 15,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "efficientnet_b0",
        "phase": "initial",
        "refit_on_all_training_rows": true,
        "seed": 17,
        "selected_epoch": 24,
        "stopped_early": true
      },
      {
        "artifact": "seed_13/epoch_selection.json",
        "best_inner_validation_loss": 2.5031433868408204,
        "best_inner_validation_metric": 2.503141401467351,
        "best_inner_validation_metric_name": "multiclass_log_loss",
        "best_inner_validation_qwk": null,
        "candidate_id": "resnet18",
        "criterion": "minimum inner-validation multiclass_log_loss",
        "dataset_rows": 2000,
        "fit_number": 16,
        "inner_fit_rows": 1800,
        "inner_validation_rows": 200,
        "max_epochs": 40,
        "metric_greater_is_better": false,
        "model": "resnet18",
        "phase": "initial_selected",
        "refit_on_all_training_rows": true,
        "seed": 13,
        "selected_epoch": 38,
        "stopped_early": true

    seed               arm  metric_value
0     13          baseline      2.458749
1     13   mlestar_initial      2.458749
2     13   mlestar_refined      2.458749
3     13  mlestar_ensemble      2.458749
4     29          baseline      2.471292
5     29   mlestar_initial      2.471292
6     29   mlestar_refined      2.471292
7     29  mlestar_ensemble      2.471292
8     47          baseline      2.464116
9     47   mlestar_initial      2.464116
10    47   mlestar_refined      2.464116
11    47  mlestar_ensemble      2.464116